### ISSUE TITLE
Exporting of single-field author lacks braces

### ISSUE THREAD

**Issue by Dunstkreis** [ZotPlus/zotero-better-bibtex#130]
I read the guidelines, but sadly its not possible for me, to bring the exact example.
I have got a link in my library, but cant open it right now. nevertheless, i'll try to explain the problem anyways.
Its this book: http://site.ebrary.com/lib/alltitles/docDetail.action?docID=10296302
In my zotero lib, authors look like this: http://imagizer.imageshack.us/a/img661/5239/L74zYU.png

If i export to BibTex or BibLaTex the author-tag looks like this:
	author = {Huizinga, Dorota and Kolawa, Adam and {Wiley InterScience (Online service)}},
but if i export to Better Bib(La)Tex, i allways get this:
  author = {Huizinga, Dorota and Kolawa, Adam and Wiley InterScience (Online service)},

So in my PDF its messed up and looks like:
http://imagizer.imageshack.us/a/img661/2126/v86qx0.png

Instead of the expected:
http://imageshack.com/a/img673/7897/cVhuc5.png

I guess you got the pharanses thing wrong? If i can help in any way, please let me know.

**Comment by AllThatIsTheCase** [comment]
Reproducible, working on a fix now

**Comment by AllThatIsTheCase** [comment]
Fixed in 0.7.3

**Comment by Dunstkreis** [comment]
you guys are awesome!

**Comment by AllThatIsTheCase** [comment]
There is no guys, just me ☺

**Comment by Dunstkreis** [comment]
:+1: So you are even more awesome! ;)
I was really surprised, thought by myself, lets have a look, if someone commented or something, but nothing to see? Is it closed? Yes, hmm did i do something wrong? Oh no, already fixed!! And due to a browser restart I already had the new version installed, without even noticing.
So yea, t y very much!!! :)
