### ISSUE TITLE
Feature Request: Omit URL export when DOI present.

### ISSUE THREAD

**Issue by bnlawrence** [ZotPlus/zotero-better-bibtex#131]
I see I can omit keywords in export, but it'd be really desirable to have (at least) one conditional.

There is no way I can ever see the use of having a URL in the export, if there is a DOI, indeed, there isn't much point having an "accessed" in the latter case either.

It'd be really nice to have the option to avoid (url,accessed) if doi was present ... 

This can be done vaguely elegantly in biblatex, but is a complete hassle in bibtex, but I think in both cases it's a post-fact-hack :-)

Cheers
Bryan

**Comment by AllThatIsTheCase** [comment]
Wouldn't it be easier to just clear the url field in such a case?

**Comment by bnlawrence** [comment]
Well, one has two choices, clear it when you first get the metadata (so you'd have to do it manually after each use of the zotero tools to collect the metadata) ... or you can do it after you've generated the bibtex export (which is what I currently do). They're both cumbersome :-). I think it'd be cleaner just to have an option to omit it .... (realising for some communities, they'd want the opposite, keep the URL, but omit the doi)

**Comment by AllThatIsTheCase** [comment]
I'm trying to figure out a way not to hard-code too much behavior into the plugin, and also not to create too many options to tinker with in the preferences. I'm totally open to doing what you ask -- if I can't think of anything, it'll likely become a radio choice between a) don't do anything b) DOI preferred c) URL preferred

**Comment by bnlawrence** [comment]
Hi. I'd be happy with (and grateful for) any option - but agree that clean preferences are good, and hard code is bad. If you decided it was a straw too far (or simply not important enough for you now), I'd understand. That said, from my view of the various fora, your suggestion to have a radio would capture most (if not all) the correspondence I've seen ... and, as I said, make me a happy bunny.

**Comment by AllThatIsTheCase** [comment]
Aww, bunnies... OK, you got me. Can you perhaps get met a testcase (select a representative entrty, export with format "Zotero TestCase", and drop it into https://dbinbox.com/allthatisthecase?

**Comment by AllThatIsTheCase** [comment]
Cool, can you also get me the "TestCase" variety? "Zotero TestCase" is one of the export options, alongside "Better BibLaTeX"

**Comment by AllThatIsTheCase** [comment]
Thanks!
