### ISSUE TITLE
Export Newspaper Article misses section field

### ISSUE THREAD

**Issue by sunew** [ZotPlus/zotero-better-bibtex#132]
Exporting Zotero itemtype "Newspaper Article" results in biblatex 'article' items. Ok.

The export misses the "Section" field from zotero.
It could be exported to the biblatex field 'journalsubtitle'.

**Comment by AllThatIsTheCase** [comment]
That sounds reasonable. Just to make sure, would you happen to have a Zotero TestCase and a BibLaTeX export that shows the desired behavior? If so, I'll add it as a testcase to prevent future regressions.

**Comment by sunew** [comment]
Sorry but I've never looked at Zotero TestCases - and right now I'm writing my thesis so I guess it is not right now I'll learn something new :)

**Comment by AllThatIsTheCase** [comment]
Never mind, I'll generate one myself. If you had one, it would make sure it'd cover your specific case.

**Comment by AllThatIsTheCase** [comment]
I'm sorry, I'm finding it hard to replicate your scenario. Exporting a testcase isn't too hard, I think -- just select a reference that has the combination of fields you describe as "Zotero testCase" (it's one of the export formats BBT adds) and then drop it into https://dbinbox.com/allthatisthecase

**Comment by sunew** [comment]
ah, allright - I'll get to it.



On 14 January 2015 at 16:04, AllThatIsTheCase <notifications@github.com>
wrote:

> I'm sorry, I'm finding it hard to replicate your scenario. Exporting a
> testcase isn't too hard, I think -- just select a reference that has the
> combination of fields you describe as "Zotero testCase" (it's one of the
> export formats BBT adds) and then drop it into
> https://dbinbox.com/allthatisthecase
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZotPlus/zotero-better-bibtex/issues/132#issuecomment-69928718>
> .
>



-- 
Sune Brøndum Wøller
+45 24256610
skype: sune.woeller

**Comment by AllThatIsTheCase** [comment]
Any reason to prefer journalsubtitle over subtitle or titleaddon? If I read the manual correctly (and I might not -- I'm not really a BibTeX expert), journaltitle refers to the newspaper name itself for a newspaper article, and the newspaper section isn't so much a subtitle to the newspaper title as it is a chapter of sorts. The manual doesn't really specifically say what to do about sections, but chapters aren't among the valid fields for article.

**Comment by sunew** [comment]
Subtitle is related to the individual article, and the same with titleaddon. That is, related to the item in the periodical, not to the periodical itself. And the section is a subdivision of the periodical, not of the work cited. But I agree, journalsubtitle is not optimal, but I think it is the best choice. Also, for instance with biblatex-chicago, it renders correctly in the bibliography:

![selection_079](https://cloud.githubusercontent.com/assets/893142/5742459/888096a8-9c12-11e4-80c5-9b47d02245bf.png)

I just uploaded the three files - a testcase, the current export of the item, and the suggested export.

**Comment by AllThatIsTheCase** [comment]
Hey, reading Bijker?

Gotcha, good reasoning. I currently get this:

    @article{Boas2014StikordTil,
      author = {Boas, Anders},
      date = {2014-04-07},
      journalsubtitle = {Ideer},
      journaltitle = {Weekendavisen},
      pages = {12},
      title = {Stikord til en hukommelse},
      url = {http://apps.infomedia.dk.ep.fjernadgang.kb.dk/Ms3E/ShowArticle.aspx?outputFormat=Full\&Duid=e4798c41},
      urldate = {2014-09-15}
    }

the only diff is in the date (4/7/2014), which is ambigous against locales; you get 2014-07-04, I get 2014-04-07. If the date is registered as 2014-07-04, it ought to be unambiguous. In any case, I think this is what you want, no?

**Comment by AllThatIsTheCase** [comment]
Tests all pass BTW, so I can release if this is what you need.

**Comment by sunew** [comment]
Cool! Thanks, I'll give a try right away. 
Bijker - yes! I'm very hooked with STS in general. You are also familiar with this field?

**Comment by AllThatIsTheCase** [comment]
I study Philosophy of Science, technology and Society, which is a hybrid between philosophy of science, philosophy of technology and STS. I lean pretty harshly towards (analytic) PoS myself -- I just didn't know Bijker was known outside the Netherlands (where I live).

The new version is out, so you might have updated silently already. Oh, and thanks for the bug report BTW.

**Comment by sunew** [comment]
Yes I have upgraded, and it works perfectly. Thanks for the fix.

**Comment by AllThatIsTheCase** [comment]
Super, always glad to hear from actual users.
