### ISSUE TITLE
Extra ';' in biblatexadata causes export failure

### ISSUE THREAD

**Issue by pipapu** [ZotPlus/zotero-better-bibtex#133]
When loading the .bib file here [ http://axel.rossberg.net/bibview.bib ] into Zotero with ZBB turned on, and then choosing "Export Library" (ZBB mode), I get an unspecified error message ("An error occured...") half way through the export, and it stops. The last item exported is that with key auerbach84:_stabil_probab_and_topol_of_food_webs . Happy to supply more info if this turns out hard to reproduce.

**Comment by AllThatIsTheCase** [comment]
Can you get me an export of your library in the "Zotero TestCase" format? It will give a file with a ".json" extension.

**Comment by pipapu** [comment]
I put it on http://axel.rossberg.net/bibview.json .

**Comment by AllThatIsTheCase** [comment]
Tests are running. The culprit was

    biblatexdata[affiliation=Fu, CL (Reprint Author), Lanzhou Univ, Sch Math & Stat, Lanzhou 730000, Peoples R China.� [Fu, Chu-Li; Deng, Zhi-Liang; Feng, Xiao-Li; Dou, Fang-Fang] Lanzhou Univ, Sch Math & Stat, Lanzhou 730000, Peoples R China.� [Deng, Zhi-Liang] Heilongjiang Univ, Sch Math Sci, Harbin 150080, Peoples R China.;author-email=fuchuli@lzu.edu.cn� zhiliangdeng@gmail.com� fengxl05@163.com� doufang566@163.com;doc-delivery-number=499DD;funding-acknowledgement=National Natural Science Foundation of China [10671085];funding-text=This project was supported by the National Natural Science Foundation� of China (grant 10671085).;journal-iso=SIAM J. Numer. Anal.;keywords-plus=TRANSFORM;number-of-cited-references=13;subject-category=Mathematics, Applied;times-cited=0]

The biblatexdata parser is extremely naive, and assumes a strict format of `biblatexdata[key=value;key=value;key=value]`. The entry above had extra ';'s and that threw the parser off. Making the parser smarter would mean that I'd have to invent a quoting syntax for it, so instead I opted to add a JSON format in addition to the naive format, so in your case, if you wanted the above fields as-is, you'd have to change it into

    biblatexdata{
      "affiliation": "Fu, CL (Reprint Author), Lanzhou Univ, Sch Math & Stat, Lanzhou 730000, Peoples R China.? [Fu, Chu-Li; Deng, Zhi-Liang; Feng, Xiao-Li; Dou, Fang-Fang] Lanzhou Univ, Sch Math & Stat, Lanzhou 730000, Peoples R China.? [Deng, Zhi-Liang] Heilongjiang Univ, Sch Math Sci, Harbin 150080, Peoples R China.",
      "author-email": "fuchuli@lzu.edu.cn? zhiliangdeng@gmail.com? fengxl05@163.com? doufang566@163.com",
      "doc-delivery-number": "499DD",
      "funding-acknowledgement": "National Natural Science Foundation of China [10671085]",
      "funding-text": "This project was supported by the National Natural Science Foundation? of China (grant 10671085).",
      "journal-iso": "SIAM J. Numer. Anal.",
      "keywords-plus": "TRANSFORM",
      "number-of-cited-references": 13,
      "subject-category": "Mathematics, Applied",
      "times-cited": 0
    }

The updated translator will instead treat the former entry as a regular comment and keep it in the notes field, without bombing out.

**Comment by AllThatIsTheCase** [comment]
Tests pass, new release out. Sorry for the inconvenience, but I think this is the cleanest solution

**Comment by pipapu** [comment]
Lovely! Just updated, thank you for fixing this so quickly!

**Comment by AllThatIsTheCase** [comment]
No worries, and again, sorry for the disruption.
