### ISSUE TITLE
spans without attributes break export

### ISSUE THREAD

**Issue by cerinunn** [ZotPlus/zotero-better-bibtex#139]
I am using Better Biblatex for the first time. I also have a new collection that I have created in the last couple of days. 
When I export to Better Biblatex format, I get "An error occured while trying to export the selected file". 

Please see https://gist.github.com/cerinunn/85ed16c0db23538e2778

**Comment by AllThatIsTheCase** [comment]
Wow, an error log! I think there's enough info in the log to find and fix
the problem, but could you get me an export of the entrie(s) in the "Zotero
TestCase" format? You can drop the resulting file in
https://dbinbox.com/allthatisthecase . That will allow me to make sure your
problem is fixed, and to add a testcase to my test suite to make sure it
can't be reintroduced.

**Comment by AllThatIsTheCase** [comment]
To be specific, I think I've found it, and the tests are running, but I'd love to be able to add a testcase to prevent regressions; if I'm right, the problem is with an entry that has html somewhere.
