### ISSUE TITLE
HTML Fragment separator escaped in url

### ISSUE THREAD

**Issue by ghiknt** [ZotPlus/zotero-better-bibtex#140]
I don't know if this a a better-bibtex export or a pandoc biblatex importer issue.  Does biblatex require # to be escaped in the url field?

Issue
===================================================
The html fragment separator "#" is escaped in the biblatex url field causing following parser to produce incorrect URL.

Example
===================================================

Zotero Test Case
----------------------------------------------------------------------------------

```
{
  "config": {
    "id": "82512813-9edb-471c-aebc-eeaaf40c6cf9",
    "label": "Zotero TestCase",
    "release": "0.7.6",
    "preferences": {
      "citeKeyFormat": "[auth][year]",
      "skipfields": [
        ""
      ],
      "useprefix": false,
      "brace-all": true,
      "fancyURLs": false,
      "langid": "babel",
      "attachmentRelativePath": false,
      "auto-abbrev": true,
      "auto-abbrev.style": "http://www.zotero.org/styles/cell",
      "pin-citekeys": "manual",
      "raw-imports": false,
      "doi-and-url": "both"
    },
    "options": {
      "exportFileData": false,
      "exportNotes": true,
      "Export Collections": true
    }
  },
  "collections": [],
  "items": [
    {
      "itemID": 389,
      "itemType": "webpage",
      "url": "http://johnmacfarlane.net/pandoc/README.html#citations",
      "extra": "bibtex: MacFarlaneJohna",
      "accessDate": "2015-01-31 16:24:56",
      "title": "Pandoc User’s Guide",
      "creators": [
        {
          "creatorType": "author",
          "firstName": "",
          "lastName": "MacFarlane, John",
          "fieldMode": ""
        }
      ],
      "notes": [],
      "attachments": [
        {
          "path": "/home/whk/.zotero/zotero/qpj7bsud.default/zotero/storage/R2TFG5NC/README.html",
          "title": "Pandoc - Pandoc User’s Guide",
          "mimeType": "text/html",
          "url": "http://johnmacfarlane.net/pandoc/README.html#citations"
        }
      ],
      "tags": [],
      "related": [],
      "seeAlso": []
    }
  ]
}
```

Export results
-----------------------------------------------------------------------------------
```
@online{MacFarlaneJohna,
  title = {Pandoc {User}’s {Guide}},
  url = {http://johnmacfarlane.net/pandoc/README.html\#citations},
  author = {{MacFarlane, John}},
  urldate = {2015-01-31},
  file = {Pandoc - Pandoc User’s Guide:/home/whk/.zotero/zotero/qpj7bsud.default/zotero/storage/R2TFG5NC/README.html:text/html}
}
```

Resulting pandoc output (I will put a ticket there if the format is supposed to be escaped)
--------------------------------------------------------------------------------------------------
```html
<p>[2]MacFarlane, John, Pandoc User’s Guide, (n.d.). <a href="http://johnmacfarlane.net/pandoc/README.html\#citations" class="uri">http://johnmacfarlane.net/pandoc/README.html\#citations</a> (accessed January 31, 2015).</p>
```

**Comment by AllThatIsTheCase** [comment]
I honestly don't know what the appropriate behavior is; #18 suggests the exact opposite being desirable.

The biblatex manual says "URI fields are processed in verbatim mode and may contain special characters. They are also URL-escaped if they don’t look like they already are", which suggests (next to) nothing should be escaped, but I can't readily find a proper definition of verbatim mode, and where the verbatim mode samples I've seen allow you to choose your own delims, url fields do not, so `}' is obviously a reserved character. I could simply escape only '}' (and likely `{`), but then I can't explain #18.

**Comment by AllThatIsTheCase** [comment]
It looks like yours is the correct view though. The following leaves the `\` in place in writeLatex:

    \documentclass[a4paper,12pt,round]{article}
    \usepackage{filecontents}
    \begin{filecontents}{\jobname.bib}
    @online{MacFarlaneJohna,
      title = {Pandoc {User}’s {Guide}},
      url = {http://johnmacfarlane.net/pandoc/README.html\#citations},
      author = {{MacFarlane, John}},
      urldate = {2015-01-31},
      file = {Pandoc - Pandoc User’s Guide:/home/whk/.zotero/zotero/qpj7bsud.default/zotero/storage/R2TFG5NC/README.html:text/html}
    }
    \end{filecontents}
    \usepackage[T1]{fontenc}
    \usepackage[utf8]{inputenc}
    \usepackage{lipsum}
    \usepackage[style=authortitle-dw]{biblatex}
    \addbibresource{\jobname.bib}
    \usepackage{hyperref}
    \author{Emiliano Heyns}
    \title{\# in URL}
    
    \begin{document}
    \maketitle 
    
    \tableofcontents
    
    \lipsum[1] \Cite{MacFarlaneJohna}
    
    \lipsum[2]
    
    \printbibliography
    \end{document}

**Comment by AllThatIsTheCase** [comment]
Hmm, this could just be the difference then between BibLaTeX and BibTeX. Fortunately, that's easy to differentiate.

**Comment by AllThatIsTheCase** [comment]
New version is out

**Comment by ghiknt** [comment]
Tested with 0.7.9 and looks good.  Thanks.

**Comment by AllThatIsTheCase** [comment]
My pleasure.
