### ISSUE TITLE
capital delta breaks .bib output

### ISSUE THREAD

**Issue by lucisandor** [ZotPlus/zotero-better-bibtex#141]
When citing the paper at http://dx.doi.org/10.1021/ja01623a027 using Better BibTex, the original title causes with Bibtex. Zotero imports the title as 
"11-Oxygenated Steroids. XIII. Synthesis and Proof of Structure of Δ1,4-Pregnadiene-17α,21-diol-3,11,20-trione and Δ1,4-Pregnadiene-11β,17α,21-triol-3,20-dione".
 BetterBibtex outputs:
  title = {11-{Oxygenated} {Steroids}. {XIII}. {Synthesis} and {Proof} of {Structure} of \ensuremath{{\{Delta}}}1,4-{Pregnadiene}-17\ensuremath{{\alpha}},21-diol-3,11,20-trione and \ensuremath{{\{Delta}}}1,4-{Pregnadiene}-11\ensuremath{{\beta}},17\ensuremath{{\alpha}},21-triol-3,20-dione}
Latex throws an error:
] [37]
! Extra }, or forgotten \endgroup.
l.153   \ensuremath{{\{Delta}}}
                             1,4-{Pregnadiene}-17\ensuremath{{\alpha}},21-di...
I've deleted a group-closing symbol because it seems to be
spurious, as in `$x}$'. But perhaps the } is legitimate and
you forgot something else, as in `\hbox{$x}'. In such cases
the way to recover is to insert both the forgotten and the
deleted material, e.g., by typing `I$}'.
Replacing the greek delta with literally "Delta" allows Latex succeed. Another way to fix this Latex error is to replace in the .bib file {{\{Delta}}} with {{\Delta}}

**Comment by AllThatIsTheCase** [comment]
I can reproduce the problem, I'm on it.
