### ISSUE TITLE
Feature request: bib timestamp

### ISSUE THREAD

**Issue by lucisandor** [ZotPlus/zotero-better-bibtex#142]
It would be great if BetterBibtex output would have entries timestamp-ed. It seems to me the field corrresponds to Date Modified in Zotero.

**Comment by AllThatIsTheCase** [comment]
What BibTeX field corresponds to the modified date?

**Comment by lucisandor** [comment]
It should be timestamp. Jabref and Mendeley seem to support it. I looked for the BibTeX specification, but could not find anything, so maybe I am misled.
The other reason I looked for specifications was the format.
I found at https://www.cs.purdue.edu/homes/dgleich/publications/bibtex.html   timestamp = {2014.08.19}
At http://dblp.uni-trier.de/pers/hb/i/Iannacone:Michael_D= they say   timestamp = {Sun, 13 Jul 2014 13:59:24 +0200}
At http://www.bibsonomy.org/bib/bibtex/1698046b33601e73d28b2e67602c22aae   timestamp = {2011-05-09T23:10:52.000+0200}
It looks non-standard, but frequently used.

**Comment by lucisandor** [comment]
I see that the code you wrote, "+ @add({name: 'timestamp', value: Zotero.Utilities.strToDate(@item.dateModified || @item.dateAdded)}) if @item.dateModified || @item.dateAdded", is in a js file inside the XPI currently running on my computer (v 0.7.31). But I get no timestamp in the "Better BibTex" nor "Better BibLaTex" output. My setting are probably default except for "abstract,file,keywords" in "Fields to omit from export". Using Zotero Standalone 4.0.26.1 on Linux.

**Comment by AllThatIsTheCase** [comment]
You're right, that'll teach me to always add tests for changes. I've found
the problem, tests are running.
