### ISSUE TITLE
no PMID, PMCID fields

### ISSUE THREAD

**Issue by jjw25** [ZotPlus/zotero-better-bibtex#144]
Individuals writing NIH proposals must include the PubMed Central ID (PMCID) in many citations. Often, investigators will provide the PubMed ID (PMID) if a citation has no PMCID. Therefore, getting PMID and PMCID into bibtex files is critical if Better-bibtex is to be an option for those of us writing NIH proposals.

Zotero stores the PMID and PMCID in the extras field. When a reference is exported using the basic Zotero bibtex export function, the PMID and the PMCID appear as new, separate fields in the bibtex file ("pmid" and "pmcid"). These fields can be identified by csl (or bst) style files when formatting one's bibliography. However, when one exports using Better-BibTex, the PMID and PMCID end up stored in a notes field. BEcause they are not in their own fields, they are not recognized when the bibliography is formatted.

Could the PMID and PMCID numbers (stored by Zotero in the extras field) be exported as separate fields ("pmid" and "pmcid")?

**Comment by AllThatIsTheCase** [comment]
Can you export a sample reference that has these fields using the "Zotero
TestCase" exporter and drop it into https://dbinbox.com/allthatisthecase?

**Comment by AllThatIsTheCase** [comment]
Your wish is my command. 0.7.12 is out.
