### ISSUE TITLE
Cannot get Better Bibtex to work on linux mint, firefox version

### ISSUE THREAD

**Issue by santa-klaus** [ZotPlus/zotero-better-bibtex#145]
Hi,

I am sorry, but I cannot get Better Bibtex to work. I am using the firefox version of zotero on Linux mint. Actually none of the features works although the buttons and preferences show up as I would expect. When I try to export using "Better Biblatex" as option, I get the error message "Ein Fehler ist aufgetreten bei dem Versuch, die ausgewählte Datei zu exportieren." which translates to "An error occured while trying to export the selected file". I sent you the log to your dbinbox.

Thanks in advance!

Update: I tried to connect to http://localhost:23119/better-bibtex/collection, it shows the standard firefox error msg for no connection.

**Comment by AllThatIsTheCase** [comment]
If you look in your zotero data directory, do you see a file named "betterbibtex.sqlite"?

**Comment by santa-klaus** [comment]
Wow, you are fast! Yup, its there.
![bildschirmfoto vom 2015-02-07 19 31 45](https://cloud.githubusercontent.com/assets/10899463/6093342/0216e706-af00-11e4-8736-6d6ef3d7ef3b.png)

**Comment by AllThatIsTheCase** [comment]
I try to be. Can you close firefox, and then drop that file into dbinbox? There's no sensitive data in the database.

**Comment by santa-klaus** [comment]
Just noticed the file was owned by root. Changed that and retried, issue is still there. Tell me if you want a new log.
Put the (new) database in the inbox.

**Comment by AllThatIsTheCase** [comment]
A new log would be helpful. How come the file was owned by root? Are there more files or directories that have wrong owners/permissions?

**Comment by santa-klaus** [comment]
Sent you a new log.

Well, I had some problems updating zotero standalone, so I sudo'ed. Maybe a bad idea... I made sure that all files in ~/.zotero are owned by me not root. Any other folder to look at?

**Comment by AllThatIsTheCase** [comment]
I don't understand; did you run the upgrade as root (using `sudo apt-get upgrade firefox`), or did you run firefox itself as root? The first should not have created any root-owned files in your home dir. The latter might have, but you *definately* don't want to run firefox as root. In any case, you'd have to look at the firefox profile files in addition to ~/.zotero.

I'm afraid it is the latter, and it has left the installation in a inconsistent state; the last log shows a query that hasn't been in BBT in at least as far back as november 2014, so I'm certain you're not running a (coherent) 0.7.11 version of BBT.

I'm afraid that problems will always plague this installation, and I'm not sure how to fix that from here. You can test if this is the problem by starting firefix with `-p`, create a new profile, and if that doesn't yield any errors. But really my recommendation would be to simply remove your .zotero directory if it doesn't have valuable data, delete the whole firefox profile dir, and start with a clean slate.

**Comment by santa-klaus** [comment]
Sorry for the misunderstanding:
I never ran firefox as root, nor upgraded it. I was talking about zotero standalone (which I don´t use anymore, but maybe shares the folders?).

As for the version of BBT: I think I use 0.6.10, at least thats what it says in my firefox extensions page. I downloaded it today from this github page.

**Comment by AllThatIsTheCase** [comment]
Yeah, they share a folder, but only the zotero data folder, so your firefox profile would be OK. The rest is sort of explainable by you running 0.6.10; sorry about that, I don't use github releases anymore. The front page gives you a link to 0.7.12 -- try that. I'd probably still recommend nixing the `.zotero` dir, but you could give it a try.

**Comment by santa-klaus** [comment]
`I'd probably still recommend nixing the .zotero dir, but you could give it a try.`

Will that delete my bibliography?

**Comment by AllThatIsTheCase** [comment]
It would! Don't do it if there's stuff of value in there!

**Comment by AllThatIsTheCase** [comment]
Just make sure ownership of the other files in the zotero dir are OK, and give 0.7.12 a go.

**Comment by santa-klaus** [comment]
Wow, it works now.

Thank you very much so far!

Sadly, I noticed some problems concerning german umlauts which didn´t apper using the standard zotero biblatex export. Shall I open a new issue for it and close this one?

**Comment by AllThatIsTheCase** [comment]
Great! Yes, new issue please.
