### ISSUE TITLE
German Umlaut "separated" by brackets

### ISSUE THREAD

**Issue by santa-klaus** [ZotPlus/zotero-better-bibtex#146]
In my library I got a title with the word `Elektrizitätsverteilungs-Systeme` in it. After exporting using BetterBibLaTeX, it looks like this: `{Elektrizita}̈tsverteilungs-{Systeme}}`. In my editor, the umlaut-points are now above the `t` and I get the compile error `Package inputenc Error: Unicode char \u8:Ì not set up for use with LaTeX.`

Apart from this issue, I don´t get why and how words are included in brackets. The standard export doesn´t do this, so whats the benefit?

Edit: Import/Export settings of BBT are set to default, so it should be Unicode...

**Comment by AllThatIsTheCase** [comment]
There's several things going on here:

1. Words are enclosed in brackets to make sure biblatex doesn't downcase them; the assumption is that if you have uppercase in your reference, you want it there. The braces make sure that is the case. I'm surprised the standard exporter doesn't do this, because it did use to.
2. The word being cut off there is the actual problem. I think the `ä` is not actually a single character, but a composite character of an `a` and an overlaid umlaut, and XRegexp apparently sees the superimposed as a separate character. Bummer, that's going to be a tricky one. Can you export that reference using the `Zotero TestCase` exporter, and drop it into dbinbox?

**Comment by AllThatIsTheCase** [comment]
Just checked, and the standard exporters do something alike, but they're more conservative. I'll look into that.

**Comment by santa-klaus** [comment]
Sorry, forget that first file - clicked the wrong one.

There is actually something very funny going on, because if I manually replace the character with an `ä`. Also, a lot of umlauts are working correctly. In the testfile the originally cited one will work now, but the one from the publisher wont.

I cant remember if I imported this entry from some library...

**Comment by AllThatIsTheCase** [comment]
Yup, it's a composite char. If I open it in `vi`, the umlaut is actually more between the 't' and the 'a' than it is actually over the `a`. I'll see if I can fix this.

**Comment by AllThatIsTheCase** [comment]
It should work regardless. I'm looking into it.

**Comment by santa-klaus** [comment]
So this happens because of some strange encoding conversion going on earlier?

If its not for practice or perfectionism on your side I don´t rely on a fix for that. In my eyes it seems to be a bug from open worldcat, and I can manually correct the few fields affected.

**Comment by AllThatIsTheCase** [comment]
A general dictum of good software engineering is the robustness principle: "be conservative in what you do, be liberal in what you accept from others". I see it as my duty to make sure it works flawless wherever possible.

Yes, it is a problem which is triggered with the input, but the input is not wrong perse, and if it affected you, it will affect others. I'm going to try to fix it.

**Comment by AllThatIsTheCase** [comment]
I found a fix, and it coincidentally fixed another problem I was having with my automated tests, so thanks for reporting the issue. You should no longer experience problems with imports from sites such as worldcat -- if you do, please open a new issue.

**Comment by santa-klaus** [comment]
Okay, cannot test it at the moment as I fixed the two characters in this entry manually. Thanks!

**Comment by AllThatIsTheCase** [comment]
No worries, it was just an FYI
