### ISSUE TITLE
Feature Request: Specify custom reference type

### ISSUE THREAD

**Issue by santa-klaus** [ZotPlus/zotero-better-bibtex#147]
Biblatex gives you the opportunity to specify custom input types, referred to as custom[a-f]. It would be great to have the possibility to not only set extra fields but also the type of the entry with BBT so one could use this types (or define own ones).

**Comment by AllThatIsTheCase** [comment]
You mean a facility to generate for example?

    @myownreftype{citekey, ..... }

**Comment by AllThatIsTheCase** [comment]
Something like this would be easy to add, but isn't the `type` field supposed to do the same?

**Comment by santa-klaus** [comment]
To be honest, I am very new to Biblatex, so I don´t know very well about these things. I just read about the custom reference types like @customa{citekey,...} and thought that would be a good thing to have.

For my use-case type and keyword were the better options to go, as I found out later. Still, I think this is an useful feature, so thank you for adding it!
