### ISSUE TITLE
Export failing again

### ISSUE THREAD

**Issue by santa-klaus** [ZotPlus/zotero-better-bibtex#148]
Hi,
I am sorry to open another issue... I don´t have a clue what might have happened, but I cannot export anymore. I get the same error report as before (issue #145), 

I uploaded the error log to the zotero server, ID D2020555024.
"An error occured while trying to export the selected file"
Reinstalling BBT through Firefox Add-on manager did not resolve this issue...

**Comment by AllThatIsTheCase** [comment]
I don't have access to the logs sent to the zotero server, so you'll have to use dbinbox again.

**Comment by santa-klaus** [comment]
Okay, done. Issue.txt is the files name, forgot to add the #.

**Comment by AllThatIsTheCase** [comment]
What version of Firefox are you running?

**Comment by santa-klaus** [comment]
30.0

**Comment by AllThatIsTheCase** [comment]
Ah, that explains it. Any chance of upgrading to 31+? Otherwise I'll have to introduce a shim, but that would make the already hefty translator another 130k bigger.

**Comment by santa-klaus** [comment]
Probably a little older version of BBT (like 0.7.12 or so) would still work, right? Any chance I can use that one? When I am finished with my current thesis I will make a new install to my system with a then again supported version of linux ;)

**Comment by AllThatIsTheCase** [comment]
You could try (all older versions are still online at https://zotplus.github.io/better-bibtex/zotero-better-bibtex-[version].xpi) but I can't fix any problems on those.

**Comment by santa-klaus** [comment]
0.7.15 works. So I will use this for now and update as soon as possible. Thanks for the fast help, you are great.

**Comment by AllThatIsTheCase** [comment]
My pleasure. I'm sorry I couldn't get you a better solution.

**Comment by AllThatIsTheCase** [comment]
I have released a new version that should be compatible with FF30, but it will have the problem of #146, no way around that.
