### ISSUE TITLE
Could preserveCaps add {} in front of Caps in export?

### ISSUE THREAD

**Issue by ocepanda** [ZotPlus/zotero-better-bibtex#150]
I have selected the "All words with capitals" under "Preserve capitalization", I found that the export title, while preserve the Cap in the tex file, without the {} BiberLaTex in some style (e.g. APA) would turn that into sentence cases. I tried very hard to look at the code in Better BibLaTeX.js and attempt to figure this out myself but I am not really a programming person so I failed to make such changes myself.... I only figure out it is something related to preserveCap :(

Could this be done?

Thank you very much. (And Better BibLaTeX saved a lot of my time already so if this can't be done I still would give you a big thank you!)

**Comment by AllThatIsTheCase** [comment]
Can you give me an example of what you get and what you want it to look
like?

**Comment by AllThatIsTheCase** [comment]
Oh and you really don't want to look at Better BibLaTeX.js, it's generated from a [coffeescript source](https://github.com/ZotPlus/zotero-better-bibtex/blob/master/resource/translators/Better%20BibLaTeX.coffee), although the caps preserving is done in the [generic translator scaffolding](https://github.com/ZotPlus/zotero-better-bibtex/blob/master/resource/translators/translator.coffee)

**Comment by ocepanda** [comment]
Thanks a lot! I have actually modified all the titles in my zotero database with corrected sentence case over 400 publications, e.g. Children's peer relations: A quantitative review. 
e.g. A database for writing English

could the export of title be:
 title = {Children's peer relations: {A} quantitative review} 
 title =  {A database for writing {E}nglish}

(Cause APA style in biblatex force all title to Sentence case and removed all my hard work on corrected sentence case... )

Thanks so much!

**Comment by ocepanda** [comment]
I see, cause I saw this: https://github.com/zotero/translators/pull/477/files and thought may be I can change the corresponding lines myself... too naive. :P

**Comment by AllThatIsTheCase** [comment]
Ah, no, that used to be a valid approach. I do try to track the behavior of the Zotero's Bib(La)TeX translator where it makes sense, but the sources have diverged substantially a long time ago.

Functionally, wouldn't declaring `\DeclareFieldFormat[article]{apacase}{#1}` do what you want?

    \documentclass{article}
    \usepackage[UKenglish]{babel}
    \usepackage[style=apa,backend=biber,natbib=true] {biblatex} 
    \DeclareLanguageMapping{british}{british-apa}
    
    \DeclareFieldFormat[article]{apacase}{#1}
    
    \usepackage{filecontents}
    \begin{filecontents}{\jobname.bib}
    @article{A01,
      author = {Author, A.},
      year = {2001},
      title = {The LaTeX companion},
      journaltitle = {Some journ.}
    }
    \end{filecontents}
    \addbibresource{\jobname.bib}
    
    \begin{document}
    Lorem ipsum \autocite{A01}?
    
    \printbibliography
    \end{document}

**Comment by ocepanda** [comment]
OMG :exclamation: that's work perfectly! I am sorry I asked such silly questions and thanks so much for your suggestions. I have read the biberlatex manual and could not figure this out myself. No words can express my gratitude! Thanksx10000!  :bow:

**Comment by AllThatIsTheCase** [comment]
It's not a silly question at all, and it's my pleasure. Don't think that I knew all this arcane stuff from memory -- I had to dig into the biblatex-apa source to see whether it could be done at all. The biblatex manual doesn't mention this, you couldn't have known.

I suspect also that `\DeclareFieldFormat{apacase}{\MakeSentenceCase{#1}}` would change the titles to sentence case everywhere (which is what it looks like you prefer) without you having to sentence case them manually in Zotero.

**Comment by ocepanda** [comment]
You are so nice! 
I actually used \DeclareFieldFormat{apacase}{\MakeSentenceCase{#1}} but it did too well a job on sentence case everything, so I will have to add the {} in the export file from Zotero manually...  So glad now this is solved with a simple {#1} !

**Comment by AllThatIsTheCase** [comment]
Again, my pleasure. I'm trying to be a little more conservative these days about what behavior I build into the translators, both for reasons of maintainability and in order not to overwhelm the user with a plethora of options; in hindsight something like fancy urls should have been handled the same. I hope you don't mind me solving it this way.

**Comment by ocepanda** [comment]
I totally agree with your programming philosophy! :+1:
