### ISSUE TITLE
Icon is too big in Zotero preferences (on OSX)

### ISSUE THREAD

**Issue by jipodine** [ZotPlus/zotero-better-bibtex#151]
Since the last update (2015-02-17), preference icon is too big

![zotero-better-bitex_big-icon](https://cloud.githubusercontent.com/assets/5286023/6228153/a510a956-b6a8-11e4-8161-4a32949001bf.png)

**Comment by AllThatIsTheCase** [comment]
Is this one better? https://dl.dropboxusercontent.com/u/5300806/zotero-better-bibtex-0.7.23.xpi

**Comment by AllThatIsTheCase** [comment]
Dos the latest release solve this?

**Comment by AllThatIsTheCase** [comment]
It looks like it does. Please feel free to reopen if your experience is different -- I'm running on a VM, so it might not be representative.

**Comment by jipodine** [comment]
Fix confirmed! Thanks.

**Comment by AllThatIsTheCase** [comment]
Always a pleasure.
