### ISSUE TITLE
Export Č as {\v C}, not \v{C} 

### ISSUE THREAD

**Issue by ldobl** [ZotPlus/zotero-better-bibtex#152]
I have a problem with ascii export of the letter Č, e.g. with the Zotero imported version of http://arxiv.org/abs/1412.4006. It is exported to \v{C} and this leads to "v. C" appearing in the bibliography, whereas {\v C} is properly interpreted as "Č". 

It seems (http://tex.stackexchange.com/questions/57743/how-to-write-%C3%A4-and-other-umlauts-and-accented-letters-in-bibliography) like it's always safer to use {\something letter} rather than \something{letter} for BibTeX. A similar problem might therefore also appear for other special characters, but I haven't noticed anything like this yet. 

I'm using Better BibTex 0.7.25

(and thanks for the great work).

**Comment by AllThatIsTheCase** [comment]
My pleasure, of course. Can you right-click on an entry that exhibits the problem and choose "Report ZotPlus Error" en post the URL that is shown here?

**Comment by ldobl** [comment]
Oh sorry, sure:
http://goo.gl/qBSHpg

**Comment by AllThatIsTheCase** [comment]
Please don't apologize, it's not something you could have known. The
reporting facility is just a week old, so it's also just that I'm keen to
use it ;)

I'm on the train now, but I have a fix lined up that I could test with your
data,  so a release is probably just a few hours away. Unless the railways
make good on their promise of wifi - and if that happens, it's probably a
good time to start worrying about armageddon.
