### ISSUE TITLE
Import fails to perform @String substitutions

### ISSUE THREAD

**Issue by GeoffRiley** [ZotPlus/zotero-better-bibtex#154]
I have a large .bib file that I've built up over the years, and one thing that I have used is `@String` definitions for all the publishers and publisher addresses.

When I imported into Zotero with the default importer the 'Publisher' picked up correctly, but 'Place' failed and picked up the publisher again.

A quick (fake) example:
```bibtex
@String{pub-FRED = "Freds Publishing"}
@String{pub-FRED:adr = "London, UK"}

@Book{Bert:2001:SQL,
  author = "R. A. Bert",
  title = "SQL is great",
  publisher = pub-FRED,
  address = pub-FRED:adr,
}
```

The easy answer would have been to do a search and replace on `:adr` with `-adr`, if it were not for the fact that I have many foreign titles which did not get correctly transformed with characters like å and ü.

I found your plugin `zotero-better-bibtex`, and thought it sounded like the perfect solution.  Unfortunately it doesn't perform the `@String` substitutions at all.

Are there any plans to do this?  I had a look at the code, but I'm not familiar with coffeescript yet.

**Comment by AllThatIsTheCase** [comment]
It's supposed to do this already. Can I get a copy of the bib file? You can drop it into https://dbinbox.com/allthatisthecase

**Comment by AllThatIsTheCase** [comment]
never mind, I should be able to test with your sample

**Comment by AllThatIsTheCase** [comment]
The test case against your sample above now passes, 0.7.28 released

**Comment by GeoffRiley** [comment]
Fantastic!  That works perfectly.  Thank you.

Sorry for lack of response earlier, I'm in the UK and I posted the bug report just before going to bed!

**Comment by AllThatIsTheCase** [comment]
Please don't apologize, you're helping me making BBT better.
