### ISSUE TITLE
Group Library Pinned keys

### ISSUE THREAD

**Issue by bcolsen** [ZotPlus/zotero-better-bibtex#156]
First I would like to thank-you for this sweet addon for zotero.  My research group is writing a paper in google docs using pandoc markdown and it's working wonders.  I have only two things that seem odd(I'll make two bug reports)

What happens:
In a group library.  I "Generate Bibtex key" and the extra field is populated with a key. If I edit a the extra field the citekey changes and the * disapears in the extra column...(I think that means it's "pinned"?).  If I edit a key or "Generate Bibtex key" on a different item in a the same library the key for the origional item will revert to the auto generated key and the * will return.

I would expect the key to retain my custom "pinned" key.

**Comment by AllThatIsTheCase** [comment]
It totally should. I will investigate.

**Comment by AllThatIsTheCase** [comment]
That was a tricky one. First startup after upgrade will take a little longer than usual, after that it should be as normal.

**Comment by AllThatIsTheCase** [comment]
Mind that for consistency, you will want to have the cite key pattern the same for all group participants.

**Comment by bcolsen** [comment]
Thanks for the quick response. I will try this out on Monday.  

I'm leaving the standard author year cite pattern.  It was just the the extra characters kept changing on us.

**Comment by AllThatIsTheCase** [comment]
I'm glad to hear you consider it quick :) It took me a full day to get it done. Good find BTW, glad I could get to fix it.

**Comment by AllThatIsTheCase** [comment]
Oh and yeah the asterix means it's not pinned, that's correct.
