### ISSUE TITLE
Group Library key and personal library key conflicts

### ISSUE THREAD

**Issue by bcolsen** [ZotPlus/zotero-better-bibtex#157]
What Happens:
If I have and existing key in my personal library such as "Smith2015",  and I add the same paper to synced group library I get an automatic cite key of "Smith2015a". 

What I expect:
The group library to get "Smith2015" since there are no duplicates found in this library.
I think I would only worry about intra library cite key conflicts.

**Comment by AllThatIsTheCase** [comment]
That should indeed be the case. I'll look into this.

**Comment by AllThatIsTheCase** [comment]
Fixed along with #156
