### ISSUE TITLE
How to debug AUX file import?

### ISSUE THREAD

**Issue by Anaphory** [ZotPlus/zotero-better-bibtex#158]
At some point I randomly stumbled upon the possibility to import LaTeX-generated .aux files into Zotero (I later tried to use the feature again and could not – it took me some time to realise it's provided by z-b-b, but that it was on a separate machine that did not have z-b-b installed.)

It worked quite well for a while, but has somewhat recently stopped working properly: I now have the problem that after importing an aux file, the BibTeX AUX scanner item lists all items from the AUX file as “missing references”. This includes both items that got their BibTeX name explicitly set (“Extra: `bibtex: wals`” – “* wals” turns up in the AUX scanner report) and those that did not.

How do I fix this, or how do I help debugging?

**Comment by AllThatIsTheCase** [comment]
Please go into Preferences->Advanced->Enable, reproduce the problem, and then select "Report ZotPlus Errors" from the zotero gear menu. You'll be presented with a short URL, please post that URL here.

**Comment by AllThatIsTheCase** [comment]
Oh and could you drop the aux file in https://dbinbox.com/allthatisthecase

**Comment by Anaphory** [comment]
The report has been pasted to http://goo.gl/cr9Ihk

The `Extra:` field of the generated “BibTeX AUX Scanner” ‘Journal Article’ is

    Missing references:
    * atkinson2005curious
    * bouckaert2012mapping
    * bouckaert2014beast
    * bybee1994evolution
    […]
    * wals
    […]

The AUX file is now https://gist.github.com/Anaphory/7c027bacd69a95369377

One of the items in there, `wals`, is in my Zotero library with the following report.

    Type 	Document
    Contributor 	Matthew S. Dryer
    Contributor 	Martin Haspelmath
    URL 	http://wals.info
    Publisher 	Leipzig: Max Planck Institute for Evolutionary Anthropology
    Date 	2013
    Extra 	bibtex: wals
    Abstract 	The World Atlas of Language Structures (WALS) is a large database of structural (phonological, grammatical, lexical) properties of languages gathered from descriptive materials (such as reference grammars) by a team of 55 authors.
    Short Title 	WALS Online
    Date Added 	10/22/2014, 12:24:39 AM
    Modified 	3/5/2015, 2:03:58 PM

**Comment by Anaphory** [comment]
Oh, this was in some way a logging problem?
Do I now just expect a BBT update, and then it should work?

**Comment by AllThatIsTheCase** [comment]
Nope, the logging fix is a performance enhancement that just made it into
the same release. The problem was that I forgot to check against the
library id - the aux scanner only worked for group libraries, not the main
library.

**Comment by AllThatIsTheCase** [comment]
Oh and yes, upgrade and it should be fixed.

Thanks for reporting the bug!
