### ISSUE TITLE
Capitalisation in techreport titles 

### ISSUE THREAD

**Issue by pmgurman** [ZotPlus/zotero-better-bibtex#160]
Firstly, thanks for this extension to zotero, it works great and has solved a lot of my issues in using bibtex from zotero. I am having one issue with getting titles for techreports. The issue is that if the title contains italics (produced by using `<i>Text</i>` in the zotero title field) then the rest of the title that contains captials is not wrapped with brackets. As an example a title that did not work correctly is

`title = {\emph{Salmonella} in Pork (SALINPORK): Pre-harvest and Harvest Control Options Based on Epidemiologic, Diagnostic and Economic Research: Final Report}`

and without italics

`title = {Domestic {Fridge} {Survey}}`

In the export section of the better bibtex export, i have selected the preserve capitalisation for all words with capitals option.

**Comment by AllThatIsTheCase** [comment]
Can you right-click the entry that doesn't work as you want, select "Report Zotplus", and post the resulting url here?

**Comment by pmgurman** [comment]
> [JavaScript Error: "bad script XDR magic number"]
> [JavaScript Error: "bad script XDR magic number"]
> [zoteroautoexporting] Group or search have not a sub:OzFoodNet
> 1425512705567	addons.update-checker	WARN	Update manifest for zoteroOpenOfficeIntegration@zotero.org did not contain an updates property
> 1425512705931	addons.update-checker	WARN	Update manifest for zoteroWinWordIntegration@zotero.org did not contain an updates property

> version => 4.0.26.1, platform => Win32, oscpu => Windows NT 6.1; WOW64, locale => en-US, appName => Zotero, appVersion => 4.0.26.1, extensions => Zotero automatic export (1.1.9.1, extension), ZotFile (4.1.3, extension), Zotero LibreOffice Integration (3.5.9.SA.4.0.26.1, extension), Zotero Word for Windows Integration (3.1.18.SA.4.0.26.1, extension), Zotero Better Bib(La)Tex (0.7.33, extension), Shockwave Flash (16.0.0.305, plugin), Google Update (1.3.26.9, plugin), Adobe Acrobat (11.0.10.32, plugin), Java(TM) Platform SE 8 U25 (11.25.2.18, plugin), Java Deployment Toolkit 8.0.250.18 (11.25.2.18, plugin), Silverlight Plug-In (5.1.30514.0, plugin), Microsoft Office 2010 (14.0.4761.1000, plugin), Microsoft Office 2010 (14.0.4730.1010, plugin)


> {
>   "config": {
>    "id": "82512813-9edb-471c-aebc-eeaaf40c6cf9",
>    "label": "Zotero TestCase",
>    "release": "0.7.32",
.    "preferences": {
>      "citeKeyFormat": "[auth]_[year]",
>      "skipfields": [
>        ""
>      ],
>      "useprefix": false,
>      "preserveCaps": "all",
>      "fancyURLs": false,
>      "langid": "babel",
>     "attachmentRelativePath": false,
>      "auto-abbrev": true,
>      "auto-abbrev.style": "http://www.zotero.org/styles/cell",
>      "pin-citekeys": "manual",
>      "raw-imports": false,
>      "doi-and-url": "doi",
>      "attachmentsNoMetadata": false
>    },
>    "options": {
>     "exportFileData": false,
>      "exportNotes": true,
>      "Export Collections": true
>    }
>  },
>  "collections": [],
>  "items": [
>    {
>      "itemID": 136,
>      "itemType": "report",
>      "url": "http://www.dfvf.dk/Files/Filer/Zoonosecentret/Publikationer/Salinpork/SALINPORK_final_report.pdf",
>      "date": "2000",
>      "institution": "Royal Veterinary and Agricultural University, Department of Animal Health and Animal Science, Division of Ethology and Health",
>      "title": "<i>Salmonella</i> in Pork (SALINPORK): Pre-harvest and Harvest Control Options Based on Epidemiologic, Diagnostic and Economic Research: Final Report",
>      "shortTitle": "<i>Salmonella</i> in Pork (SALINPORK): Pre-harvest and Harvest Control Options Based on Epidemiologic, Diagnostic and Economic Research: Final Report",
>      "creators": [
>        {
>          "creatorType": "author",
>          "firstName": "T.",
>          "lastName": "Hald",
>          "fieldMode": ""
>        },
>        {
>          "creatorType": "author",
>          "firstName": "D.M.A.L.F.",
>         "lastName": "Wong",
>          "fieldMode": ""
>        }
>      ],
>      "notes": [],
>      "attachments": [
>        {
>          "path": "C:\\UserData\\ZoteroDatabase\\storage\\8BTMWQHX\\SALINPORK_final_report.pdf",
>          "title": "SALINPORK_final_report.pdf",
>          "mimeType": "application/pdf",
>          "url": ""
>        }
>      ],
>      "tags": [],
>      "related": [],
>      "seeAlso": [],
>      "publisher": "Royal Veterinary and Agricultural University, Department of Animal Health and Animal Science, Division of Ethology and Health"
>    }
>  ]
>}

**Comment by AllThatIsTheCase** [comment]
Ah, could you click "continue" in the report window and post just the red url? The github issue tracker meddles with the formatting.

**Comment by pmgurman** [comment]
http://goo.gl/uBZFAs

**Comment by AllThatIsTheCase** [comment]
OK, I see. I take it you expect

    
    @report{hald2000,
      title = {\emph{Salmonella} in {Pork} ({SALINPORK}): {Pre}-harvest and {Harvest} {Control} {Options} {Based} on {Epidemiologic}, {Diagnostic} and {Economic} {Research}: {Final} {Report}},
      url = {http://www.dfvf.dk/Files/Filer/Zoonosecentret/Publikationer/Salinpork/SALINPORK_final_report.pdf},
      shorttitle = {\emph{Salmonella} in {Pork} ({SALINPORK}): {Pre}-harvest and {Harvest} {Control} {Options} {Based} on {Epidemiologic}, {Diagnostic} and {Economic} {Research}: {Final} {Report}},
      timestamp = {2015-03-05 23:40:44},
      institution = {Royal {Veterinary} and {Agricultural} {University}, {Department} of {Animal} {Health} and {Animal} {Science}, {Division} of {Ethology} and {Health}},
      author = {Hald, {T}. and {Wong}, {D}.{M}.{A}.{L}.{F}.},
      date = {2000}
    }
    
I'll get on it.

**Comment by pmgurman** [comment]
Yes that looks right. It works fine for articles but not reports.

**Comment by AllThatIsTheCase** [comment]
Wow, that's peculiar. Anyhow, now that I have a test case it should be easy
enough to fix.
