### ISSUE TITLE
performance during pull export degraded after last upgrade

### ISSUE THREAD

**Issue by sunew** [ZotPlus/zotero-better-bibtex#161]
I'm exporting my entire library with a command line script.
Before the last update (0.7.33 at least I noticed it with that update) it took between 5 and 10 seconds. Now it is consistently about a minute.
Perhaps you already know / have some hints to the cause?

**Comment by AllThatIsTheCase** [comment]
Wow, that's a huge difference. So this was introduced with .33? I don't immediately see anything that could be the cause of this yet -- it would be helpful if you have some idea about what version had the more desirable performance.

For another test, could you upgrade to .34, and set `extensions.zotero.translators.better-bibtex.caching` in `about:config` to `true`, and then run your script twice... if the caching is effective, the second (and following) runs should be much faster.

**Comment by AllThatIsTheCase** [comment]
As an aside, would it be possible to export your library to `Zotero TestCase` and drop the result in https://dbinbox.com/allthatisthecase? That way I could do more directed tests.

**Comment by AllThatIsTheCase** [comment]
Could you see if this makes any difference: https://dl.dropboxusercontent.com/u/5300806/zotero-better-bibtex-0.7.34.xpi

**Comment by AllThatIsTheCase** [comment]
Really odd. If I look at the timing at CircleCI and Travis, if anything, the export has gotten slightly faster.

**Comment by sunew** [comment]
just upgraded to .34 
With caching enabled the export takes much longer - I did not let it finish. It was running for about 5 minuttes with very heavy disk access during the export.
Disable cahing again and back to about one minute (a little more after a zotero restart, a little less after running once). No noticeable disk access during export with cache disabled.

**Comment by sunew** [comment]
I'm running zotero 4.0.26, standalone. With Zotfile, linking to my files placed outside of zotero folder.

**Comment by sunew** [comment]
just sent you my zotero library as test case.

**Comment by sunew** [comment]
testcase export went quick - a manual (no url) better biblatex export (even without collections) also takes about a minute.

**Comment by sunew** [comment]
actually it is not a big problem for me - just thought I'd report it. Luxury if we could get back the old performance though:) It could also be related to the last few zotero updates - dont know what is the cause. My library have not grown so much lately (pehaps a 50 to a 100 more references - max!- after the problem began)

**Comment by sunew** [comment]
my export script: 

    #!/bin/sh
    curl --connect-timeout 5 -o Zotero.bib http://localhost:23119/better-bibtex/library?library.biblatex

**Comment by AllThatIsTheCase** [comment]
I don't think it relates to Zotero upgrades -- the last Zotero upgrade was from before .33. I do consider this performance loss to be a major issue; at some point, script timeouts are going to break stuff. The testcase export hardly does anything, so that speed is easily explained. That caching makes things *worse* is also not great.

**Comment by AllThatIsTheCase** [comment]
Ah wait, with caching, did the first-time full export take very long, or the second? The first would be a little (but just a little) less worrisome than the second.

**Comment by sunew** [comment]
With caching it was impossible - I never let the first run finish - stopped it after 5 minuttes. With caching enabled, there was intensive diskaccess. Does the caching perhaps access the attached files or something like that? Related to some combination of zotfile and betterbibtex?

**Comment by sunew** [comment]
sorry forget about the caching issue! There must have been some other problem last night:)

**Comment by sunew** [comment]
Okay here we go: 
I enabled caching.
First time: 20 seconds
Second time: 6 seconds.

Seems we have good performance again.

**Comment by sunew** [comment]
Just a quick question: How is the cache of items invalidated? On edit of an item?

**Comment by AllThatIsTheCase** [comment]
Wait what? The 20 seconds is for your full library? What happened?

**Comment by sunew** [comment]
Yes. I cannot reproduce the one-minute export time any longer, even though they were consistent for a long period of time. The 20 seconds is about normal for a freshly started zotero. 
I must admit it could have been a local problem on my side - I'm really sorry for the noice if that is the case.

**Comment by AllThatIsTheCase** [comment]
The cache for a reference is invalidated when:
* it has a dynamic (non-pinned) key, and either:
  * a pinned key is generated that equals its current dynamic one
  * the format pattern is changed
* it is modified in any way

The cache for a reference is retained but ignored when:
* Any of the BBT settings change except the format pattern.

The latter is an outflow of the fact that cache entries are saved relative to their "context", which is largely just the relevant export settings; I'm still thinking about a non-aggressive way to reap those. I have caching enabled myself, and the automated tests do too, but I want to wait for public release of the feature until I have an idea about cache reaping. Unless you change settings often (which I do as part of dog-fooding BBT) you shouldn't have to worry about cache pollution too much.

The caching doesn't touch the attachments in any way, just the references.

As an aside, I'd hugely prefer it if people wouldn't apologize for reporting problems, even if they do turn out to be transient. I'd rather have one reported too many than have one reported too few, and I appreciate the time people take to get me debug information.

If you choose to keep caching enabled, don't hesitate for a second to report any problems, but please do make mention of it when you do report.

**Comment by sunew** [comment]
Allright, thanks for the caching info - this seems sensible. I keep cache enable for now. 

And I like your policy on bug reporting. Next time I'll try to reproduce on a freshly booted machine, though ;)

Thanks again for the communication speed! Really apreciated.

**Comment by AllThatIsTheCase** [comment]
It is my pleasure.

**Comment by AllThatIsTheCase** [comment]
No such reports are ever in vain. It prompted me to work towards releasing the caching and add the cache test to my automated builds, and it's pretty clear I need to get this out. Your library is now the basis for the cache tests, with these consistent results on travis:

* Unprimed cache: 57 seconds
* Primed cached: 3.56 seconds

Even on my slow dev system I consistently get a factor 10 speedup. Relevant difference I should think! And I also think I've found a nice way to do cache reaping.

**Comment by sunew** [comment]
Great!

I had some trouble getting changed items exported when caching is enabled (editing the author for instance) Disabling cache of course got me the updated data in the export.

Is this a bug or should the bibtex key change? I interpret what you described above that any change of an item should invalidate the cache for this item?

**Comment by AllThatIsTheCase** [comment]
This is most definitely a bug. I think I've found it, tests are running.

**Comment by AllThatIsTheCase** [comment]
OK, fix is out.

**Comment by sunew** [comment]
super - I'll upgrade

**Comment by sunew** [comment]
Ok - seems to be working. Thanks for the quick fix!

**Comment by AllThatIsTheCase** [comment]
Phew - great. Cache reaping is currently (quite arbitrarily) set at one month after last access.
