### ISSUE TITLE
Issue Tracker for ZotPlus/zotero-citations

### ISSUE THREAD

**Issue by balrok** [ZotPlus/zotero-better-bibtex#162]
There is no issue tracker for the *zotero-citations* project.

Since I can find no contact information I have to put this request here.

My bugreport for this project:

When running *zotero-citations:scan* the request looks like this:

     curl "http://localhost:23119/better-bibtex/schomd" -H "Origin: file://" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Atom/0.186.0 Chrome/40.0.2214.91 AtomShell/0.21.0 Safari/537.36" -H "Content-Type: text/plain;charset=UTF-8" --data-binary "{""method"":""bibliography"",""params"":[""cell"",[""Yakovlev1998a"",""Patil1972""]]}" --compressed

and the response like this

    {"jsonrpc":"2.0","error":{"code":5000,"message":"Zotero.Cite.System.retrieveItem called on non-item false\nundefined"},"id":null}

Zotero Version 4.0.26.1
BBT Version 0.7.33
zotero-citation: latest from git

**Comment by AllThatIsTheCase** [comment]
Sorry about that. I just pushed a change that should fix it. I've also enabled the tracker on the project -- that was an oversight on my part.
