### ISSUE TITLE
Problem with caching

### ISSUE THREAD

**Issue by sunew** [ZotPlus/zotero-better-bibtex#164]
Newer reference changes does show up in bibtex file. You have my library - try to reproduce with 

Klimatilpasning Kokkedal, and Fredensborg Kommune. Klimatilpasning Kokkedal. Dommerbetænkning 1. Etape 2012, 2012.

This is now a book item, was previously a document item. I gave it a frozen bibtex key - the old autogenerated key is used. (Not sure what version of that item you have in the copy)

Disabling cache solves the problem.

**Comment by sunew** [comment]
btw . its 0.8.1

Where do I see the released versions btw.?

**Comment by AllThatIsTheCase** [comment]
Let me see if I understand this correctly:
1. You have a document item "Klimatilpasning" etc
2. You change the type to book item
3. You then set a fixed key (generated? manually?)
4. The export produces a book item, but with the wrong key.

correct?

I don't add tags currently at release, I could add that. The currently release version is always listed on the front page -- it's currently 0.8.1.

**Comment by AllThatIsTheCase** [comment]
I think I see it already -- Zotero doesn't give plugins notifications of reference type changes. I have a way to work around this -- coming up.

**Comment by AllThatIsTheCase** [comment]
My bad, it does actually get notifications. Looking for the cause.

**Comment by sunew** [comment]
The item has probably changed several times. First time was change from document to book and a change of author.
The second change, later, was probably a fixation of the key.

I think I got the correct updated item at some point, since I use the correct key in my tex file - and have been building the project without warnings.

But then after a reboot, and re-export of the bibfile from zotero, I got the old values of at least this item, maybe more items.

I suspect a revert to old cache values after the reboot (and restart of zotero as a consequence of the reboot). - But this is just guessing..

**Comment by AllThatIsTheCase** [comment]
That last part is probably due to the fact that there's actually two caching mechanisms at play -- one that caches citation keys for fast access (always on) and full reference caching (optional so far). The citekey cache is in-memory, so it gets restored from the DB on restart. I've changed the item change notifier to be a bit more aggressive about the citekey cache -- I could reproduce the problem earlier, and it's now gone, so I've cut a new release (which it turns out are in fact tagged).

**Comment by sunew** [comment]
excellent - and lightning fast bug fix and release as usual - pure luxury!

**Comment by AllThatIsTheCase** [comment]
I do try.

**Comment by AllThatIsTheCase** [comment]
Can we consider this issue closed?
