### ISSUE TITLE
deleting other info (PMIC, PMCID) stored in extra field

### ISSUE THREAD

**Issue by jjw25** [ZotPlus/zotero-better-bibtex#165]
In my Zotero database, PubMed ID (PMID) and PubMed Central ID (PMCID) are stored in the extra field. Issue #1: when I select a reference, and right click on the "Generate BibTex key" command, it generates the key but sometimes over-writes (deletes) the PMID and PMCID ID's. Seems to overwrite when I already have an existing BibKey in the extra field (along with PMID and PMCID) but want to change the format of the key. Issue #2: the right click "Clear BibTex key " does not seem to do anything in my database (although this is a minor point compared to the first issue).

**Comment by AllThatIsTheCase** [comment]
Can you right-click an entry where you experience the problem, select "Report ZotPlus error", and post the resulting URL (in red) here?

Can you open a second issue for the "Clear BibTeX" problem?

Thanks!

**Comment by AllThatIsTheCase** [comment]
And a release is out.
