### ISSUE TITLE
Betterbibtex overwrites extra field

### ISSUE THREAD

**Issue by lucisandor** [ZotPlus/zotero-better-bibtex#167]
References saved to Zotero until February 25th show, in the extra field, the bibtex key AND whatever else Zotero was adding. In my case, from the Pubmed translator, the extra field includes bibtex and PMID call numbers.
References added after Februray 25th lack PMID #, although the bibtex key is present. Disabling BetterBibtex brings back PMID in the extra field, so I am guessing something changed in Betterbibtex. 
Is the plugin overwriting the extra field, while in the past it used to prepend to it?

**Comment by lucisandor** [comment]
Duplicate of #166

**Comment by AllThatIsTheCase** [comment]
Thanks both for reporting and for noticing the duplicate ☺. Yeah, that was
a pretty big goof up on my part. Never hesitate to report problems though!
I'd rather have duplicates than users suffering in silence.
