### ISSUE TITLE
Better biblatex export is not possible anymore

### ISSUE THREAD

**Issue by CamilleH** [ZotPlus/zotero-better-bibtex#168]
Hello,

I have been able to use the better biblatex export previously but, suddenly, the option disappeared from the export drop down menu. I attach a picture of that menu.

![screenshot from 2015-03-17 09 33 37](https://cloud.githubusercontent.com/assets/127704/6683601/c2490a7c-cc88-11e4-8ef7-f67e15c8d7e2.png)

**Comment by AllThatIsTheCase** [comment]
Are the Better BibTeX preferences still present in the preferences pane?

**Comment by CamilleH** [comment]
Yes, they are. I also tried to reinstall better biblatex but it did not solve the problem.

**Comment by AllThatIsTheCase** [comment]
OK, good.
* go into Preferences->Advanced, check "Enable after restart"
* close down Firefox entirely (all FF windows must be closed or FF won't really restart), 
* after restart, select "report ZotPlus error" from the gear menu
* click through until you see a red URL displayed
* post that URL here

**Comment by CamilleH** [comment]
I cannot see any red URL but the log has thousands of lines so I may have missed it. Is there a particular string close to that URL that I can look for to find it easily?

**Comment by AllThatIsTheCase** [comment]
There ought to be a "continue" button, the resulting window will display a short red URL.

**Comment by CamilleH** [comment]
I see. The url is http://goo.gl/vKNtJ4

**Comment by AllThatIsTheCase** [comment]
There are no errors in the log. Could you try disabling all plugins except zotero and BBT and then restart, to see if the translators come back? Not meant as a permanent solution, but there has been interference by other plugins before (recoll for example), and I'd like to know whether this could be the case. If so, we can work towards narrowing down which it is.

**Comment by CamilleH** [comment]
I disabled all add-ons but Zotero and BBT, but it does not change anything :(

**Comment by CamilleH** [comment]
I installed Zotero standalone instead and it works well.
I also noticed that when I used Zotero with Firefox, the last line in the Import/Export preferences of BBT (Clickable URLs) is not shown. The window is somehow truncated just under "Retain Latex markup ..."

**Comment by AllThatIsTheCase** [comment]
The display issue is unrelated (if annoying) and will be fixed in #159. Can you go to Preferences->Advanced->Files and Folders->Show data directory, and check whether:
* the file "translators/Better BibLaTeX.js" exists, and
* the directory "translators" is writable for the current user by going into that directory and creating a file. You  can remove the file once created, name doesn't matter.

**Comment by CamilleH** [comment]
The file does exist and the directory is writable.

**Comment by AllThatIsTheCase** [comment]
Sheesh, there goes one easy explanation. Could you go into Preferences->Advanced->Files and Folders again, click "Reset translators", restart firefox, and see whether that file reappears?

**Comment by CamilleH** [comment]
Hmm, now I can see the Better BibLatex exporter again in Firefox! I think that the installation of standalone Zotero made it work again, even in Firefox. It could be that the translator did not exist prior to the installation of standalone Zotero. I only checked after I had installed the standalone version.

**Comment by AllThatIsTheCase** [comment]
It's still weird though, the FF installation had the preferences, and BBT
installs the translators anew at every start.

**Comment by CamilleH** [comment]
I had to install BBT in standalone Zotero. Could it be that the installation in FF was broken and installing BBT in the standalone somehow repaired it?

**Comment by AllThatIsTheCase** [comment]
If those two installations shared a profile, it is not impossible, but I
don't immediately see how.

**Comment by CamilleH** [comment]
Anyway, it works now. Thanks for your help!
Shall I close the issue?

**Comment by AllThatIsTheCase** [comment]
Always a pleasure, never a chore. Yes, you can close the issue; I generally leave that up to the user, so I don't close the issue before the customer is satisfied :)
