### ISSUE TITLE
better-bibtex does not use biblatex fields eprint and eprinttype

### ISSUE THREAD

**Issue by DenizSt** [ZotPlus/zotero-better-bibtex#170]
better-biblatex does not correctly export preprints from arXiv (or JSTOR, or Handle). To be biblatex-conformal, it should use the fields `eprint`,`eprinttype`, and `eprintclass`. See the biblatex manual for details.

…Or probably I just didn't see how it can be done with the current version of better-biblatex…?

**Comment by AllThatIsTheCase** [comment]
Could you please do the following:

1. Right-click an entry that doesn't export as you'd expect, select "Report ZotPlus error", click through until you see a red URL and post that here
2. add an BibTeX entry (here, or in a gist) that shows the expected output

and I'm sure I'll be able to fix it quickly.

**Comment by DenizSt** [comment]
Please find the error report here: [http://is.gd/xlAtph](http://is.gd/xlAtph)

In this case, Zotero has filled the "Publisher" field with "arXiv:1412.2970 [math-ph, physics:quant-ph]", which should never be taken as the `journal` field in the output (since arXiv is not a journal).

The output should look like this (I have omitted the fields which may stay unchanged):
```
@article{SomeKey,
  ...
  eprint = {1412.2970},
  eprinttype = {arxiv},
  ...
}
```
Note that there should be no `arxiv`, `journal` or `journaltitle` fields at all!

However, in the case where Zotero's "Publisher" field does _not_ contain some arXiv reference, there _must_ be a `journal` field in the output, filled with the content of the "Publisher" field from Zotero.

To sum it up, the exporter should do the following:

1. Look if Zotero's "Extra" field is of the form `arXiv: 1412.2970` or `arXiv: cond-mat/9504001`, that is, `arXiv:` plus some identifier. Chop off spaces from the identifier.
2. Add fields `eprint = {1412.2970}` (i.e. the identifier) and `eprinttype = {arxiv}` to the output.
3. If the "Publisher" field in Zotero contains the string "arXiv" (don't check case-sensitively!), then there will be no `journal` or `journaltitle` field in the output. Else, do the usual, i.e. copy the content of "Publisher" or "Journal Abbr" into the `journal` field.

Might seem like quite some work, but the current output is not biblatex conformal.

(Something similar applies to Handle and JSTOR identifiers, but I am not an expert on that.)

**Comment by AllThatIsTheCase** [comment]
no, it's going to be easy to do, but I'd prefer a full sample of the BibTeX you expect to see, in addition to the great explanation you provide above.

**Comment by AllThatIsTheCase** [comment]
In the case of the publisher field containing 'arxive', do you also expect the eprint and eprinttype to be set from that?

**Comment by AllThatIsTheCase** [comment]
I've been perusing the biblatex manual, but I can't find anything that states that when `eprint`/`eprinttype` is given, the `journal` field must be missing. I have a patch lined up that removes the arxiv/pmid/etc fields and replaces them with `eprint` fields, but I need to have a clear position on the `journal` fields in this case.

**Comment by AllThatIsTheCase** [comment]
Ah, I see now what you mean. The existing change should cover the cases above.

**Comment by retorquere** [comment]
@DenizSt I'm getting a request in #460 which conflicts with your request. Can you shed some light here?

Your request: if the Publication field has "arXiV:...", fill out the relevant eprint fields and don't put out an journaltitle,

https://github.com/retorquere/zotero-better-bibtex/issues/460#issuecomment-211639752 however claims that the arXiv title *should* be retained, because it assumedly indicates the paper is *only* available at arXiv.

The [arXiv docs](https://arxiv.org/hypertex/) aren't very clear on this matter I must say.
