### ISSUE TITLE
Wrong instruction on https://www.zotero.org/support/plugins

### ISSUE THREAD

**Issue by dbitouze** [ZotPlus/zotero-better-bibtex#171]
This isn't a `zotero-better-bibtex` issue by itself but, if I'm right, there is a wrong instruction on https://www.zotero.org/support/plugins#importexport_of_item_metadata_attachments, "Better Bib(La)TeX" item: for the drag-and-drop citations feature, it is said to select "BibTex cite keys" as the default export format, instead of “LaTeX Citation”.

I could create a account on the Zotero wiki in order to fix this error but all my attempts failed. Moreover, I guess you're much better qualified than me for this (I wouldn't like to give myself a wrong instruction).

**Comment by AllThatIsTheCase** [comment]
Thanks for the heads-up! I've changed the Wiki.
