### ISSUE TITLE
Generic link to the latest release

### ISSUE THREAD

**Issue by dbitouze** [ZotPlus/zotero-better-bibtex#172]
In https://github.com/ZotPlus/zotero-better-bibtex#installation-one-time, the link to the latest release in the sentence: "After installation, the plugin will auto-update to [newer releases](https://zotplus.github.io/better-bibtex/zotero-better-bibtex-0.8.11.xpi)." is hard coded, currently:

https://zotplus.github.io/better-bibtex/zotero-better-bibtex-0.8.11.xpi

I would suggest to replace it by a generic one, e.g.:

https://zotplus.github.io/better-bibtex/zotero-better-bibtex-latest-release

which turns to go to the relevant current `.xpi` file.

**Comment by AllThatIsTheCase** [comment]
I can't do redirects on Github Pages, unfortunately. The link is indeed hardcoded, but the deployment script always updates it during the publishing process, and after the first-time installation the plugin is auto-updated by the firefox extension upgrade mechanism, which polls for https://zotplus.github.io/better-bibtex/update.rdf, which in turn always points to the latest version. So the redirect is there, after a fashion. After first-time installation, there;s really no need to ever download the xpi again, and even if you have stumbled upon an older version, auto-update will take care of it.

**Comment by dbitouze** [comment]
I knew for the automatic update but my feature request was because I'd want to give, in a LaTeX course PDF file available online, the direct link to the `zotero-better-bibtex`'s (latest) installation file. But I understand the problem and will instead give the link to the Web page https://github.com/ZotPlus/zotero-better-bibtex#installation-one-time. Thanks.

**Comment by AllThatIsTheCase** [comment]
Ah, that's what you mean. You can use https://zotplus.github.io/better-bibtex/index.html#xpi, which will always trigger a download of the latest version.

**Comment by dbitouze** [comment]
This does the trick: thanks!
