### ISSUE TITLE
Mimicing Zotero's citation scheme

### ISSUE THREAD

**Issue by dillonma** [ZotPlus/zotero-better-bibtex#173]
For those of us that have extensive libraries that use Zotero's unfortunate citation naming scheme, I found that 

    [auth:fold:lower]_[Title:nopunct:skipwords:select,1,1:lower]_[year]

mimics the zotero one pretty closely. I think the one that you posted has the year/title in the wrong order. The above uses underscores (I know, bad), but again, for those of us that need to mimic what Zotero "mostly" does.

**Comment by AllThatIsTheCase** [comment]
Gotcha, that's a nice example, it's in the docs now (or at least it will be as soon as I can push it -- github is under a DDoS attack).
