### ISSUE TITLE
References with multiple notes fail to export

### ISSUE THREAD

**Issue by vanderlindenma** [ZotPlus/zotero-better-bibtex#174]
Back with  "An error occurred while trying to export the selected file" ( I previously posted https://github.com/ZotPlus/zotero-better-bibtex/issues/134)

Report ID : 1864302113.

Report Zotplus ID : http://is.gd/OHv7Qq

Note that part of the library is exported (the .bib file generated is not empty), but it stops at some point (I'd guess after 10 or 20%?)

**Comment by AllThatIsTheCase** [comment]
I've found the problem, tests are running.

**Comment by AllThatIsTheCase** [comment]
0.8.14 is out which includes a fix for this issue.
