### ISSUE TITLE
Link broken: Install by downloading the latest version (0.8.21).

### ISSUE THREAD

**Issue by felixhayashi** [ZotPlus/zotero-better-bibtex#176]
The link in  README.md  gives me a 404

-Felix

**Comment by naegling** [comment]
The link from: https://zotplus.github.io/better-bibtex/latest.html redirects to https://zotplus.github.io/better-bibtex/zotero-better-bibtex-0.8.36.xpi and also returns a 404.

**Comment by AllThatIsTheCase** [comment]
The deploy mechanism was broken; it should all be working again as of now.

**Comment by AllThatIsTheCase** [comment]
Ah, and the 'latest' link has been replaced by `https://zotplus.github.io/better-bibtex/index.html#xpi`

**Comment by naegling** [comment]
Outstanding! Thanks!

**Comment by AllThatIsTheCase** [comment]
Apologies for the disturbance. #175 was caused by a dirty deploy, and I didn't want that to be possible again; releases are now straight from the continuous integration.

**Comment by felixhayashi** [comment]
Thanks @AllThatIsTheCase
