### ISSUE TITLE
Not export again the bibtex key of an already exported reference

### ISSUE THREAD

**Issue by dbitouze** [ZotPlus/zotero-better-bibtex#178]
Hi,

thanks a lot for your very nice addon!

Suppose you cited numerous times a given reference in a very long document (say a PhD thesis), moreover split in different `.tex` chapters files. Suddenly, you notice an error in the author's name of this reference and you fix it in Zotero.

AFAICS, the bib key is based of the author's name, Zotero Better Bib(La)TeX will change it accordingly and you then have to retrieve all the occurrences of this reference's citations in all your `.tex` chapters files in order to reflect this new bibtex key.

Hence my feature request is that, for an already exported reference, Zotero Better Bib(La)TeX exports every field *but* the bibtex key. Or at least that, in case this bibtex key is going to be changed by the export, the user is asked what to do.

Thanks for your attention.

Best regards.

**Comment by AllThatIsTheCase** [comment]
This is already possible; in the export preference, select "on export" as
the key pin policy.

**Comment by dbitouze** [comment]
OK, thanks and sorry for the noise.

**Comment by AllThatIsTheCase** [comment]
My pleasure, and it's not noise. You can feel entirely free to assume I did a lousy job of documenting it. Be well!
