### ISSUE TITLE
autosave not working

### ISSUE THREAD

**Issue by lucisandor** [ZotPlus/zotero-better-bibtex#181]
For your sanity, I hoped we'll never get to this. But just in case, here it is:
A collection was setup to auto-export as BibTex evey time it is changed. I enabled debug, and removed a reference from said collection. The bib file stayed unchanged. The debug console showed:
http://pastebin.com/9itrgB1Q
Every other functionality is OK, so no biggie.

**Comment by retorquere** [comment]
Jeez, I'm insanely sorry about that one, that was sloppy of me :( test are running, and a new release will be put up when they pass.

**Comment by retorquere** [comment]
.15 is out. My sincere apologies, this ought not to have happened. I'll close after you confirm.

**Comment by lucisandor** [comment]
The autosaved .bib file remains unchanged when one item is removed from collection.
The console output is at http://pastebin.com/hFYTxPQ7 It looks like it's a new error.

**Comment by retorquere** [comment]
Could I have an export of your full library in TestCase format? You can
drop it into my dbinbox.

**Comment by retorquere** [comment]
I have added a test for autoexport, but how long did you wait for the file to change? In the version you have the idle time is fixed at 60 seconds; in the one I'll release today it'll be a configurable 10-second default.

**Comment by retorquere** [comment]
Still don't know where the recursion error comes from. Could you try resetting your translators and restarting?

**Comment by retorquere** [comment]
The default delay is now 10 seconds, and there's a hidden pref to set it even shorter should you want.

**Comment by retorquere** [comment]
I can't replicate your remaining error however. Are you exporting your whole library, or a collection? How many items approximately? Do you use on-change or on-idle?

**Comment by lucisandor** [comment]
It's a colection that has 1-10 items. I figured it will take minutes to export the main collection, so I am using two collections - a huge main store and a small working lot. The export is meant to be on change. Auto-save seems to work only when there is no file in place already.

**Comment by retorquere** [comment]
Does that mean if you remove the file and cause a change, it does export on
change? Because the initial export isn't an auto export, it's just a
regular export that as a side effect sets up auto export.

**Comment by lucisandor** [comment]
"Does that mean if you remove the file and cause a change, it does export on
change?" Correct.
The first export has been flawless for the last weeks.

**Comment by retorquere** [comment]
Just to be sure I'm understanding you correctly, this is what you're seeing:

* you perform an export, and you tick "Keep updated"
* you cause a change, nothing happens.
* you remove the file from the first step
* you cause a change
* the file is exported automatically successfully

Correct?

**Comment by retorquere** [comment]
I think I've found the problem and I've added a test for it. I've pushed out a new release (.17). Thank you for reporting the issue!

**Comment by retorquere** [comment]
Feel free to reopen BTW should the problem not be solved.
