### ISSUE TITLE
Automatic export options screen is inactive?

### ISSUE THREAD

**Issue by kendonB** [ZotPlus/zotero-better-bibtex#182]
Is this still to be implemented? None of the option fields (other than the radio buttons at the top) allow me to interact with them.

![tmp](https://cloud.githubusercontent.com/assets/5327505/7401825/edfc4836-ee7b-11e4-9b73-9e8ac05f4f12.png)

**Comment by retorquere** [comment]
This screen only allows review and removal of auto exports. To add new
ones, you'll have to set it up by doing a regular export and ticking "Keep
updated". After setup, the parameters chosen cannot be modified; to affect
a modification, you'll need to remove and add an auto export.

**Comment by kendonB** [comment]
There is no option for "Keep Updated" on my version of Zotero (standalone 4.0.26.4).

Not on the Zotero "Export" tab in preferences, nor the "Import/Export" tab in the Better Bibtex options.

Can you also provide instructions for how to do this initial export with Better Bibtex?

**Comment by retorquere** [comment]
I'll try to provide clearer instructions, but it comes down to doing an
export as you normally would (so right-click on your library or a
collection, choosing "Better BibTeX" or "Better BibLaTeX" as the export
format, tick the "Keep updated" option on that screen, and click OK. The
export will be done as usual, but any changes you make to the library or
relevant collection will be re-exported automatically.
