### ISSUE TITLE
Auto export collection hangs in 0.9.18

### ISSUE THREAD

**Issue by dofine** [ZotPlus/zotero-better-bibtex#183]
I have Zotero standalone 4.0.26.3 on Mac OS X and BBT 0.9.18. 
Problem is that if I right click on the collection name, check "keep updated" and export it, Zotero will hang forever. I have to force close it and there's no exported file at all.
Disabled other plugins and no luck.
If it helps, [here is the Zotero Testcase](https://gist.github.com/dofine/2a30820772940f3f5437) generated with the collection. 

The screenshot means "exporting collection", which hangs here.

![error](http://ww2.sinaimg.cn/large/625c9a47jw1errh8qrjlaj20pw0f8tf7.jpg)

**Comment by jlongrc** [comment]
I have also had this issue on 0.9.18, which appeared right after updating. I'm going to try to reinstall 0.9.17.

**Comment by retorquere** [comment]
.21 is out, and it successfully exports for me. Fortunately, I just got myself a Mac, so I could test.

**Comment by retorquere** [comment]
I'll leave it to you guys to close the issue if the problem is also fixed for you.

**Comment by dofine** [comment]
Fixed for me.
Thanks for such excellent work!
