### ISSUE TITLE
Auto-export of group libraries

### ISSUE THREAD

**Issue by abrasive** [ZotPlus/zotero-better-bibtex#185]
Hello,
I wonder if it might be possible to enable auto-export of group libraries? I'm using the HTTP interface to export my group library at the moment, which is a pain.

There is currently no way to export a group library from Zotero, and it seems they aren't interested presently in adding this feature - see [their ticket](https://github.com/zotero/zotero/issues/487).

Either a context menu entry or a manual way to add things to auto-export would solve this problem.

**Comment by retorquere** [comment]
I have regular export for groups working, auto-export needs more work because the existing export-capture won't work as-is.

**Comment by abrasive** [comment]
Thanks! I've been exporting it manually over HTTP for some time now, hadn't realised there was no UI for doing so.

**Comment by retorquere** [comment]
.23 is out, which adds group (auto-) export. If you find any problems with it (it needed a little trickery to get it working), please file a new issue.

Enjoy!

**Comment by abrasive** [comment]
Fantastic. Thank you very much!

**Comment by retorquere** [comment]
Always a pleasure.
