### ISSUE TITLE
Thrashing on betterbibtex.sqlite

### ISSUE THREAD

**Issue by eigengrau** [ZotPlus/zotero-better-bibtex#186]
I’ve had issues with Firefox sometimes taking in the range of 5 minutes and more to start-up for a while. I finally decided to `strace` the process during start-up, and this showed that practically the complete start-up interval was spent on doing I/O on `betterbibtex.sqlite` (and the corresponding SQLite3 journal file). Surprisingly, most of it seem to be writes. When I temporarily disable Better BibTeX, the 5 minute start-up reduces to a few seconds.

Bug reporter output from one machine below, but it doesn’t seem to be showing much, I guess⁉

Any ideas very welcome.

```
[JavaScript Error: "1431500260766	tabgroupsbtn	ERROR	ReferenceError: prefs is not defined (resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/seb/.mozilla/firefox/nw2x3i1i.default/extensions/tabgroupsbtn@char101.github.com.xpi!/bootstrap.js:20) JS Stack trace: processWindow@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/seb/.mozilla/firefox/nw2x3i1i.default/extensions/tabgroupsbtn@bootstrap.js:20:1 < watcher@addon.jsm:115:7 < runOnLoad/<@addon.jsm:79:7" {file: "resource://gre/modules/Log.jsm" line: 749}]
[JavaScript Error: "not well-formed" {file: "jar:file:///home/seb/.mozilla/firefox/nw2x3i1i.default/extensions/firefox@ghostery.com.xpi!/resources/ghostery/data/locales/en/messages.json" line: 1 column: 1 source: "{"}]
[JavaScript Error: "not well-formed" {file: "jar:file:///home/seb/.mozilla/firefox/nw2x3i1i.default/extensions/firefox@ghostery.com.xpi!/resources/ghostery/data/locales/en/messages.json" line: 1 column: 1 source: "{"}]
[JavaScript Error: "not well-formed" {file: "jar:file:///home/seb/.mozilla/firefox/nw2x3i1i.default/extensions/firefox@ghostery.com.xpi!/resources/ghostery/data/locales/en/messages.json" line: 1 column: 1 source: "{"}]
[JavaScript Error: "not well-formed" {file: "jar:file:///home/seb/.mozilla/firefox/nw2x3i1i.default/extensions/firefox@ghostery.com.xpi!/resources/ghostery/data/locales/en/messages.json" line: 1 column: 1 source: "{"}]
[JavaScript Error: "not well-formed" {file: "jar:file:///home/seb/.mozilla/firefox/nw2x3i1i.default/extensions/firefox@ghostery.com.xpi!/resources/ghostery/data/locales/en/messages.json" line: 1 column: 1 source: "{"}]
[JavaScript Error: "not well-formed" {file: "jar:file:///home/seb/.mozilla/firefox/nw2x3i1i.default/extensions/firefox@ghostery.com.xpi!/resources/ghostery/data/locales/en/messages.json" line: 1 column: 1 source: "{"}]
[JavaScript Error: "not well-formed" {file: "jar:file:///home/seb/.mozilla/firefox/nw2x3i1i.default/extensions/firefox@ghostery.com.xpi!/resources/ghostery/data/locales/en/messages.json" line: 1 column: 1 source: "{"}]
[JavaScript Error: "not well-formed" {file: "jar:file:///home/seb/.mozilla/firefox/nw2x3i1i.default/extensions/firefox@ghostery.com.xpi!/resources/ghostery/data/locales/en/messages.json" line: 1 column: 1 source: "{"}]
[JavaScript Error: "not well-formed" {file: "jar:file:///home/seb/.mozilla/firefox/nw2x3i1i.default/extensions/firefox@ghostery.com.xpi!/resources/ghostery/data/locales/en/messages.json" line: 1 column: 1 source: "{"}]

version => 4.0.26.4, platform => Linux x86_64, oscpu => Linux x86_64, locale => en-US, appName => Firefox, appVersion => 38.0, extensions => Places Maintenance (1.3, extension), Copy Link URL (1.5, extension), Columner (0.5, extension), Grab and Drag (3.2.5.2, extension), Zotero Storage Scanner Plugin (0.0.15, extension), Zutilo Utility for Zotero (1.2.10, extension), FireGestures (1.8.7, extension), Customizable Shortcuts (0.6.2, extension), WikiWand: Wikipedia Modernized (3.1, extension), Google search link fix (1.4.9, extension), All-in-One Sidebar (0.7.25, extension), SSL Version Control (0.4, extension), GNOME Theme Tweak (35.1, extension), Save File to (2.5.4, extension), Save Images (1.1.0, extension), Adblock Edge (2.1.9, extension), Tab Groups Button (0.52, extension), Simple White (2.2.9, theme), NoScript (2.6.9.22, extension), Ghostery (5.4.5, extension), ZotFile (4.1.5, extension), Classic Theme Restorer (1.3.1.1, extension), GNotifier (1.8.9, extension), Zotero Better Bib(La)Tex (0.9.22, extension), Stylish (2.0.2, extension), OpenH264 Video Codec provided by Cisco Systems, Inc. (1.4, plugin), Reddit Revamped (, userstyle), WiTeX (, userstyle), Personas Plus (1.7.3, extension, disabled), Print pages to PDF (0.1.9.3, extension, disabled), RequestPolicy (0.5.28, extension, disabled), Expire history by days (1.1, extension, disabled), Live HTTP headers (0.17, extension, disabled), Export Cookies (1.2, extension, disabled), Bookmark Duplicate Cleaner (0.2, extension, disabled), ScrapBook Plus (1.9.24.40b3, extension, disabled), Firemacs (4.5, extension, disabled), Mouseless Browsing (0.5.6Build201310302030, extension, disabled), Column Reader (4.1, extension, disabled), FoxReplace (0.16.1, extension, disabled), Abduction! (3.5.0, extension, disabled), GNOME (35.1, theme, disabled), Lightbeam (1.2.1, extension, disabled), StumbleUpon (4.19, extension, disabled), TabGroups Menu (0.9.6, extension, disabled), It's All Text! (1.9.1, extension, disabled), Tile Tabs (12.9, extension, disabled), Tranquility (1.1.8, extension, disabled), Greasemonkey (3.1, extension, disabled), Firebug (2.0.9, extension, disabled), Tree Style Tab (0.15.2015030601, extension, disabled), FT DeepDark (12.0.1, theme, disabled), Video DownloadHelper (5.2.0, extension, disabled), ArchView (0.7.2, extension, disabled), IcedTea-Web Plugin (using IcedTea-Web 1.6) (, plugin, disabled)
```

**Comment by retorquere** [comment]
How big a library do you have, and is this on every startup (which is a bug) or only after an upgrade of BBT (which could indeed take a while on large libraries but should occur only once). Even so, writes being the bulk of the work is surprising.

**Comment by eigengrau** [comment]
This happens reliably on every start-up. My Zotero library is fairly large, with about a thousand library items. On this machine, the `zotero.sqlite` store is ~90M. For some reason on my other machine, it’s substantially smaller (the bug affects both machines, though). The odd thing is that for all the thrashing done on `betterbibtex.sqlite`, this file is only 600K.

**Comment by retorquere** [comment]
1000 items is nothing, I have about 2700, and have tested with 15k items. If it's on every startup, it's not the schema upgrade, so I suspect it's doing a library key scan. Do you see a message popup in the bottom left saying 'Citation key rescan' on startup? What platform are you on?

**Comment by eigengrau** [comment]
This is on Linux 3.19.8, Firefox 38.0 (freshly upgraded; I ran into the bug on FF 37 too).

I’m not seeing any popup, I’m afraid. You mean after Firefox has launched, right? I’m only seeing the UI once all the activity to `betterbibtex.sqlite` has ceased. Would it show as some sort of overlay inside the Firefox UI?

**Comment by retorquere** [comment]
It would hover over the FF UI. Could you do the following for me:

* Go into preferences-> Advanced, and tick "enable after restart"
* Download the instrumented BBT from http://is.gd/Q0er7E
* Install and let it restart
* After the startup has completed, select "Report ZotPlus error" from the gear menu and click through until it shows a red URL
* Post that URL here.

**Comment by eigengrau** [comment]
Here’s the [reporter output](http://is.gd/SYIqGT). This is very odd though. Did that build just add instrumentation? Because after installing it, I killed Firefox, restarted it, and it came up almost immediately. So it seemed like the bug was gone. I then reinstalled the default build from the ZotPlus site, and sure enough the bug came back.

**Comment by retorquere** [comment]
It did more than instrumentation; I added a minor change that would have fixed the bug if  the plugin thought it was upgrading -- which means that it must think it does. I think I know why this could happen -- could you try the new instrumented build and post the reporter output here again?

**Comment by eigengrau** [comment]
Same URL, right? Report [here](http://is.gd/C57u6U).

**Comment by retorquere** [comment]
OK, I think I've found the problem. There's a new instrumented version at the same URL, would very much appreciate a new report to confirm.

**Comment by eigengrau** [comment]
[Link](http://is.gd/3rbiyL)

**Comment by retorquere** [comment]
That did indeed fix it, thanks for your investigation! A new release will be published automatically when the tests have passed on circleCI.

**Comment by eigengrau** [comment]
Awesome! Thank you kindly for the help!
