### ISSUE TITLE
support export Keep Updated for entire library

### ISSUE THREAD

**Issue by rcoreilly** [ZotPlus/zotero-better-bibtex#187]
Would it be possible to support the keep updated feature for an entire library?  I have no need for collections -- we have just moved our entire lab's worth (21K items) into a shared group, and generally just export the whole thing because any given paper is going to reference lots of different things and there is no value to using something like a collection.  It is horribly slow right now -- hoping that the keep updated feature will help. If it is not possible to do this, then at least making the fact that it only applies to collections more prominently documented would be helpful.

Thanks for developing such an awesome system!

**Comment by rcoreilly** [comment]
Actually it seems that this function does not work at all with Group libraries?  After making the collection and doing the export again, it does not show up in the preferences list of saved exports, and there is no appreciable improvement in speed upon subsequent exports.

**Comment by retorquere** [comment]
It should already work for group libraries, so this is a genuine bug. I've just checked in a change to the caching system that should provide a massive speedup, so that's probably going to help as well.
