### ISSUE TITLE
autoexported collections not displayed in preferences

### ISSUE THREAD

**Issue by lucisandor** [ZotPlus/zotero-better-bibtex#188]
When exporting a collection and checking "Keep updated", I get:
```zotero(5)(+0006902): insert or replace into betterbibtex.autoexport (collection, path, exportOptions, exportedRecursively, status) values (?, ?, ?, ?, 'done')```
Also, nothing is added to the list of autoexported collections.
I deleted betterbibtex.sqlite, tried again, got betterbibtex.sqlite back, but got the same error in the console.

**Comment by retorquere** [comment]
I'll look into it not being saved, but is the above an error? Zotero logs all its queries to the console, regardless of their success status.

**Comment by retorquere** [comment]
Turns out it was remembering them, but not displaying them. I'm doing a little more testing, then putting out a new release somewhere today.

**Comment by retorquere** [comment]
a new release has been published to address this.
