### ISSUE TITLE
Improved caching, etc for faster download of large databases

### ISSUE THREAD

**Issue by rcoreilly** [ZotPlus/zotero-better-bibtex#190]
You can use this ticket for updating on the following:

I've done some profiling; the bulk of the time is spent in Zotero getting the items ready for export, and it looks like there's very little I can do about that. 21k items is going to be slow with even the most nimble of exporters, like Zotero TestCase, which just dumps what Zotero hands the translators as-is, or indeed BBT with a primed cache. I'll have a peek if I can short-circuit Zotero to skip prep for cached items, but that's going to be invasive, and thus tricky. If you're interested in being kept abreast of this, please file a separate issue -- this one is for the zotfile integration.

**Comment by retorquere** [comment]
This is trickier than I thought. It can be done, but only for BBT, not globally, and only when no attachments are exported.

**Comment by retorquere** [comment]
(note to self -- keep updated will have to imply "no file paths").

**Comment by rcoreilly** [comment]
well, we don't export attachments so that works for us.  btw if you want access to my group library for testing just let me know..

**Comment by retorquere** [comment]
I'll need to do more testing, but first results are encouraging: all existing tests pass, and I see a 20+ fold speedup with a primed cache.

**Comment by rcoreilly** [comment]
exciting!  eager to give it a test!

**Comment by retorquere** [comment]
I'm in the process of finalizing. Keep in mind that:

1. I can't help that the priming of the cache will be at regular speed (i.e., slow). The cache will be kept after priming across restarts, so this truly ought to be a one-time thing, except
2. My confidence in the caching mechanism isn't perfect, so at every BBT upgrade, the cache will be rebuilt.

That said:

1. The automated tests pass, and I've been running it on my 4k+ item library, and
2. An export of a 15122 item test library on my home system (which is an admittedly beefy i7 M620 with 8GB of RAM) export takes about 16 minutes unprimed, and about 1.5 minutes primed.

Not quite the 20-fold speedup I see on my own library, but most of those 1.5 minutes is spent in IO, not in pegging the CPU. And a 10-fold speedup is still respectable.

**Comment by retorquere** [comment]
A 1822 item library goes from 46 seconds to 2 on the automated tests at circle (my automated test service), from 47 to 1.2 on Travis (my other automated test service). Performance obviously varies with context, but this is pretty neat.

**Comment by retorquere** [comment]
For a lark I'm going to test on my mac at work tomorrow. If that works as well as this, I'm putting out the release

**Comment by retorquere** [comment]
All this comes at a memory consumption cost of course. The 15k library claims somewhere between 70 and 90 MB. OTOH, if you have a large library, you'll want to have this, and if you have a small library, you won't notice.

**Comment by retorquere** [comment]
0.9.30 is out; all tests pass (or I couldn't even have released) and I've done some exploratory testing, but if anything doesn't work, please file a new issue. Enjoy!

**Comment by rcoreilly** [comment]
under a minute for my 21k item group -- entirely usable now -- thanks!!!

**Comment by retorquere** [comment]
There is one more tricksy thing I could (I think) do to shave off another order of magnitude, but that is beyond merely complicated. It's on my back burner.
