### ISSUE TITLE
Feature request: automatically generate citation key for highlighted item and copy the key to clipboard

### ISSUE THREAD

**Issue by QiangF** [ZotPlus/zotero-better-bibtex#191]
Hi Everyone,
I like the graphic interface for browsing my collection. It will very convenient if I can select and paste. Also how  to copy the citation key withouth the bibtex:  prefix?
Thank you so much for this extraordinary plugin.

**Comment by retorquere** [comment]
If you upgrade to .33, you can do this by setting the citation command in the BetterBibTeX preferences to empty, the default export format under "Export" to `LaTeX Citation`, and then drag-and-drop, or copy to clipboard with Cmd-Shift-A (or Ctrl-Alt-A on Windows/Linux).

**Comment by retorquere** [comment]
Oh and there is no everyone, just me ☺

**Comment by QiangF** [comment]
The plugin zutilo can quickcopy item to clipboard and bind it to a key, I bind that to shift+C, which probabaly does the same thing.  I am not sure if the key is that same that better bibtex will gnerate  and probably it's not unique.  Will Ctrol - Alt + A auto generate a key for the citation?

**Comment by retorquere** [comment]
If you set the default export format to any of BBT's exporters (including LaTeX Citation), the generated keys will come from the BBT database, and will be subject to the same uniqueness algorithms. I'm not familiar with Zutilo, but if Zutilo does the same as c-a-A, then yes, it will be the BBT key on the clipboard.
