### ISSUE TITLE
automatic export does not export groups

### ISSUE THREAD

**Issue by adriaanph** [ZotPlus/zotero-better-bibtex#196]
i've ticked both "export collections" and "keep updated" when i exported my library. now the .bib file keeps getting refreshed (great!) but the group information was only included in the first (manual) export. all subsequent automatic exports omit the "@comment{jabref-meta: groupsversion:3;}..." section.

i've noticed that the preferences panel [Automatic Export] does not include "export collections" in the greyed-out list of tickboxes. is that where the switch got lost?

(zotero 4.0.26.4, zbb 0.9.35)

**Comment by retorquere** [comment]
I have omitted collection info export from the auto export, but the UI on that wasn't good, the new release makes that limitation visible. Would you prefer to have collections info in the auto exported file? As it's really only relevant to jabref I figured there would be little use for it, and it limits the cache memory consumption.

**Comment by adriaanph** [comment]
i am using zotero together with docear, which uses jabref. i like the collections feature for grouping my documents. is there another way to get what i want, or are you considering implementing this?

**Comment by retorquere** [comment]
I'll just add it, I've thought of a way to do this that won't have any
cache memory consumption. File data export is different though. That I
really can't add.

**Comment by adriaanph** [comment]
that's perfect, thank you. as far as i am concerned i have no need for the file export capability.

**Comment by retorquere** [comment]
I've simply removed the "export collections" option and made it the standard behavior. The main reason I had the option at all was to simplify my tests, but I've modified those. 0.10.6 is out which has this.

**Comment by adriaanph** [comment]
perfect! 0.10.6 does the job nicely. thank you.
