### ISSUE TITLE
Bibtex key generation no longer is unique

### ISSUE THREAD

**Issue by ghiknt** [ZotPlus/zotero-better-bibtex#199]
Report ID: http://is.gd/wFFEhC

Issue: When doing "&lt;RMB> | Generate BibTeX key" on an entry with the same Author as a previous entry the tool now generates both keys as "bibtex: Author" rather than "bibtex: Authora" for the second generated entry.

Workaround: Manually edit "Extra" field after generation with a unique bibtex key.

Doing "Clear BibTeX Key" on all entries and redoing produces the same result: all have the same key.

**Comment by ghiknt** [comment]
Additional Data: http://is.gd/T9ih8F

I thought the issue might be related to the fact that I had "Auto-pin citation keys" set to No.  If...

* I clear all bibtex keys
* Set Auto-pin citation keys to "On item change"
* Select Generate key for each item

... they get correct key suffix (a,b,c...) added to all but the first

But the next item I add an item with that Author it gets a duplicate key "Author" as the first entry.

**Comment by retorquere** [comment]
Reprodicible, working on a fix.

**Comment by hetsch** [comment]
Same happend to me right now using `@collection`and `@incollection`.

**Comment by retorquere** [comment]
0.10.1 is out which ought to fix these issues.

**Comment by retorquere** [comment]
Of course, if it doesn't for you, please do re-open the issue. Thank you for reporting the issue, and for your patience. Fixing this took a little longer than I'd hoped, and since I saw this as a very critical bug, I spent a little more time on testing and code review before putting it out.

**Comment by hetsch** [comment]
Thank's! The fix works perfectly for me!

**Comment by retorquere** [comment]
*phew*. On my phone, I just saw "Bibtex key generation no longer is unique" :) thanks for the confirmation, I really appreciate that.

**Comment by ghiknt** [comment]
:+1: Works now for me.  Thanks.
