### ISSUE TITLE
Export error for items without publicationTitle and "Preserve BibTeX variables" enabled

### ISSUE THREAD

**Issue by moble** [ZotPlus/zotero-better-bibtex#201]
I'm on Zotero standalone 4.0.26.3 (most recent version for Mac) with Zotero Better Bib(La)TeX 0.10.6, and getting lots of errors when I try to export collections, even just one or two items.  The debug output log fills up with errors like:

```
[JavaScript Error: "item.publicationTitle is undefined" {file: "<redacted>/zotero/translators/Better BibTeX.js" line: 8137}]
```

Looking at line 8137, I see this:

```javascript
case !(Translator.preserveBibTeXVariables && item.publicationTitle.match(/^[a-z][a-z0-9_]*$/i)):
```

I can change it to this:

```javascript
case !(Translator.preserveBibTeXVariables && item.publicationTitle && item.publicationTitle.match(/^[a-z][a-z0-9_]*$/i)):
```

and everything works again.

I don't understand javascript well enough to know if that's a legitimate fix.  And I definitely don't understand coffeescript well enough to fix this directly, though it appears that the problem comes from somewhere around [here](https://github.com/ZotPlus/zotero-better-bibtex/blob/master/resource/translators/Better%20BibTeX.coffee#L56).

It bothers me a little that all the items I'm exporting do indeed have titles.  But I don't honestly understand what's going on.  Also, a standalone note was causing trouble before I did this tweak.  I made a new item to put it under as a child note, gave that item a name, and then the export ran fine, even before my hack.

**Comment by retorquere** [comment]
Can you right-click on one of those entries, and select "report ZotPlus
error"? It'll give me the reference data, I'd like to see if more is going
on than the problem you found and fixed.

**Comment by moble** [comment]
Yep.  http://is.gd/6WByzk

Of course, now that I've tried again, I can't seem to reproduce the issues I was having.  When I was testing, I went back and forth a few times, restarting Zotero and editing the JS file, and could consistently reproduced it.  But now I can't.  Hm...  If I'm sending you on a goose chase, I apologize.

**Comment by moble** [comment]
Ah, but if I delete my  `better-bibtex-serialized-items.json` and `betterbibtex.sqlite` files, restart, and try again, I get the error again, which I've reported at http://is.gd/yC7sTw

**Comment by retorquere** [comment]
.23 will be published once the tests pass. Thank you for your report and your analysis.

**Comment by moble** [comment]
Great!  Thanks very much for taking care of this, and thanks generally for a very useful package.
