### ISSUE TITLE
Can't compile due to lacking Year?

### ISSUE THREAD

**Issue by florianheinemann** [ZotPlus/zotero-better-bibtex#202]
Hey
I really like the idea of this plugin, but when I use Better BibTex instead of BibTex as exporter I receive the following errors in TexShop when I compile BibTex:
```
Warning--empty year in Dushnitsky2005a
Warning--empty journal in Dushnitsky2005a
```
And then later when I compile Latex:
```
Package natbib Error: Bibliograpbhy not compatible with author-year citations
```
All works well for Zotero's standard export :( When looking at the generated output it is indeed visible that Better BibTex is using date instead of year. 

Is Natbib not supported? Or the APA style (apalike)? Any ideas?

Many many thanks in advance!

**Comment by florianheinemann** [comment]
A change to `biblatex` resolved the issues, but I think it would be still an interesting discussion of Better BibTex should follow the standard of BibTex or Biblatex :-)

**Comment by retorquere** [comment]
Are you sure you are exporting with `Better BibTeX`, and not with `Better BibLaTeX`? `Better BibTeX` adds the `year` field (when date is present in the reference), `Better BibLaTeX` adds the `date` field.

BBT shouldn't have any impact on your choice of citation styles, other than the choice of journal abbreviator. So APA(like) ought to work, I use APA(like) myself.

**Comment by florianheinemann** [comment]
This is absolutely odd - I tried it again today and compared the output: `year` was added! Not sure what happened yesterday. I could have sworn I tried it several times with both options comparing the output. 

Thanks for the fast response & the great plugin

**Comment by retorquere** [comment]
It is my pleasure.

**Comment by retorquere** [comment]
A similar problem was just reported in #205, so I'm looking into whether this can be a cache failure. Could you subscribe to that issue to be kept in the loop? I could use your help tracking the problem down.

**Comment by florianheinemann** [comment]
Sure thing!

**Comment by retorquere** [comment]
We've got him: https://github.com/ZotPlus/zotero-better-bibtex/issues/205#issuecomment-107085548
