### ISSUE TITLE
Implement option to clear all pinned keys

### ISSUE THREAD

**Issue by murmlgrmpf** [ZotPlus/zotero-better-bibtex#206]
Is there a way to clear all pinned keys?

Background: We have migrated to Zotero and want to use pinned keys in a shared library. Unfortunately now we have a wild mixture of different schemes of citation keys, all of which are pinned.

Best,
Thomas

**Comment by retorquere** [comment]
Unless there's a bug, you should just be able to select the group library,
select-all, right-click, and select "clear keys".

**Comment by murmlgrmpf** [comment]
Very well! Thanks for the fast response. I was looking for a global option, but your procedure works for me.
