### ISSUE TITLE
Auto-updated .bib files not preserved after update

### ISSUE THREAD

**Issue by davepwsmith** [ZotPlus/zotero-better-bibtex#207]
Whenever the plugin gets updated, any automatically exported .bib files have to be re-exported and set to "Keep Updated" again. This is only a minor inconvenience for sure, but perhaps also something which would be easy to fix?

**Comment by retorquere** [comment]
I sure hope so -- I don't consider data loss of any magnitude a minor inconvenience! I'll try to get a fix out tonight.

**Comment by davepwsmith** [comment]
No no, there's no data loss -- the bib file remains. What doesn't survive the update is Better BibTex's *settings* to keep the files updated, so anything added to zotero after an update won't be in the bibtex file until after a manual export. Sorry, didn't explain that well.

**Comment by retorquere** [comment]
Settings = data. Thanks for the report - I'm on it.

**Comment by retorquere** [comment]
See? No bug is insignificant. The problem you noticed was going to bring massive problems down the line. Thanks so much!
