### ISSUE TITLE
Problem with export

### ISSUE THREAD

**Issue by dmbortz** [ZotPlus/zotero-better-bibtex#210]
When using zotero-standalon 4.0.26.3 with BBT 0.11.8 (on ubuntu trusty) to export a collection to a bibtex file, I get a popup error of "An error occurred while trying to export the selected file."

I turned on debugging immediately before doing the "export".  The debug output is here:

http://pastebin.com/Y5zLYwXG

Let me know if there's any other files/info I can provide. thanks!

**Comment by retorquere** [comment]
Tests are running

**Comment by retorquere** [comment]
release is out.

**Comment by dmbortz** [comment]
Awesome.  Works perfectly. Thanks!

**Comment by retorquere** [comment]
My pleasure, and apologies for the disruption.
