### ISSUE TITLE
AUX file import generates JSON list, but no objects.

### ISSUE THREAD

**Issue by Anaphory** [ZotPlus/zotero-better-bibtex#211]
I have a problem with importing AUX files into Zotero.
Instead of getting a new collection with the corresponding items, I get a new collection that only contains the `BibTeX AUX Scanner` item, which in its `extra` field contains something like the following JSON (?) object.
```
{"translator":"0af8f14d-9af7-43d9-a016-3c5df3426c98", "citations":["allen2012mutation","altrock2009fixation", … ]}
```
The Hash (?) `0af8f14d-9af7-43d9-a016-3c5df3426c98` looks to be the same for different imports.

The Zotero debug report should be on http://is.gd/uCPxjZ, what else do you need to know?

**Comment by retorquere** [comment]
Just as a test, could you disable vimperator, restart, and try the import again?

**Comment by retorquere** [comment]
Never mind, I think I've found it.

**Comment by retorquere** [comment]
Tests are running, and I've included a new test to prevent regression.

**Comment by retorquere** [comment]
new release is out

**Comment by Anaphory** [comment]
The problem persists for me even in zotero-better-bibtex-0.11.10.xpi.
I have tried it with all other addons deactivated, and still get an import containing a json object and nothing else. The new report is http://is.gd/MFIvp7.

**Comment by retorquere** [comment]
Can you try installing the version from http://zotplus.github.io/better-bibtex/#debug and getting me a new debug log?

**Comment by retorquere** [comment]
(the problem is not related to other plugins BTW but to a library I'm using for the cache)

**Comment by retorquere** [comment]
Never mind that log; I think I might have isolated the problem. The dev of the cache library is usually super responsive, so I hope to have a fix later today.
