### ISSUE TITLE
Translate or keep bibtex keys

### ISSUE THREAD

**Issue by melsophos** [ZotPlus/zotero-better-bibtex#212]
I just started to use Better Bibtex recently, and I think it will be very useful. But before using it there is one feature that would be needed in order to move previous projects: indeed currently I am using the keys generated by Zotero (author_(title first word)_date), and changing all citations in my various projects would be very painful. Hence I see two features that would be useful for helping the migration:

- have an option to export default Zotero's key instead of the one generated by Better Bibtex;
- export a file mapping the keys (one column with Zotero's keys, one with Better Bibtex ones), such that one can use it as input for sed to perform the replacements.

**Comment by retorquere** [comment]
The keys generated by Zotero aren't available as a) they're always generated on the fly, and b) they don't have an unambiguous disambiguation algorithm, so it is in principle not possible to deterministically generate the same keys in case of overlap -- not even for Zotero itself.

The first point is somewhat easy to address: set the cite key pattern to `[auth:fold:lower]_[Title:nopunct:skipwords:select,1,1:lower]_[year]` (which emulates the default Zotero generator), select the references you want to have Zotero-like keys, right-click, and select `Generate BibTeX key`. After that you can set the pattern to whatever you like, those entries will retain their keys.

The second point is harder, but what I'd do is:

1. Go to `Preferences`, `Export`, and set `Default Output Format` to `LaTeX Citation`
2. Go to `Preferences`, `Better BibTeX`, set `Citation Command` to empty
3. Go to `Preferences`, `Better BibTeX`, set `Citation Key Format` to `[auth:fold:lower]_[Title:nopunct:skipwords:select,1,1:lower]_[year]`
4. Select the references you want the mapping table for, and drag-and-drop into a text editor. Make sure the selection does not get lost
5. Go to `Preferences`, `Better BibTeX`, set `Citation Key Format` to your desired former
6. Drag-and-drop the still selected references into a text editor.

Those two text editors will have the "old" and the "new" keys in the same order.

**Comment by melsophos** [comment]
Thank you for you help and your feedback.
Indeed I saw the first solution on the website: I was hoping for something mixed in order to export in both formats (during the time to convert everything). By the way I believed that this was the role of the option "keep bibtex variables", and it is how I got this idea. The second trick seems good and simple and I will try this later, thanks again for your suggestion.
Concerning the disambiguation I believed that this would be possible by automating in some way your proposal for the second point: in any case if this works for most of the keys then this is still simpler than renaming everything, and also shorter than your solution if there are many bibliographies (in my case I don't have so many to convert so your solution is very fine for me, I am just thinking for a more general case).

**Comment by retorquere** [comment]
Mixed in what way? I mean, why would you want to have several formatter options going? You could just set the pattern to Zotero-emulation, and everything would work. You don't need to fix the bibtex keys in that case, even, although I always do recommend fixing bibtex keys.

If you have used the default Zotero bibtex keys before, I'd recommend going with option 1; but your case made me think that setting the first-time-use pattern to the Zotero emulator. The next release will have that as a default to make migration smoother. Good one.

As for migrating bibtex keys... I'm trying to think of a way to make this process easier. It shouldn't actually be hard to generate these lists. Let me think about this for a few hours and I might have something for you.

I should document "Keep bibtex variables" -- it just means that bare strings don't get surrounding braces, so you can include @strings from external files. That really needs to go into preferences, not export options, too.

**Comment by melsophos** [comment]
I would have liked several formatter options in order to make the transition smoothly, keep the old ones using Zotero format, and the new ones with the new format. I wanted to change because I do not like Zotero format. So it is why I was thinking that an option at export for using Zotero default's pattern (whatever is the current defined pattern) would be useful.
Setting Zotero format as a default is an excellent idea. Thanks again for all what you do.

**Comment by retorquere** [comment]
If there were several formatter options you'd still have to specify per-reference which one you wanted to apply. If you want old ones with one pattern, and new ones with a second, the easiest is to go to the library view, select all, right-click, and select "Generate BibTeX key". That will fix the "old" references at the pattern in effect at that moment, and any new references will take whatever you set the pattern to then.

I have an idea for the cite key migration. Will probably be done tonight.

**Comment by melsophos** [comment]
This is a good idea, which could also be useful. I was more thinking to a choice per-export (this is why I believed the checkbox "preserve bibtex" was exactly this, a way to - for the given export - to keep Zotero's convention). But in any case iif there is something for making the migration then having such an option is not really useful so this is not a big deal.

**Comment by retorquere** [comment]
Ah, I see. I can only add checkboxes to that screen unfortunately, that is all that Zotero allows. The "preserve bibtex vars" is moving into the preferences for the next release. With the new default pattern, newcomers should find the standard behaviour mostly as they'd expect.

**Comment by retorquere** [comment]
Alright, since mentioned "sed" I'm going to assume you're not bothered by the migration support being a little on the geeky side (for now, anyway). None of this is in the docs yet, I want a little more time to think about whether this is going to be its final form.

As of 0.11.2, there is a an extension to the allowed formatter patterns you can set in the prefs; in addition to separating candidates by `|` (a little used feature I suspect) you can now separate patterns also by `>`. The `>` separator starts a new candidate group for citekey generation.

If you use only one candidate group (which was the only option so far) everything remains as-is, and even if you do use more than one candidate group, all but the first will be pretty much universally ignored. You can add a second (or more) group, using e.g. 
    `[auth:fold:lower]_[Title:fold:nopunct:skipwords:select,1,1:lower]_[year]>[auth][year]`
With more than one group in place (and only then), an export using the `BetterBibTeX JSON` format will add to each reference a field named `__citekeys__`, which will hold, in order, the generated value for each candidate group. It should be easy enough to use this in your migrartion with a little scripting code; this ruby one-liner would convert that to CSV should that be easier to process:

    require 'json'; require 'csv'; puts CSV.generate { |csv| JSON.parse(open(ARGV[0]).read)['items'].collect{|item| item['__citekeys__']}.each{|row| csv << row} }

**Comment by retorquere** [comment]
Oh and BTW the AUX scanner can tell you about papers that have missing keys.

**Comment by melsophos** [comment]
This is very excellent, thank you for this!

**Comment by retorquere** [comment]
Hi, is there a particular problem that caused you to reopen this issue?

**Comment by melsophos** [comment]
No sorry, I did not mean to close it first (I took the wrong button), so I reopened it to be sure that everything was fine from your side.

**Comment by retorquere** [comment]
My opinion doesn't matter - yours does :)
