### ISSUE TITLE
Error with exporting library to Bibtex

### ISSUE THREAD

**Issue by CptDreggs** [ZotPlus/zotero-better-bibtex#214]
Public ID for this issue: http://is.gd/a2Vnjp

I have an issue when I try to export my library to Better Bibtex/BibLaTex (works fine for individual items). The popup error message is "An error occurred while trying to export the selected file".

I turned on debugging right before trying to export and the output is here: http://pastebin.com/edmTcXcS

I am using the latest release of Better Bibtex on Firefox.

**Comment by retorquere** [comment]
Was this the main library or a group library?

**Comment by retorquere** [comment]
Can you try generating a debug log using the version at http://zotplus.github.io/better-bibtex/#debug ?

**Comment by CptDreggs** [comment]
It was a group library. I'll Install the version you linked to and get back to you.

**Comment by CptDreggs** [comment]
Here's the log: http://pastebin.com/84smy3Wn

**Comment by retorquere** [comment]
This group library has items? And you've restarted after installing the debug version?

**Comment by CptDreggs** [comment]
My sincerest apologies. I've found the source of the error - I was trying to export to .bib via the actions menu (cog symbol), which I now realise looks at "My Library" for files (and is empty). Right click -> export group works just fine. Your last comment made me think of this possibility, so thank you for solving the issue!

**Comment by retorquere** [comment]
Still, an empty library export should not yield an error. Does it also error out if you use another exporter, or is this just BBT?

**Comment by CptDreggs** [comment]
As in, export to some non-BBT file format? Yes it does.

**Comment by retorquere** [comment]
Yes, that's what I needed to know. I saw the same thing, but I'd like to get confirmation of such things :) This would appear to be an edge case in Zotero, I just tested without BBT. Oh and BTW, while the problem you reported might not be in BBT, it made me inspect the code for group export and find an edge case of my own -- so thanks for reporting in any case :+1:
