### ISSUE TITLE
support for saved searched

### ISSUE THREAD

**Issue by katrinleinweber** [ZotPlus/zotero-better-bibtex#216]
Is this technically possible? It would be very helpful for directing different bibliographies (different manuscripts or projects for example) to their respective working directories, if one manages those bibliographies with tag-based saved searches.

The [Zotero autoexporting addon](https://github.com/rokondo/Zotero-autoexporting/) can export saved searches, but only into the same folder.

**Comment by retorquere** [comment]
Technically possible, yes, but not as smoothly as the collection-based exports. Zotero doesn't notify plugins from changes that would make a reference match/no longer match a search, so it'd mean that I'd have to kick off all searches for any change made. I can have a look, but performance-wise, it's never going to be as good as collection-based.

**Comment by retorquere** [comment]
Actually even worse; saved searched have no baseline against which to compare whether an item was "added" (now does match, did not previously) or "removed" (did match previously, does not now). Zotero auto exporting probably simply does a timed export regardless of changes; that's not how the BBT auto export is set up. I'll have a go at it regardless, but this won't be finished this weekend.

**Comment by katrinleinweber** [comment]
Cool, thanks for checking :-) I'll definitely switch to collections then.

**Comment by retorquere** [comment]
I'm still going to do it :)

**Comment by katrinleinweber** [comment]
OK; Looking forward to test it :beers:

**Comment by retorquere** [comment]
Work on this has started on the `saved-search` branch, but this is trickier than I thought. Not impossible, so it *will* happen, but they're not making this easy.

**Comment by retorquere** [comment]
I want to do a little more testing, but you could have a go with http://zotplus.github.io/better-bibtex/#debug . The untested bits won't cause damage, but I am not 100% sure you won't see UI errors... I haven't so far, but this one was a little tricky. Also, this (by necessity) kicks of all searches you have set for auto-export at any change to any reference, so I would not encourage setting up many very complicated searches this way... I cache the hell out of everything I can, but Zotero DB access is incredibly slow (for reasons they can't help), and the searches are DB queries.

This will always be substantially slower than collections export. What "substantially" depends on your hardware and your patience.

**Comment by retorquere** [comment]
Whether Zotero AutoExporting is faster or slower BTW is going to depend on a number of criteria. I think ZAE kicks off queries for saved searches only on the timer heartbeat, whereas I kick them off for every reference change, and as noted, searches can be expensive, performance-wise. On the other hand, BBT doesn't do an export unless the search has actually changed, and exports are expensive in their own right. The caching ought not to make a difference -- ZAE will profit from BBTs caching in any case.

**Comment by retorquere** [comment]
I haven't been able to trigger any errors, and it works consistently, so I've released .3 with saved-search export.

**Comment by katrinleinweber** [comment]
It works, thanks :-)
