### ISSUE TITLE
Rename files according to the citekey

### ISSUE THREAD

**Issue by samspo** [ZotPlus/zotero-better-bibtex#217]
I use Zotero-better-bibtex to define the citekey. It is very convenient (thank you for this work)
I use Zotefile to rename my files according to the citekey. 
With the extra field generated by zotero-better-bibtex, I can use the wildcard of zotfile (http://zotfile.com/#user-defined-wildcards) to rename my files. My wildcard takes this form: 
```
{"4": {"field":"extra", "operations": [{"function": "replace", "regex": "bibtex: ", "replacement": "", "flags":"g"}] } }
```
I would like to avoid to generate the extra field, but when I try to use directly the field "citekey", it doesn't work
```
{"1": "citekey"}
```
Error message:
```
Error: Invalid field 'citekey" for base field in ItemFields.getFieldIDFromTypeAndBase()
```
Do you know what field name I should use?
Thank you for your help

**Comment by retorquere** [comment]
Is there a full stack trace around that message?

**Comment by retorquere** [comment]
BTW, this syntax is used to introduce new wildcards, right? But BBT already introduces the `%b` wildcard to produce the bibtex key. Doesn't that already do what you need?

**Comment by samspo** [comment]
Yes. You're right. It works. Thank you!
