### ISSUE TITLE
"Preserve bibtex variables" error

### ISSUE THREAD

**Issue by smileyface42** [ZotPlus/zotero-better-bibtex#218]
Report ID: QPDK8RBX-5SHWWKN5

With the changeover to it being in preferences (rather than the export menu), I've had issues with it's behaviour. It seems to be defaulting as on and while you can click on the corresponding checkbox in preferences, it doesn't change the behaviour (and is always marked as unchecked even though it always behaves as if it is checked).

The issue is occurring in both Zotero standalone and firefox and the only other zotero add-on that is active is Zotfile (most current version). Tried temporarily going back to the old betterbibtex before it was moved to the preferences section and it was working okay there.

I really need to have it turned off given how it messes up single word journal titles like Science and Ultramicroscopy

**Comment by retorquere** [comment]
Odd, I can't readily find the place where this could be messing up, but with a little more info I am confident I can get this fixed today. The log didn't show much unfortunately; could you do the following for me:

1. check in `about:config` whether `extensions.zotero.translators.better-bibtex.preserveBibTeXVariables` is set to `false`
2. Right-click a reference that doesn't export as you'd want to and select `Report ZotPlus error` and post that resulting ID here.

Thanks!

**Comment by smileyface42** [comment]
Going into the config and changing it there directly seemed to work. It was set to true there before but wasn't changeable through the preferences interface.

Just testing it afterwards, checking the corresponding checkbox still does nothing and doesn't revert to how it was before (still stays false) so it looks like it's an probably issue with the checkbox not interacting with the settings.

Things are exporting fine now but if there's anything I can provide to help figure out what's happening with the checkbox, let me know.

Thanks very much

**Comment by retorquere** [comment]
Super, that led me to the error. A new release will be published automatically when https://travis-ci.org/ZotPlus/zotero-better-bibtex/builds/68935870 finishes.
