### ISSUE TITLE
Export mapping for reporter field

### ISSUE THREAD

**Issue by rjww** [ZotPlus/zotero-better-bibtex#219]
Thanks for your work on this, it's really helped me out. At the moment, it seems like the `reporter` field for `case` isn't mapped. Would it be possible for this to be mapped to `journaltitle`? It's crucial for legal citation.

**Comment by retorquere** [comment]
Could you please right-click such an entry and select `report zotplus error`? It will give me a testcase to work with.

**Comment by rjww** [comment]
Thanks for the quick reply! Of course, it should be coming through now.

**Comment by retorquere** [comment]
DAM2QRC6-FAV5KMUB, right?

**Comment by rjww** [comment]
Sounds familiar. The citation should have been to *Kartinyeri v Commonwealth* (1998) 195 CLR 337.

**Comment by retorquere** [comment]
This is for BibLaTeX export, resulting in a `jurisdiction` stanza, correct?

**Comment by rjww** [comment]
Yep, sorry should have been more specific about that.

**Comment by retorquere** [comment]
got it.

Unrelatedly, in that reference the `author` field is empty, and you've added `bibtex` metadata in the `extra` field consisting of

    bibtex{
    author:"Kaetinyeri v Commonwealth",
    translator:"Kartinyeri"
    }

why not just set "Kaetinyeri v Commonwealth" in the regular (unsplit) Zotero `author` field?

**Comment by rjww** [comment]
Yeah it's just a kind of test entry. Technically it shouldn't have any author field at all, but I need a way to suppress the title field for certain citations, i.e. where the name of the case is mentioned in the text, but (as far as I know) CSL only allows for suppressing fields under `cs:names`. In other words it's an admittedly inelegant workaround.

**Comment by retorquere** [comment]
Sorry for the delay; Zotero 4.0.27 just released this morning, and changes between 4.0.26 and 4.0.27 broke BBT (I dig pretty deeply into Zotero), so I had to fix that first. Tests are running, 0.13.10 has the change you want (Travis is a little slow lately, but it should publish the new release in 5-10 minutes). You will have to upgrade to Zotero 4.0.27 -- the changes were extensive enough that backwards compatibility was not feasible.

**Comment by rjww** [comment]
Not a problem, thanks very much for turning this around so quickly. I really appreciate it.

**Comment by retorquere** [comment]
Would you be OK with `reporter` actually going into a `reporter` field instead of `journaltitle? If not, what style are you using for legal citations?
