### ISSUE TITLE
BBT incompatible with Zotero 4.0.27 -- being worked on

### ISSUE THREAD

**Issue by retorquere** [ZotPlus/zotero-better-bibtex#220]

**Comment by retorquere** [comment]
Looks like the translators lose access to the itemID (&%#&^%@), and the serialisation format has changed (need to drop the serialisation cache)

**Comment by retorquere** [comment]
Add `-ZoteroNoUserInput` to the cucumber command line

**Comment by retorquere** [comment]
OK, itemID is available (for now) and the serialisation format unchanged until I set `minversion` to `4.0.27` in the translator metadata. key fetches will have to move to the item key at that point.

**Comment by cocofifi** [comment]
Would going back to an earlier Zotero solve the problem ? This would be a temporary solution to be able to continue to benefit from BBT unitl a solution is found.

**Comment by retorquere** [comment]
4.0.26.x will still work. I expect to have BBT working soemwhere between tonight and tomorrow afternoon -- all tests but one pass at this point (and boy am I glad I have tests)

**Comment by retorquere** [comment]
release tests for 0.13.9 are running, and the previous tests ran green, so I expect the new version to be published in about 5 minutes. Unfortunately the changes to Zotero were extensive enough that I will have to enforce 4.0.27 being installed.

**Comment by rjww** [comment]
Just upgraded Zotero 4.0.27, but BBT doesn't seem to be detecting the correct version. Getting the following message: `Better BibTeX has been disabled because it did not find Zotero 4.0.27 or later.` (The error reporting facility didn't produce anything, so I couldn't submit through that – I guess because it's not an unhandled error.)

**Comment by fwilkes** [comment]
I'm seeing the same issue as rjww. I have 4.0.27 installed, but BBT isn't finding it.

**Comment by rjww** [comment]
(This is on the developer preview of OS X 10.11, that may or may not be relevant.)

**Comment by retorquere** [comment]
It shouldn't make a difference. I'm on OSX 10.10 myself, and all tests pass on Linux.

Wait, are you guys on standalone? I didn't test on standalone. I'll go test that.

**Comment by rjww** [comment]
Yeah, I'm on standalone (Chrome user).

**Comment by fwilkes** [comment]
Yes, on standalone/Chrome plugin on OS10.10.3. It was working just fine yesterday.

**Comment by retorquere** [comment]
Wouldn't have been today (the differences between 4.0.26 and 4.0.27 really mess up BBT), but I've found the culprit, won't be long

**Comment by retorquere** [comment]
(BTW I don't mean to say the changes between 4.0.26 and 4.0.27 *shouldn't* have messed up BBT -- I go *far* beyond what the API says I can do to make BBT work, so they didn't break any promises between those two versions)

**Comment by retorquere** [comment]
0.13.11 is out that addresses this.

**Comment by rjww** [comment]
Hahaha, it's all good. I'm torn between the (complete) flexibility of the data structure in biblatex, and the fact the CSL is actually compatible with stuff other than LaTeX.

**Comment by rjww** [comment]
Thanks!

**Comment by fwilkes** [comment]
thank you!

**Comment by retorquere** [comment]
In my case it's simply that I'm hooked on LaTeX, but find that the database approach of Zotero preferable to the file-based approach from JabRef. That, and I liking scripting languages (even Javascript, bad as it is) more than I do languages like Java, and I like to tinker with my tools.
