### ISSUE TITLE
Export not working: TypeError: this._itemToArray is not a function

### ISSUE THREAD

**Issue by Dominik-K** [ZotPlus/zotero-better-bibtex#222]
Doesn't work with book or paper (or others?) on Zotero Standalone 4.0.27.

	(4)(+0000005): Translate: Parsing code for Better BibLaTeX (f895aa0d-f28e-47fe-b247-2ea77c6ed583, 2015-06-30 08:20:27)

	(3)(+0000134): Translate: Beginning translation with Better BibLaTeX

	(3)(+0000007): Item.itemID is deprecated -- use Item.id

	(1)(+0000001): TypeError: this._itemToArray is not a function
		===== Stack Trace =====
		Zotero.BetterBibTeX.serialized.get@chrome://zotero-better-bibtex/content/serialized.js:69:1
		Zotero.BetterBibTeX.init/Zotero.Translate.ItemGetter.prototype.nextItem@chrome://zotero-better-bibtex/content/zotero-better-bibtex.js:797:16
		Zotero.Translate.Sandbox.Export.nextItem@chrome://zotero/content/xpcom/translation/translate.js:775:15
		Zotero.Translate.SandboxManager.prototype.importObject/attachTo[localKey]<@chrome://zotero/content/xpcom/translation/translate_firefox.js:527:29
		@chrome://zotero/content/xpcom/translation/translate_firefox.js:433:66
		Translator.nextItem@P:\Zotero\translators\Better BibLaTeX.js:3308:17
		doExport@P:\Zotero\translators\Better BibLaTeX.js:4217:17
		Zotero.Translate.Base.prototype._translateTranslatorLoaded@chrome://zotero/content/xpcom/translation/translate.js:1218:4
		Zotero.Translate.Base.prototype.translate/<@chrome://zotero/content/xpcom/translation/translate.js:1185:58
		Zotero.Translate.Base.prototype._loadTranslator@chrome://zotero/content/xpcom/translation/translate.js:1570:16
		Zotero.Translate.Base.prototype.translate@chrome://zotero/content/xpcom/translation/translate.js:1185:4
		Zotero.Translate.Export.prototype.translate@chrome://zotero/content/xpcom/translation/translate.js:2261:3
		Zotero.BetterBibTeX.init/Zotero.Translate.Export.prototype.translate@chrome://zotero-better-bibtex/content/zotero-better-bibtex.js:736:1
		Zotero_File_Exporter.prototype.save@chrome://zotero/content/fileInterface.js:96:3
		exportItems@chrome://zotero/content/fileInterface.js:178:3
		oncommand@chrome://zotero/content/standalone/standalone.xul:1:1
		=======================

**Comment by retorquere** [comment]
Which version Zotero/BBT are you on?

**Comment by rian39** [comment]
Hi
I've got problems with export this morning too, but in firefox with today's update 0.13.11. There is no export URL (http://localhost:23119/better-bibtex/collection gives 'Could not export bibliography: no path')

 Here's the line from debug console for me:
[JavaScript Error: "ReferenceError: zotero is not defined" {file: "chrome://zotero-better-bibtex/content/zotero-better-bibtex.js" line: 127}]

version => 4.0.27.1, platform => Linux x86_64, oscpu => Linux x86_64, locale => en-GB, appName => Firefox, appVersion => 38.0

**Comment by retorquere** [comment]
@rian39 that is a different issue, but this is fixed in .12 (out just now)
@Dominik-K `_itemToArray` was deprecated between 4.0.26 and 4.0.27; it may be the case that you've upgraded to Zotero, but not yet to BBT 0.13.10 or later.

**Comment by rian39** [comment]
Ok, yes, looks like its different. Didn't want to multiply issues for you  ...

**Comment by retorquere** [comment]
No worries, just indicating I could fix this separately. Your problem should be solved after upgrade to .12; I'm keeping this issue open to address the problem @Dominik-K is experiencing.

**Comment by Dominik-K** [comment]
Oh, yes. You're right. I'm sorry. I just updated the translators, not the Addons. With updating to BBT 0.13.11, it worked.

Unfortunately, after restarting, BBT (just updated to 0.13.12) is disabled. I got the message (on startup):
   Better BibTex has been disabled because it found Zotero 4.0.27.SOURCE, but requires 4.0.27 or later

**Comment by retorquere** [comment]
@Dominik-K you're on the source build? I can fix that, but can you tell me how you build Zotero? I could use that info.

**Comment by Dominik-K** [comment]
No. I updated Zotero Standalone within itself, i.e. "Help -> Check for updates".

**Comment by retorquere** [comment]
That is really odd, Zotero standalone should not be reporting that version. They just released 4.0.27.1, can you try if the problem still occurs there? What platform are you on BTW?

**Comment by Dominik-K** [comment]
I'm using Zotero Standalone on Windows 7. On the [changelog](https://www.zotero.org/support/4.0_changelog): "Zotero 4.0.27.1 was released for Zotero for Firefox only." So, I don't get an update on standalone.

**Comment by retorquere** [comment]
The linux version of standalone does indeed contain "4.0.27.SOURCE"; this is certainly a bug. I'll file a bug, should be fixed soon; in the mean while, .13 will allow source builds (or official builds that misidentify as a source build) with a warning at startup.

**Comment by Dominik-K** [comment]
With .13, BBT is still disabled. I get both messages, the new warning and the disabled message.

**Comment by retorquere** [comment]
Yeah, that was a screw-up on my part, see also #225. .15 ought to fix this; I'd appreciate if you could confirm it does for you.

**Comment by Dominik-K** [comment]
Seems to work with .15 :-) Thanks for the quick fix.
