### ISSUE TITLE
collection export URL not working for firefox

### ISSUE THREAD

**Issue by rian39** [ZotPlus/zotero-better-bibtex#224]
hi again,
Using the latest version 0.13.12, I'm getting this error in the debug console when I try to look at the export URL for a zotero collection:

Detected no build no. : Install button newly

[JavaScript Error: "TypeError: elem is null" {file: "chrome://zoteroautoexporting/content/toolbar.js" line: 28}]

[JavaScript Error: "ReferenceError: ZOTERO_CONFIG is not defined" {file: "chrome://zotero-better-bibtex/content/zoteroPane.js" line: 7}]

[JavaScript Error: "TypeError: Zotero.BetterBibTeX.pref.serverURL is not a function" {file: "chrome://zotero/content/tab.xul" line: 1}]

**Comment by retorquere** [comment]
I can replicate the second error but bot the first; I'm hoping it is knock-on damage. Can you try upgrading to .14 and see if the problem persists?

**Comment by rian39** [comment]
It's good now. Thanks for the quick fix.

best

adrian

On 01/07/15 12:57, retorquere wrote:
>
> I can replicate the second error but bot the first; I'm hoping it is 
> knock-on damage. Can you try upgrading to .14 and see if the problem 
> persists?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ZotPlus/zotero-better-bibtex/issues/224#issuecomment-117631440>.
>

-- 

------------------------

(Professor) Adrian Mackenzie
Department of Sociology
Room b08, Bowland North
Lancaster University, LA1 4YT, UK

a.mackenzie@lancaster.ac.uk
http://www.lancaster.ac.uk/sociology/profiles/adrian-mackenzie

ph (44) 01524 594184
twitter: @rian2011ad

Co-Director, Centre for Science Studies
http://www.lancs.ac.uk/fass/centres/css/
-----------------------------
Save our in-boxes! http://emailcharter.org

**Comment by retorquere** [comment]
Awesome, thanks for the confirmation
