### ISSUE TITLE
Translators not appearing in Zotero standalone on OS X 10.10

### ISSUE THREAD

**Issue by rjww** [ZotPlus/zotero-better-bibtex#230]
Sorry to be raising another issue, but I just reverted to OS X 10.10 from 10.11, reinstalled Zotero standalone 4.0.27, added BBT 0.14.5, and while the add-on appears and is configurable in the preferences pane, none of the export translators appear.

**Comment by retorquere** [comment]
That's not any good. I can look into it in a few hours - in the meantime,
it would probably help me if you could check "enable after restart" in the
advanced settings, restart zotero, and then submit a ZotPlus error report
from the gear menu.

**Comment by retorquere** [comment]
Ugh, I've just found that error reporting for zotplus is broken on standalone. If you could just paste the debug log (accessible by typing `zotero://debug/` in the address bar) in a gist that would be helpful.

**Comment by rjww** [comment]
No problem, [here you go](https://gist.github.com/rjww/efc261ee4f8fda0b3d83).

**Comment by retorquere** [comment]
OK, this only happened on a virgin database -- thanks for the log, might not have found this otherwise. The error reporting is also fixed now.

**Comment by retorquere** [comment]
0.14.6 is out
