### ISSUE TITLE
"Report ZotPlus errors" for item does not work

### ISSUE THREAD

**Issue by noschinl** [ZotPlus/zotero-better-bibtex#234]
When I select an item and select "Report ZotPlus errors" in the context menu, nothing happens. This is on Iceweasel 38.0.1 (i.e., a Debian-branded Firefox) with

  * Zotero 4.0.27.4
  * ZotFile 4.1.6
  * Better BibTex 0.14.10

Disabling ZotFile does not change anything; "Report ZotPlus errors" on collections works.

**Comment by retorquere** [comment]
can you type "zotero://debug" in the address bar and paste the contents in a gist after you tried on an item?

**Comment by noschinl** [comment]
This gives me a completely empty page (source of the page is also empty).

**Comment by retorquere** [comment]
Even if you disable BBT?

**Comment by noschinl** [comment]
It seems I need to enable debugging output in the Zotero preferences (or should I also enable enhanced BBT debug output?). If I activate this and then try to report an error for an item, the zotero://debug shows: https://gist.github.com/noschinl/b305360ed5732927cce8
