### ISSUE TITLE
Single-field author entries with commas generate invalid BibTex

### ISSUE THREAD

**Issue by noschinl** [ZotPlus/zotero-better-bibtex#235]
Report ID: H3D3HSP8-GGDA594G

The report contains an Author Entry in single-field mode of the form "A, B, C". Export as "Better BibTex" generates "A, B, C, undefined", which is invalid because it contains to many commas:

Too many commas in name 1 of "Hunt, Warren A., Jr, undefined and Kaufmann, Matt and Krug, Robert Bellarmine and Moore, J Strother and Smith, Eric Whitman" for entry hunt_meta_2005
while executing---line 2947 of file splncs03.bst

**Comment by rolve** [comment]
Probably related: Single-field author entries *without commas* generate `[name], undefined`.

**Comment by retorquere** [comment]
It generates the following BibTeX for me:

    @inbook{hunt_meta_2005,
      title = {Meta Reasoning in {ACL}2},
      isbn = {978-3-540-28372-0},
      url = {http://dx.doi.org/10.1007/11541868_11},
      timestamp = {2015-07-08 16:49:03},
      booktitle = {Proc. {TPHOLs} '05},
      publisher = {Springer},
      author = {{Hunt, Warren A., Jr} and Kaufmann, Matt and Krug, Robert Bellarmine and Moore, J Strother and Smith, Eric Whitman},
      date = {2005},
      pages = {163--178}
    }

Your log shows an error which was fixed in 0.14.11 -- could you upgrade and try again? It could be that this error is a collateral damage from #234.

**Comment by retorquere** [comment]
I think it is collateral damage; the error in your log is probably preventing 0.4.10 from installing the bundled translator; the bug you experience was fixed in the move to Zotero 4.0.27. I did however find I hadn't fixed that bug for BibTeX, only BibLaTeX, so I'm going to release a new version for that in any case.

**Comment by noschinl** [comment]
I upgrade to 0.14.13 and this is fixed now. Thanks for this great tool and the swift bugfixes!

**Comment by retorquere** [comment]
Always a pleasure, and thanks for reporting the issue.
