### ISSUE TITLE
Extended debugging too verbose?

### ISSUE THREAD

**Issue by igravious** [ZotPlus/zotero-better-bibtex#238]
Seems to be logging the entire XRegExp.js code to the Zotero log...

Is this the intended behaviour?

Do you want me to attach a log or do you have enough to go by?

**Comment by retorquere** [comment]
It's not intended, but it's not soemthing I can prevent; Zotero for some reason logs the entire source of the translator if it's not one of their own. which in the case of BBT means 5 times, as I bundle 5 translators. The log lines added by BBT are always prefixed by `[better-bibtex`, all the rest is Zotero itself or other extensions. For less verbose logging, you can set `extensions.zotero.debug.level` to `3`, but as Zotero logs the translators to loglevel 3 when it saves them, there's not much I can do about it.

**Comment by igravious** [comment]
I understand. 5? I only noticed XRegExp in the logs. If the logging wasn't so verbose I'd nearly leave it on the whole time. As it is I'll just enable it when I really need it. Should I file an issue with the Zotero folks? Great tool by the way, I'm using it in conjunction with the Atom.io citations package. Happy user here.

**Comment by retorquere** [comment]
I wouldn't necessarily count it as a Zotero bug; I don't really even know
why the translation installer is included as they don't use it themselves.
I'll just write my own translator installer, that will get rid of the
source in the logs, should be done tonight. The zotero logs are indeed
quite chatty; setting the log level at 3 trims them down substantially.

**Comment by igravious** [comment]
Super. Do you want to leave this issue open until after you push that change? And I'll check from my end? Where do I set  ```extensions.zotero.debug.level``` to ```3```? Browser JS Console?

**Comment by retorquere** [comment]
Yes, please leave it open. You can configure the debug level in
`about:config`; it would be easy enough to add a slider to the preferences
screen, but any change to the debug level would also affect logs sent to
zotero itself, and I'd rather not provide a mechanism by which a user could
casually (and unwittingly) meddle with the diagnosis process of zotero
itself. BBT is already invasive enough that people should really disable it
while trying to track down problems in zotero itself.

**Comment by retorquere** [comment]
Will be out in the next release

**Comment by igravious** [comment]
Great. Thanks for the about:config tip!
