### ISSUE TITLE
Better Bib(La)TeX export: square brackets

### ISSUE THREAD

**Issue by Wekhrlin** [ZotPlus/zotero-better-bibtex#245]
I have problems with the export of square brackets. It seems to be a bit like this one: https://github.com/ZotPlus/zotero-better-bibtex/issues/85 – but it doesn't solve my problem.

As historian, I sometimes have books without a mentioned date and/or location of the publication. In this case, I put the historically derived year and location in square brackets. My citation should then look like this:

Andreas Riem: Behemoth. Der Roman über alle Romane, [Hamburg] [1796].

If I put the year and the location in square brackets in Zotero, Better BibTeX and Better BibLaTeX exports it this way:
@book{riem_behemoth_1796,
  location = {{[}Hamburg{]}},
  title = {Behemoth. Der Roman über alle Romane},
  author = {Riem, Andreas},
  date = {1796}
}

– The square brackets of the location now are in curly brackets and the square brackets of the year are gone. This causes my footnote (after running LaTeX) to look like this:

Andreas Riem: Behemoth. Der Roman über alle Romane, [ 1796.

Now, I could work with a script which replaces every "{[}" and "{]}" with "[" and "]", but it would have to run after every new (automatic) export. But this only solves the problem with the location and for the year I would have to add all the missing brackets by hand.

Is it possible to export the data in the regarding fields of Zotero just as they are entered? With all the square brackets I add?

Besides that, Better BibTeX is a great plugin that helps a lot connecting Zotero and LaTeX!

**Comment by retorquere** [comment]
Alright, these are two separate issues (no worries, just making sure I'm addressing them both).

## the year field strips brackets

I'm a little surprised the year is stripped from its braces; can you right-click on that reference and select `submit zotplus error`? That should get me going on fixing the year.

## biber doesn't like closing brackets being escaped

The location might look a little gnarly but it should be correct LaTeX; the following MWE:

    \RequirePackage{filecontents}
    \begin{filecontents*}{\jobname.bib}
    @book{riem_behemoth_1796,
    location = {{[}Hamburg{]}},
    title = {Behemoth. Der Roman über alle Romane},
    author = {Riem, Andreas},
    date = {1796}
    }
    \end{filecontents*}

    \documentclass{article}
    \usepackage[%
      backend=bibtex   % use BibTeX
    % backend=biber    % Use biber
    ]{biblatex}
    \addbibresource{\jobname.bib}
    \begin{document}
    Hello \cite{riem_behemoth_1796}. How are you?
    \printbibliography
    \end{document}

compiles to

    Andreas Riem.Behemoth. Der Roman über alle Romane. [Hamburg], 1796

The biber backend however doesn't like the above at all, and that results in pretty much what you describe. I escape `[` and`]` to prevent LaTeX from treating literal square brackets as parameters, but my preliminary tests show that if I only escape `[` stuff looks OK. I'll get to work on that too.

**Comment by retorquere** [comment]
Can you test whether zotero-better-bibtex-1.0.5-2015-07-14@16:20:55.xpi at https://zotplus.github.io/better-bibtex/#debug addresses the second problem?

**Comment by Wekhrlin** [comment]
okay, the second problem seems to be my fault. I added "backend=bibtex" to my file and the square brackets are there as they should be. Thank you!

For the first problem I submitted the error. the code is 4RCU2UNQ-TXFDRJDT (if you need this).

**Comment by Wekhrlin** [comment]
without "backend=bibtex" and with the version you posted above, it works perfect, too. it exports "{{[}Hamburg]}"

**Comment by retorquere** [comment]
Nono, not your fault, I want it to work with biber too; the debug version I
posted above should work with biber as you had it before.

I'll look into the first problem when I get home.

**Comment by Wekhrlin** [comment]
Thank you.
I just remembered another problem, I had recently with a customized export: I wanted to define a xref entry and put

bibtex[xref=welker_andreas_1999]

into the extra field of Zotero. The output is translated into correct LaTeX with a backslash before each underscore.

  xref = {welker\_andreas\_1999}

Is there a way to prevent the LaTeX translation of the underscores?

**Comment by retorquere** [comment]
Sure; could you file a separate issue for that?

**Comment by retorquere** [comment]
Could you try to generate another debug log by right-clicking on the entry that has the `[1796]` and selecting `Report Zotplus Error` from that menu (so not from the gear menu - -that doesn't send me the sample)

**Comment by retorquere** [comment]
Never mind, I see it now.

**Comment by Wekhrlin** [comment]
it was the report from right-clicking – but I see the same report text when I access it via the gear menu...

**Comment by retorquere** [comment]
It is indeed broken -- I've filed a separate bug for that, but I have a handle on things for this bug

**Comment by retorquere** [comment]
1.0.6 is out, and fixes both #245 and #246

**Comment by Wekhrlin** [comment]
you are going to hate me, but it seems that the export is broken, now. I get a JavaScript Application-warning that an error occurred while exporting: 
![bildschirmfoto 2015-07-14 um 21 33 33](https://cloud.githubusercontent.com/assets/4112781/8682944/0bd9c812-2a70-11e5-92e2-5a9584e64d7b.png)

It's the same on my girlfriend's computer with a whole different library... shall I report a new issue?

**Comment by retorquere** [comment]
Yes please! Inclusing a debug log

**Comment by Wekhrlin** [comment]
no. doesn't work. HIM54E48-XSGUUNT9
