### ISSUE TITLE
xref should not be escaped

### ISSUE THREAD

**Issue by Wekhrlin** [ZotPlus/zotero-better-bibtex#246]
As mentioned in https://github.com/ZotPlus/zotero-better-bibtex/issues/245 I have the following problem with customized export: If I want, for example, define a xref entry and put

    bibtex[xref=welker_andreas_1999]

into the extra field of Zotero, the output is translated into correct LaTeX with a backslash before each underscore:

    xref = {welker\_andreas\_1999}

Since this value should be a BibTeX key, and not to be translated to LaTeX, it doesn't link to the right key with the backslashes before the underscores.

**Comment by retorquere** [comment]
This is not hard to fix, but wouldn't you rather use the Zotero-native "related" feature?

**Comment by Wekhrlin** [comment]
I use the xref for articles from collections: If there are two or more articles from the same book, it does not need to cite the full title of the collected volume for a second time; then the short title of the collection is enough. it looks like this (for german footnotes):

 1. Michael Maaser: Andreas Riems literarisches Werk, in: Karl H. L. Welker [Hrsg.]: Andreas Riem. Ein Europäer aus der Pfalz (Schriften der Siebenpfeiffer-Stiftung 6), Stuttgart 1999, S. 37–49.
 
 2. Johannes Süssmann: Andreas Riem und die Französische Revolution, in: Welker [Hrsg.]: Andreas Riem (wie Anm. 1), S. 107–118.

The relate-feature in Zotero doesn't support this sort of relation – and I use it in Zotero to connect primary literature/historical sources with related research literature, not the articles from the same collection... But if one doesn't need the short title collection-feature of xref, the native feature should be enough.

**Comment by retorquere** [comment]
Alright, good to know. Both work now in any case. Enjoy, and thanks for your reports!

**Comment by Wekhrlin** [comment]
no. doesn't work. HIM54E48-XSGUUNT9

**Comment by retorquere** [comment]
Progress. Can you try zotero-better-bibtex-1.0.6-2015-07-14@21:51:22.xpi ?
