### ISSUE TITLE
Export failure for items that have related references

### ISSUE THREAD

**Issue by Wekhrlin** [ZotPlus/zotero-better-bibtex#248]
can't export with both BibTeX & BibLaTeX. See: https://github.com/ZotPlus/zotero-better-bibtex/issues/245#issuecomment-121352432

**Comment by retorquere** [comment]
I'll need a debug ID, I can't reproduce it right now

**Comment by Wekhrlin** [comment]
VWSKH5VV-GA9UJWQ2:

[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibLaTeX.js" line: 3346}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]
[JavaScript Error: "xref is undefined" {file: "/Users/ml/Library/Application Support/Zotero/Profiles/udbid167.default/zotero/translators/Better BibTeX.js" line: 3347}]

version => 4.0.27.6, platform => MacIntel, oscpu => Intel Mac OS X 10.10, locale => en-US, appName => Zotero, appVersion => 4.0.27.6, extensions => Zotero Better Bib(La)Tex (1.0.6, extension), Default Browser Helper (600, plugin), QuickTime Plug-in 7.7.3 (7.7.3, plugin), Shockwave Flash (18.0.0.203, plugin), Automatic Zotero to BibTeX exporter (0.51, extension, disabled), Zotero automatic export (1.1.9.1.1-signed, extension, disabled), Zotero Word for Mac Integration (3.5.8.SA.4.0.27.6, extension, disabled), Zotero LibreOffice Integration (3.5.9.SA.4.0.27.6, extension, disabled)

**Comment by Wekhrlin** [comment]
and DZZQ7J9N-6AMM82J6 from the other computer

**Comment by retorquere** [comment]
Can you try zotero-better-bibtex-1.0.6-2015-07-14@21:47:37.xpi from https://zotplus.github.io/better-bibtex/#debug ?

**Comment by retorquere** [comment]
Whoops, I posted in the wrong issue. Can you try zotero-better-bibtex-1.0.6-2015-07-14@21:51:22.xpi ?

**Comment by Wekhrlin** [comment]
yes. it seems to work again!

**Comment by Wekhrlin** [comment]
(the wrong issue was my fault. I messed up the windows on my screen...)

**Comment by retorquere** [comment]
Meh, fault. The fault was mine, if I hadn't introduced the bug, you wouldn't have messed up the windows, etc. The build is running, 1.0.7 will be out when https://travis-ci.org/ZotPlus/zotero-better-bibtex/builds/70965928 goes green.

**Comment by retorquere** [comment]
Done, and the error report is now also fixed. As always, thanks for your reports and your patience!

**Comment by Wekhrlin** [comment]
I have to thank you: This is the best extension for Zotero because without it, we could not use Zotero that smooth in connection with LaTeX!
