### ISSUE TITLE
bibtex dislikes \textbackslash

### ISSUE THREAD

**Issue by jeffalstott** [ZotPlus/zotero-better-bibtex#251]
I export my Zotero library with Better Biblatex, which creates 'Exported Items.bib'. I then use that .bib file in my LaTeX document:
 
```  
\usepackage[sorting=none,
doi=false,isbn=false,url=false,
style=numeric-comp]{biblatex}
\addbibresource{Exported_Items.bib}

.... %document here

\printbibliography
```
On compilation, I get the error:
```
   Tex capacity exceeded, sorry [input stack size = 5000]
```
Here is the Exported Items.bib created. Any ideas what's going on?
https://gist.github.com/jeffalstott/7f8ce4d282ff8fe4def0

As backstory, In order to get Exported Items.bib to actually be created I had to go through many of the items in Zotero and remove the abstracts, because they had & characters that were causing problems ("R&D" rendered as "R;ampD" in Zotero; maybe it was a unicode issue).

**Comment by retorquere** [comment]
This is usually an error in the latex file. Does it matter if you export
only part of the library? Is it different if you export using the standard
zotero bibtex exporter.

**Comment by retorquere** [comment]
Wait what, do you have samples of those abstracts? That should not be happening.

**Comment by retorquere** [comment]
I get a different error than the one above; https://gist.github.com/1aa311331aa9bdbb2aba fails because of the `\textbackslash`. No idea why, honestly, as I think it is valid BibTeX; pragmatically you could add `abstract` to the skipfields in the BBT preferences to filter out the abstracts.

**Comment by retorquere** [comment]
If you could right-click an entry that has the `R;ampD` problem and select "report zotplus error", I'd be very keen to investigate further. I haven't been able to reproduce the problem yet.

**Comment by retorquere** [comment]
Can you try replacing 

    \textbackslash

with

    \char`\\

and see if that compiles for you?

**Comment by retorquere** [comment]
\char`\\ has issues of its own. I've reverted to the old-style $\backslash$, which isn't perfect, but at least it works consistently. I'm leaving the issue open for now as I'd still very much like to get to the bottom of the "R;ampD" problem, which I haven't been able to reproduce so far.

**Comment by retorquere** [comment]
I think 1.0.11 will fix both issues you experience, but I'd love to have confirmation on that.

**Comment by retorquere** [comment]
Can you provide me with a sample of an entry with the R&D problem? I haven't been able to reproduce, and I *really* want to fix it.

**Comment by jeffalstott** [comment]
I have for other reasons reinstalled the OS on this computer, and in the process of reinstalling Zotero and ZotPlus realized I was previously on a version older than 1.0.11. Everything seems to be working now. Sorry, and thanks for all the great work!

**Comment by retorquere** [comment]
No apologies expected -- you did lead me to a two bugs I have now fixed. No report is ever in vain.

**Comment by jeffalstott** [comment]
\o/

**Comment by retorquere** [comment]
Just to verify: do you remember one of the entries that had the R&D problem? If so, could you right-click and send me a bug report on one? There is still something strange going on; the current fix might be *over* correcting for things like &amp; in the reference.

**Comment by retorquere** [comment]
Just to verify: do you remember one of the entries that had the R&D problem? If so, could you right-click and send me a bug report on one? There is still something strange going on; the current fix might be *over* correcting for things like `&amp;` in the reference.

**Comment by jeffalstott** [comment]
I had deleted all the abstract fields that were causing me a problem with
the "R;ampD" text. After upgrading, there were no problems. I just created
a test case, and this is what ZotPlus put in the abstract field of
Exported_Items.bib:

```
abstract = {R;ampD},
```

**Comment by retorquere** [comment]
Did you just submit an error report for that reference? I see an error report but I can't tell who it's from.

**Comment by jeffalstott** [comment]
Nope. There was no error!

**Comment by retorquere** [comment]
Ah OK. Could you please right-click the reference that resulted in the `abstract = {R;ampD},` output and submit an error report? Doing so will get me the reference in full so I can use it to debug.

**Comment by jeffalstott** [comment]
Report ID: 20150718-V8FU69NG

**Comment by retorquere** [comment]
What the... that entry does indeed have the text "R;ampD" literally, but I sure that isn't actually in your Zotero library. Could you do me a favor and export that entry in "CSL JSON" format, and put that in a gist?

**Comment by jeffalstott** [comment]
I am confused; I put that text "R;ampD" in there *manually*; I had deleted
all the original abstracts that had the real offending characters.

**Comment by retorquere** [comment]
OK, I should have been more clear on that :) I was under the impression that there were items where you typed in `R&D`, and in the exported BibTeX you saw `R;ampD`, and your debug log confirmed my worst fears based on that faulty assumption :)

**Comment by jeffalstott** [comment]
Indeed. Typing in "R&D" gives "abstract = {R\&D},", which I believe is what
we want.

**Comment by retorquere** [comment]
Right! OK, so that is now OK, but it turns out BBT is indeed over-correcting. Typing in `R&amp;D` will *also* yield `R\&D`, which, while probably desirable in many instances, simply isn't correct. Looking into that -- but it's good to know BBT isn't injecting HTML-ish output.
