### ISSUE TITLE
Export Library Javascript error

### ISSUE THREAD

**Issue by lizzydoodle** [ZotPlus/zotero-better-bibtex#253]
Error ID: MWZ7559W-92WC92J5

When I (manually) chose to export my Library with the settings:
Better BibTeX
keep updated
I get an error message:
[JavaScript Application]
An error occurred while trying to export the selected file.

**Comment by retorquere** [comment]
I have a test suite in place to prevent regression, but with the diversity in libraries out there, it is hard for me to prevent any errors from getting out in the wild. Sorry for the disruption though. The error log unfortunately doesn't show any errors related to BBT; can you please go into the BBT preferences, enable "extended debugging", reproduce the error, and submit a new error log?

**Comment by retorquere** [comment]
(sorry for editing the issue subject, but the wording felt uncomfortable to me)

**Comment by lizzydoodle** [comment]
Sorry regarding the title, you guys do amazing work!
Error ID: IXSTW5VD-XPPJM5EN
I turned on the extended logging. Still not able to export. Getting the exact same error message :-(

**Comment by retorquere** [comment]
There's no guys, it's just me :) I do realize BBT is a little volatile; my time however is stretched between a full time job, a study, and a family, so I haven't fully been able to prevent errors getting out in the wild. I do have a fairly substantial test suite at this time, and I generally add new test cases for each bug I solve to prevent regression, but it's an imperfect process. I try to make up for the imperfection by having good turnaround times.

The error log gives me enough to fix the error, so I'll put a release out shortly, but I'd love to know exactly what source text triggered it. You have a reference that has (probably in the abstract)

> In 2011 the international development community committed to make development co-operation more effective to deliver better results for

Can you right-click that and produce a new debug log? That will get me the reference in question, and it probably also gives me a lead into a secondary problem hinted at in #251.

**Comment by retorquere** [comment]
In the interim, can you test whether http://tempsend.com/5632599977 fixes the problem you experience?

**Comment by lizzydoodle** [comment]
As requested: ID 4IWZHWPP-HA7GBWM5
That new update worked - thanks!

**Comment by retorquere** [comment]
Super -- thanks for the confirmation and for the debug data -- a new release has been published.

**Comment by retorquere** [comment]
There is still a remaining bug that puts HTML-ish codes in the export -- I'm working on that, but 1.0.10 at least will let you export.

**Comment by lizzydoodle** [comment]
Awesome, thanks!

**Comment by retorquere** [comment]
Got it, using your test case. 1.0.11 is out.

**Comment by retorquere** [comment]
Just to verify, if I import your reference, it *actually* has the literal text `world&#8217;s poor`, ampersand included. Is that also what you have? Or is there an apostrophe?

**Comment by retorquere** [comment]
It looks like BBT wasn't actually injecting HTMLish codes, but rather that the source reference had them. I think the reference does in fact have `world&#8217;s poor` if you look into the abstract field rather than the apostrophe that would translate to if displayed in a web page. If so, that would have been an error introduced by the import translator which was used to import the reference rather than by BBT on output.

**Comment by retorquere** [comment]
(the "second-guesser" aspect of the bug title is still correct though -- and the export failure that it caused is still fixed)

**Comment by lizzydoodle** [comment]
It did indeed have `world&#8217;s poor` in the abstract. In addition, I found `,&nbsp;` as well. Does this make a difference?

**Comment by retorquere** [comment]
It makes a difference in the sense that BBT correctly (in a letter-of-the-law sense) translates those to `\&\#8217;` and `\&nbsp;`, where you'd obviously want a quote  and a space instead. But these were introduced during initial import of the reference, and BBT auto-correcting for those would mean one could never have those literal texts in a reference -- I don't really want to go that far. The current behaviour  has been restored to do a straightforward translation of whatever-you-have to valid LaTeX -- in this case, `\&\#8217;` and `\&nbsp;`. I initially thought I was introducing these myself.
