### ISSUE TITLE
this.skipFields is undefined

### ISSUE THREAD

**Issue by adunning** [ZotPlus/zotero-better-bibtex#255]
I am getting the message 'An error occurred while trying to export the selected file' when trying to export any part of my library with BBT; other exporters work (report ID: BSQAT6CG). I've tried the steps suggested in #175 of reinstalling everything (Zotero 4.0.27.7, BBT 1.0.13), but nothing seems to have an effect.

**Comment by adunning** [comment]
By the way, I also have ZotFile and zotxt installed, but disabling these has no effect.

**Comment by retorquere** [comment]
Could you go into your profile directory, and (after shutting down Firefox) drop the file `betterbibtex.sqlite` into https://dbinbox.com/retorquere?

**Comment by adunning** [comment]
Done.

**Comment by retorquere** [comment]
Can you try http://tempsend.com/05D40480FE ?

**Comment by retorquere** [comment]
Hold on, before your try that, can I send you a file?

**Comment by adunning** [comment]
I already gave it a shot (still getting an error), but certainly.

**Comment by retorquere** [comment]
Sorry, I meant: how can I send you a file?

**Comment by retorquere** [comment]
(no harm done by trying, it just wasn't going to work)

**Comment by retorquere** [comment]
If there's nothing sensitive in your reference list, I can just put it on tempsend

**Comment by adunning** [comment]
You can also use <https://dbinbox.com/dunning>.

**Comment by retorquere** [comment]
Sorry, what is in your dbinbox now is not the file I meant to send. I'm putting a new one there with a `-1` postfix.

**Comment by retorquere** [comment]
Could you please back up your current betterbibtex.sqlite (while firefox isn't running), put this one in place (renamed to `betterbibtex.sqlite`), and try again? The DB schema upgrader wrongly marked your database as upgraded and so doesn't even try to at this moment. There's only a single change in the database -- I've set the schema version to empty to trigger the upgrader. If you're comfortable with sqlite, what I've done is `update schema set version='';`

**Comment by adunning** [comment]
I really hate to say it, but I'm still getting the same error after replacing the file. If it's a problem in the database, is there a way to simply reset the whole thing?

**Comment by retorquere** [comment]
I'm hoping it is now a different error, so a new debug log should tell me more.

It is terribly easy to reset -- just delete betterbibtex.sqlite -- but all your current keys except those that are pinned will be regenerated.

**Comment by adunning** [comment]
After deleting the database, I'm now running into a completely different problem: everything disappears from the Zotero menu (this is OS X) except for the Quit item, meaning that I can't access the preferences unless I disable BBT.

**Comment by retorquere** [comment]
I don't have that, but you can access the preferences by going to the addons menu of Firefox, and clicking the preferences button of Zotero

Terribly sorry you're having these problems.

**Comment by retorquere** [comment]
(with "I don't have that" meaning "I do have an OSX machine, but I don't have that problem if I delete the database)

**Comment by adunning** [comment]
I'm sorry to be taking up your time with this! It's Zotero Standalone.

**Comment by retorquere** [comment]
Oh jeez please don't apologize; it's not your doing. I'll get ZSA, but in the meantime you should still be able to access the prefs via the addons menu.

**Comment by adunning** [comment]
I am from Canada; it's my job to apologize. I've sent a new report: R879VTVP.

**Comment by retorquere** [comment]
*grin* so the stereotypes are true then. I do see an error in the log, and http://tempsend.com/CFEB3609AC should take care of that, but that error doesn't explain why BBT cleans out the gear menu.

**Comment by retorquere** [comment]
I can't reproduce the problem with ZSA either (if I delete the DB, everything is just fine), but it could be an interplay with your specific library. Keen to get a new debug log from that last version.

**Comment by adunning** [comment]
Whatever it was, it seems to have gone away. Export is now working, but the generated file ignores the key format I have set (it appears correctly within Zotero).

**Comment by adunning** [comment]
Actually, it's only ignoring it for some of the items, which makes even less sense.

**Comment by retorquere** [comment]
That's probably the serialization cache. If you want a full reset, you will need to delete both betterbibtex.sqlite, and serialized-items.json.

**Comment by adunning** [comment]
Yes, that worked. Thank you!

The menus disappeared again after removing both files, but they came back after running an export and restarting Zotero.

**Comment by retorquere** [comment]
Crrrrazy!l The menus disappearing really ought to leave a trace in the debug log -- if it happens again, please do submit a new error log from the prefs menu.

**Comment by retorquere** [comment]
Once the test pass again I'll put out a new version which properly upgrades older databases -- it wont help you after the reset (unless you're interested in getting your old keys back as they were), but at least it won't affect other. So thanks for the reports -- always appreciated!

**Comment by adunning** [comment]
Actually, I didn't even have to delete the files again: see A4FQ6JUI.

**Comment by adunning** [comment]
Thanks again for taking care of that export problem: I'll create a new issue for the menus.

**Comment by retorquere** [comment]
Oddly enough, zero errors in that log.

**Comment by retorquere** [comment]
I have to step out for a little while.

**Comment by adunning** [comment]
I do as well; and this isn't at all urgent. Thanks again!
