### ISSUE TITLE
System menus disappear under Zotero Standalone

### ISSUE THREAD

**Issue by adunning** [ZotPlus/zotero-better-bibtex#256]
Most of the Zotero Standalone menu items disappear (leaving only Quit in the application menu) if I enable BBT extended debugging and restart. They come back after disabling the option.

**Comment by retorquere** [comment]
Is this specifically with extended debugging, or just generally if you have BBT installed? I suspect that it won't be possible to submit an error given that menus are breaking, but if you could

* go into Preferences -> Advanced -> Enable after restart
* restart Zotero
* go into Preferences -> Advanced -> View Output

you will see the error log; if you could paste that into a gist, that would be helpful

**Comment by retorquere** [comment]
Do you have both Standalone and Firefox running BTW?

**Comment by adunning** [comment]
Only Zotero Standalone. I realized that the preferences are also available in the gear menu: report ID TP2S3FE8.

**Comment by retorquere** [comment]
Wait, the actual *menu* items disappear? Like `File`, `Edit`, etc? Once again, no errors in the logs, which means that the error occurs before the Zotero logging system kicks in. Does it make any difference if you disable zotxt and zotfile?

**Comment by retorquere** [comment]
Would it be possible to zip up your entire zotero folder (make sure zotero isn't running) and plunk it into my dbinbox? Perhaps with your library I can reproduce the error.

**Comment by adunning** [comment]
It's only the options within the individual menus. My Zotero folder is 2.4 GB; I suppose attachments could be omitted?

I see that this consistently occurs only with zotxt enabled as well as BBT extended debugging.

**Comment by retorquere** [comment]
Yes, I suppose they could. Could you also try the following:

* Open Terminal in /Applications/Utilities
* Go to the Terminal menu and open Preferences. In Profiles→Window, make sure Scrollback is set to "Limit to available memory".
* Paste the following into the terminal window:

```
/Applications/Zotero.app/Contents/MacOS/zotero-bin -app /Applications/Zotero.app/Contents/Resources/application.ini -ZoteroDebug | tee zotero.log
```

This will start Zotero and spew its startup messages to the console, copying them into zotero.log. One Zotero is started (you'll notice the text stream in the console having stopped), you can exit zotero by typing control-C in the console window. If you could then drop zotero.log in my dbinbox, I can investigate further.

**Comment by adunning** [comment]
That doesn't result in any output to the console; Zotero launches, but with the same results.

**Comment by retorquere** [comment]
Not *any*?! Does it output to the console with BBT disabled?

**Comment by adunning** [comment]
Sorry, no; either way, it's completely silent.

**Comment by retorquere** [comment]
OK, that's officially not supposed to be possible -- those are the official Zotero instructions for getting a debug trace.

I loathe to ask, but would it be possible for me to remotely login to your system, using something like TeamViewer or Chrome Remote Desktop?

**Comment by adunning** [comment]
It only seems to display serious errors. I can get a longish file if I enable Debug Output Logging in the preferences: is this the same thing?

Today is a touch busy for me, but we could certainly look at that tomorrow.

**Comment by retorquere** [comment]
Serious errors is what I'm looking for -- anything else would be captured by the standard logging facilities.

**Comment by adunning** [comment]
I've sent you the results from the standard debugging – see if that's of any use.

**Comment by retorquere** [comment]
How have you sent those?

**Comment by adunning** [comment]
Through <https://dbinbox.com/retorquere>.

**Comment by retorquere** [comment]
Ah, right. Unfortunately, no errors in that log.​

**Comment by adunning** [comment]
Weird. Given that you can't reproduce it, and it's not in my way at all, there are probably better uses of your time; I'm going to close this for now. Thanks again!

There can't be that many people wanting to use both BBT and Zotxt in any case: I'm only wanting a stable way to get citations from Zotero to Pandoc, and I find that I get better results by feeding it CSL JSON directly rather than converting from that (in Zotero) to BibLaTeX and then back again, but I still need a BibLaTeX file to provide autocomplete (e.g. using [autocomplete-bibtex](https://atom.io/packages/autocomplete-bibtex) in Atom).

**Comment by retorquere** [comment]
I haven't gotten around to autocompletion for the Zotero integration, but if Atom + Markdown is your thing, https://atom.io/packages/zotero-citations or http://wasifbaig.com/brackets-zotero/ could be of interest to you.

**Comment by retorquere** [comment]
The first of those two produces the bibliography by pushing it though Zotero's CSL processor BTW.

**Comment by adunning** [comment]
Zotero-citations is an interesting approach; I'll have to remember that. Pandoc's native citations mechanism is fantastic, since it allows one to output either notes or inline citations from the same markup. (It can do this, and it actually works, because it's aware of the full document context, unlike the Zotero word-processor plugins.) The issue is simply making sure that the citation keys are correctly matched up with the data in Zotero, and get to pandoc-citeproc: Zotxt handles this flawlessly in most cases (but the BBT key generation is more reliable, since it can ensure that two items do not end up with the same key).

**Comment by retorquere** [comment]
I must admit I'm not entirely clear what zotxt does BTW does for your particular case? Generate the CSL JSON + citation keys? More?

**Comment by retorquere** [comment]
Are you using `-F pandoc-zotxt` in your document generation process? You can (as of .17) simulate that to some extent using auto-export -- a new translator has been added that exports pandoc-compatible JSON. Using a YAML metadata block you could point pandoc to the auto-exported JSON file.

**Comment by adunning** [comment]
Exactly: it simply bridges the gap between Zotero and Pandoc. It consists of two parts:

1. A Zotero plugin that provides a translator to output a citation key and an HTTP interface similar to that of BBT.
2. A Python filter for Pandoc that scans a document for citation keys and generates a temporary CSL JSON file from Zotero that pandoc-citeproc can read directly.

Since a file is created on-the-fly, one can correct an error in Zotero and regenerate the file immediately without having to worry about an exported database getting out of sync. Additionally, because the generated JSON file is limited to what is cited in the file, one can efficiently archive this, either if one wants to keep the citation data from a particular revision, modify it outside of Zotero to meet the requirements of a particular publisher, or send the raw data to a third party. It's also smart enough to sort out minor differences between the citation key and the Zotero data.

It falls a little short in the area of key creation: because it generates everything on-the-fly, including the citation keys, it's possible to get keys that don't correspond to anything, and one has to set a manual key instead. It also can't know whether two items might generate the same key, and Zotero always has to be running in order for its filter to work. It's brilliant, but it's not yet a system I could hand to my grandmother and expect everything to go smoothly.

**Comment by adunning** [comment]
And yes, the JSON export function is perfect: you read my mind!

**Comment by retorquere** [comment]
I've looked at the ZoTXT source and I see that it can use BBT-generated keys; personally, I've come to prefer auto-export over dynamic fetch; when co-authoring it is more easily shared, and I don't have to have Zotero running always (I do much of my work on a laptop during train rides; screen real estate is scarce).

A scanner that taps directly into BBT is drop-dead easy; the plumbing is already there as the brackets integration uses it. I'm just not entirely sure it's worthwhile; I'd much sooner look into forking autocomplete-bibtex into autocomplete-csl for a much smoother experience.

**Comment by adunning** [comment]
That's a good point: I hadn't considered that. I'm definitely going to give this a shot for my next paper.

I have already taken up too much of your time, so please say no if this isn't incredibly easy to implement, or if it would degrade performance too much: is it possible to automatically rewrite the JSON output to fix Zotero's lack of support for certain fields, primarily for DOIs on book sections (i.e. changing `"note":"DOI: 10.3828/978-0-85323-683-2"` to `"doi":"10.3828/978-0-85323-683-2"`)? Zotero already does this when sending its data to citeproc-js: see [the end of the relevant thread on the Zotero forums](https://forums.zotero.org/discussion/47132/book-sections-have-dois-too/).

**Comment by retorquere** [comment]
If there's a list of such fields it'd be trivial in fact. I've pushed a change that does it for `origdate`, but adding new fields is as simple as adding a name-to-name mapping.

**Comment by adunning** [comment]
I've added a list as #260.
