### ISSUE TITLE
Tags with <italic> rather than <i> throw an error during export

### ISSUE THREAD

**Issue by Moredread** [ZotPlus/zotero-better-bibtex#257]
When one of my references is present in a collection, exporting of the collection fails with "An error occured while trying to export the selected file." Exporting just this item also fails. This first occurs with version 1.0.1, older versions work.

Debug IDs:

1.0.13: GGVF9NRA
1.0.1: VREDB3MQ-DS5D7D2W

**Comment by retorquere** [comment]
Fixed in .14 -- apologies for the disruption

**Comment by retorquere** [comment]
Just to verify: you intentionally had `<italic>k</italic>-distribution` as one of your tags? I take it you'd want to have that translate to `\emph{k}-distribution` rather than `\ensuremath{<}italic\ensuremath{>}k\ensuremath{<}/italic\ensuremath{>}-distribution`?
