### ISSUE TITLE
Zotero hangs on exporting saved search

### ISSUE THREAD

**Issue by TorbjornT** [ZotPlus/zotero-better-bibtex#258]
This seems to have started after updating to the last version of Zotero Standalone. With BBT enabled, if I try to export a saved search, the progress bar will show up, but just keep running (as in screenshot below). The only thing that seems to work to stop the process is to close Zotero with Alt + F4, after which only an empty file is created. Exporting collections on the other hand, work fine. Exporting saved searches with BBT disabled also work fine.

I have tried removing Zotero, including config-directories, and reinstalling. I've also tried the Firefox plugin, with the same result. 

 - Zotero Standalone version 4.0.27.6
 - Better-Bib(La)TeX version 1.0.11
 - OS: Kubuntu 14.04

I do realize that this report is somewhat thin with regard to debug-information, but I don't really know what else to add. If there is anything I can try or do to provide you with more information, please advise. 

(I was a little bit unsure if I should report this to Zotero or here, apologies if my choice was wrong.)

![image](https://cloud.githubusercontent.com/assets/3189311/8774526/8beb5c8c-2edf-11e5-8489-a153b4d22ef6.png)

**Comment by retorquere** [comment]
It's reproducible, and this is the right place. On it.

**Comment by retorquere** [comment]
Yeah, definitely BBT. Zotero doesn't officially have a way to capture exports as I do for auto-export, so I root around quite deeply in zotero to make that happen. In the case of saved-searches specifically Zotero makes some assumptions for simplicity which require really ugly hackery to make auto-export work, and that ugly hackery broke on a recent change in Zotero. 1.0.16 has fresh new ugly hackery that is compatible with how the current Zotero works. Thank you for your report.

**Comment by retorquere** [comment]
ah and apologies are never necessary here -- I truly do appreciate any and all reports. It is a safe assumption, given how deeply I have to go into Zotero to make BBT work, that if something is broken while BBT is installed, that is of my doing. Given that, I generally hugely prefer bug reports to come here first -- I would very much like to avoid wasting the Zotero dev's time over an issue they cannot sensibly diagnose.

**Comment by TorbjornT** [comment]
Thanks for the quick response! 1.0.16 seems to work fine.

**Comment by retorquere** [comment]
My pleasure.
