### ISSUE TITLE
Add pandoc-compatible CSL-JSON auto-export

### ISSUE THREAD

**Issue by retorquere** [ZotPlus/zotero-better-bibtex#259]
See http://pandoc.org/README.html#citations

**Comment by adunning** [comment]
This is absolutely perfect (or as close to it as possible within the given restraints). Thanks for doing this!

**Comment by retorquere** [comment]
That's the fun thing about the current state of BBT; many of its workings have been generalized, and adding a new translator with auto-export is a cinch.

**Comment by retorquere** [comment]
https://zotplus.github.io/better-bibtex/cayw.html

**Comment by adunning** [comment]
Now *that* is cool.

**Comment by retorquere** [comment]
I must admit to a tinge of pride on that one. The bulk of the work was done by the Zotero guys & gals of course -- I mainly tricked the existing picker into thinking LibreOffice was asking for keys, and intercept the result.

**Comment by adunning** [comment]
Clever. That's going to be very handy.
