### ISSUE TITLE
Parsing extra variables from CSL notes

### ISSUE THREAD

**Issue by adunning** [ZotPlus/zotero-better-bibtex#260]
As a stopgap measure until Zotero can start adding fields again, these are variables already present in CSL (see the [specification](http://docs.citationstyles.org/en/stable/specification.html)), but can only be entered through Zotero's Extra field (= `notes` in CSL):

- DOI = doi in CSL
- PMID = pmid
- PMCID = pmcid
- original-date
- original-publisher
- original-publisher-place
- original-title
- reviewed-title
- status

The Zotero forums suggest entering these into the Extra field either in raw JSON (e.g. `{:original-date: 1876}`) or with the variable separated by a colon and space (e.g. `DOI: 10.3828/978-0-85323-683-2`); in the latter case, line breaks separate each variable.

**Comment by retorquere** [comment]
I'm looking through http://aurimasv.github.io/z2csl/typeMap.xml, and it suggests that DOI needs to be uppercased; I'm also a little surprised they mention it there, as DOI is a Zotero-supported field.

The current implementation (tests running) has 4 ways to enter data into the extra field:

1. the key-value format: `PMID: XXXX` on its own line.
2. the naive data block (mainly for compatibility with the stock BibTeX translators): `bibtex[key=value;key=value]`
3. the proper data block: `bibtex{...}`, where `{...}` is JSON5-formatted key-value data
4. csl variables: `{:original-date: 1876}`

Of 1-3, I currently only add PMID and PMCID; any data written in csl variable format (case 4) I assume is valid csl and will be passed to the same-named field in the resulting CSL-JSON.

**Comment by adunning** [comment]
Good find. The problem is that a DOI is only allowed on journal articles: if you need to cite it for a book section, encyclopedia article, etc. one currently needs to do this by hand. (This will probably save me aggregated hours of work by the time Zotero adds proper support.)

**Comment by retorquere** [comment]
I've added `DOI`; keep in mind that fields provided in the `extra` field will override anything else, so if you have two different `DOI`s (or any other field that maps to CSL), the one in the extra field will be used.

**Comment by retorquere** [comment]
All tests are green, so if this is all you need for now, I could cut a release.

**Comment by adunning** [comment]
Marvellous. This is everything I've personally needed at some point: if you want to be super-thorough, that list you found has a complete list of the missing variables, namely those with an asterisk under 'CSL variable descriptions'. These are the ones I missed:

- annote
- archive-place
- [citation-label, citation-number, container: probably not useful to expose]
- editorial-director
- event-date
- illustrator
- jurisdiction
- keyword
- locator [?]
- page-first
- year-suffix [probably not useful?]

**Comment by retorquere** [comment]
All of those will already work with the current implementation as long as
you use the csl-variable format; I don't do validity checks on those, I
simply pass those through as-is. Only 1-3 are restricted.

**Comment by adunning** [comment]
Oh, I see: sorry about that. I don't know of any apart from those three that have received special treatment.

**Comment by retorquere** [comment]
*grin* there you go again with the apologies. I'll cut a release tonight.
