### ISSUE TITLE
 booktitle/journal no {} enclosure for single word entries on export

### ISSUE THREAD

**Issue by darked89** [ZotPlus/zotero-better-bibtex#261]
Hello,

is there any way to force putting  {} around journal/journaltitle for articles and around booktitle for inbook/incollection on exports? I am using Lyx 2.1.3 with TeX Live 2014, and is quite bewildering that bibtex8 is dropping these entries and either printing references without them (apa) or not producing the PDF (apacite). 

I am using the latest versions: Zotero 4.0.27.6 + zotero-better-bibtex 1.0.18 on Lubuntu 15.04.

Many thanks for your help

Darek Kedra
PS Here is the example:
```
@article{doe_something_2000,
  title = {About something},
  volume = {100},
  number = {5},
  journal = Singleword,
  author = {Doe, {Anna}},
  month = jan,
  year = {2000},
  pages = {1--50}
}
```

**Comment by retorquere** [comment]
Do you have "preserve BibTeX variables" checked in your preferences perhaps? If it is off, it ought to output those fields with braces.

**Comment by darked89** [comment]
Thank you. That solved my problem. I will look for same large brown bag now...

**Comment by retorquere** [comment]
I would strongly advice assuming abhorrent documentation before user error.
Unless you have a brown bag fetish, in which case I wouldn't want to
intervene - but feel free to keep me in the dark (so to speak) on the
details.

Enjoy!
