### ISSUE TITLE
Parsed CSL variables from notes are supplied with extra keys

### ISSUE THREAD

**Issue by adunning** [ZotPlus/zotero-better-bibtex#262]
Almost there! Using BBT 1.0.19, with this in the Extra field in Zotero:

```
{:doi: 10.3828/978-0-85323-683-2}
{:pmid: 16016791}
{:pmcid: PMC194697}
```

I receive this:

```json
[
  {"id":"bloggs:2015test","type":"chapter","title":"Test","container-title":"Test","note":"\n\n","author":[{"family":"Bloggs","given":"Joe"}],"issued":{"date-parts":[["2015"]]},"doi":{"value":"10.3828/978-0-85323-683-2","format":"csl"},"pmid":{"value":"16016791","format":"csl"},"pmcid":{"value":"PMC194697","format":"csl"}}
]
```

Pandoc-citeproc cannot parse this, since it expects the following:

```json
[
  {"id":"bloggs:2015test","type":"chapter","title":"Test","container-title":"Test","doi":"10.3828/978-0-85323-683-2","author":[{"family":"Bloggs","given":"Joe"}],"issued":{"date-parts":[["2015"]]},"PMID":"16016791","PMCID":"PMC194697"}
]
```

The parsed vales for DOI, PMID, PMCID do not need their own object. I would also suggest removing the `notes` value if it contains only line breaks or whitespace.

I would expect the same results with this in Extra:

```
DOI: 10.3828/978-0-85323-683-2
PMID: 16016791
PMCID: PMC194697
```

But I get this:

```json
[
  {"id":"bloggs:2015test","type":"chapter","title":"Test","container-title":"Test","note":"DOI: 10.3828/978-0-85323-683-2","author":[{"family":"Bloggs","given":"Joe"}],"issued":{"date-parts":[["2015"]]},"PMID":{"value":"16016791","format":"key-value"},"PMCID":{"value":"PMC194697","format":"key-value"}}
]
```

The DOI doesn't seem to be processed at all; the PMID and PMCID are, but pandoc-citeproc cannot parse this at all.

I assume this is not allowable syntax:

```
original-date: 1662
original-publisher: Sheldonian Theatre
```

This is left unparsed.

**Comment by retorquere** [comment]
I have amended the following:

* clear out extra field if empty
* pass the value rather than the parsed value-object
* allow DOI in key-value format

Those last two (original-date and original-publisher) are indeed not parsed; because the key-value format is a little too easy to my taste to enter intentionally as regular text, I pick out only a very specific set, to which I've now added DOI. You could enter those as

```
{:original-date: 1662:}
{:original-publisher: Sheldonian Theatre:}
```
and they'll be picked up. I've put up a version with these changes at http://tempsend.com/B80FF53C15

**Comment by adunning** [comment]
This works! I had to delete the BBT serialized-items file before it would apply the new method to my library (even with a new export).

(By the way, just in case it makes it into documentation somewhere, there should not be colons before the closing brace in your last example.)

**Comment by retorquere** [comment]
Right, sorry about that serialization cache, that really only happens when
you test between-release versions. I'll cut a new release when I get home.
