### ISSUE TITLE
Scrivener support

### ISSUE THREAD

**Issue by retorquere** [ZotPlus/zotero-better-bibtex#263]
It should in principle be possible to compile straight from Scrivener through pandoc to what-have-you, citations and all. For this appropriate scripts would be placed in `~/Library/Application Support/MultiMarkdown` for OSX -- yet to figure out what to do for Linux & Windows.

**Comment by retorquere** [comment]
http://literatureandlatte.com/forum/viewtopic.php?f=21&t=30956&p=196747&hilit=pandoc#p196747 points at a way to point to the bibliography

**Comment by retorquere** [comment]
http://literatureandlatte.com/forum/viewtopic.php?f=21&t=30956&p=196747&hilit=pandoc#p196747

**Comment by mijalce** [comment]
proposal for workflow that will need to be supported
1. Writing in Scrivener, add citations
1.1. In Scrivener when you call for citation (cmd+Y) to open a plugin in which you can search zotero and select a paper. When you press on the paper to automatically copy the citation on the clipboard and then by cmd+v to add it in the text in Scrivener
1.2. Options for citations for example (author date) or (date) or author (date)
1.3. Options for multiple citations
1.4. The citation to be short for example something like {@santa, 2015} and be able to add page or some text before after the citation. The citation should look simple
2. In Scrivener compile for markdown (pandoc-markdown)
3. In BetterBibtex or new addon scan the generated markdown file and create word file that contains the citations and the bibliography
4. BetterBibtex or the new addon to give you an option to choose style  
5. Get a fully expanded Word document including bibliography, with which you can do whatever you need to

**Comment by retorquere** [comment]
http://tempsend.com/19E1A1797C

**Comment by retorquere** [comment]
http://tempsend.com/26BC40D33B, url is now localhost:23119/better-bibtex/cayw

**Comment by retorquere** [comment]
http://tempsend.com/94F11B21C2

So if your Cmd-Y command calls a script that does
```
#!/bin/bash
curl -o /dev/null localhost:23119/better-bibtex/cayw?keyprefix=@
```
the Zotero citation dialog will pop up and will leave the selected citations on the clipboard. If Scrivener wants to go for real integration (they haven't answered my emails yet -- disappointing) they could call the same URL and the body text will give the citations.

This handles 1.1/1.3/1.4. I don't know if pandoc handles 1.2.

2 would be handled by zotxt from @egh.

3 would no longer be necessary

4. would be specified in the front matter which will be picked up by pandoc

5. profit

So we're nearly there, really.

**Comment by mijalce** [comment]
This is excellent. The development is going very fast. I will raise the issues with Scrivener and push the integration. 
Is it possible to create a script that can be added in the field for Bibliography manager in Scrivener? This will help non-technical users to more easily use the integration.

**Comment by retorquere** [comment]
```
#!/bin/bash
curl -o /dev/null localhost:23119/better-bibtex/cayw?keyprefix=@
```
is the entire script.

**Comment by retorquere** [comment]
This was all release under 1.1.1 BTW.

If Scrivener were interested in a *proper* integration without having to paste in the results, this can also be done with 1.1.1, using https://zotplus.github.io/better-bibtex/cayw.html . But that would be up to them.

**Comment by retorquere** [comment]
Sorry, that should be
```
#!/bin/bash
curl -o /dev/null localhost:23119/better-bibtex/cayw?keyprefix=@&clipboard=yes
```

**Comment by retorquere** [comment]
You will want to read up on the pandoc manual. What's here can already be used with markdown, but it won't be anywhere near as fluid. The new picker + current zotxt + pandoc will do one-click full compile without any of the rtf scan malarkey.

**Comment by retorquere** [comment]
Try to minimize the Zotero window(s) after the picker is closed.

**Comment by retorquere** [comment]
Fixed: zotpick.app added to cayw page, plus instructions
Todo: review of installation of pandoc-zotxt
Todo: minimize Zotero after picker closes

**Comment by retorquere** [comment]
Fixed: zotpick.app added to cayw page, plus instructions
Todo: review of installation of pandoc-zotxt
Fixed: minimize Zotero after picker closes
Todo: figure out why Scrivener prevents the clipboard from being filled

I will contact L&L; if I start zotpick manually, the clipboard gets filled, if Scrivener calls it, it is not.

**Comment by mijalce** [comment]
now, by using zotpick2.app, the clipboard is filled in. The citation output is @Kane.etal.2014.whats not [@Kane.etal.2014.whats]

**Comment by retorquere** [comment]
Where does zotpick2.app come from? Did you appify that yourself? And this works consistently? Because mine does not, as in, it consistently doesn't work. Could you drop yours into https://dbinbox.com/retorquere ? I'm starting to deeply dislike OSX. Nothing just works, dammit. 

BTW, the best I can do is to minimise Zotero after the pick is done; the picker expects the app that wants the pick to activate itself after the pick is done. Scrivener could easily do this (just raise itself after it calls the URL), but given that Scrivener is closed source and has no extension API, there's really not anything else I can do myself. Zotero will be out of the way, but it's unlikely that Scrivener will have input focus.

**Comment by retorquere** [comment]
(oh and if you want `[@Kane.etal.2014.whats]`, the url you want is `http://localhost:23119/better-bibtex/cayw?keyprefix=%40&citeprefix=%5B&citepostfix=%5D&clipboard=yes` rather than `http://localhost:23119/better-bibtex/cayw?keyprefix=@&clipboard=yes`)

**Comment by retorquere** [comment]
hrng I hate those apps trying to be smart on your behalf -- dbinbox *also* unzips whatever you put in it. even obliterating the directory structure in the process. Is there another way I can directly download the zip?

**Comment by mijalce** [comment]
I used the download from the CAYW web site. The rename might have been made automatically by my computer. I placed the zotpick.app in Applications (in Finder) and then I placed it in Scrivener's Bibliography manager. 
For now the workaround, when you open Zotero and then minimize it, makes it possible when you call the picker and select the bibliography you to "still be" on Scrivener.

**Comment by mijalce** [comment]
Regarding the pick output format in Setting up Pandoc (https://zotplus.github.io/better-bibtex/cayw.html)

I changed it —to parametar to doc and docx but it failed to compile. It gives this error "pandoc: Unknown writer: doc”. Thus now it works only with html output. I test it it works. 

Question: Can we use something that I found on pandoc site (https://github.com/mb21/Pandoc-Mac-OS-X-Services) to create doc output?

**Comment by retorquere** [comment]
The link to the pandoc page lists supported formats (you can use docx, but doc is not supported), and caveat link does say some output formats are problematic: "though output to stdout is disabled for the odt, docx, epub, and epub3 output formats". We could perhaps fiddle around with putting the result in a temp file and then outputting that to stdout -- that might satisfy Scrivener.

Pandoc can create all these things just fine, it's just that Scrivener demands that it can run a script that reads standard input and outputs to standard output.

**Comment by mijalce** [comment]
I get these errors when I use compile to MultiMarkdown ->Web (html)

With this script 
#!/bin/bash
pandoc -F pandoc-zotxt -F pandoc-citeproc --from markdown --to docx

Error 1
There was a problem writing to the path '/Users/mijalce/Downloads/file.html'. You may not have the necessary permissions to save to this location - please try saving to a different place.

Error 2
Error parsing MultiMarkdown File 
pandoc: Cannot write docx output to stdout.
Specify an output file using the -o option.

When I tried compile to MultiMarkdown ->Web (html)

With this script 
#!/bin/bash
pandoc -F pandoc-zotxt -F pandoc-citeproc --from markdown_mmd+citations --to html

I get the same error 1 and 
This error
Error parsing MultiMarkdown File 
pandoc: Unknown writer: html

with this script 
#!/bin/bash
pandoc -F pandoc-zotxt -F pandoc-citeproc --from markdown_mmd+citations --to docx
I get the same error 1 and this error
Error parsing MultiMarkdown File 
pandoc: Unknown writer: docx

**Comment by egh** [comment]
You should be able to work around this issue using a script like this:
```
#/bin/bash
t=$(tempfile) || exit
pandoc -f markdown_mmd+citations -t docx -F pandoc-zotxt -F pandoc-citeproc -s -o "$t" < foo.mmd 
cat "$t" && rm "$t"
```

**Comment by retorquere** [comment]
in the case of Scrivener it should probably be:
```
#/bin/bash
t=$(tempfile) || exit
pandoc -f markdown_mmd+citations -t docx -F pandoc-zotxt -F pandoc-citeproc -s -o "$t"
cat "$t" && rm "$t"
```

As Scrivener will pipe in the markdown through stdin.

Mind that I have no idea what Scrivener does with the output -- I haven't heard back from L&L how the pipeline works in detail.

**Comment by retorquere** [comment]
(but what really should be happening is that L&L puts in place proper pandoc support of course)

**Comment by mijalce** [comment]
I tried with both scripts 
now there is no error, but the compile freezes in the middle and the output is not generated. 
I compile Multimarkdown -> Webpage (.html)
One error I noticed, might not have any influence, but it might be connected - when it asks me where to save the output it automatically assigns the .html extension. When I try to change the extension and save the output as .docx it does not allow me.

**Comment by retorquere** [comment]
As far as I can tell, only the html and LaTeX pathways allow interception the way we've documented. The other way would be to replace the binaries that Scrivener itself calls rather than pretending to be the convenience scripts, but for that we need input from L&L -- who have gone silent again.

**Comment by egh** [comment]
Is Scrivener using Multimarkdown to convert to XHTML and then post-processing with an XSLT as described here: http://fletcherpenney.net/multimarkdown/use/

Because if that is the case I don't think this approach will work. You want Scrivener to output markdown with citations that can then be processed by pandoc, not HTML with citations - that cannot currently be processed by pandoc. (It can handle HTML input, but not with citations.)

**Comment by retorquere** [comment]
They are and they aren't -- there's two ways MMD can generate XHTML, one using a one-go transformation using the mmd binary, and one that does post-processing using XSLT. If you choose post-processing, Scrivener will call a script that calls mmd to call the xslt, and what I do in the CAYW explanation is simply replace the script that calls mmd wholesale.

We will really need assistance fro L&L on this one. We're flying blind, Erik even moreso than me, trying to work around limitations that only L&L really knows. What we'd *really* need from L&L (if they're not going to do proper pandoc support) is an instruction on how we can achieve what we want given these limitations only they know in sufficient detail. What we want is simple: allow piping the generated markdown to a script and outputting in any of the supported pandoc formats.

**Comment by mijalce** [comment]
I sent an email to L&L and waiting for their response.

**Comment by retorquere** [comment]
Response from L&L on the paste issue:

I'm not set up to test the script precisely as you wrote it, but I did a dirt simple check to make sure nothing strange was happening with the integration between pipes and Cocoa process execution, and the building blocks all seem to be functioning. I created a simple .app with a Bash script that did nothing other than:

    #!/bin/bash
    echo "Test" | /usr/bin/pbcopy

This placed the word "Test" on the clipboard, and I was able to successfully do so from Scrivener's Cmd-Y hotkey. My guess: wrap your URL in quotes, that question mark might be tripping up execution.

**Comment by retorquere** [comment]
Todo: add quotes around URL in zotpick.app
Done: review of installation of pandoc-zotxt
Fixed: minimize Zotero after picker closes

**Comment by mijalce** [comment]
In the existing workflow solution, I have not identified how we can select the style (APA, Cell etc)?
Also, regarding 1.2 can we use the guidelines by pandoc-citeproc?
"Citations go inside square brackets and are separated by semicolons. Each citation must have a key,
composed of ‘@’ + the citation identifier from the database, and may optionally have a prefix, a locator,
and a suffix. The citation key must begin with a letter, digit, or _, and may contain alphanumerics, _,
and internal punctuation characters (:.#$%&-+?<>~/). Here are some examples:
Blah blah [see @doe99, pp. 33-35; also @smith04, ch. 1].
Blah blah [@doe99, pp. 33-35, 38-39 and *passim*].
Blah blah [@smith04; @doe99].
A minus sign (-) before the @ will suppress mention of the author in the citation. This can be useful
when the author is already mentioned in the text:
Smith says blah [-@smith04].
You can also write an in-text citation, as follows: 
@smith04 says blah.
@smith04 [p. 33] says blah."
(source: http://pandoc.org/README.pdf, p. 49)

**Comment by mijalce** [comment]
can I ask you when you add quotes around url in zotpick.app to use this url

http://localhost:23119/better-bibtex/cayw?keyprefix=%40&citeprefix=%5B&citepostfix=%5D&clipboard=yes

This url creates a citation (that I think) is more common in writing papers (author, date)

**Comment by mijalce** [comment]
answer from L&L
"> The optimum solution from the user point of view would be to have Scrivener call the Zotero CAYW url itself and do its own pasting -- but this can of course only be done by L&L. 
> 

This should already be possible. For instance, if you test out Bookends with Scrivener, you will see that if you hit Cmd-Y in Bookends once you have the citation, it will return focus to Scrivener and paste the text in. This is done by sending Scrivener an Apple Event, which Scrivener accepts. I believe you just need to send Scrivener the kAEMiscStandards (‘misc’) event class with the kAEPaste (‘past’) event ID.

**Comment by retorquere** [comment]
This will work (if someone finds out the requisite applescript incantation), but this is a workaround (and a hackish one at that), not a solution. This will paste the references in the first scrivener window found, whichever that may be - indeterminate if you have more than one open. The proper solution is still for scrivener to either call the picker themselves, or to add an api that allows me to do it.

**Comment by retorquere** [comment]
Done: add quotes around URL in zotpick.app
Done: review of installation of pandoc-zotxt
Done: minimize Zotero after picker closes
Todo: add AppleScript code to zotpick.sh to give a random scrivener window the focus and paste the clipboard, in lieu of proper support by Scrivener.

The applescript code will probably look something like
```
tell application "Scrivener"
	activate
	tell application "System Events"
		keystroke "v" using {command down}
	end tell
end tell
```
Not tested yet.

**Comment by retorquere** [comment]
zotpick.app has been updated BTW.

**Comment by mijalce** [comment]
I made some tests of compiling in MMD and then using the terminal to us the terminal with the command > pandoc -F pandoc-zotxt -F pandoc-citeproc -s -o file.docx file.md < and it successfully makes the transformation. 
Because Pandoc support will be enabled in Scrivener next year I would like to suggest the following solution for discussion
	- The author writes in Scrivener, adds citations through zotpick.app
	- It compiles in MultiMarkdown
	- We create GUI app (part of BetterBibTex) that can be invoked through Zotero by using a keyboard shortcut or general shortcut.  This app based on the selections will compile the pandoc command we now use in the terminal. There are some existing wrappers and interfaces that can be use it (https://github.com/jgm/pandoc/wiki/Pandoc-Extras#pandoc-wrappers-and-interfaces), but they do not include the filters of pandoc-zotxt and pandoc-citeproc
	- The author is asked to select the input file (file.md) 
	- The author is asked to select the Style (s/he can choose from the styles s/he has in Zotero)
	- The author is asked for the format of the output file (docx, odt, pdf, rtf etc). With an option to check an option for default output 
	- The author clicks on convert button
The  new file is placed in the folder where the input file is. I do not know is it possible to have an option when the output file is created the input file to be deleted?
By having the GUI app we actually (independently from scrivener) make successful integration

**Comment by mijalce** [comment]
What is interesting when I run the command we have in the script for compile MMD-HTML (pandoc -F pandoc-zotxt -F pandoc-citeproc --from markdown --to docx) in terminal it does not make the transformation. Thus there might be a thing that we need to change the command in the script.

**Comment by mijalce** [comment]
the updated zotpick.app works perfectly.
One question regarding it: 
In the zotero citation picker when I add the page or add text as suffix/ prefix that is not reflected in the citation key placed on the clipboard. I can use the syntax from pandoc to make this adjustments in the Scrivener document, but it will have more "like-word" feeling if the values I put in the picker regarding the page/ suffix/ prefix are added to the bibtex citation key (using the pandoc-citeproc syntax) and placed in the clipboard so I can add it in the document.

**Comment by retorquere** [comment]
## GUI app

I'm sorry, but the GUI app as described isn't going to come from me. This has a few reasons, but the main ones are:

* BBT aims to make Zotero a usable BibTeX reference manager. Part of this is that I facilitate integration with programs that use BibTeX bibliography and/or BibTeX keys, but BBT does not aim to become a program that uses BibTeX(/keys).
* I suck at building GUIs and I only build them when I absolutely must
* Such a GUI built into BBT would mean I'd have to invoke external executables, which automatically means BBT would have to pass the continental-drift speed Mozilla review process once extension signing becomes mandatory. Right now, BBT passes the checks for automatic validation, and I intend to do whatever it takes to keep it that way.

There is an embarrassment of riches when it comes to markdown editors that either support pandoc, or are open source or have a plugin architecture that allows adding pandoc support cleanly; a much better way to address this problem. I can yield the selection via the http endpoint.

## Selecting the citation style

I honestly don't know how to do this for pandoc.

## CAYW picker reference details

How do you call up this interface? I only see the reference picker, not any place to enter details.

**Comment by mijalce** [comment]
Yes, I completely understand you about the GUI app. It will take a lot of time. I am working to make it very clear how can it be done through terminal so that could ease the workflow for the other people that will use the integration 

Regarding the CAYW picker reference details. When you have selected the citation, and the citation is in the picker, you just press on the citation and it will show dropdown options for page, prefix, suffix and suppress authors.

**Comment by mijalce** [comment]
changing style in the workflow
When you compile the .md file through Scrivener you can use the following command to convert the file from .md to .docx by using zotxt and pandoc-citeproc and **changing the citation style**

In the Terminal you go to the folder where inputfile.md and citation-style-name.csl is (for example cd ~\Documents\Paper)

Then you put the following command
 
>pandoc inputfile.md -o outputfile.docx -F pandoc-zotxt -F pandoc-citeproc --csl=citation-style-name.csl

Important: You put the both files: inputfile.md and citation-style-name.csl, in the same folder (for example cd ~\Documents\Paper)

With this I think that we have completed the whole workflow we have set in the beginning. Now we can work on making it more nicer :)

**Comment by retorquere** [comment]
I've updated https://zotplus.github.io/better-bibtex/cayw.html; http://tempsend.com/55AA42F9D8 goes with that for now until I publish a new release. The Pandoc format is too much for simple prefixes etc, so I've just made it so `format=pandoc` or `format=mmd` does the right thing given the selection.

WRT the GUI app, it's not just that it will take a lot of time (it may or may not), it simply falls outside the scope of what BBT wants to be. This really is work that Scrivener ought to be doing themselves, and I'm quite willing to adapt BBT to facilitate integration, but it can't be the case that I'm building glue apps to make up for deficiencies in an app that is hostile to integration builders; not open source, and zero extension facilities. Even MS Word is more open than Scrivener. If I'm going to build GUI apps, I'd much sooner work on http://leoeditor.com to bring that up to par with Scrivener.

**Comment by retorquere** [comment]
1.2.20 has the new caw endpoint

**Comment by mijalce** [comment]
some update on the workflow, that make settings one time activity (even when you change styles) and simplified process how to convert.

use the following content for the new mmd-xslt (see https://zotplus.github.io/better-bibtex/cayw.html how you can do that) 

`#!/bin/sh`
`pandoc --from markdown --to html -F pandoc-zotxt -F pandoc-citeproc --csl=/Applications/citation.csl`

In order to be able to change the citations as you like I made a decision to give a generic name to the csl file (citation.csl) and to place it in a location where not much changes are done (Applications). Also it is the same path for all the users and no need for adjustments of the content. 

In order to change the citation style, you download the wanted citation style from Zotero Style Repository and when you save it, you save it in Applications with the name citation.csl. So you overwrite the previous citation and now pandoc-citeproc uses the new citation style. 

When you have done that, you run Compile Markdown -> Web Page (.html)
Save this html file where you want. 

To convert the html to docx you need to use the terminal (the existing GUI complicate the issue more). However, because very often the html is located somewhere in a folder that is in a folder that is in a folder (i.e. the folder where you have all your documents for the paper) and has empty spaces in the title it can be problematic to enter everything correctly in the terminal. Thus I propose the following procedure: 

Open Terminal and write 

Pandoc (empty space)

than go in Finder and drag your html file in the terminal. You will get something like this /Users/mijalce/Desktop/My\ Beautiful\ paper.html

than leave empty space and write -o (leave empty space)

than again drag and drop the same html file in the terminal. However now you delete .html (at the end) and write .docx and press enter. Then in the same folder you should have the My Beautiful paper.docx

The content in the terminal should look like this:
**pandoc** /Users/mijalce/Desktop/My\ Beautiful\ paper.html **-o** /Users/mijalce/Desktop/My\ Beautiful\ paper.**docx** 
(in bold is what you write)

**Comment by retorquere** [comment]
I've put up an editable version at https://github.com/ZotPlus/ZotPlus.github.io/wiki; can you update the page with your contributions? When you're done, let me know, and I can publish it to the site.

**Comment by mijalce** [comment]
Thanks. I will update it tomorrow.
One thing that I found out. With the proposed script If my scrivener file has image, I can not create one html, it creates a folder.  However I need standalone html file. To do this I need to use --standalone command. I tried several timse to make the order of the commands appropriate so I can get standalone html, but with no success. Do you know how we can do this?
Thanks

**Comment by retorquere** [comment]
I don't really know -- it shouldn't matter what order they're in, but your best bet is to ask on http://stackoverflow.com/questions/tagged/pandoc

**Comment by mijalce** [comment]
for standalone html the content of the script should be 

`#!/bin/sh'
'pandoc --from markdown --to html --standalone -F pandoc-zotxt -F pandoc-citeproc --csl=/Applications/citation.csl`

However I suggest not to use it because of the following:
* you need to put the image in scriv document like this `![This image won't be a figure](/url/of/image.png)\` or like this `![This is the caption](/url/of/image.png)`. If you make mistake in location pandoc will show error
* if the image is too big (MB) it will create problem in the conversion process
* if the image is too large (size W/H) it will take large space of your html and latter docx file. 

Thus you can use the --standalone command, but with care

**Comment by mijalce** [comment]
I updated the Wiki. Please inform me when you publish it so we can spread the word for this (in my opinion) very good integration.

**Comment by retorquere** [comment]
OK, the page is up.

**Comment by mijalce** [comment]
Information shared at 

Zotero - https://forums.zotero.org/discussion/51168/scrivener-and-zotero-integration/#Item_1

Scrivener - http://www.literatureandlatte.com/forum/viewtopic.php?f=5&t=32047&p=201800&hilit=zotero#p201800

Marked2 - http://support.markedapp.com/discussions/suggestions/44981-scrivener-zotero-markded-integration

**Comment by retorquere** [comment]
I appreciate the accolades, but I assure you Erik's work is at least as
important as what BBT provides!

**Comment by mijalce** [comment]
One question: 
is it possible to have a downloadable script (or an app that) when executed will make all the things that we propose in **Setting up pandoc** section?

**Comment by retorquere** [comment]
It is technically possible, but I don't feel comfortable writing programs that root around in directories of other applications. I'd be blind in making changes to other people's systems without any way to reproduce any errors. I'm not opposed to adding a link to such a script or app, but it's not something I feel comfortable doing myself, sorry, As the instructions are, the user is in control, and will be required to apply good judgement; a script cannot do this.

**Comment by mijalce** [comment]
you have a good point. Also, what I noticed is that on Scrivener forum the post already has 90 views and still no questions about issued how to do the setup. Thus it might be that the complete process is already explained well and not very demanding. As a result development of such a script or app is not a necessity.

**Comment by retorquere** [comment]
OK, I'm going to consider this fixed, barring any problems with the cayw endpoints; please open a new issue if problems arise with the endpoint.

**Comment by davepwsmith** [comment]
Hey, if you are interested in doing the scrivener integration with pasting happening automatically, I can confirm the following as working and stable. Can easily be packaged as an app:

````{.applescript}
do shell script "/usr/bin/curl 'http://localhost:23119/better-bibtex/cayw?format=pandoc' | /usr/bin/pbcopy"
tell application "Scrivener"
	activate
	tell application "System Events"
		keystroke "v" using {command down}
	end tell
end tell
````

**Comment by davepwsmith** [comment]
I have pasting into scrivener working and tested if you're interested. Applescript which runs bash and bash script which runs osascript below. The bash script running embedded applescript is faster even though it is mostly applescript because... Apple.  

Bash Script
````{.bash}
#!/bin/bash

/usr/bin/curl "http://localhost:23119/better-bibtex/cayw?format=pandoc" | /usr/bin/pbcopy
/usr/bin/osascript -e 'tell application "Scrivener"
	activate
	repeat until application "Scrivener" is frontmost
	end repeat
	tell application "System Events"
		keystroke "v" using command down
	end tell
end tell'
````
Applescript
````{.applescript}
do shell script "/usr/bin/curl 'http://localhost:23119/better-bibtex/cayw?format=pandoc' | /usr/bin/pbcopy"
tell application "Scrivener"
	activate
	repeat until application "Scrivener" is frontmost
	end repeat
	tell application "System Events"
		keystroke "v" using command down
	end tell
end tell
````

**Comment by retorquere** [comment]
I've updated https://github.com/ZotPlus/ZotPlus.github.io/blob/master/better-bibtex/cayw.md; should appear on https://zotplus.github.io/better-bibtex/cayw.html soon (github pages have been slow to update lately).

**Comment by mijalce** [comment]
@davepwsmith thanks for doing this. I used the Bash script and it works perfectly. Even with multiple Scrivener files opened it pastes in the one from which you called the picker. 
@retorquere , can I ask you on the CAYW page to bring back the downloadable app only with the changed content from the Bash script. I think that in this way people that do not know how to make-script-change-to-app will be able to download the app and add it in Scrivener. 
Thanks!

**Comment by davepwsmith** [comment]
Sorry, should probably also note that presumably GUI scripting must be enabled for this to work (although I haven't verified or tested this!).

App here:
https://www.dropbox.com/sh/htybak3pb3uhfp0/AAAvozL5etMu7V9WSH-gx9Csa?dl=1

**Comment by davepwsmith** [comment]
"What really should be happening is that L&L takes the 30 minutes it would take to add this to Scrivener and make this conversation irrelevant."

I wouldn't hold your breath. Scripting with external applications has been a long-requested feature and absolutely no interest has been shown.

**Comment by retorquere** [comment]
Not holding my breath, but also not taking a potentially risky responsibility because they have no interest in their users' needs.

**Comment by davepwsmith** [comment]
OK, sorry, back on topic:

Bug with the search box when called with the script:

If you do the following, then it is impossible to get rid of the box without quitting zotero:

1. Open search box with URL call piped to pbcopy.
2. Press [Esc]
3. Attempt to enter reference followed by [Enter] fails. 

It's also problematic that you can't dismiss the box using [Esc].

Presume that this has to do with the pipe in Bash -- You can escape out if the box is from a url called from the browser.

**Comment by retorquere** [comment]
Can you open a new issue for this?

**Comment by mijalce** [comment]
I think that we have two very good solutions for the picker. Both have their weak and strong side. I think that the win-win situation is when we offer both of them to potential users, with appropriate explanation for the possible issues with the auto-paster app. When the bug is fixed in the auto-paster I can hosted on my dropbox or use Dave's dropbox and link it to CAYW.

**Comment by retorquere** [comment]
Tests on #334 are running.

**Comment by retorquere** [comment]
new version with fix is out
