### ISSUE TITLE
Ignore HTML tags when generating citation key

### ISSUE THREAD

**Issue by adunning** [ZotPlus/zotero-better-bibtex#264]
Using `[auth:lower]:[year:nopunct][Title:lower:nopunct:skipwords:select,1,1]` as my key format (to match Zotxt), BBT is including the contents of HTML tags in the title. For instance, the title `<span class="nocase">Historia Selebiensis monasterii</span>. The history of the Monastery of Selby` results in the key `burton:2013span` instead of `burton:2013historia`; `<i><span class="nocase">De laude scriptorum manualium</span></i> and <i><span class="nocase">De laude editorum</span></i>` gives `ziolkowski:2011ispan` rather than `ziolkowski:2011laude`.

**Comment by retorquere** [comment]
Could you get me a reference using zotplus report?

**Comment by retorquere** [comment]
BTW, zotxt can be configured to use the BBT keys, whatever they are.

**Comment by adunning** [comment]
I must confess that I'm not clear on what format you want the report in; here is the full JSON for an example reference, but let me know if something else would be more ideal:

```json
[
    {
        "URL": "https://journals.lib.unb.ca/index.php/flor/article/view/14263",
        "accessed": {
            "date-parts": [
                [
                    "2015",
                    7,
                    7
                ]
            ]
        },
        "author": [
            {
                "family": "Hannam",
                "given": "Walter A."
            }
        ],
        "container-title": "Florilegium",
        "id": "hannam:1998ispan",
        "issued": {
            "date-parts": [
                [
                    "1998"
                ]
            ]
        },
        "page": "145\u2013165",
        "source": "journals.lib.unb.ca",
        "title": "<i><span class=\"nocase\">Nodo unitatis et caritatis</span></i>: The Structure and Argument of Augustine's <i><span class=\"nocase\">De doctrina Christiana</span></i>",
        "type": "article-journal",
        "volume": "15"
    }
]
```

(While zotxt can use BBT keys, I want to minimize the degree to which I need to change my existing papers to run them through BBT, and its format strikes me as more sensible than the default one provided by Zotero.)

**Comment by retorquere** [comment]
Sorry, I should have been clearer on that: this works, but the easiest for
me would be if you right-click an entry and select "report ZotPlus error".
That gets me the error log (which I don't need in this case) but also the
reference in a format that I can just drop into my test suite.

**Comment by retorquere** [comment]
Ack, never mind, the above exported from the clipboard cleanly. Looking into it.

**Comment by retorquere** [comment]
(BTW, if you want to make sure the BBT keys are set to the ZoTXT keys for those papers, that's possible)

**Comment by adunning** [comment]
Ah, I see: I sent report ID DABXAU2N if you want a few more examples.

**Comment by adunning** [comment]
I can confirm that this is fixed in your most recent test build; thank you!

To clarify, it's not desirable to take Zotxt keys directly if what one wants is a stable identifier; it makes more sense to set BBT to generate keys as close to it as possible and use its own mechanism. Zotxt has a very intuitive key generation format, but it also has a few shortcomings that BBT overcomes:

- Zotxt cannot handle date ranges, using the workaround recommended on the Zotero forums of using an underscore rather than a dash or hyphen, e.g. `1889_1954`. It generates a key such as `wordsworth:1889nouum`, but cannot then find the item unless one adds specifies this key manually. BBT instead gives  `wordsworth:1889_1954nouum`, which is a touch ugly (and I wonder what is going to happen with these once Zotero finally fixes this), but the important thing is that it works.
- Because it does not survey the entire library, it cannot disambiguate citation keys where the author, year, and first word of the title matches (rare, but I have at least a dozen cases of this in a library of three thousand items).
- It always uses the first creator listed rather than prioritizing author/editor/translator etc. as BBT does, which gives inconsistent results.

**Comment by retorquere** [comment]
Is this a common thing? I could just replace the underscore with dashes for export, and handle this case in the key generation -- should be easy enough.

**Comment by adunning** [comment]
Sorry about the slow response! Yes, this workaround has been recommended on the Zotero forum for years: see <https://forums.zotero.org/discussion/40880/export-date-range-yyyymmddyyyymmdd-as-literal-date/> on the current state of affairs. Pandoc-citeproc will parse a date in the format YYYY_YYYY as a range. Replacing the underscore with a dash would probably be ideal, but only if it's straightforward. It's not something that's causing any problems right now: I am only thinking in terms of future compatibility with citekeys generated by a version of Zotero with proper support for date ranges.

**Comment by retorquere** [comment]
I'll add this to the work I'm doing for #352

**Comment by retorquere** [comment]
Sorry, you mean you want YYYY_YYYY changed to YYYY-YYYY rather than just YYYY?

Could you open a new issue for this? Closed issues drop off my rader fairly soon -- I really had to dig around to find this after I saw the mail flash by
