### ISSUE TITLE
Diacritics stripped from keys regardless of `ascii` or `fold` filters

### ISSUE THREAD

**Issue by adunning** [ZotPlus/zotero-better-bibtex#266]
This may be intentional behaviour, but just to check: the [citation keys documentation](https://zotplus.github.io/better-bibtex/citation-keys.html) mentions `ascii` and `fold` filters, but it appears (unless I am misunderstanding their purpose) that these apply regardless of whether they are included in the citation key format, since diacritics are stripped in every case (and non-ASCII characters are omitted entirely).

**Comment by retorquere** [comment]
They apply to all the built-in functions automatically - they're really
only useful if you use the uppercased fields, which return the Zotero
values as-is.

**Comment by adunning** [comment]
Good to know. I feel quite dense, but I can't find anything about uppercased fields in the online documentation (and I don't get anything by using `Auth` or `AUTH` instead of `auth`). If one actually wants non-ASCII characters to remain in the citation key, is there a way to do that?

**Comment by adunning** [comment]
Looking over this again, I realize that you were simply referring to the list of capitalized fields. Still, this doesn't appear to be passing on the raw values; with `[auth:lower:nopunct][year:nopunct][Title:lower:nopunct:skipwords:select,1,1]`, an item named 'Le cœur voyant' generates the citation key `rischpler2004cur`. Enabling `fold` on the title doesn't change anything. (Assuming that it's automatically enabled, could a pattern be added to replace 'æ' with 'ae' and 'œ' with 'oe'?)

**Comment by retorquere** [comment]
You're totally right; I forgot that at the end of the formatting process, `removediacritics` is always applied. I have tests running now on a change that only auto-applies `fold` to the JabRef-ish functions, not to property access.

I use `removeDiacritics` from Zotero itself -- I guess they're folding guided by how the character sounds rather than how it reads.

**Comment by retorquere** [comment]
(BTW, for an all-ascii freak like me, the first thing that hit me was "*why?!*").

**Comment by adunning** [comment]
Thank you! It turns out that œ was simply missing from the mapping: I've submitted a fix in zotero/zotero#807.

As to the why, if one has a string in non-Latin characters (I have some titles in Greek. Russian, and Japanese), this is completely stripped out, which can leave one with nothing at all to go on.

**Comment by retorquere** [comment]
The "why?!" was more about why one would want non-ascii in the final cite
key. Different strokes for different folks I suppose. I'm trying to get
there, but filtering for non-ascii turns out to be rather tricky.

**Comment by retorquere** [comment]
I think I've finally got it. Could you try out http://tempsend.com/DBC6034F2E ?

**Comment by retorquere** [comment]
There's more at play with the folder -- javascript strings are fundamentally flawed, making a simple walk of the string for diacritics sometimes miss combined characters. I've simply incorporated https://github.com/mplatt/fold-to-ascii into BBT -- it works around the insanity that is the javascript UTF-16 string, and it's slightly faster to boot.

**Comment by retorquere** [comment]
can you try whether http://tempsend.com/52D26DAD31 meets your expectations?

**Comment by retorquere** [comment]
(fold-to-ascii also has the `oe` ligature, so that's now also fixed)

**Comment by adunning** [comment]
This definitely improves the Latin transliteration, and Unicode strings appear in the citation key when `fold` is not enabled on the capitalized fields. The [citation keys page](https://zotplus.github.io/better-bibtex/citation-keys.html) also implies that `fold` is required to remove diacritics from an author's name, but this obviously isn't the case, as you indicated above. This is still a problem if one is citing a work entirely in non-Latin characters, since the characters are stripped out completely (leaving no author in the citation key) rather than transliterated. See Report ID 93CBV98G for an example of a book in Russian.

That said, I think you're correct that most people would want to keep the citation key as ASCII. To keep the behaviour of BBT stable, and because it seems unlikely that anyone will want the author in ASCII, but the title in Unicode, I might suggest adding another set of radio buttons in the preferences below the field for the citation key format that toggles the application of `fold` and `ascii` when generating the entire key. It could be phrased something like this, with ASCII remaining the default:

- Citation key encoding
    - ASCII (replaces diacritics)
    - Unicode

Another option might be to add a `unicode` filter that could be applied to any field for passing on the Zotero string without modification (again, rather than removing `fold` and `ascii` as defaults).

**Comment by retorquere** [comment]
There is zero hope for transliteration of languages like Russian and Japanese. I have opted for the following in http://tempsend.com/C4F514B60A:

* the jabref-ish functions work as the always have. Too much would break out there.
* fold works as it used to, but
* I have added pseudo properties for all the `auth*`, `edtr*`, and `editors` functions (so `Authors`, `Editors`, etc) which return their unadulterated counterparts.

**Comment by adunning** [comment]
`[Authors:lower:nopunct]` or `[Editors:lower:nopunct]` gives an entirely blank citation key with that build.

(Perhaps you've already done this, but ideally, the replacement function would do the same thing as `auth`, only with Unicode, and continuing to return editors, translators, etc. if there is no author.)

**Comment by retorquere** [comment]
I've also added the `alphanum` function (which I needed to strip out non-alphanum chars)

**Comment by retorquere** [comment]
The build is green for the changes on #266 and #268; that version is at http://tempsend.com/91A89F8A8. I'm ready to release this if this is in line with your expectations.

**Comment by adunning** [comment]
That link doesn't work; is there a missing character?

**Comment by retorquere** [comment]
perhaps, new build at http://tempsend.com/2EA07327B5

**Comment by adunning** [comment]
This build has the same behaviour as the last one; is `[Authors:lower:nopunct]` the intended syntax for the citation key format?

**Comment by retorquere** [comment]
Yes, that ought to work. Do you have a testcase for me?

**Comment by adunning** [comment]
Certainly: report ID TG2URPVI.

**Comment by retorquere** [comment]
Something went wrong; that shows and error in your log I fixed a few commits ago. Could you try again with http://tempsend.com/2C8C804DE2 (and I truly do appreciate your patience, but I'd rather not cut a new release until I have these niggles worked out)

**Comment by adunning** [comment]
Not at all! Yes, I'm now getting a citation key, with the appropriate accents. The only error I see is that it's taking everyone that fits the category, rather than limiting it to one name; report ID IBX477D3.

(By the way, does this normalize combining accents? I remember this being something that Zotxt stumbled over until a few releases ago, since I believe that Zotero sometimes takes care of this internally, but not in all situations.)

**Comment by retorquere** [comment]
The "taking everyone..." is specced behavior for the `authors` function (see http://jabref.sourceforge.net/help/LabelPatterns.php); you might want `Auth` rather than `Authors`.

I think fold-to-ascii does indeed normalize combining accents. It's no shame that anyone should stumble here -- javascript goes out of its way to make working with non-ascii strings as miserable an experience as possible.

Could you see whether https://github.com/ZotPlus/zotero-better-bibtex/commit/27bf08e05e340e99e5c7d58ffb91b0e5d1b41fd8 desribes what you had intended? I just checked that in as a test case.

**Comment by retorquere** [comment]
build is green again, so if this is functionally what you need, it looks like we're good to go.

**Comment by adunning** [comment]
Oh, I see, I had understood earlier that `Authors` was the equivalent of `auth`; that was silly of me.

Yes, I think that test should cover it. Thank you again for all of this!

**Comment by retorquere** [comment]
My pleasure!

**Comment by retorquere** [comment]
A release build is running. Nothing has changed, so it should just be green, but I've set it up so that the only way to release a new version is after a marked test build goes green. It prevents me from deploying untested code. Should be 5 minutes or so.

**Comment by adunning** [comment]
Got it; everything is still working. This is fantastic.

**Comment by retorquere** [comment]
I have had to add a new preference to augment this behaviour, defaulting it to fold again -- keys in the wild were getting lost (#286) which is not OK.

**Comment by retorquere** [comment]
This is not simply the old behaviour BTW; the old behaviour would always fold after each generation step; this new-old behaviour does it only at the end, if the option is on.

**Comment by retorquere** [comment]
So simply setting it to off should get you the behaviour we had when I implemented this. A bit of a hack, but I can't just confront people with this, sorry.

**Comment by adunning** [comment]
I wondered whether something like that might happen; this is probably a simpler interface than the 'Citation key encoding' radio buttons I suggested earlier.
