### ISSUE TITLE
Fail to install on zotero 4.0.27.6 standalone version

### ISSUE THREAD

**Issue by zhuzhongshu** [ZotPlus/zotero-better-bibtex#269]
I find I can't install zotero-better-bibtex (from V1.0.18-V1.1.0) after I update my zotero standalone version to 4.0.27.6.  May be it conflicts with some other plugins because I successfull installed it after I clear the .zotero folder.

**Comment by retorquere** [comment]
In what sense can you not install? Do you get an error during installation (if so, which?), does it install but complain (if so, what is its complaint?), or does it install cleanly but doesn't work?

**Comment by zhuzhongshu** [comment]
I get an error during installation: it tells me that the plugin doesn't compatible with this verison of zotero.  
My solution is just clear my personal configuration, and reinstall all the plugins I need. Now it works well and no conflcts with other plugins found.

**Comment by retorquere** [comment]
If it says that, the message is likely

> Better BibTeX has been disabled because it found Zotero ZOTERO_VERSION, but requires 4.0.27 or later.

I'd need to know what ZOTERO_VERSION is in your case. I can reproduce the error here, and the problem is tied to the exact value of ZOTERO_VERSION.

**Comment by retorquere** [comment]
I meant to say I cannot reproduce the problem here

**Comment by zhuzhongshu** [comment]
I am afraid that the Better BibTeX is not installed at all, rather than installed but disabled due to the incompatibility. Beacuse after I restart the Zotero, the Better BibTeX doesn't in the plugins list. Besides, my error message is in Chinese, it reads like "the plugin XXX can't be installed because  it doesn't compatible with this verison of zotero."

**Comment by zhuzhongshu** [comment]
Now I cannot reproduce the problem either  because I delete my earlier configuration :)

**Comment by retorquere** [comment]
Ah, right. That's a message from Zotero, not from BBT; BBT demands Zotero Standalone 4.0.X to be installed, and Zotero will complain during installation if there's a version mismatch. But 4.0.27.6 is 4.0.X (otherwise you would not have been able to install after deleting your profile either), so I don't think this is a problem BBT can fix.

If it reoccurs, please do reopen the issue or file a new one.
