### ISSUE TITLE
URL escaping in BibLaTeX (not BibTeX!)

### ISSUE THREAD

**Issue by sixtyfive** [ZotPlus/zotero-better-bibtex#271]
It seems that Better BibTeX escapes the ampersand (&) character in URLs when exporting to BibLaTeX. We believe this to be wrong, as BibLaTeX requires it to be unescaped in order to retain the URL so that it is clickable in the document (i.e. still points to the correct resource). Any sort of fix would be appreciated :-)

Edit: in order to comply with https://zotplus.github.io/support.html, I'll add that we're on Better BibTeX 1.1.1. The report ID is EPAJW5P3.

**Comment by retorquere** [comment]
Would you happen to know of a reference of what and what not to do in verbatim mode? I currently escape the characters `\%&{}]` in verbatim.

**Comment by sixtyfive** [comment]
I interpret verbatim to mean "nothing needs to be escaped", but perhaps the definition could even be "nothing _should_ be escaped" (?) The only real problem I can think of is unbalanced braces. Googling for that brings up http://tex.stackexchange.com/questions/177201/bibtex-biblatex-verbatim-fields-and-special-characters where people seem to be of the same opinion...

**Comment by retorquere** [comment]
Could you give http://tempsend.com/7F221325CF a spin?

**Comment by sixtyfive** [comment]
Confused. Is this the one I already said "thank you" for?

**Comment by retorquere** [comment]
No, but I took it as implied.

**Comment by retorquere** [comment]
(oh and this is lso already part of 1.2.1)

**Comment by sixtyfive** [comment]
Yes, am on 1.2.1 already now and it continues to work (who would have thought!)

**Comment by retorquere** [comment]
It happens :)

**Comment by sixtyfive** [comment]
Oh. So that completed the confusion now - shouldn't be doing so many things at once. Apparently I had still been mistaking this issue here for the other one over there. So tested this as well now and can confirm that it, too, works. Thanks again then!

**Comment by retorquere** [comment]
You're welcome.
