### ISSUE TITLE
FR: "prefixcolon" filter

### ISSUE THREAD

**Issue by sixtyfive** [ZotPlus/zotero-better-bibtex#272]
Quoting my own comment in #268:

Seeing as quite a few people prefer to use a colon, how about adding a new filter called "prefixcolon". That way, no escaping facility would be required at all and the colon would still not appear in the case of an empty field... just an idea.

**Comment by retorquere** [comment]
I've rather just allowed escaping of parameters with a backslash. Could you give http://tempsend.com/E773422870 a spin?

**Comment by sixtyfive** [comment]
What can I say, works like a charm! Thank you! Why is the fixed build versioned as 1.1.x by the way? It seems you just released 1.2.1 a couple of hours ago. Is it tuned to my Zotero version or something?

**Comment by retorquere** [comment]
Nope, that's just how fast things move with BBT :) the 1.2.1 version includes this.

**Comment by retorquere** [comment]
iow 1.1.2 was still the current version 19 hours ago

**Comment by sixtyfive** [comment]
Yes, you seem to have had a quick turnaround these last 24 hours. My flatmate has a serious problem atm btw which might be related to him having installed 1.2.1 (similar to #175, i.e. German error message about not being able to export, empty .bib file, "BetterBibTeX is undefined" in the log, but doesn't seem to be _the same_) ... waiting for him to reinstall and send another log over to make a new ticket.

**Comment by retorquere** [comment]
Why reinstall?

**Comment by sixtyfive** [comment]
That's what non-programmers do as a first reflex when something doesn't work...

**Comment by retorquere** [comment]
Shouldn't be necessary.

**Comment by retorquere** [comment]
Just open a new issue; if "report zotplus error" still works, that will probably give me what I need, if not, I'll get you a walkthrough to get the logs.

**Comment by retorquere** [comment]
(also, if somethings breaks, you have my permission to assume it's something I did rather than you)

**Comment by sixtyfive** [comment]
Lol, understood & thanks :)
