### ISSUE TITLE
Keys are not unique

### ISSUE THREAD

**Issue by gracile-fr** [ZotPlus/zotero-better-bibtex#274]
BBT 1.1.1, Standalone 4.0.27.6

*BBT Prefs:*
Citation key format: [auth:lower][Title:fold:nopunct:skipwords:select,1,1:lower:alphanum:prefix,_][year:prefix,_][0]
Auto-pin citation keys: No
On conflict, non-pinned key should be : kept

Steps to reproduce:
1.Create an item (book), fill the author, title and year fields. A key is created: *author_title_year*
2.Create a second item, fill it with the same info (same first words for title). Key: *author_title_year-1*
3.Create a third item, idem. Key: *author_title_year-1*

The second and third items have the same key. Generating / clearing BibTeX key doesn't change anything.

Am I doing something wrong ? (#199 regression ?)

**Comment by retorquere** [comment]
Not doing anything wrong, reproducible. It must be a different bug from #199 -- the test for that issue still passes.

**Comment by retorquere** [comment]
Got it -- tests are running

**Comment by retorquere** [comment]
It was specific to the numeric postfixes -- which I changed the default to a while ago

**Comment by retorquere** [comment]
New release is out -- thanks for reporting this!

**Comment by gracile-fr** [comment]
Great! Thanks!

**Comment by gracile-fr** [comment]
I assume I should Generate then Clear the key of items which have a duplicate key ?

**Comment by retorquere** [comment]
What platform are you on?

**Comment by retorquere** [comment]
Never mind -- yes, that procedure will work, but if you don't mind that *all* soft keys are regenerated, you can check "re-scan citekeys" in the debug pane of BBT, and restart Firefox.

**Comment by retorquere** [comment]
I've just scheduled a release build 1.2.0 -- any minor or major version change will cause (a.o.) a key rescan, and I really do think it is necessary to do this for everyone. So if you can spare some 6 minutes and update, that's all there should be to it.

**Comment by gracile-fr** [comment]
a.o.? (I'm on Windows 7)

**Comment by retorquere** [comment]
among others, sorry. I monor or major version bump causes a ket rescan, but also rebuilds the database tables (keeping the data of course) and drops the cache (so first time export after the upgrade will be slower than with caches primed). I was going to tell you how to cause a key rescan manually, and what tools to use vary by platform, but then I figured I already had the tools built-in.
