### ISSUE TITLE
BBT fails to start when invalid cite key pattern is configured

### ISSUE THREAD

**Issue by sixtyfive** [ZotPlus/zotero-better-bibtex#276]
Here's the new issue just mentioned. Everything was fine yesterday, had stopped working this morning:

![screenshot 2015-07-28 14 17 32-1](https://cloud.githubusercontent.com/assets/192860/8933132/7a7d99a2-3541-11e5-9de0-ed50e8157e45.png)

The full log is:

    [JavaScript Error: "SyntaxError: Expected "\\" or [^,\\\]:] but ":" found."]
    [JavaScript Error: "Zotero.BetterBibTeX is undefined" {file: "C:\Users\Jonas\AppData\Roaming\Mozilla\Firefox\Profiles\rccfm421.default\zotero\translators\Better BibLaTeX.js" line: 3408}]

    version => 4.0.27.6, platform => Win32, oscpu => Windows NT 6.1; WOW64, locale => en-US, appName => Zotero, appVersion => 4.0.27.6, extensions => Zotero LibreOffice Integration (3.5.9.SA.4.0.27.6, extension), Zotero Word for Windows Integration (3.1.20.SA.4.0.27.6, extension), Zotero Better Bib(La)Tex (1.2.1, extension), Adobe Acrobat (15.8.20082.15957, plugin), Silverlight Plug-In (5.1.40620.0, plugin),  (3.0.72.0, plugin),  (3.0.72.0, plugin), Shockwave Flash (18.0.0.209, plugin)

**Comment by retorquere** [comment]
That's a strange combo of errors. In any case, can you  still access the BBT preferences? If so, can you enable "extended logging" in the BBT debug prefs, restart Zotero, and try to get a new debug log?

**Comment by retorquere** [comment]
Oh, and does this happen on the highlighted entry? Could you give it a shot to right-click that and select "report zotplus error" and paste the debug ID here should that work?

**Comment by sixtyfive** [comment]
Yes, working on it.

**Comment by sixtyfive** [comment]
I'm not at home right now atm but he is, so this all goes through email...

**Comment by retorquere** [comment]
*grin* he isn't hip with github :)

**Comment by retorquere** [comment]
You can both join me on https://hello.firefox.com/dg4GyP6EPfw should you prefer that.

**Comment by retorquere** [comment]
Sorry, that should be http://www.disposablechat.com/chat/%23276?password=

**Comment by sixtyfive** [comment]
Naw, def. not. That chat doesn't seem to be working

**Comment by sixtyfive** [comment]
Okay, so most strangely, the report window remains empty, blank. Same thing when he turns on extended logging.

![screenshot 2015-07-28 16 04 54](https://cloud.githubusercontent.com/assets/192860/8933556/d0de9830-3543-11e5-9c5a-ba66f9cf98cd.png)

**Comment by retorquere** [comment]
I could be. He doen't have github but he's down with IRC? I'm on webchat.freenode.net, #bbt-276. The log being empty there is collateral damage; BBT failed to start up fully. You can call up the debug log from preferences->advanced->view output

**Comment by retorquere** [comment]
I'll bet dollars to dimes that disposable chat doesn't like me sticking hashes in the URL

**Comment by sixtyfive** [comment]
Here's the debug log: http://pastebin.com/jgdCcqTL
My friend's "fluppi" on FreeNode (showed him how to get on there with a web client).

**Comment by retorquere** [comment]
You wanted a more obvious warning, you got it.

**Comment by sixtyfive** [comment]
Hahahah, YAY for dark orange! :+1:
