### ISSUE TITLE
referencetype= does not work

### ISSUE THREAD

**Issue by sixtyfive** [ZotPlus/zotero-better-bibtex#278]
I have an Encyclopedia in Zotero, which is of Item Type "Book". Its "extra" field currently reads:

    bibtex:ea bibtex[referencetype=mvreference]

Despite this, the exported .bib file contains:

    @collection{ea, ...

Adding other Biblatex keys in the "extra" field seems to work just fine. Latest Zotero with BBT 1.2.1.

**Comment by retorquere** [comment]
Could you get me a report by right-clicking on that reference and selecting "send zotplus error"? That will get me a testcase so I can prevent it from happening again after I fix it.

**Comment by sixtyfive** [comment]
Of course! XZ96IPMQ.

**Comment by sixtyfive** [comment]
Cheers! :)
