### ISSUE TITLE
Fields to omit from export : collaborators ?

### ISSUE THREAD

**Issue by gracile-fr** [ZotPlus/zotero-better-bibtex#279]
Is it possible to avoid the exportation of certain creators types, especially in my case the "collaborator" field?
Collaborator is a special creator type in Zotero ; it has no CSL-mapping and then can't appear in a bibliography. But the field is active with BibLaTeX and that can create undesired output. It might be easier to omit its exportation rather than modifying a TeX style.

The BBT documentation says "add a comma-separated list of BibTeX fields you do not want to see in your export." but I don't think this applies to creators.

Thank you.

**Comment by retorquere** [comment]
You mean you don't want any of the collaborators to show up in the `authors` field? Something else? Can you get me a sample reference by right-clicking and selecting "Report ZotPlus Error" and pasting the ID here?

**Comment by gracile-fr** [comment]
Exactly.
I can't send a report, I got this error:
<code>Réponse invalide du dépôt: 403: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Invalid according to Policy: Policy expired.</Message><RequestId>7C6FDF4B450492A5</RequestId><HostId>fr0YS4gE693si30qcwlzB6qbpiivIQb7+u/21H+2kuNe/+T6O+8LdWWcec6u67Bfi3Cb5p5MTPM=</HostId></Error></code>
FWIW, "Réponse invalide du dépôt" means "Invalid response from the repository".

**Comment by retorquere** [comment]
Yeah, I just saw that. If you upgrade to 1.2.3, it should fix it -- no idea why amazon suddenly thinks the policy expired, but I have a new one in place in 1.2.3.

**Comment by gracile-fr** [comment]
Report ID: BVD6ZEHV
(sorry, I was not using the latest BBT version, but 1.2.2. With 1.2.3, sending error reports is ok)

**Comment by retorquere** [comment]
1.2.3 was released just 10 minutes ago, specifically for the reporting issue.

**Comment by retorquere** [comment]
In this particular case, adding `editora` and `editoratype` to skipfields ought to do the job, no? That is where Zotero contributers show up.

**Comment by gracile-fr** [comment]
Perfectly, indeed. Problem (question) solved. Thanks…

I assume my question becomes: are <code>editora </code>and <code>editoratype</code> "reserved" by zotero for contributors? 

And, a BibLaTeX question (I can't find the answer): can you have, in a .bib file, something inconsistent like an item which has an <code>editoratype</code>=founder and another item which has an <code>editoratype</code>=redactor ? I think such inconsistency is possible, but I'm not sure to understand (and to be clear: I don't need that, I just want to understand how BibLaTeX handles editortype.)

**Comment by retorquere** [comment]
Not by zotero as such, it's just the mapping that the BBT BibLaTeX happens to use:

all creators of type ... => biblatex field:
'author', 'interviewer', 'director', 'programmer', 'artist', 'podcaster', 'presenter' => 'author'
'bookAuthor' => 'bookauthor'
'commenter' => 'commentator'
'editor' => 'editor'
'inventor' => 'holder'
'translator' => 'translator'
'seriesEditor' => 'editorb'
anything else => 'editora'

where editoratype will be 'collaborator' if anything showed up in editora, and editorbtype will be 'redactor' is anything showed up in editorb. I just grabbed this conversion table from the Zotero translators -- I have no particular reason for this mapping other than that if it made sense for Zotero then, it probably does here too.

Looking through the biblatex manual, it seems to indicate that these type fields are per-reference, so no consistency is expected between references.

**Comment by gracile-fr** [comment]
<blockquote>the mapping that the BBT BibLaTeX happens to use</blockquote> <a href="https://github.com/ZotPlus/zotero-better-bibtex/blob/master/resource/translators/Better%20BibLaTeX.coffee#L425">There</a>, right?
Thanks for the clarification, closing this issue !

**Comment by retorquere** [comment]
Right, that's where it happens.
