### ISSUE TITLE
Field missing from exported bib file

### ISSUE THREAD

**Issue by janfreyberg** [ZotPlus/zotero-better-bibtex#280]
Hi,

I commented on an old (unresolved) issue but thought I would open a new one since I also saw you commenting elsewhere that closed issues fall off your radar.

When I export to BibTex or BibLatex using the Better Bibtex translator, the database has missing fields. In particular, it seems that "year" and "journal title" are problematic, although sometimes Journal Title is exported properly.

I've made a test citation to demonstrate it. This is the citation, just dragged and dropped from Zotero:
Test, Cite. “Test Citation.” Journal of Testing, January 1, 1960.

This is the BibTex Source that I get when I click Export -> Better BibTeX:
@Article{test_test_1960,
Title = {Test {Citation}},
Author = {Test, {Cite}},
Date = {1960-01-01},
Journaltitle = {Journal of {Testing}},

Abstract = {Test test test},
Shortjournal = {{J} {Test}},
Timestamp = {2015-07-30 14:48:29}
}

Am I missing something? Trying to go through the "Report zotplus error" dialogue didn't work, but I can try again if needed.

Thanks for the help!

PS: I should note that this is a problem because JabRef (and Latex as far as I know) consider Year a required field, and my referencing doesn't work without this.

**Comment by retorquere** [comment]
The reporting did seem broken, I've released 1.2.3 that fixes that; can you upgrade and try "Report Zotplus error" again on the relevant reference?

The "year" field is indeed mandatory, and BBT does export it. If the above is literally the output you get, this cannot be from BBT; BBT exports lowercase field names.

**Comment by retorquere** [comment]
Oh and it's absolutely OK to either open a new issue, or to re-open an old one, but closed issues do indeed drop off my radar.

**Comment by janfreyberg** [comment]
Thanks for the quick response. I think the fields were capitalized by JabRef, if I open the file in a text editor they're not capitalized.

I did an error report, number XH4S7UVV.

However, I should note that the problem this time around didn't seem to be the "year" field, but the "journaltitle" field. Here's the output:

@article{test_test_1960,
  title = {Test {Citation}},
  abstract = {Test test test},
  timestamp = {2015-07-30 14:48:29},
  journal = {Journal of {Testing}},
  author = {Test, {Cite}},
  month = jan,
  year = {1960}
}

It seems the journaltitle field is now the journal field? That seems OK to me, since I could just find & replace journal with journaltitle, but is there a way to fix this?

Thanks a lot.

**Comment by janfreyberg** [comment]
OK, I now did it on the same reference using Better BibLaTeX. I've submitted another error for this, reference: 6RTJ7PCH

This is the output I got this time:

@article{test_test_1960,
  title = {Test {Citation}},
  abstract = {Test test test},
  timestamp = {2015-07-30 14:48:29},
  journaltitle = {Journal of {Testing}},
  shortjournal = {{J} {Test}},
  author = {Test, {Cite}},
  date = {1960-01-01}
}

It has everything except the year... Maybe I should just merge the too :)

**Comment by retorquere** [comment]
As far as I can tell from "Tame the BeaST" and "BIBTEXing", BibTeX doesn't know `journaltitle`, only `journal`. 

When it comes to BibLaTeX, the manual is a little ambiguous, but 2.1 seems to imply that *either* `date` or `year` must be set. It seems a little counterintuitive to set them both, I must say, and biblatex used to complain when both were present. I think JabRef is a BibTeX manager, not a BibLaTeX manager, so it may be complaining about that -- if you could verify that biblatex processes an entry with both year and date set without complaints, I could perhaps just add the field.

Which bibliography processor do you use? bibtex or biblatex? I don't think biblatex has promised to keep its references bibtex-compatible, so tread cautiously. Any particular reason to run things through JabRef before compiling your document?

**Comment by retorquere** [comment]
BibLaTeX used to at least report stuff like:

```
Package biblatex Warning: BibTeX reported the following issues
(biblatex) with 'ENTRY':
(biblatex) - Can't use 'date' + 'month'
(biblatex) - Can't use 'date' + 'year'.
```

**Comment by janfreyberg** [comment]
Ahh OK.

I may have been confusing BibTeX and BibLaTeX then. I was having trouble getting things to work with LyX, used JabRef to check the .bib files, and just assumed the fields JabRef was complaining about were the reason my references weren't compiling.

All works now, I found the problem elsewhere :)

**Comment by retorquere** [comment]
Great. Don't hesitate to open a new issue if something else crops up.

**Comment by retorquere** [comment]
JabRef also appears to have a biblatex mode from what I can gather from their forums.
