### ISSUE TITLE
Zotero's bookSection is always converted to @inbook, never @incollection

### ISSUE THREAD

**Issue by gracile-fr** [ZotPlus/zotero-better-bibtex#282]
If I understand correctly the code, a <code>bookSection</code> can be either a <code>@inbook</code> or <code>@incollection</code>. See <a href="https://github.com/ZotPlus/zotero-better-bibtex/blob/master/resource/translators/Better%20BibLaTeX.coffee#L25">BetterBibLaTeX.coffee#L25</a>.

And if there's a <code>bookAuthor</code> defined, a <code>bookSection</code> should be converted into <code>@inbook</code>, see <a href="https://github.com/ZotPlus/zotero-better-bibtex/blob/master/resource/translators/Better%20BibLaTeX.coffee#L294">Better BibLaTeX.coffee#L294</a>.

But in practice, <code>bookSection</code> items are always converted by BBT into <code>@inbook</code>.

Zotero's biblatex translator is stricter, and perhaps more consistent: <a href="https://github.com/zotero/translators/blob/master/BibLaTeX.js#L111">it converts</a> <code>bookSection</code> into <code>@incollection</code> <a href="https://github.com/zotero/translators/blob/master/BibLaTeX.js#L465">except if there's a</a> <code>bookAuthor</code> (it is, then, converted into <code>@inbook</code>).

I have absolutely no opinion on the pros and cons, but is there a reason for BBT behaviour ?

**Comment by retorquere** [comment]
I'd consider this a bug. Can you right-click on a reference that exhibits
the faulty behavior on export, select "report ZotPlus error", and paste the
resulting ID here?

**Comment by gracile-fr** [comment]
Report ID: 6U2W9FXI

**Comment by retorquere** [comment]
I don't fully understand the problem then; when I export this item using standard BibTeX or Better BibTeX, both yield @incollection. Looking at the reference, it has an "author" set, not a "Book author", and if I change that creator to "Book Author", both export it as @inbook. Are you sure you selected the right reference? 6U2W9FXI had one reference from Charles Eisenmann with title "Problèmes d’organisation de l’Administration [1966-1967]".

**Comment by retorquere** [comment]
Oh hold on, the default behavior is reversed between the two? I'll look into that.

**Comment by retorquere** [comment]
Got it. Tests are running.

**Comment by gracile-fr** [comment]
Thanks!

[For future reference, if that's not clear from above:
bookSection with a bookAuthor -> @inbook
bookSection without any bookAuthor -> @incollection (i.e. that's the default behaviour)]
