### ISSUE TITLE
Auto-Export with "keep updated" not updated after new mapping 

### ISSUE THREAD

**Issue by gracile-fr** [ZotPlus/zotero-better-bibtex#285]
After #282 has been solved, my automatic exported .bib files have not been updated to reflect the new mapping. My auto-export is "on change" so it's normal, but:

1- I tried to update an item to force an export (because my auto-export setting is "on change"). The item was a journalArticle – article, and then not concerned by the new mapping. It was auto-exported, but my bookSection items were not updated.

2- I then created a new bookSection item, it was auto-exported and all my bookSection were updated (most of them became <code>@incollection</code>). Good.

Is it the desired behaviour?

**Comment by retorquere** [comment]
Sorry, forgot to force a cache drop.

**Comment by retorquere** [comment]
1.2.7 is out.

**Comment by gracile-fr** [comment]
Fixed, thanks.
