### ISSUE TITLE
after latest update all my citation keys cannot be looked up

### ISSUE THREAD

**Issue by sunew** [ZotPlus/zotero-better-bibtex#286]
for instance: Citation 'KlimatilpasningKokkedal2012Projektkonkurrence' on page 7 undefined

Note: it is all citations that are undefined. 

Could it be related to non-ascii characters in the keys? 

I see, amongst others, the following change in my bib file:

-@article{Andersson2011PaSporet,
+@article{Andersson2011PåSporet,

Is there a way to revert back to the old functionality?

**Comment by sunew** [comment]
Okay, found out about the new possiblities for controlling keys here: https://zotplus.github.io/better-bibtex/citation-keys.html
I specify "fold" to avoid danish chars. ([auth:nopunct][year][Title:skipwords:fold:nopunct:select,1,2:capitalize])

**Comment by retorquere** [comment]
Wait, what is your pattern format? An upgrade shouldn't suddenly be changing existing keys, that's serious.

**Comment by retorquere** [comment]
Tests are running -- in 1.2.8, the previous behaviour will be back again. This was a serious bug -- thanks for reporting it!

**Comment by retorquere** [comment]
(BTW those possibilities were always there, it's just that in previous versions, "fold" was always imposed. This wasn't supposed to happen, but then breaking existing behaviour is very bad, so I've made the implicit fold the default, but it can be disabled)

**Comment by sunew** [comment]
Cool! thanks for fixing it!
Glad I could help.

On Sunday, August 2, 2015, retorquere <notifications@github.com> wrote:

> (BTW those possibilities were always there, it's just that in previous
> versions, "fold" was always imposed. This wasn't supposed to happen, but
> then breaking existing behaviour is very bad, so I've made the implicit
> fold the default, but it can be disabled)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZotPlus/zotero-better-bibtex/issues/286#issuecomment-126966451>
> .
>


-- 
Sune Brøndum Wøller
+45 24256610
skype: sune.woeller

**Comment by retorquere** [comment]
And apologies for the disruption. I've added a testcase to cover this situation so it can't happen again -- a failing test case will prevent release of a new version.

**Comment by sunew** [comment]
non-human agency - very unpredictable sometimes:)

On 2 August 2015 at 20:25, retorquere <notifications@github.com> wrote:

> And apologies for the disruption. I've added a testcase to cover this
> situation so it can't happen again -- a failing test case will prevent
> release of a new version.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZotPlus/zotero-better-bibtex/issues/286#issuecomment-127052150>
> .
>



-- 
Sune Brøndum Wøller
+45 24256610
skype: sune.woeller

**Comment by retorquere** [comment]
Fortunately for me, this particular agency is quite reliably stubborn - I
can request a release, and it will refuse if any one of my tests fail.
Wouldn't be the first time the test suite saved my bacon.

Thanks for understanding. Causing disruption in what I know are busy lives
is not something I like to have my signature on - I try to avoid it where I
can (the disruption that is, not the signature).
