### ISSUE TITLE
is there a way to avoid automatic updates?

### ISSUE THREAD

**Issue by sunew** [ZotPlus/zotero-better-bibtex#287]

**Comment by sunew** [comment]
okay, found the setting in zotero: tools->addons

**Comment by retorquere** [comment]
Any particular reason why you want to avoid updates?

**Comment by sunew** [comment]
Because I have a deadline, and want to keep everything stable:) No time for
technocal issues.

On Sunday, August 2, 2015, retorquere <notifications@github.com> wrote:

> Any particular reason why you want to avoid updates?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZotPlus/zotero-better-bibtex/issues/287#issuecomment-126965609>
> .
>


-- 
Sune Brøndum Wøller
+45 24256610
skype: sune.woeller

**Comment by retorquere** [comment]
Fair enough - I hadn't seen the other problem you posted before I responded
to this one.
