### ISSUE TITLE
LaTeXTools support

### ISSUE THREAD

**Issue by retorquere** [ZotPlus/zotero-better-bibtex#289]
https://github.com/SublimeText/LaTeXTools/issues/513#issuecomment-111191643

**Comment by retorquere** [comment]
Superseded by the CAYW picker

**Comment by adibender** [comment]
So how exactly do I use zotero with LaTeXTools? I Couldn't find any documentation.

**Comment by retorquere** [comment]
I don't know - editors can call the cayw url (although it's not yet functional in the zotero 5 port) but after that it's out of my hands.
