### ISSUE TITLE
Exclude parts of date (day or month) from export for certain fields

### ISSUE THREAD

**Issue by gracile-fr** [ZotPlus/zotero-better-bibtex#293]
Is it possible to exclude parts of a date from the (auto-)export?
E.g. in zotero, if the date field is "30/08/2015", could I just import "2015"?
Zotero parsing is <a href="https://forums.zotero.org/discussion/6111/better-date-field/">not perfect</a> and with date ranges or <a href="https://github.com/zotero/zotero/issues/64">localized months in Standalone</a>, export can be problematic.

Ideally, that could be done on a per-(zotero)item type basis, should I open another specific issue (i.e. exclude fields to export per item type) ?

I think it would be enough for me if I can just export the year, instead of the full date, for <code>journalArticle</code>.

**Comment by retorquere** [comment]
The simple solution is just to add it as custom metadata in the extra field using bibtex[date=...], which will override whatever BBT would otherwise generate. 

Well that or fix the dates per item of course :)

**Comment by gracile-fr** [comment]
Sure, but Zotero lacks a(n easy to use) batch editing function so that's somewhat cumbersome for around 800 items.

I've gone that route, following <a href="https://www.zotero.org/support/dev/client_coding/javascript_api#batch_editing">the examples here</a>, but I'm wondering whether it's a problem or not if there are more than one "<code>bibtex[field=…]</code>" in the Extra field ? Because my code just *add* to the Extra field another <code>bibtex[date=…]</code>, it doesn't check for the presence of another <code>bibtex[…]</code>.

```javascript
var typeName = 'journalArticle';
var originFieldName = 'date';
var destFieldName = 'extra';
 
var fieldID = Zotero.ItemFields.getID(originFieldName); 
var s = new Zotero.Search;      
s.addCondition('itemType', 'is', typeName);

//Exclude group libraries
let groups = Zotero.Groups.getAll();
for (let i=0; i<groups.length; i++) {
	s.addCondition('libraryID', 'isNot', groups[i].libraryID);}

var ids = s.search();                   
if (ids) {
	for each(var id in ids) {

		var item = Zotero.Items.get(id);
		//alert(item.getField(originFieldName));
		var dateStr = item.getField(originFieldName,true, true);
		var yearStr = dateStr.substr(0,4);
		
		//record changes in the console log
		console.log('Date field: ' + dateStr + '. Year alone: ' + yearStr);
		
		var destFieldContent = item.getField(destFieldName);
		item.setField(destFieldName, destFieldContent + ' bibtex[date=' + yearStr + ']');
		item.save();
	}
		alert(ids.length + ' items updated');
}
else {
	alert('No items found');
}
```

**Comment by retorquere** [comment]
I'll have to check when I get home what the behavior is when multiple are
present, but the correct behavior is that it should pick them up in order.
But if you're going this route, wouldn't it be easier to just correct the
dates? I've been thinking about ways to omit date parts, but none of them
are very appealing, specifically when it comes to marking

**Comment by gracile-fr** [comment]
<blockquote>wouldn't it be easier to just correct the dates? </blockquote> What do you mean ? The dates are correct, they're just not parsed correctly or fully.

And there's actually another reason which can appear to be idiosyncratic: some articles/journals I'm citing must be referred to with day-month-year, others with month-year, but the great majority needs only to be referred by their year. I've used the distinction in Zotero/CSL between <code>journalArticle</code>, <code>newspaperArticle </code>and <code>magazineArticle </code>to reflect that… so I can keep full dates without displaying them in bibliographies. But for BibLaTeX, they're all of the <code>@article </code>type…

Anyway, my code must take into account the presence of bibtex[…] strings, otherwise my extra fields will be cluttered by multiple multiple bibtex[date=…] string.

**Comment by retorquere** [comment]
Oh, I thought that Zotero would always parse YYYY-MM-DD the same way, but that thread is not entirely clear on that one either. Why on earth anyone would want YYYY-DD-MM is beyond me, but never can tell with USAnians. 

You could always put the desired date in CSL var format if you know the var name -- I'd have to adjust the parser but that would be easy, and it'd (probably?) have the side benefit of also generating same-formatted dates other than in the bibtex export. Not *entirely* sure on that one, though.

As for parsing, https://github.com/ZotPlus/zotero-better-bibtex/blob/master/resource/translators/translator.coffee#L60 shows how I parse out bibtex[...]; that format is the easiest to parse from the 3 (because it is dumb, restrictive and unforgiving), so you could in your code just extract & remove (if applicable), generate a wholly new one, and tack it onto the end:

```
var assignment, data, i, key, len, m, ref;

var extra = item.getField('extra') || '';
var fields = {};

if (m = /(biblatexdata|bibtex|biblatex)\[([^\]]+)\]/.exec(extra)) {
  extra = extra.replace(m[0], '').trim();
  ref = m[2].split(';');
  for (i = 0, len = ref.length; i < len; i++) {
    assignment = ref[i];
    if (data = assignment.match(/^([^=]+)=\s*(.*)/)) {
      fields[data[1]] = data[2];
    }
  }
}

/* add or overwrite your own here */
/* fields.date = ... */

extra = extra.trim() + "\nbibtex[";
for (key in fields) {
  if (!fields.hasOwnProperty(key)) continue;
  extra += key + "=" + fields[key];
}
extra += "]";
item.setField('extra', extra);
item.save();
```

**Comment by retorquere** [comment]
I'm also still open to generating only date partials, but I haven't thought of a decent way to indicate what. If Javascript had strftime it'd be easier, but it doesn't.

**Comment by gracile-fr** [comment]
<blockquote>Why on earth anyone would want YYYY-DD-MM </blockquote> Not sure to understand, the thread I linked to might be partially outdated (there's also <a href="https://forums.zotero.org/discussion/14572/1/a-ui-proposal-for-a-better-date-field/">this thread…</a>).

Anyway, YYYY-MM-DD is the internal parsing format, not for humans. Zotero is parsing and localizing dates correctly in most cases [apart the standalone issue with localized written months (e.g. french "août" is not recognized whereas "august" is, as "08"), date ranges (main concern), uncertain dates, seasons…].
For date ranges, <a href="https://forums.zotero.org/discussion/6111/better-date-field/?Focus=75492#Comment_75492">this workaround</a> does the trick with CSL, maybe it could be added (I think BibLaTeX uses a slash for date ranges) to the BBT exporter?

<blockquote>You could always put the desired date in CSL var format if you know the var name […] the side benefit of also generating same-formatted dates other than in the bibtex export. Not entirely sure on that one, though</blockquote> Var names and mappings <a href="http://aurimasv.github.io/z2csl/typeMap.xml">are here</a> (I'm sure you know that). But that's not working with all variables :-)

Thanks for your code (I don't understand everything), I'll adjust mine.

**Comment by retorquere** [comment]
> Anyway, YYYY-MM-DD is the internal parsing format, not for humans.

*grin* that would make me a pretty fancy AI - it's how I usually put down
dates :) Wouldn't be the first time I'd be mistaken for a robot. Anyhow,
*if* Zotero consistently parses this format unambiguously, why not change
the dates for the problematic references to this format? Seems easier than
futzing about with the extra field.

> For date ranges, this workaround does the trick with CSL, maybe it could
be added (I think BibLaTeX uses a slash for date ranges) to the BBT
exporter?

You mean an option per reference, not global, to just put whatever is in
the date field into the BibTeX date field? But then how would that be
different from just adding it to the extra field directly? Or do you mean
if I see a slash? That would interfere with people using d/m/y.

> Var names and mappings are here (I'm sure you know that). But that's not
working with all variables :-)

I add them as needed. The mapping isn't always obvious between csl and
BibTeX, so I wait until I have a use-case.

> Thanks for your code (I don't understand everything), I'll adjust mine.

I'll gladly explain, but roughly it looks whether it can find a chunk of
text, removes it if so, parses the assignments contained in it, then
reconstructs it and adds it to the end.

**Comment by gracile-fr** [comment]
I realize we're not talking about the same things. But that's my fault as I mixed different issues.

1- (tl ; dr : not an issue)
<blockquote>why not change the dates for the problematic references to this format? Seems easier than futzing about with the extra field.</blockquote>The only problematic references are those which are not correctly parsed by Zotero Standalone because I've written them in French (e.g. "<i>juil</i>let" is not recognized as "<i>jul</i>y", but "<i>jan</i>vier" is ok for "<i>jan</i>uary", because ZStandalone relies on the three or four first letters, which are in some cases the same in French and English). Zotero for Firefox handles that correctly. Anyway, it's not very problematic because there are only 60-70 references. I can change that manually.

2- (tl; dr : my original request, will be solved thanks to your code)
My bigger issue is with full dates and articles. I'd like to limit the export to year for <code>journalArticle </code>because I only need year to be cited in citations or bibliography. But for magazineArticle and newspaperArticle, which are converted to <code>@article</code> too, I'm ok with the full export of the date field.<code></code>
As it seems too complex to: (1st feature request) limit exportation of date-parts + (2nd feature request) for some defined zotero item types, I'd use the Extra field as you advise me to do. That's indeed simpler, even if slightly hackish.

3- (tl; dr : not a priority)
As for date ranges, it was not my original intention to talk about them, this was just an example of non-parsed dates (or, more exactly partially parsed) in Zotero. My suggestion was to take into account, in the BBT export, the workaround used by some Zotero users to display date ranges.
Indeed to fool the parser and force CSL-proc to write down the date field unparsed, one can just insert some characters, e.g. an underscore "1992_1994" (but not "1992-1994" or "1992/1994" which both are parsed as "1992"), and then make a find & replace in the final document.
My suggestion would be to recognize that temporarily, and converts "1992_1994" to a proper biblatex date range, which uses a slash: "1992/1994" (biblatex manual 2.3.8). But  let's leave this aside (at least for now) !

4- (tl; dr : could you add that?)
<blockquote>The mapping isn't always obvious between csl and BibTeX, so I wait until I have a use-case.</blockquote>I was not asking you to add all the CSL variables, just giving the information of CSL-zotero mappings ;-))
At the moment, <code>{:original-date: 1234}</code> in the <code>extra</code> field is recognized and converted to <code>origdate</code>. Great. Could you add these three (cf. <a href="https://forums.zotero.org/discussion/3673/original-date-of-publication/?Focus=86228#Comment_86228">this post</a>):
*<code>original-publisher</code> to <code>origpublisher</code>
*<code>original-publisher-place</code> to <code>origlocation</code>
*<code>original-title</code> to <code>origtitle</code>


Sorry for this ridiculously long comment / thread…

**Comment by retorquere** [comment]
OK, tests are running for 4; I'd love to have a testcase for those, just to be sure. Can you open new issues for 3, and for 2 if you think of a decent workflow from the user POV?

**Comment by retorquere** [comment]
I've added a synthetic testcase, but a realistic one is always preferred.

**Comment by retorquere** [comment]
If you manage to find a good CSL->BibTeX mapping anywhere, I'll add more, but I haven't found mch solid info.

**Comment by retorquere** [comment]
I've added my versions of the batch-editing code (coffeescript original + javascript translation of it) at https://gist.github.com/anonymous/4cb9bc231a8df62d3f13

**Comment by gracile-fr** [comment]
2-
Thanks for your code. I've made <a href="https://gist.github.com/gracile-fr/715834878654dbd5133b">mine finally</a>, but using your regex. The drawback of your code is that it removes non bibtex (bbt) data in the extra field. Correct me if I'm wrong.
4-
Tests: https://gist.github.com/gracile-fr/03d83bd43a792b35dc94 and https://gist.github.com/gracile-fr/63752d48fb99452d8dba
You need to add the jabref things at the end, I think…

Thank you!

**Comment by retorquere** [comment]
2 - nope, my code removes it, augments the data in it (overwriting the `date` field in the `bibtext[...]` block if it was there, otherwise adding it), and then adds everything again. Order of the fields may be different, as javascript doesn't guarantee object traversal order, but no data is lost in the process.
4 - thanks for the tescase, tests are running

**Comment by retorquere** [comment]
WRT my sample in the gist: Note that you'd *either* want the code starting at https://gist.github.com/anonymous/4cb9bc231a8df62d3f13#file-tt-coffee-L17 *or* the code starting at https://gist.github.com/anonymous/4cb9bc231a8df62d3f13#file-tt-coffee-L28, depending on whether you want `bibtex[....]` or csl-style vars... but now that I think of it, there is currently no CSL mapping to the BibTeX `date` field, so you want the `bibtex[...]` variant. I remove the whole `bibtex[...]` block, parse it, modify the parsed data, then reconstitute the `bibtex[...]` block and add it to the end

**Comment by retorquere** [comment]
I stripped out the unnecessary bits at https://gist.github.com/anonymous/4803048ee16d5d63f0f1
