### ISSUE TITLE
Spaces not stripped from citation keys

### ISSUE THREAD

**Issue by Chris-2u** [ZotPlus/zotero-better-bibtex#294]
Hi. First of all thanks a ton for the wonderful BBT plugin. After an automatic update to latest Zotero 4.0.28 and possibly an update of BBT to 1.2.13 (I'm not 100% sure whether it was updated in parallel), my citation keys all contain a space that was not there before. I use
[auth:fold:lower]\_[Title:nopunct:skipwords:fold:select,1,3:lower]\_[year]
as citekey format, and it used to work as expected. Now, after the update(s), all keys are of the form
author_word1word2 word3_year (note the space between word2 and word3). My library is completely messed up by this.

My report code, if useful, is: JF3BH2PT

Thanks in advance for having a look at it!
Christian

**Comment by retorquere** [comment]
I am on the road right now so I can't check, but can you right-click such a
reference and submit a new report? I'll check as soon as I get home.

**Comment by retorquere** [comment]
As a temporary measure, you can add ":condense" after the "lower"

**Comment by retorquere** [comment]
Found it. I've added a test case to prevent this from happening again. 1.2.14 is out.

**Comment by Chris-2u** [comment]
Awesome support, thx!
