### ISSUE TITLE
Numbers confuse capital-preservation

### ISSUE THREAD

**Issue by QuLogic** [ZotPlus/zotero-better-bibtex#295]
I have a title entry that mixes numbers and capital letters as `S40RTS`. My 'Preserve capitalization' setting is 'All words with capitals'. However, the export (to BiBTeX) produces `{S}40RTS`, which naturally does not preserve capitals once it goes through BiBTeX.

**Comment by retorquere** [comment]
I don't have access to a computer right now, but does LaTeX render this to
S40rts then? Easy enough to change the translator to capture the whole
term, and I will once I get home, but just curious.

**Comment by retorquere** [comment]
If I compile https://gist.github.com/retorquere/0b00fb8268ec3f8f7527, I get

*Patent Landscape analysis: sample from S40RTS.* url:http://www.patanalyse.com/sample-analysis.html(visited on 10/18/2014).

which is what I had expected. Do you get different output? Do you have an minimal working example for me?

**Comment by QuLogic** [comment]
It does seem to occur when running with bibtex: https://gist.github.com/QuLogic/74029d736ff70168edd8

**Comment by retorquere** [comment]
So it does. Tests are running on a fix.

**Comment by retorquere** [comment]
1.2.16 is out

**Comment by QuLogic** [comment]
Thanks! Working well so far.
