### ISSUE TITLE
Escape chars in field are unnecessarily added by BBT

### ISSUE THREAD

**Issue by gracile-fr** [ZotPlus/zotero-better-bibtex#296]
In Zotero <code>extra</code> field, I have <code>bibtex[crossref=doe_cours_1952]</code>, it is exported by BBT as <code>crossref = {doe\\_cours\\_1952}</code>. How can I avoid the added backslashes?

[edit: in the original version of this post, the backlashes didn't appear, because they were not escaped…!]

**Comment by retorquere** [comment]
Hmm, this is a tricky one. Not all fields added this way are verbatim fields -- I'm going to have to look if I can find a good overview of fields that should go out verbatim. I'll look in the BibLaTeX manual as soon as I have a chance.

**Comment by gracile-fr** [comment]
BibLaTeX manual:<blockquote>Verbatim fields are processed in verbatim mode and may contain special characters. Typical examples of verbatim fields are file and doi.</blockquote> BibLaTeX manual list also <code>eprint</code> and <code>pdf</code> ("An alias for <code>file</code>, provided for JabRef compatibility.")

And in the Custom Fields section 2.2.4, adds:<blockquote>verb[a–c] field (literal)
Similar to the custom fields above except that these are verbatim fields. Not used by
the standard bibliography styles.</blockquote>
 
 ~
As for <code>crossref</code>, it's not a verbatim field. It is defined as <blockquote>crossref field (entry key) This field holds an entry key for the cross-referencing feature.</blockquote>
I think that field which are of this type (entry key), should be exported *by BBT*, verbatim. <code>xdata</code> and <code>xref</code> are filled with entry keys too.

**Comment by retorquere** [comment]
OK, tests are running on a change that should take care of this. Could you do me a favor and right-click the entry you have with this and select "report zotplus error", and report the ID here? It will give me a ready-to-use testcase for this so I can add it to the test suite.

**Comment by retorquere** [comment]
I have a working build at http://tempsend.com/80AEB1A95F that shows no regressions and *should* work but I'd really prefer to have a test case in place.
