### ISSUE TITLE
Unchecking 'Force citation key to ASCII' replaces contents of citation key format

### ISSUE THREAD

**Issue by adunning** [ZotPlus/zotero-better-bibtex#297]
When unchecking the 'Force citation key to ASCII' option in the preferences, the contents of the 'Citation key format' field is replaced with the text 'false', erasing the key format; checking this again results in 'true'.

**Comment by retorquere** [comment]
You have no idea how happy I am that you caught this one.

**Comment by retorquere** [comment]
I have added https://github.com/ZotPlus/zotero-better-bibtex/commit/9b16437be33ffb92e2d8ca327e731c6cff768394 for those unfortunate enough to have been hit by it and not able to recover. Damn.

**Comment by adunning** [comment]
I doubt whether it has caused many problems; thanks for taking care of it so quickly!

**Comment by retorquere** [comment]
It never should have made it out - I am on the road, so I'm a little strapped for time and Internet access, plus I do sometimes forget people actually use the gui bits :/
