### ISSUE TITLE
Underscores break capital-preservation

### ISSUE THREAD

**Issue by QuLogic** [ZotPlus/zotero-better-bibtex#300]
Sorry, found another one: `SPECFEM3D_GLOBE` gets transformed to `{SPECFEM3D}\_GLOBE` on export, which like #295 will not get the capitals preserved through a BiBTeX run.

**Comment by retorquere** [comment]
I'm sort of tempted to just enclose any space or punctuation separated
string of characters that include at least one uppercase letter, but I'm
trying to think through potential adverse effects of that. Any ideas?

**Comment by retorquere** [comment]
One immediate issue I think is that dashes count as punctuation, so dash-separated words would not be captured as one but as multiple groups. The underscore probably also counts as punctuation.

**Comment by retorquere** [comment]
Note to self: \\b doesn't even work universally, might need sth like (?=[^\p{Letter}]...)

**Comment by retorquere** [comment]
1.2.21 has the fix for this
