### ISSUE TITLE
Add more simple HTML/Zotero markup: small-caps

### ISSUE THREAD

**Issue by gracile-fr** [ZotPlus/zotero-better-bibtex#301]
<a href="https://zotplus.github.io/better-bibtex/unicode.html">Docs</a>: "Zotero supports some simple HTML markup in your references that Bib(La)TeX won’t understand; BBT will converts from/to HTML/LaTeX; Currently supports \<i\>⇔\emph & \textit, \<b\>⇔\textbf, \<sup\>⇔_{…} and \<sub\>⇔^{…}; more can be added on request"

Could you add support of smallcaps, or do you think it's a bad idea? According to <a href="https://www.zotero.org/support/kb/rich_text_bibliography">Zotero docs</a>, it has this syntax: <code>\<span style="font-variant:small-caps;"\> \</span\></code>.
The lightweight, and more user-friendly <code>\<sc\>syntax\</sc\></code> is also recognized, even if not proper HTML (and https://forums.zotero.org/discussion/23785/parse-markup-tags-in-titles/ advises against it, for this reason… but it's so easier to read in any zotero field than the long *span style* syntax…)

**Comment by retorquere** [comment]
The span style is already recognized; I'll add the sc ones as soon as I get to a keyboard. Why they'd recommend against it I wouldn't know - nobody sane would hand-type the span format.

**Comment by retorquere** [comment]
Sorry, it recognised a different variant. I've added both this span style and `sc`

**Comment by gracile-fr** [comment]
For sure! The reason is that it's not standard html, but it's recognized by csl-processor (not by zotero itself actually), even if undocumented (and, maybe, I'm the only one to use it!)
The long-term project is to add some buttons (and kb shortcuts) which would allow this kind of formatting in zotero without having to type anything,

**Comment by retorquere** [comment]
What Zotero accepts is already not valid HTML; you can have bare angle brackets in titles for example, and it doesn't recognise most of what actually is valid HTML (such as `em`). To argue for some kind of purity seems a little silly.

**Comment by gracile-fr** [comment]
Thanks!

**Comment by retorquere** [comment]
This seemed like a simple change, so I haven't added a test case, but if you submit a sample, I'll add it.

**Comment by gracile-fr** [comment]
Give me ten minutes.

**Comment by gracile-fr** [comment]
https://gist.github.com/gracile-fr/7f4c590067d08f784bc7
https://gist.github.com/gracile-fr/ec485982a7694b8cf2ab

(italics, small-caps, superscript ; I don't have real subscript examples, and I hardly imagine a real bold example)

**Comment by retorquere** [comment]
Sweet, pass.
