### ISSUE TITLE
Clear a field / export as empty

### ISSUE THREAD

**Issue by gracile-fr** [ZotPlus/zotero-better-bibtex#303]
The <a href="https://github.com/zotero/translators/blob/e40e922bbb01bc213f7c52d9a4dacdd5c99a15f6/BibLaTeX.js#L505">BibLaTeX translator converts</a> <code>journalArticle</code>'s <code>issue</code> field from Zotero into BibLaTex (blt) <code>number</code>, except when zotero issue field isn't numeric. In this case, it is converted into BibLaTeX <code>issue</code>.

Z ––––––––––––––>–––––––––––––BLT

 _____-----is numeric------->-----number
issue |
‾ ‾ ‾ ‾ ‾ ---not numeric ------>------ issue

I can understand why (cf. BibLaTeX manual definitions of the <code>issue</code> and <code>number</code> fields), even if I find this behaviour too aggressive and would prefer to override it.

To force the exportation of my zotero <code>issue </code>field into blt <code>number</code>, I could add in the <code>extra </code>field bibtex[number=…]. However, if that overrides blt <code>number</code> field (perfect), that does not prevent the exportation of zotero <code>issue</code> field into blt <code>issue</code> field. (I don't want to remove the data in zotero issue field because that would break my usage of CSL styles)

Solution: I thought I could add to the extra field something like bibtex[issue=] but that does not seem to work, i.e. to create an empty blt issue field. Would it be possible to add such a syntax in order to "empty" a blt field? (<code>\AtEveryCitekey{\clearfield{issue}}</code> doesn't work for the bibliography)

Thank you very much !

**Comment by retorquere** [comment]
Could I bother you for a test case?

**Comment by retorquere** [comment]
The current implementation just removes the field if the override is empty.

**Comment by gracile-fr** [comment]
Yes, of course, thanks again!
