### ISSUE TITLE
 editable citation keys

### ISSUE THREAD

**Issue by naught101** [ZotPlus/zotero-better-bibtex#304]
The new citation keys are nice - much better than using "bibtex: blah" in the extra field. I notice all of my old extra field citation keys got imported too, which is nice. But now it seems that I can't edit the citation key. Is there a good reason for that? It'd be nice to have keys that were a bit more meaningful (the first 4 words aren't always that descriptive). Is there a way I can edit the citation keys of items? 

Originally posted this on the zotero forums: https://forums.zotero.org/discussion/51071/editable-citation-keys/

**Comment by retorquere** [comment]
I can't currently open pages on forums.zotero.org, but with "edit the citation key", do you mean the citation key displayed in the reference details pane? If so, then unfortunately, no. BBT knows of two kinds of keys, "soft" keys which are generated from details of the reference and which will change as those details do, and "pinned" keys which don't. The pinned keys are stored in the "extra" field, Zotero doesn't offer any other way. So I am afraid the answer to your questions is "no"; the generated keys aren't editable, and the pinned keys are only editable through the "extra" field. A future version of Zotero is expected to have fields available for extensions to use, but that is still a way off.

**Comment by retorquere** [comment]
You can change the pattern according to which they're generated btw - it's
in the preferences.

**Comment by naught101** [comment]
Ah, ok, I guess I can just continue using the extra field for now. Thanks!
