### ISSUE TITLE
Export fails -- key + library ID fails to yield reference in 4.0.28

### ISSUE THREAD

**Issue by douxfly** [ZotPlus/zotero-better-bibtex#306]
Since a few days, I cannot export my zotero library with betterbiblatex any longer. 
The export fails with "Une erreur s'est produite lors de la tentative d'exportation du fichier sélectionné" (an error occured while trying to export the selected file). 

The automatic error report fails with "Policy expired" - I include what I believe to be the relevant lines from the debug log below. 
Version info: 
Firefox 40.0 
Better Bibtex 1.2.20
OS: MacOS 10.10.3. 

Please tell me if/how I can provide more information. 

Excerpt from the debug log: 

(5)(+0000001): [better-bibtex] cache.fetch miss for {"itemID":927,"exportCharset… (225 chars)

(5)(+0000000): SELECT ROWID FROM items WHERE libraryID IS NULL AND key=?

(5)(+0000001): Binding parameter 1 of type string: "AKFEHE3Q"

(3)(+0000000): No arguments provided to Items.get()

(1)(+0000000): Error: undefined 'undefined' is not an integer-string
    ===== Stack Trace =====
    _Class.prototype.integer@chrome://zotero-better-bibtex/content/keymanager.js… (85 chars)
    _Class.prototype.get@chrome://zotero-better-bibtex/content/keymanager.js:558… (83 chars)
    Zotero.Translate.SandboxManager.prototype.importObject/attachTo[localKey]<@c… (148 chars)
    @chrome://zotero/content/xpcom/translation/translate_firefox.js:433:66
    Translator.nextItem@/Users/mag/Library/Application Support/Firefox/Profiles/… (142 chars)
    doExport@/Users/mag/Library/Application Support/Firefox/Profiles/m8kxmn90.de… (131 chars)
    Zotero.Translate.Base.prototype._translateTranslatorLoaded@chrome://zotero/c… (124 chars)
    Zotero.Translate.Base.prototype.translate/<@chrome://zotero/content/xpcom/tr… (110 chars)
    Zotero.Translate.Base.prototype._loadTranslator@chrome://zotero/content/xpco… (114 chars)
    Zotero.Translate.Base.prototype.translate@chrome://zotero/content/xpcom/tran… (107 chars)
    Zotero.Translate.Export.prototype.translate@chrome://zotero/content/xpcom/tr… (109 chars)
    Zotero.BetterBibTeX.init/Zotero.Translate.Export.prototype.translate@chrome:… (140 chars)
    Zotero_File_Exporter.prototype.save@chrome://zotero/content/fileInterface.js… (85 chars)
    exportFile@chrome://zotero/content/fileInterface.js:141:3
    oncommand@chrome://zotero/content/tab.xul:1:1
    =======================

(2)(+0000000): Translate: Translation using Better BibLaTeX failed: 
string => Error: undefined 'undefined' is not an integer-string
stack => _Class.prototype.integer@chrome://zotero-better-bibtex/content/keymanag… (90 chars)
_Class.prototype.get@chrome://zotero-better-bibtex/content/keymanager.js:558:15
Zotero.Translate.SandboxManager.prototype.importObject/attachTo[localKey]<@chrom… (144 chars)
@chrome://zotero/content/xpcom/translation/translate_firefox.js:433:66
Translator.nextItem@/Users/mag/Library/Application Support/Firefox/Profiles/m8kx… (138 chars)
doExport@/Users/mag/Library/Application Support/Firefox/Profiles/m8kxmn90.defaul… (127 chars)
Zotero.Translate.Base.prototype._translateTranslatorLoaded@chrome://zotero/conte… (120 chars)
Zotero.Translate.Base.prototype.translate/<@chrome://zotero/content/xpcom/transl… (106 chars)
Zotero.Translate.Base.prototype._loadTranslator@chrome://zotero/content/xpcom/tr… (110 chars)
Zotero.Translate.Base.prototype.translate@chrome://zotero/content/xpcom/translat… (103 chars)
Zotero.Translate.Export.prototype.translate@chrome://zotero/content/xpcom/transl… (105 chars)
Zotero.BetterBibTeX.init/Zotero.Translate.Export.prototype.translate@chrome://zo… (136 chars)
Zotero_File_Exporter.prototype.save@chrome://zotero/content/fileInterface.js:96:… (81 chars)
exportFile@chrome://zotero/content/fileInterface.js:141:3
oncommand@chrome://zotero/content/tab.xul:1:1

**Comment by retorquere** [comment]
Can you select "Report ZotPlus error" from the gear menu after a failed export and paste the debug ID here?

**Comment by retorquere** [comment]
Sorry, I see you're getting an error doing that -- can you call up 'zotero://debug' in a Firefox tab and paste the results in a gist?

**Comment by retorquere** [comment]
Do you know with which reference it happens?

**Comment by retorquere** [comment]
I've put up a debug build at http://tempsend.com/44057110CB -- if you could generate a new debug log with that after an export (whether it succeeds or not doesn't matter) and post the ID here I'll have more info.

**Comment by retorquere** [comment]
Could you perhaps also check if your computer clock is set correctly? I've heard that clock drift might cause the "policy expired" error.

**Comment by douxfly** [comment]
Here is the debug log with the debug build (if I managed to install it correctly)

https://gist.github.com/7fa02ab9094794e69700.git

I am not sure how to find the "guilty" reference (I always export the whole library). 

My clock seems to be set correctly. 

(and thank you for the incredible responsiveness)

**Comment by douxfly** [comment]
The "export zotero errors" works again!  The report ID is : 6TVWI86G

**Comment by retorquere** [comment]
Could you try again with http://tempsend.com/532132B495? I know the export will fail, but the debug log should tell me why

**Comment by retorquere** [comment]
Could you also try entering "zotero://select/any/927" in the Firefox address bar? It will be hard to notice, but it ought to select the problematic reference.

**Comment by retorquere** [comment]
(in the event the export should not fail, I would still very much like to have the debug ID)

**Comment by douxfly** [comment]
This time the export worked! The .bib file seems to be fine. 

The debug ID is:
EFFWJ9R2

**Comment by douxfly** [comment]
The "select/any/927" indeed selects an entry. 
I entered it very recently via the "save in zotero" button on the webpage:
http://www.cairn.info/resume.php?ID_ARTICLE=EG_382_0139

Hope this help! And thank you very much...

**Comment by retorquere** [comment]
I think I have a solution (tests are running), but I'm a little puzzled about the cause. Could you right-click that reference in your library and select "send zotplus error" from that menu?

**Comment by retorquere** [comment]
tests are green, and with your confirmation I know I've fixed your problem, so I've scheduled the release of 1.2.23 -- shouldn't be long, but I'd still love to get that reference as per the previous comment.

Apologies for the disruption, and thanks for your report.

**Comment by retorquere** [comment]
Sorry, that will be 1.2.21, which will be released when https://travis-ci.org/ZotPlus/zotero-better-bibtex/builds/75171261 goes green -- I need to step out for a while, but that run should release in 10 minutes max.

**Comment by douxfly** [comment]
The ID for the report on the problematic entry is CFDQJ436. 
However I believe its citation key was buggy ("zoteroNull") before your fixes.

Thank you again for the quick fix!

**Comment by retorquere** [comment]
My pleasure -- I know I can't deliver perfection, so quick fixes is the next best thing. The key being buggy was probably knock-on damage.
