### ISSUE TITLE
thesis zotero entries always create `@phdthesis` bibtex entries

### ISSUE THREAD

**Issue by ssfrr** [ZotPlus/zotero-better-bibtex#307]
I'm trying to cite a masters thesis, but Zotero only has a generic "thesis" type. It seems to be generating a `@phdthesis` bibtex entry and I can't figure out how to stop it.

From the code it looks like it's checking a `thesisType` field, but I can't tell where that gets set. I've tried setting the `type` field on Zotero to `mastersthesis` and `masters` and neither seems to make a difference. Am I doing something wrong?

**Comment by ssfrr** [comment]
Ah hah, with a little more research it looks like the solution was to add `bibtex[referencetype=mastersthesis]` to the `extras` field in Zotero.

Sorry for the noise.

**Comment by retorquere** [comment]
No problem. The "thesisType" field is the "Type" field in a "thesis" reference. Setting this will add a "type" field to the @thesis BibTeX reference -- it does not change the reference type, which is what setting "referencetype" does. So where your solution yields
```
@mastersthesis{...}
```
setting the "type" on a "thesis" reference would yield
```
@thesis{type= {mastersthesis}, ...}
```

**Comment by retorquere** [comment]
Tests are running now on a change that will export `@mastersthesis` if you set Type to "mastersthesis" (as per the BibLaTeX manual section 2.1.2. (see? no report is ever noise)

**Comment by retorquere** [comment]
I am going to release this together with the fixes for #308 and #309 -- probably tomorrow.

**Comment by retorquere** [comment]
1.2.22 contains the fixes for #308 and #307
