### ISSUE TITLE
condense in cite key format not working

### ISSUE THREAD

**Issue by floe** [ZotPlus/zotero-better-bibtex#308]
First of all, thanks for your work - your plugin has fixed exactly what's been bugging me about Zotero.

I'm currently running Zotero 4.0.28.1 and Better BibLaTex 1.2.21. Some days ago (maybe after a recent autoupdate?) I noticed that some Bibtex keys in my master file have changed and don't contain underscores in the author names anymore - here's an example of what's changed:

```diff
-@inproceedings{de_kort2007digital,
+@inproceedings{dekort2007digital,
```

My cite key format looks like this:
`[auth:condense,_:fold:lower][year][Title:fold:skipwords:select,1,1:lower]`

The whole bibtex entry in question looks like this:
```
@inproceedings{dekort2007digital,
  title = {Digital games as social presence technology: development of the social presence in gaming questionnaire ({SPGQ})},
  booktitle = {Proceedings of the 10th Annual International Workshop on Presence},
  author = {de Kort, Y.A.W. and {IJsselsteijn}, W.A. and Poels, K.},
  year = {2007},
  pages = {195 -- 203}
}
```

Any hints?

**Comment by retorquere** [comment]
Could you do me a favour and right-click that reference, select "Report ZotPlus Error" and paste the debug ID here? I think I have found the problem, but this will give me a test case so I can prevent future regressions.

**Comment by floe** [comment]
Sure, it's HPRN3UGV. Thanks for the quick response.

**Comment by retorquere** [comment]
Thanks, test is green! I've scheduled a release. Apologies for the disruption I caused.

What is your area of research? That paper looks interesting.

**Comment by retorquere** [comment]
1.2.22 contains the fixes for #308 and #307

**Comment by floe** [comment]
No worries, many thanks for the quick fix. My research is in human-computer interaction, which occasionally touches on psychology etc. (hence the example citation).

**Comment by retorquere** [comment]
In this case, what is meant with "social presence"? Can you tell me a little more about that?

**Comment by floe** [comment]
In this case, I think it's about how similar or different online games feel compared to real-life interaction, i.e. how "present" you feel the other person to be.

**Comment by retorquere** [comment]
That could actually be very interesting for my own research - any papers
you could recommend?

**Comment by floe** [comment]
I'd be happy to - here are a few additional examples I have in my collection:

```
@inproceedings{poels_identification_2008,
	address = {Florence, Italy},
	title = {Identification and validation of post game experiences.},
	booktitle = {Evaluating user experiences in games. {Workshop} at {CHI} 2008},
	author = {Poels, K. and de Kort, Y.A.W. and IJsselsteijn, W.A.},
	year = {2008}
}

@inproceedings{yarosh_almost_2013,
	address = {New York, NY, USA},
	series = {{CSCW} '13},
	title = {"{Almost} {Touching}": {Parent}-child {Remote} {Communication} {Using} the {Sharetable} {System}},
	isbn = {978-1-4503-1331-5},
	shorttitle = {"{Almost} {Touching}"},
	url = {http://doi.acm.org/10.1145/2441776.2441798},
	doi = {10.1145/2441776.2441798},
	urldate = {2015-06-25},
	booktitle = {Proceedings of the 2013 {Conference} on {Computer} {Supported} {Cooperative} {Work}},
	publisher = {ACM},
	author = {Yarosh, Svetlana and Tang, Anthony and Mokashi, Sanika and Abowd, Gregory D.},
	year = {2013},
	keywords = {camera-projector system, children, computer-mediated communication, divorced families, home, tabletop},
	pages = {181--192}
}

@inproceedings{yarosh_towards_2014,
	address = {New York, NY, USA},
	series = {{CSCW} '14},
	title = {Towards a {Questionnaire} for {Measuring} {Affective} {Benefits} and {Costs} of {Communication} {Technologies}},
	isbn = {978-1-4503-2540-0},
	url = {http://doi.acm.org/10.1145/2531602.2531634},
	doi = {10.1145/2531602.2531634},
	urldate = {2015-06-30},
	booktitle = {Proceedings of the 17th {ACM} {Conference} on {Computer} {Supported} {Cooperative} {Work} \& {Social} {Computing}},
	publisher = {ACM},
	author = {Yarosh, Svetlana and Markopoulos, Panos and Abowd, Gregory D.},
	year = {2014},
	keywords = {affect, cmc, communication, evaluation., questionnaire},
	pages = {84--96}
}
```

Hope these are useful as starting points!

**Comment by retorquere** [comment]
The url for the PDF of the first reference is inaccessible to me.

**Comment by floe** [comment]
Send me an email (floe ÄT butterbrot DOT org) and I'll send you the PDFs.

**Comment by retorquere** [comment]
Damn... turns out I might have misread this report. `auth` has condense applied before any other filter runs, and moving application to the end has (as it turns out) some undesired side-effects. What would have worked for you is `Auth` instead, which does not pre-apply a default condense. Unfortunately I am going to have to revert the part where I defer cleanup to the end as that cleanup (which includes the default condense) would also run on the filters, in some cases undoing them. So if you replace your pattern with

```
[Auth:condense,_:fold:lower][year][Title:fold:skipwords:select,1,1:lower]
```

you should be good.

**Comment by floe** [comment]
Thanks for the update, tried `Auth` and it seems to work just as well.
