### ISSUE TITLE
BibTeX variable support for journal titles.

### ISSUE THREAD

**Issue by tomseidel1** [ZotPlus/zotero-better-bibtex#309]
When the option "Use journal abbreviation" is set, the exported file indeed contains the abbreviation, however, backslashes are added: The result may then look like this `{{IEEE}\\_J\\_{IT}}`.

Do you have any ideas how to fix this? In this case, Bibtex is obviously not able to perform the substitution.

Any hints appreciated!

**Comment by retorquere** [comment]
So journal abbreviations should be exempt from preserve caps then. I think I can arrange that -- can you right-click on the reference in question, select "Report ZotPlus Error", and paste the debug ID here? It will give me a test case to work with.

**Comment by retorquere** [comment]
The adjusted tests already covered this case, so I have my test case, I'll cut a release.

**Comment by retorquere** [comment]
Can you explain what you mean with "perform the substitution"? I can't find anything on short journal usage in the BibTeX manuals (such as they are), and the BibLaTeX manual says that short journal is not used by any of the styles. It does offer some suggestions on how it could be used, manually, but none of these use-cases speak of substitution. I'm going to hold off releasing this until I understand what the desired behaviour is, lest I break something. Can you give me some info on this substitution behaviour?

**Comment by tomseidel1** [comment]
The ID is 2VR7X4EV.
What I expect is the following:  For a given reference, I update the Publication field as IEEE_J_IT and once I export this reference using Better BibLatex and the "Use journal abbreviation field" I would like to have it exported as 

[...]
  journal = IEEE_J_IT,
[...]

Then, in my Latex document I add a corresponding abbreviation list (like http://mirror.unl.edu/ctan/macros/latex/contrib/IEEEtran/bibtex/IEEEabrv.bib) and it bibtex replaces IEEE_J_IT by  "{IEEE} Trans. Inf. Theory". However, right now, this does not work, as the export looks like {{IEEE}\\_J\\_{IT}}.

I just updatet to 1.2.22 and the problem still exists.

**Comment by tomseidel1** [comment]
To be precise, the modified title of this issue "Journal abbreviations should be exempt from caps preservation" does not reflect the actual problem. I hope my last comment makes things more clear.

**Comment by retorquere** [comment]
Ah, so you want to use bibtex variables. For that you need to enable the corresponding BBT preference -- that will take care of the extra braces. Given that there is no formal purpose for the short journal I'm loathe to assume too much on how it ought to be used. The BibLaTeX manual doesn't say list the field as verbatim, which is what would be needed to achieve
```
shortjournal = IEEE_J_IT,
```
but marking `journaltitle` as verbatim is too much to assume.

I'll need to think about this a little more, preferably a way to do this without adding yet another preference. If you're in a hurry, adding
```
bibtex[journaltitle=IEEE_J_IT]
```
and enabling "preserve BibTeX variables" should do the trick for now.

**Comment by retorquere** [comment]
Ah, wait! I think I understand what you need!

**Comment by retorquere** [comment]
I think I got it. Tests are running.

**Comment by retorquere** [comment]
Awesome, it goes green, and I've added your reference as a test. Given that reference, you want just with "preserve BibTeX variables", not necessarily "use journal abbreviation". Could you try http://tempsend.com/60AA8342CF (with "preserve BibTeX variables" on)? If you confirm that this is what you want, I can cut a release.

**Comment by retorquere** [comment]
That release does no require the `bibtex[journaltitle=IEEE_J_IT]` workaround BTW

**Comment by retorquere** [comment]
Since the version I have now exhibits the behaviour you describe, I've merged it into master. I think my testcase represents your case, but I'd still love to add yours.
