### ISSUE TITLE
auth leaves punctuation in citation key

### ISSUE THREAD

**Issue by felixhayashi** [ZotPlus/zotero-better-bibtex#310]
Hi,

in my library there is an author with a single quotation mark in his name (O'hara) and using better-biblatex the generated citation key becomes "O'hara2011" and this causes biblatex to somehow go crazy, i.e. all citations in my latex document are regarded as undefined. Shouldn't better-biblatex remove the symbol on the citation key?

Many thanks!
Felix

**Comment by felixhayashi** [comment]
…I think actually did in the previous versions, since I didn't change my zotero library for a while and this problem suddenly occurred. I am using the latest version (1.2.22).

**Comment by retorquere** [comment]
Can you right-click that reference for me and select "report ZotPlus
error", and paste the resulting debug id here? That will give me the
information I need.

**Comment by retorquere** [comment]
Doing so will also give me a copy of your current configuration, including your key format pattern; without it I really can't tell what is at hand.

**Comment by retorquere** [comment]
I see a new debug ID, but without a reference -- can you make sure you select "Send ZotPlus Error" after right-clicking this reference, rather than from the Zotero gear menu?

**Comment by retorquere** [comment]
Since the version I have now exhibits the behaviour you describe, I've merged it into master. I think my testcase represents your case, but I'd still love to add yours.

**Comment by retorquere** [comment]
(sorry, the previous comment was not meant for this issue; I still really need that reference).

**Comment by retorquere** [comment]
You're killing me -- I really want to fix this ASAP.

**Comment by felixhayashi** [comment]
Hi @retorquere 

sorry for the late response. Thanks for your effort.

> I see a new debug ID, but without a reference -- can you make sure you select "Send ZotPlus Error" after right-clicking this reference, rather than from the Zotero gear menu?

That wasn't me. I didn't create a ZotPlus error report.

However, **I think I found the problem**. When I enter the citation key format `[auth][year]` it happens. When I enter `[auth:lower][year]` it doesn't create a malcious title.

Because the zotplus report contains too much privat information about my system, I removed some of it and paste the rest here if that is ok with you. My machine is linux mint FF 40 : 

```
1439812705622	Services.Metrics.Provider.org.mozilla.addons	WARN	Add-on type without field: locale
[JavaScript Error: "SyntaxError: Expected "+", ":", ":(", "]", [0-9] or [0.a-zA-Z] but end of input found."]
[JavaScript Error: "SyntaxError: Expected "Auth", "Authors", "Editors", "Edtr", "auth", "authors", "editors", "edtr" or [0.a-zA-Z] but end of input found."]
[JavaScript Error: "SyntaxError: Expected "+", ":", ":(", "]", [0-9] or [0.a-zA-Z] but end of input found."]
[JavaScript Error: "SyntaxError: Expected "Auth", "Authors", "Editors", "Edtr", "auth", "authors", "editors", "edtr" or [0.a-zA-Z] but "[" found."]
[JavaScript Error: "SyntaxError: Expected [^:\],] but "]" found."]
[JavaScript Error: "SyntaxError: Expected "[", [^|>[\]], [|>] or end of input but "]" found."]
[JavaScript Error: "SyntaxError: Expected [^:\],] but "]" found."]
[JavaScript Error: "TypeError: can't access dead object" {file: "chrome://global/content/bindings/popup.xml" line: 311}]

Better BibTeX schema 1.2.22: {"autoexport":{"id":{"cid":0,"name":"id","type":"INTEGER","notnull":1,"dflt_value":"NULL","pk":1},"collection":{"cid":1,"name":"collection","type":"","notnull":1,"dflt_value":null,"pk":0},"path":{"cid":2,"name":"path","type":"","notnull":1,"dflt_value":null,"pk":0},"exportCharset":{"cid":3,"name":"exportCharset","type":"","notnull":1,"dflt_value":null,"pk":0},"exportNotes":{"cid":4,"name":"exportNotes","type":"","notnull":0,"dflt_value":"'false'","pk":0},"translatorID":{"cid":5,"name":"translatorID","type":"","notnull":1,"dflt_value":null,"pk":0},"useJournalAbbreviation":{"cid":6,"name":"useJournalAbbreviation","type":"","notnull":0,"dflt_value":"'false'","pk":0},"exportedRecursively":{"cid":7,"name":"exportedRecursively","type":"","notnull":0,"dflt_value":null,"pk":0},"status":{"cid":8,"name":"status","type":"","notnull":0,"dflt_value":null,"pk":0}},"cache":{"itemID":{"cid":0,"name":"itemID","type":"","notnull":1,"dflt_value":null,"pk":1},"exportCharset":{"cid":1,"name":"exportCharset","type":"","notnull":1,"dflt_value":null,"pk":2},"exportNotes":{"cid":2,"name":"exportNotes","type":"","notnull":0,"dflt_value":"'false'","pk":3},"getCollections":{"cid":3,"name":"getCollections","type":"","notnull":0,"dflt_value":"'false'","pk":4},"translatorID":{"cid":4,"name":"translatorID","type":"","notnull":1,"dflt_value":null,"pk":5},"useJournalAbbreviation":{"cid":5,"name":"useJournalAbbreviation","type":"","notnull":0,"dflt_value":"'false'","pk":6},"citekey":{"cid":6,"name":"citekey","type":"","notnull":1,"dflt_value":null,"pk":0},"bibtex":{"cid":7,"name":"bibtex","type":"","notnull":1,"dflt_value":null,"pk":0},"lastaccess":{"cid":8,"name":"lastaccess","type":"","notnull":1,"dflt_value":"CURRENT_TIMESTAMP","pk":0}},"keys":{"itemID":{"cid":0,"name":"itemID","type":"","notnull":0,"dflt_value":null,"pk":1},"citekey":{"cid":1,"name":"citekey","type":"","notnull":1,"dflt_value":null,"pk":0},"citekeyFormat":{"cid":2,"name":"citekeyFormat","type":"","notnull":0,"dflt_value":null,"pk":0}}}

{
  "config": {
    "id": "36a3b0b5-bad0-4a04-b79b-441c7cef77db",
    "label": "BetterBibTeX JSON",
    "release": "1.2.22",
    "preferences": {
      "csquotes": "",
      "citekeyFormat": "[auth][year]",
      "skipWords": "a,ab,aboard,about,above,across,after,against,al,along,amid,among,an,and,anti,around,as,at,before,behind,below,beneath,beside,besides,between,beyond,but,by,d,da,das,de,del,dell,dello,dei,degli,della,dell,delle,dem,den,der,des,despite,die,do,down,du,during,ein,eine,einem,einen,einer,eines,el,en,et,except,for,from,gli,i,il,in,inside,into,is,l,la,las,le,les,like,lo,los,near,nor,of,off,on,onto,or,over,past,per,plus,round,save,since,so,some,sur,than,the,through,to,toward,towards,un,una,unas,under,underneath,une,unlike,uno,unos,until,up,upon,versus,via,von,while,with,within,without,yet,zu,zum",
      "skipFields": "",
      "usePrefix": false,
      "preserveCaps": "inner",
      "fancyURLs": false,
      "langID": "babel",
      "autoAbbrev": true,
      "autoAbbrevStyle": "http://www.zotero.org/styles/american-medical-association",
      "pinCitekeys": "manual",
      "rawImports": false,
      "DOIandURL": "both",
      "attachmentsNoMetadata": false,
      "preserveBibTeXVariables": false
    },
    "options": {
      "exportFileData": false,
      "exportNotes": true
    }
  },
  "collections": [],
  "items": [
    {
      "itemType": "book",
      "tags": [],
      "relations": {},
      "date": "2015",
      "extra": "bibtex: O'hara2015",
      "title": "A testbook",
      "creators": [
        {
          "creatorType": "author",
          "lastName": "O'hara",
          "firstName": "james"
        }
      ],
      "attachments": [],
      "notes": [],
      "itemID": 1,
      "seeAlso": [],
      "__citekey__": "O'hara2015"
    }
  ]
}

Thanks
Felix

**Comment by retorquere** [comment]
I'll look into as soon as I get home, but is there some information I could filter out of the debug report to make it less privacy sensitive?

**Comment by felixhayashi** [comment]
Hi @retorquere 

thanks for fixing this.

> I'll look into as soon as I get home, but is there some information I could filter out of the debug report to make it less privacy sensitive? 

Well, yes, the current report lists all my firefox plugins and I don't want to share that info ;) I understand that some plugins cause other plugins to fail, yet I feel this is somewhat private territory…

Just a thought (maybe an overkill) but I would suggest to add checkboxes next to each section of the error report so the user may decide what information he/she wants to exclude. In the end a little bit of debug information might be enough and it is better than a user who does not send any debug info at all because of privacy concerns...

-Felix

**Comment by retorquere** [comment]
I'll have a look at it. Shouldn't be too hard.

**Comment by retorquere** [comment]
Next release will have it.

**Comment by felixhayashi** [comment]
:+1:
