### ISSUE TITLE
Zutilo 1.2.10.1 interferes with Quick Copy

### ISSUE THREAD

**Issue by wilkohardenberg** [ZotPlus/zotero-better-bibtex#311]
Since I installed Better Bibtex Zotero's quick copy is not working: Nothing seems to happen. If I disable BBT I get a Javascript error pop-up saying: "An error occurred while trying to export the selected file." I am not completely clear however if this is a BBT issue, or if it is due to something else. I know that a similar issues has been declared solved in issue #195, but it is still happening on my computer. I'd be most grateful if you could help me out.

Here is the Report ID with BBT disabled: G5WQJEGS
And here w/ BBT enabled: UV9CSTZC

Zotero 4.0.28
Firefox 40.0
Ubuntu 14.04 LTS

**Comment by retorquere** [comment]
With BBT disabled I'm surprised you can even submit the report, but it will for sure have BBT in an error state. I can't reproduce the error yet locally, but UV9CSTZC suggest it might be an interaction with Zutilo -- could you try disabling it, restarting firefox, and then try again?

**Comment by retorquere** [comment]
It's almost certainly related to Zutilo; when I install Zutilo I'm also getting errors. The error is most likely related to a change Zotero made in februari; Zutilo searches for `zotero-status-image-context` in line 310 of  firefoxOverlay.js, which errors out because it doesn't exist anymore after https://github.com/zotero/zotero/commit/9a87f1595660a1715f3448172d6ce008e308adec#diff-a42cc3f2f595999239df2741cc274f59L71, and it looks like it's patched itself into getContentsFromURL, which BBT happens to call. It doesn't look like something I can work my way around, so I'm afraid @willsALMANJ from https://github.com/willsALMANJ/Zutilo will have to take a look at this.

**Comment by retorquere** [comment]
I've submitted https://github.com/willsALMANJ/Zutilo/issues/42 for this but I'd appreciate it if you could stay in the loop -- I don't use Zutilo myself.

**Comment by willsALMANJ** [comment]
@wilkohardenberg could you please try the latest beta version of Zutilo available on AMO: https://addons.mozilla.org/en-US/firefox/addon/zutilo-utility-for-zotero/versions/ It is 1.2.11pre007 at the moment.

I believe I fixed this issue a while back with this commit: https://github.com/willsALMANJ/Zutilo/commit/7187893b0e858495b9b2e66279c03ca965a2fe11#diff-100e0e9943682f9300772c04a9fd6b19

I have not been able to prioritize getting Zutilo through the AMO review process recently. Also, another recent change to Zotero broke Zutilo's additions to the Zotero icon menu again just in the last couple weeks, but hopefully it did so in a way that doesn't interact with BBT.

**Comment by retorquere** [comment]
I can confirm BBT quick copy works with the Zutilo Beta.

@willsALMANJ: I'd personally recommend hosting Zutilo as an unlisted add-on. Simple changes will make an extension eligible for automatic signing (I've submitted a pull request for Zutilo, but if you don't feel like going that route, no offence taken). I've fully given up in AMO. The process behind always had a works-on-paper mentality, and they seem oblivious to the extra problems they're introducing with mandatory signing.

**Comment by retorquere** [comment]
I've added a change that will make BBT complain when it sees Zutilo 1.2.10.1; there's nothing else I can do. I'll add the link to the betas.

**Comment by wilkohardenberg** [comment]
Thank you for your time and help: unfortunately it did not help out here. I uninstalled Zutilo for the time being and still nothing happens (also after reinstalling both Zotero and BBT). Since I get a Javascript error message with BBT uninstalled I will refer back to the Zotero people.

**Comment by retorquere** [comment]
Is that even after a restart? BBT is fairly invasive, so I'd sooner double-check that it's not my fault than assume it's theirs.
