### ISSUE TITLE
(non-)dropping particle handling

### ISSUE THREAD

**Issue by gracile-fr** [ZotPlus/zotero-better-bibtex#313]
How can I change the way authors names are exported?
For one specific author, "Georg Henrik von Wright", I need to have in my .bib file both the particle "von" and the name enclosed, together, in braces in order to make sure that BibLaTeX treats the particle correctly.
i.e. the desired output would be: <code>author = {{von Wright}, {Georg} {Henrik}}</code>
whereas, at the moment, it is exported: <code>author = {von {Wright}, {Georg} {Henrik}}</code>

I tried to use the extra field: <code>"extra": "bibtex[author={von Wright}, Georg Henrik]"</code> (side note: it doesn't work at all if I put some braces around the given names) but the braces are escaped by BBT: <code>author = {\\{von Wright\\}, Georg Henrik},</code>.

Thank you!
[<a href="https://gist.github.com/gracile-fr/390c24e8471e8d1a6bfc">desired bib file</a> and <a href="https://gist.github.com/gracile-fr/75284e7b3a39e962b4bc">json file</a> (doesn't work at the moment)]

**Comment by retorquere** [comment]
I think I have a way to address that, but doesn't the "useprefix" option do what you want?

**Comment by gracile-fr** [comment]
Indeed, I didn't know that I can use this option on a per-type basis. So with <code>bibtex[options={useprefix=false}]</code>? The braces are escaped…

**Comment by gracile-fr** [comment]
Actually, <code>useprefix </code>doesn't exactly do what I want, and in any case can't distinguish between authors in a single item with multiple authors. So it would be useful to change the way authors names are exported.

**Comment by gracile-fr** [comment]
You wrote:<blockquote>a BBT bibliography should yield the same(ish) output the references would produce through zotero itself</blockquote> In this case, what do you think of reproducing the way citeproc-js parses the names ? Thread <a href="http://forums.zotero.org/discussion/30974/any-idea-why-an-a-author-comes-last-in-the-bibliography/?Focus=231595#Comment_231595">here</a>.

**Comment by retorquere** [comment]
I'm going to look into this https://forums.zotero.org/discussion/12730/double-surname-last-name-has-two-words-bibtex-export/ but as I'm currently travelling, pace is slower than usual.

**Comment by retorquere** [comment]
Messages crossed - looks like we found the same info.

**Comment by retorquere** [comment]
Citeproc can't really be used, as it produces already-expanded bibliographies rather than letting BibTeX do it.

**Comment by gracile-fr** [comment]
I was thinking about an equivalent of exporting with "CSL JSON" just for BBT to get the relevant information concerning names. Is it a nonsense? Too resource-consuming?

Citeproc-js has a mechanism to parse particles. At the moment, it is based on a list of particles, <a href="https://bitbucket.org/fbennett/citeproc-js/history-node/f501a37e2b1a/src/util_name_particles.js?at=default">here</a> or for a human readable version <a href="https://gist.github.com/gracile-fr/ed650f9ca31faf8f671c">here</a>. Each is either non-dropping, dropping or unfixed. In the last case (unfixed), the parsing will depend upon the field in which the particle is entered (first-name: dropping ; last-name: non-dropping). In a limited number of cases, however, you might need to suppress the automatic parsing; you can do that by enclosing the particle and the last name in double quotes (<a href="http://gsl-nagoya-u.net/http/pub/citeproc-doc.html#particles-as-part-of-the-last-name">documented here</a>).

But you don't really need to understand that if you can rely on citeproc-js for this specific task. Once you've got the names parsed by citeproc-js, the remaining question is how that should be exported to BibLaTeX. In the last-name part for sure, but more precisely and if I understand correctly,

* the non-dropping particle and the name should be enclosed, in braces. either together, e.g.: {{von Wright}, {Georg} {Henrik}} or with separate braces, e.g. : <code>{{von} {Wright}, {Georg} {Henrik}}</code> ;
* the dropping particle should <i>not</i> be enclosed in braces, e.g. <code>{von {Savigny}, {Friedrich} {Carl}}</code>. (nb: if the particle is « d' », a space must be put between the apostrophe and the opening brace, e.g.: <code>{d' {Almeida}, {Luis}}</code>, otherwise it's not treated correctly by BibLaTeX).

**Comment by retorquere** [comment]
There is a performance hit, but that should be mitigated by the BBT cache. I'll give the CSL JSON a stab -- I have no deep desire to replicate those efforts.

**Comment by gracile-fr** [comment]
<blockquote> I have no deep desire to replicate those efforts. </blockquote>Yes, sure.
If that's not possible, allow to entry the names in the Extra field would be an improvement.

**Comment by retorquere** [comment]
The CSL-JSON returns more data than I had expected; do you know what the following terms could mean?

* comma-suffix
* comma-dropping-particle
* suffix

**Comment by gracile-fr** [comment]
http://gsl-nagoya-u.net/http/pub/citeproc-doc.html#suffix-ordinary
comma-dropping-particle might be related to a <a href="https://forums.zotero.org/discussion/17801/authors-with-no-given-name/?Focus=91229#Comment_91229">very specific case</a> but I'm really not sure. @fbennett, can you help?

**Comment by retorquere** [comment]
I take it `non-dropping-particle` and `dropping-particle` cannot occur on the same creator?

**Comment by gracile-fr** [comment]
No, they can occur on the same creator e.g.: "Jean de La Fontaine" => "Jean" is the given name, "de" a dropping-particle, "La" a non-dropping particle, "Fontaine" the last-name. In a bibliography, that will be "La Fontaine, Jean de"

**Comment by retorquere** [comment]
How should that be represented in BibTeX?

The CSL-JSON can't be used, as it doesn't export all author types, but I can use the particle parser.

**Comment by retorquere** [comment]
What should be done with the suffix BTW?

**Comment by retorquere** [comment]
First tests are looking sort of OK, but I need to take care of anomalies such as https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/76594744#L541. I haven't yet found suffixes, but I'd rather not merge them not knowing what to do with them when I do.

**Comment by retorquere** [comment]
And https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/76594744#L572 goes haywire (these are mostly notes for myself)

**Comment by gracile-fr** [comment]
It seems that BibLateX consider non-dropping particle as part of the last name, there's no specific concept of non-dropping particle. That's why a non-dropping particle should be enclosed in braces with (or without, actually) the last-name.
In the example above: author = <code>{de {La Fontaine}, {Jean}}</code> works for me

Suffix (III) : <code> author = {de {La Martinière}, III, {Gérard}}</code>
Multiple authors: <code> author = {de {La Martinière}, III, {Gérard} and {Luther King}, Jr., {Martin}}</code>

See also: http://tex.stackexchange.com/a/209951/82783

Generally speaking, two syntaxes are possible for names (particles, for biber, means dropping particles and begin with a lower case)
<code>{Given_name particle Name}</code> => <code>author = {Jean de La Fontaine}</code>
<code>{particle Name, suffix Given_name}</code> => <code>author = {de La Fontaine, Jr. Jean}</code>
The latter seems better for hard cases. I'm not completely sure why Zotero/BBT exports with a lot of braces, but I think this is to avoid ambiguity and to give more flexibility.

**Comment by retorquere** [comment]
I'll have a look at those when I get home. You can remove most of the
braces by disabling "preserve capitals" - the reason the braces are there
is mostly to override BibTeX recapitalization rules, assuming you want
names to appear as they have been typed into Zotero.

**Comment by retorquere** [comment]
Do you mean that "{von} Wright" should be preferred over "{von Wright}"?

**Comment by retorquere** [comment]
I'm collecting testcases for this issue here: https://github.com/ZotPlus/zotero-better-bibtex/blob/313/test/fixtures/export/(non-)dropping%20particle%20handling%20%23313.json

**Comment by retorquere** [comment]
The Zotero particle parser converts
```
{"lastName":"de La Fontaine","firstName":"Jean"}
```
to
```
{"family":"Fontaine","given":"Jean","non-dropping-particle":"de La"}
```

**Comment by retorquere** [comment]
Can you get me JSON testcases for <code>{von {Savigny}, {Friedrich} {Carl}}</code>, <code>{d' {Almeida}, {Luis}}</code> and <code>Jean de La Fontaine</code>?

**Comment by retorquere** [comment]
and also for <code> author = {de {La Martinière}, III, {Gérard}}</code>
and <code> author = {de {La Martinière}, III, {Gérard} and {Luther King}, Jr., {Martin}}</code>?

**Comment by retorquere** [comment]
I also have unhandled particla data for `{"lastName":"Kvorning","firstName":"Jens, Forstædernes Tænketank"}`, which translates to `{"family":"Kvorning","given":"Jens Forstædernes Tænketank","dropping-particle":"Forstædernes Tænketank","comma-dropping-particle":","}`. Would appreciate advise on what to do with this one.

**Comment by retorquere** [comment]
OK, so it looks like the "comma" bits should be handled by BibTeX, so I need only look at the suffix. Suffix encoding is reasonably clear in BibTeX, so that's now handled. But one thing that worries me is that the particle parser translates
```
{"family":"Aubignac","given":"François Hédelin, abbé d'"}
```
to
```
{"family":"Aubignac","given":"François Hédelin","dropping-particle":"d'"}
```
where has abbé gone? Can it be left out without damage?

**Comment by fbennett** [comment]
@gracile noted that I dropped this from the parsing struct. That was on
purpose - if I recall correctly, I wasn't able to achieve the exact
behaviour of the original implementation for that "particle", which is some
sort of hybrid. @gracile has suggested that I put it back, though, since
the use case was covered in response to user request, and that seems the
right thing to do.

However, that result looks not good. I'll take a look in the processor test
harness later tonight or tomorrow.

Frank

**Comment by retorquere** [comment]
Hey @fbennett, thanks for weighing in; I think you meant to ping @gracile-fr rather than @gracile. I have a mini test harness that only exercises the particle parser, which is how I found this one. My tests for particle parsing in BBT is now all-green except for this issue -- I'll just wait and see what you think is wise.

**Comment by retorquere** [comment]
BTW, if you could point me to your test harness, I'll be happy to pilfer it for test cases for BBT.

**Comment by fbennett** [comment]
On Sun, Aug 23, 2015 at 10:09 PM, retorquere <notifications@github.com>
wrote:

> BTW, if you could point me to your test harness, I'll be happy to pilfer
> it for test cases for BBT.
>
It's a homebrew mess, pulled together and extended as required while the
processor was being written. The test cases are here:

    https://bitbucket.org/bdarcus/citeproc-test

They are run by a Python script (test.py) that embeds a JS engine:

    https://bitbucket.org/fbennett/citeproc-js/src

I'll write again tomorrow.

Frank

**Comment by retorquere** [comment]
I'm parsing the test cases, and I'm finding some creator info of which I don't know what it means:

* static-ordering
* isInstitution
* static-particles
* parse-names
* multi

**Comment by gracile-fr** [comment]
@retorquere: sorry, I'm currently travelling, I'll have a look in a few hours. Thank you very much.
(The abbé case is a bit special as fbennett wrote, out of CSL specs, and not really a particle.)

**Comment by retorquere** [comment]
Be that as it may, I'll need to handle it somehow; if the particleParser can't (or won't) handle it, and I can't detect that it can't (or won't), I can't use the particle parser.

**Comment by retorquere** [comment]
I've added the tests from @fbennett for a bit more coverage. Still not entirely certain I have a sample for every case, but I think the results look good so far (except the poor Abbott). I like this enhancement a lot, but I'm still not entirely sure whether I should merge with the Abbott stripped from his title.

@gracile-fr, I'd appreciate it if you could review https://github.com/ZotPlus/zotero-better-bibtex/blob/313/test/fixtures/export/(non-)dropping%20particle%20handling%20%23313.bib and https://github.com/ZotPlus/zotero-better-bibtex/blob/313/test/fixtures/export/(non-)dropping%20particle%20handling%20%23313.json

**Comment by gracile-fr** [comment]
This is a very long series of tests, hard to check manually. Seems ok to me. Just  some quick remarks:

lines <a href="https://github.com/ZotPlus/zotero-better-bibtex/blob/313/test/fixtures/export/%28non-%29dropping%20particle%20handling%20%23313.bib#L93">93</a>, <a href="https://github.com/ZotPlus/zotero-better-bibtex/blob/313/test/fixtures/export/%28non-%29dropping%20particle%20handling%20%23313.bib#L860">860</a>: You don't need to add a space between the particle « d' » and the last-name when the particle is non-dropping. The space is only necessary when the particle is dropping (i.e. in Zotero given name field).
[<a href="https://github.com/ZotPlus/zotero-better-bibtex/blob/313/test/fixtures/export/%28non-%29dropping%20particle%20handling%20%23313.bib#L15">This test </a>is different (odd, but ok) because the space was in the <a href="https://github.com/ZotPlus/zotero-better-bibtex/blob/313/test/fixtures/export/%28non-%29dropping%20particle%20handling%20%23313.json#L115">original json</a> file.]

[This paragraph can be considered as a note for myself. — As for <a href="http://gsl-nagoya-u.net/http/pub/citeproc-doc.html#particles-as-part-of-the-last-name">particles which are part of the last name</a> (you called that "explicit", cf. <a href="https://github.com/ZotPlus/zotero-better-bibtex/blob/313/test/fixtures/export/%28non-%29dropping%20particle%20handling%20%23313.json#L78">l. 78</a>), it's nice to have a test for it because it might be used by Zotero users. But note that it's directly related to the fact that CSL has a concept of "non-dropping particle", and that these non-dropping particles can nonetheless be dropped (!) with the CSL attribute "<a href="http://docs.citationstyles.org/en/stable/specification.html#name-particles">demote-non-dropping-particle</a>" correctly set in styles. To make sure that a non-dropping particle will absolutely never be demoted/dropped, and treated as part of the last-name, Zotero users can enclose them in quotes.]

I'm not sure for the "abbé" case. At the moment, there's no reason for BibLaTeX not to initialize "abbé" to "a." if a style requires the given name to be initialized because it appears in the tests with the given name without specific markup showing that "abbé" is not a given name. I wonder whether it would be better to treat it like a suffix…
Anyway these two are inconsistent (no abbé in json, abbé in bib): name_ParsedDroppingParticleWithApostrophe (compare <a href="https://github.com/ZotPlus/zotero-better-bibtex/blob/313/test/fixtures/export/%28non-%29dropping%20particle%20handling%20%23313.json#L2836">json</a> and <a href="https://github.com/ZotPlus/zotero-better-bibtex/blob/313/test/fixtures/export/%28non-%29dropping%20particle%20handling%20%23313.bib#L833">bib</a>) and name_ParsedNonDroppingParticleWithApostrophe (compare <a href="https://github.com/ZotPlus/zotero-better-bibtex/blob/313/test/fixtures/export/%28non-%29dropping%20particle%20handling%20%23313.json#L2910">json</a> and <a href="https://github.com/ZotPlus/zotero-better-bibtex/blob/313/test/fixtures/export/%28non-%29dropping%20particle%20handling%20%23313.bib#L833">bib</a>).

**Comment by retorquere** [comment]
With "explicit" only meant to denote "don't do anything fancy with this author: take it literally". There's no more meaning to it.

I've adjusted doe the "d'" cases (I think) and pared down further the tests from citeproc-js.

The problem I'm still having with the abbé case is that "abbé" is missing entirely from the particleParser output in some cases (but not all, see the first reference in the testcase), so I can't reconstruct that name. Regardless of how BibTeX is going to render the final reference, I'd rather not omit data that the user has offered explicitly without good reason. Interestingly, "abbé" is only missing in one of its notations; see https://github.com/ZotPlus/zotero-better-bibtex/blob/313/test/fixtures/export/(non-)dropping%20particle%20handling%20%23313.json#L50, and the output at travis when builds later than 1644 start again (github CI integration doesn't seem to work at the moment; not Travis and Circle are not updating). @fbennett will probably know better what to make of it.

I've adjusted the JSON for those latter entries (I think); if you see more errors in the tests, could you correct those as a pull request? That way you don't have to rely on me understanding you correctly.

What do you make of sort_FamilyOnly? Is this just incorrectly entered (I think it ought to have fieldMode 1) or should I do something special?

**Comment by retorquere** [comment]
https://github.com/ZotPlus/zotero-better-bibtex/blob/313/test/fixtures/export/(non-)dropping%20particle%20handling%20%23313.bib and https://github.com/ZotPlus/zotero-better-bibtex/blob/313/test/fixtures/export/(non-)dropping%20particle%20handling%20%23313.json have been slimmed down considerably, could you give it a glance again @gracile-fr ?

**Comment by retorquere** [comment]
Travis is back; the output for the abbot cases can be found at https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/77131410#L516

**Comment by gracile-fr** [comment]
sort_FamilyOnly, yes, I think it should be set as fieldMode=1 if "correctly" entered. But that might be not the case on purpose, for the test. Compare with sort_ChicagoYearSuffix1 which has, too, its first author without fieldMode=1 whereas this should be the case if "correctly" entered.

name_ParsedNonDroppingParticleWithApostrophe has strange data (double « d' ») but parsing is ok.

sort_LeadingApostropheOnNameParticle is problematic for another reason: « 't » and « in 't » are dropping particle but « 't », because of the leading apostrophe, is not recognized as such by BibLaTeX, but you can't do anything against that…

I understand now that abbot = abbé, probably corrected by your spell check, right? Anyway no idea, @fbennett ?

**Comment by retorquere** [comment]
abbot is just the translation of abbé, and easier to type since I can never remember how to enter the é other than by cut and paste (or \\'e, which is how I usually do it).

Is either `abbé d'Aubignac, François Hédelin` or `abbé {d'Aubignac}, François Hédelin` correct? Because if so, there is a proper way to enter this name into Zotero; that there is an edge case (which I think Frank said he wanted to look into -- not sure) is not necessarily a reason not to merge at this point.

**Comment by retorquere** [comment]
@gracile-fr given sort_FamilyOnly, do you think the output is reasonable? Or should I assume only lastname present to be equivalent to fieldmode = 1? It looks odd, but then I don't know for what reason people enter names this way.

**Comment by retorquere** [comment]
Could you add  `{Luther King}, Jr., Martin` to the tescase? Curious how you'd note it in Zotero -- I have an idea, but I want to make sure.

**Comment by gracile-fr** [comment]
sort_FamilyOnly: <code>author = {ANZ Group,}</code> with a comma (as if there was no first name). If the user wants it as an institutional name, s/he has to change that in Zotero !

<code>author = {abbé d' {Aubignac}, François Hédelin}</code> in order to sort it as Aubignac, under "A". That is the <a href="https://forums.zotero.org/discussion/17801/authors-with-no-given-name/?Focus=94762#Comment_94762">desired output</a>.

I'd say <code>King, Jr., Martin Luther</code> because Martin Luther was his given name (born Michael King, though). Is that your question?

**Comment by gracile-fr** [comment]
JSON: https://gist.github.com/gracile-fr/c06cb7661c5d5832ddfe
Bib: https://gist.github.com/gracile-fr/e8af8703f7f24bd2d727

I also added a test to cover this case: http://gsl-nagoya-u.net/http/pub/citeproc-doc.html#suffix-forced-comma – in my opinion, BBT should disregard the exclamation mark and treat the suffix normally: whether to display the comma before Jr. is a matter of (BibLaTeX) styles, I think.

**Comment by gracile-fr** [comment]
(I generated the json and bib, then manually changed the bib, with "preserve capitals" enabled, I hope it's not a problem. – and the timestamp is not the good one, I forgot to manually change this, sorry.)

**Comment by retorquere** [comment]
now worries, it's all good. 

wrt sort_FamilyOnly, would you say the same goes for firstname only -- `{, ANZ Group}`?

wrt to our abbot, why `{abbé d' {Aubignac}, François Hédelin}` rather than `{abbé d' Aubignac, François Hédelin}`?

**Comment by gracile-fr** [comment]
<blockquote>wrt sort_FamilyOnly, would you say the same goes for firstname only -- {, ANZ Group}?</blockquote>Yes, if the json has only a first name. That seems more logical and predictable.

With <code>author = {abbé d' {Aubignac}, François Hédelin}</code>, BibLaTex treats <code>abbé d'</code> as a particle because it's all lowercase, allowing the desired output: Aubignac, François Hedelin, abbé d' ,cf. https://forums.zotero.org/discussion/17801/authors-with-no-given-name/?Focus=94762#Comment_94762
Actually this is broken at the moment in Zotero because Frank made some important changes recently, but that might come back (?). And just to be clear, that's with:
<code>"creators": [
        {
          "creatorType": "author",
          "lastName": "Aubignac",
          "firstName": "François Hedelin, abbé d'"
        }</code>

**Comment by retorquere** [comment]
And with `abbé d' Aubignac`, `abbé d'` is not recognized as a particle? That complicates matters.

What exactly is broken?

**Comment by retorquere** [comment]
I can currently generate these forms:

```
@article{abbot1,
  author = {d'Aubignac, François Hédelin},
}

@article{abbot2, 
  author = {abbé d'Aubignac, François Hédelin},
}

@article{abbot3, 
  author = {abbé d' Aubignac, François Hédelin},
}

@article{abbot4, 
  author = {abbé {d'Aubignac}, François Hédelin},
}

@article{abbot5, 
  author = {abbé {d' Aubignac}, François Hédelin},
}
```

if none of these is the right one, that leaves me with a bit of a problem; how should I decide that the lastname after the particle should be braced? I don't always want to do it, since bracing for example an inner dash would interfere with the word breaking algorithm.

**Comment by retorquere** [comment]
the exclamation mark is removed by the particle parser, so that seems to go alright.

**Comment by retorquere** [comment]
I've added the current forms here: https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/77207902.

Is there actually a good way to deal with this one? I can detect if all letters have been used and just generate `firstName lastName` for those where I don't. BibLaTeX renders

```
author = {Fran\c{c}ois H\'edelin abb\'e d' Aubignac} 
```

into

```
Aubignac, Francois Hedelin abbe d'
```

(with all the fancy french squiggles that I can't paste in here looks like it); that seems reasonable to me.

**Comment by retorquere** [comment]
Perhaps it would even be better to just forego the particle parser entirely and just generate "firstName lastName" always. Biber is perhaps smarter than we think.

**Comment by retorquere** [comment]
The output from the fallback detection is at https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/77216433

**Comment by retorquere** [comment]
Sorry, that should be https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/77217210

**Comment by gracile-fr** [comment]
<code>author = {abbé d' Aubignac, François Hédelin}</code> is ok. But honestly, this case should not be a stopper. It has only been raised once on the Zotero forums in almost nine years.

**Comment by retorquere** [comment]
One more abbot: https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/77218176

If we have one OK way to enter it, I'm happy with it. I can put that in the docs. I don't like the fallback heuristic as much as I thought -- I'm having one last stab at it, otherwise the abbot case is a known problem with a workaround (as noted)

**Comment by gracile-fr** [comment]
I've edited my previous message, yes there's a way to enter it in zotero (even if it's broken at the moment, it used to work), and a way to enter it in the bib. What else?

**Comment by retorquere** [comment]
Nothing I think. I have a reasonable fallback now I think that catches exactly that one abbott case -- tests running now, think it's good to go.

**Comment by gracile-fr** [comment]
Great, well done, and thanks a lot! There will be probably some adjustments on the Zotero/CSL side in the next months, but the general logic should remain.

**Comment by retorquere** [comment]
Please do keep me posted. I can update the particle parser separately from
zotero if need be.

Could you do me a favor and put in what you think is reasonable output for
the abbot cases? You seem to know more of this than I do.

**Comment by gracile-fr** [comment]
Yes, but this is not sufficient: https://github.com/ZotPlus/zotero-better-bibtex/issues/313#issuecomment-134726539 ?

**Comment by retorquere** [comment]
It should be, I'm just a little edgy about having edge cases. Still, it's better than it was.

**Comment by mdlincoln** [comment]
Sorry to reanimate this issue, but is it possible to get some documentation on how particles are handled? At the moment I seem to be unable to get BBT to parse a _dropping_ particle:

Zotero: lastname: `Heuvel`, firstname: `Chalres van den`

Current output: `{van den Heuvel}, Charles`

The desired output would be: `van den {Heuvel}, Charles`

**Comment by retorquere** [comment]
@mdlincoln I agree. Can you please open a new issue for this? Closed issues tend to drop off my radar, and I don't want to re-open this issue; technically, it's not this feature misbehaving, it's the CSL particle parser doing unexpected things. I've set up a test for the particle parser at https://zotplus.github.io/better-bibtex/nameparser.html

**Comment by retorquere** [comment]
I've also opened an issue at https://bitbucket.org/fbennett/citeproc-js/issues/183/particle-parser-returning-non-dropping

**Comment by retorquere** [comment]
@fbennett: what do you make of https://zotplus.github.io/better-bibtex/nameparser.html?lastname=Heuvel&firstname=Charles+van+den ?

**Comment by retorquere** [comment]
I've opened this as #348; an update is expected this weekend, and an interim workaround can be found on the issue too.

**Comment by gracile-fr** [comment]
@retorquere : I think you should redirect users to the Zotero forums if s/he asks something related to particle parsing, if this is not a proper BBT issue/bug. That's the best place to discuss these things, with many reactive and competent people on the subject, especially at the moment with the "new" particle parser.

**Comment by retorquere** [comment]
@gracile-fr: it really is a BBT question, though. The choice to use the CSL
particle parser is mine - aamof it isn't even usually exposed to the
translators, I did some trickery to make it available at all. I can stop
using the particle parser at any time if it no longer serves our purpose.

**Comment by gracile-fr** [comment]
Ok, I didn't know for the trickery. What I tried to say confusingly is that it might be of interest for the Zotero/CSL side in order to improve the parsing. Thanks.
