### ISSUE TITLE
Changes in Zotero do not invalidate serialisation cache.

### ISSUE THREAD

**Issue by douxfly** [ZotPlus/zotero-better-bibtex#316]
I am currently correcting many mistakes in my bibliography. Unfortunately some of the changes
seem to be "forgotten" in the bibtex export. For example the zotero entry mentioned in
the error log GXNUHNC2 gets exported with the "issue" field "Supp. 3"; it should be just "3". 
Similarly, in the entry corresponding to the log QXNJSWCK, the author first names disappear. It is as if I was exporting an old version of my database (even though I am doing a fresh manual export). Am I missing the obvious or is it a bug?

The bibtex exports for the two entries mentioned above: 

@article{Simonet2015,
  title = {Une brève histoire de l’adaptation : l’évolution conceptuelle au fil des rapports du {GIEC} (1990-2014)},
  volume = {Supplément},
  issn = {1240-1307},
  url = {http://www.cairn.info/resume.php?ID_ARTICLE=NSS_HS03_0052},
  shorttitle = {Une brève histoire de l’adaptation},
  timestamp = {2015-08-05 14:32:14},
  issue = {Supp. 3},
  author = {Simonet, Guillaume},
  urldate = {2015-08-05},
  date = {2015-06-23},
  pages = {52--64},
  langid = {french},
  file = {Full Text PDF:/Users/mag/Library/Application Support/Firefox/Profiles/m8kxmn90.default/zotero/storage/BIK6TIGQ/Simonet - 2015 - Une brève histoire de l’adaptation  l’évolution c.pdf:application/pdf;Snapshot:/Users/mag/Library/Application Support/Firefox/Profiles/m8kxmn90.default/zotero/storage/J895ID9P/revue-natures-sciences-societes-2015-Supp. 3-page-52.html:text/html}
}

@article{Weichselgartner2014,
  title = {Geographies of resilience: Challenges and opportunities of a descriptive concept},
  url = {http://phg.sagepub.com/cgi/doi/10.1177/0309132513518834},
  doi = {10.1177/0309132513518834},
  timestamp = {2015-05-25 09:59:12},
  journaltitle = {Progress in Human Geography},
  shortjournal = {Prog. Hum. Geogr.},
  author = {Weichselgartner, J. and Kelman, I.},
  date = {2014},
  file = {Prog Hum Geogr-2014-Weichselgartner-0309132513518834:/Users/mag/Library/Application Support/Firefox/Profiles/m8kxmn90.default/zotero/storage/8R4SJZWI/Prog Hum Geogr-2014-Weichselgartner-0309132513518834.pdf:application/pdf}
}

**Comment by retorquere** [comment]
Can't be anything but a bug. I'm looking into your logs now, but for temporary relief, you can go into `about:config` and set `extensions.zotero.translators.better-bibtex.cacheReset` to `1`, and restart firefox.

**Comment by retorquere** [comment]
No errors that seem relevant to the question at hand. Could you drop a copy of the file `zotero/better-bibtex/serialized-items.json` into https://dbinbox.com/retorquere?

**Comment by douxfly** [comment]
The cache reset was a great relief :-) 
I just sent the file (before the cache reset, if it matters). Let me know if I can help narrow down the bug...

**Comment by retorquere** [comment]
Could you send me another copy of that file after the reset?

**Comment by retorquere** [comment]
Definitely the serialisation cache, but how it got out of sync is not in the logs unfortunately. I've added a button in the debug prefs to allow for a manual cache reset without restart, but there must be an underlying error that caused the cache to no longer invalidate items upon change. I'd need a live instance of the problem, so while you see it happening, and without restart. Is the problem reproducible on your end?

**Comment by douxfly** [comment]
I jsut sent the new serialized-items.json. I tried changing the entries once again, this time they are exported correctly (I did not change the pref back to zero, but did not restart Firefox either). I will look out for other occurences...

**Comment by retorquere** [comment]
That confirms it, it was the serialisation cache. The pref has already been set back to zero; it only works for one restart.

I'm going to have to propose to close this issue. If it reoccurs, please to file a new issue or reopen this one. Agreed?

**Comment by douxfly** [comment]
That's fine, I will let you know if it happens again. Thank you!

**Comment by retorquere** [comment]
My pleasure -- sorry I couldn't be more help in this case. I'm going to cut a new release that has a "reset cache" button so it can be done without "about:config" fiddling.
