### ISSUE TITLE
Mandatory signing by Addons.Mozilla.org

### ISSUE THREAD

**Issue by retorquere** [ZotPlus/zotero-better-bibtex#317]
Late 2015, mandatory signing by Mozilla goes into effect. This will make it impossible for me to do quick-turnaround debugging and releases. The options I have are:

1. Accept 10-week review times
2. Try to dupe the validator to accept code it otherwise wouldn't
3. Target Zotero standalone and unbranded Firefox only

All have their downsides. 1. is clearly unacceptable. 2. is only going to work until they catch on. Which leaves 3, but unbranded firefox will only be available in English.

**Comment by benblamey** [comment]
Is there a development roadmap? Will the firefox extension continue to be developed?

I'm looking to migrate from bibtex (after sorting out some issues) -- perhaps now isn't a smart time to migrate to Zotero?

**Comment by retorquere** [comment]
I can work around the signing problem for release builds - debug builds is
an open question for now. I am committed (if only for my own sake) to a
workable bibtex manager. So for the foreseeable time I'll keep building
this plugin, and I'm working actively with Mozilla to resolve the problem.
If XUL deprecates (see other rant) that will pose a significant problem
however.

**Comment by retorquere** [comment]
IOW: there shouldn't be a problem for at least another year, and I'm sure Zotero will have found/forced a solution, which I'll follow.

Sorry for the noise. I was terribly frustrated at the time with Mozilla, who are going about this with all the grace of a tap-dancing rhino.

**Comment by retorquere** [comment]
Zotero is already on it, mirroring my concerns and proposed solutions: https://groups.google.com/forum/#!topic/mozilla.addons.user-experience/lU5WZmwS4Qc

**Comment by retorquere** [comment]
So this has now become a full-on shitstorm on reddit [\[1\]](https://www.reddit.com/r/linux/comments/3u2ksy/automated_scanning_of_firefox_extensions_is/), [\[2\]](https://www.reddit.com/r/programming/comments/3u75po/automated_scanning_of_firefox_extensions_is/), [\[3\]](https://www.reddit.com/r/firefox/comments/3u8cbe/automated_scanning_of_firefox_extensions_is/) and [mozilla.addons.user-experience](https://groups.google.com/forum/#!topic/mozilla.addons.user-experience/XFdiHtcvwoY)

Grab your popcorn folks.

**Comment by retorquere** [comment]
Looks like [sanity has prevailed](https://groups.google.com/forum/#!topic/mozilla.addons.user-experience/iwjQbLIb-Fo)!
