### ISSUE TITLE
Abandoning Firefox: Firefox abandoning extension authors

### ISSUE THREAD

**Issue by retorquere** [ZotPlus/zotero-better-bibtex#318]
Mozilla has lost its mind and is going to deprecate wholesale the technology that makes Zotero (and thereby BBT) possible; see https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/. The only upside of this is that whatever can be implemented with the new and severely neutered API is equally easy (and perhaps better) implemented in Chrome, and Chrome doesn't have any of the walled-garden signing requirements. Whether or not this also affects Zotero standalone is an open question but it's likely.

If this is happening (and Mozilla seems to make such sweeping decisions with reckless abandon lately, so it probably is), there is absolutely no incentive to do all the work to rewrite BBT from scratch (because that's what it'll take) and still target Mozilla; who knows what bombshell they're going to drop next.

**Comment by adunning** [comment]
Personally, I would advocate for making BBT part of the core Zotero functionality.

**Comment by retorquere** [comment]
I'm all for it, but Zotero I think LaTeX users are a bit of a niche for Zotero.

**Comment by adunning** [comment]
But it's now LaTeX, Pandoc, Scrivener … basically anything other than LibreOffice and MS Word. Surely that's more than a niche (or it should be).

**Comment by retorquere** [comment]
I agree, but I think the Zotero authors see as their main focus the WYSIWYG(ish) editors. My code is theirs for the taking, and it would solve some of the liberties I've been taking with run-time patching (monkey-patching FTW. Until XUL and XPCOM go in any case).

**Comment by adunning** [comment]
Well, I'm happy to write a letter of support …

**Comment by retorquere** [comment]
Not the only one who's annoyed by this: https://groups.google.com/forum/#!topic/mozilla.addons.user-experience/lU5WZmwS4Qc
