### ISSUE TITLE
CAYW Not Copying Pandoc

### ISSUE THREAD

**Issue by craigeley** [ZotPlus/zotero-better-bibtex#320]
I've been experimenting with CAYW today on a Mac running 10.10.5—calling it from `curl`, via the link provided on the [documentation](http://zotplus.github.io/better-bibtex/cayw.html), the standalone app, etc. What I've found in all of these cases is that the pop up window stays up, does not minimize, and does not copy the citation to the clipboard when using the `latex` format. Everything is fine with `mmd`.

See attached screencap:

![screen shot 2015-08-24 at 14 46 07](https://cloud.githubusercontent.com/assets/1425316/9451047/ee7873e6-4a71-11e5-805f-761b33c4198b.png)

Any idea what might be causing this? A dependency I might not have installed?

**Comment by retorquere** [comment]
No, it means an error occurred. Can you enable extended debugging in the bbt prefs, reproduce the error, and then select "report ZotPlus error" from the gear menu? You'll get a debug id, if you post that here, I can likely tell what the issue is.

**Comment by retorquere** [comment]
The latex format isn't implemented yet (I haven't quite figured out what to do with prefix, suffix and locator in the case of multiple references), but it still shouldn't have errored out. I can't reproduce the error yet, so I'll need your debug report.

**Comment by retorquere** [comment]
Ah never mind, it was specific to the pandoc picker, I thought you were experimenting with the latex picker. I've found the problem, 1.2.28 is out which fixes this bug and adds a latex picker, see https://zotplus.github.io/better-bibtex/cayw.html

**Comment by craigeley** [comment]
Can confirm that the `pandoc` format is working in this new version—sorry for the confusion by saying `latex`. Thanks for your quick work on this; it's really great software.

**Comment by retorquere** [comment]
That's quite alright -- thanks for reporting the bug.
