### ISSUE TITLE
Combining accents not normalized in export

### ISSUE THREAD

**Issue by adunning** [ZotPlus/zotero-better-bibtex#322]
If an author's name has been entered using a combining accent (seems to have come from the ISBN import), the citation key is generated using precomposed characters in Zotero, but the exported version uses combining characters. In addition, the field containing the author's name is normalized in the BibTeX export, but not in CSL JSON.

CSL JSON:

```json
{"id":"näf:2002roberti","type":"book","title":"Roberti Crikeladensis Defloratio Naturalis Historie Plinii Secundi","collection-title":"Lateinische Sprache und Literatur des Mittelalters","collection-number":"36","publisher":"Lang","publisher-place":"Bern","number-of-pages":"507","source":"Library of Congress ISBN","event-place":"Bern","ISBN":"3-906770-29-X","call-number":"PA6614.A2 R63 2002","language":"Latin","editor":[{"family":"Näf","given":"Bodo"}],"issued":{"date-parts":[["2002"]]}}
```

BibTex:

```tex
@collection{näf:2002roberti,
  location = {Bern},
  title = {Roberti Crikeladensis Defloratio Naturalis Historie Plinii Secundi},
  isbn = {3-906770-29-X},
  pagetotal = {507},
  timestamp = {2015-08-14 16:20:04},
  number = {36},
  series = {Lateinische Sprache und Literatur des Mittelalters},
  publisher = {Lang},
  editor = {Näf, Bodo},
  editora = {{Robert of Cricklade}},
  editoratype = {collaborator},
  date = {2002},
  langid = {latin},
  keywords = {Natural history,Naturalis historia,Pliny,Robert of Cricklade}
}
```

(Separately, I'm surprised that this shows up as @collection rather than @book, but I'm not sure it matters.)

**Comment by retorquere** [comment]
I'm guessing this pertains to some kind of unicode issue, but I really can't tell :) Unicode is non-trivial, and javascripts support of it is less than stellar, so I'm not surprised it fails.

It shows up as a collection because it's a book without an author, and it has an editor. I took this logic from the existing BibLaTeX translator, is all.

**Comment by adunning** [comment]
Ah, *that's* it. In this case, it's an edited classical work; we really need a separate role for that.

**Comment by retorquere** [comment]
I'm open to suggestions, but in the meantime, `bibtex[referentype=something]` will do the trick.

**Comment by retorquere** [comment]
(I'm serious about the unicode stuff BTW, I really don't know what the failure you are experiencing is, exactly. Or approximately. Or at all, really.)

**Comment by adunning** [comment]
Zotero is supposed to normalize decomposed characters, but I think that was a more recent change that hasn't been applied retroactively to older entries (though I seem to remember reading something about plans to do this?). I can fix it very easily by simply retyping the last time with precomposed accents.
