### ISSUE TITLE
Single letter capitals are no longer preserved

### ISSUE THREAD

**Issue by QuLogic** [ZotPlus/zotero-better-bibtex#325]
I have a pair of articles named something like: `A clever title --- I. Theory` and `A clever title --- II. Numerical results`. This exports as `{A clever title --- I. {Theory}},` and `{A clever title --- {II}. {Numerical} results}`. When these go through BiBTeX, the first one ends up lower case, while the second is upper case.

I think this might have changed in the last week, maybe? I'm pretty sure this worked alright when my last bug was fixed.

**Comment by retorquere** [comment]
Sorry about that.

**Comment by QuLogic** [comment]
It's actually probably fine for author names like in the referenced tests above, but doesn't work for titles, unfortunately.

**Comment by retorquere** [comment]
That's OK. I can exclude authors later if so desired.
