### ISSUE TITLE
Command to force autoexport update

### ISSUE THREAD

**Issue by adunning** [ZotPlus/zotero-better-bibtex#330]
Updating my autoexported files takes a minute or two (library of going to both LaTeX and CSL JSON), which makes the 'On Change' option impractical. On the other hand, I occasionally want to make a change and immediately have it go reflected in a document; it would thus be useful to have a command somewhere that would manually trigger an automatic export.

**Comment by gracile-fr** [comment]
I second this request. Sometimes the automatic export (on change) doesn't seem automatic, and I delete, then re-create the automatic export. Having a button or a configurable keyboard shortcut would help.

**Comment by retorquere** [comment]
How big a library is this? The cache should be able to handle fairly big libraries. 

I'll look at manual triggering. But how did you get CSL JSON into the auto exporter? Its not supposed to get there, and I would reckon it's slow since it doesn't use either the serialization or the output cache.

**Comment by retorquere** [comment]
@gracile-fr that's what the "mark" button does.

**Comment by adunning** [comment]
I meant Better BibLaTex and Pandoc JSON. Library has 3083 items.

**Comment by retorquere** [comment]
I'll look into manual export, but it's not as trivial as you might think given the current infrastructure. Just out of curiosity, how long does each take, approximately?

**Comment by gracile-fr** [comment]
Mark = update ?

**Comment by retorquere** [comment]
The terminology isn't great (I just pushed a change), but it's really more like "schedule" than it is "update" (I had meant it to signify "mark for export"). The auto-exports are asynchronous, triggered either by an idle event or an item change, at which time it starts exporting.

**Comment by retorquere** [comment]
It's not terribly pretty, but could you give http://tempsend.com/6F8E93D569 a whirl?

**Comment by gracile-fr** [comment]
But once it's scheduled/marked, how the export is triggered?

**Comment by retorquere** [comment]
@gracile-fr in the released version it simply marks the auto-export as needing an export; the actual export won't happen until the trigger comes, either any change if you have it set to "on-change", or on idle when you have it set to "idle". If you have it "off", it doesn't export at all. The one at tempsend kicks off forced exports regardless of that setting.

**Comment by gracile-fr** [comment]
ok, I thought the tempsend was for adunning. I've just tried it. Forced exports work.
But there's a strange bug: a bunch of "p" in are deleted on export! (tested with zotero 4.28.2-beta.r2+a7c2506)

**Comment by retorquere** [comment]
"a bunch of 'p'"?

**Comment by gracile-fr** [comment]
the letter "p" : in Zotero fields containing the letter "p". They're stripped on export.
Json: <code>"title": "De la « participation du public » à la « démocratie participative » ?",</code>
Bib: <code>title = {De la «articiation duublic » à la « démocratiearticiative » ?},</code>

**Comment by retorquere** [comment]
That is unexpected. Does this also happen on 4.0.28.1?

**Comment by gracile-fr** [comment]
No, it's doesn't happen on 4.0.28.1 - probably a different issue.
With 4.0.28.1, the auto-export doesn't work though. It appears as "force" in the list, but the bib file hasn't been updated.

**Comment by retorquere** [comment]
Do you see an error in the log? For me it changes to "done" almost instantly on my test library.

**Comment by gracile-fr** [comment]
Console Log of Firefox?

**Comment by retorquere** [comment]
No, the Zotero debug log

**Comment by gracile-fr** [comment]
Nothing related to zotero/BBT.
But I tried to create a new export with "Keep updated" checked: zotero is frozen with the BBT Export bar.

**Comment by gracile-fr** [comment]
Close/reopen Zotero. Everything is blank, error message on startup: A Zotero operation is currently in progress. Please wait until it has finished. :-((
BBT ID: UZMRNETU

**Comment by gracile-fr** [comment]
(I've closed zotero in firefox, where I had installed the tempsend version, opened Standalone with vanilla BBT, everything looks ok. But the created auto-export appears as "done" even if the bib file doesn't actually exist on my system…)

**Comment by retorquere** [comment]
The error in that log is a little strange, it seems to indicate the preference pane has non-node children; I don't even know how that can be possible. There are no further errors in the log -- perhaps if extended logging is turned on (extensions.zotero.translators.better-bibtex.debug) there is more. 

The "done" means Zotero has told BBT the export is finished. A whole load of whacky is going on. Does the released BBT still load OK?

**Comment by gracile-fr** [comment]
With Zotero for Firefox and the released version of BBT, no problem to create a new export with keep updated. report: ISIZVSX4
Then an attempt to schedule the newly created export (which appears as pending): 57D9UABI.

Hope that helps. I might try again the tempsend version if you want, but with another FX profile which I need to create… tomorrow !

[It's like I've hijacked @adunning issue]

**Comment by retorquere** [comment]
Nothing strange in those logs. What does "aucun élément trouvé" mean?

**Comment by gracile-fr** [comment]
No item found

**Comment by retorquere** [comment]
Bugger, I was hoping google translate missed some subtleties. It's the only error present in the log, I had hoped it meant something. Tomorrow I'll have at it again -- gotta get some sleep.

**Comment by retorquere** [comment]
How about http://tempsend.com/168B841EBC ?

**Comment by gracile-fr** [comment]
Works well. Three "forced" exports: J2M48WCJ

**Comment by retorquere** [comment]
The prefs pane still fails to refresh because the list of export has non-node children. I don't even know how that's possible, but at least the `try` will keep it from failing. Tests are running, I'll merge and release when they pass.

It's no longer "forced" BTW, just forced. Clicking that button no longer schedules an export but simply performs one outside the scheduling logic from the auto-exports.

**Comment by gracile-fr** [comment]
Thanks. 
>It's no longer "forced" BTW, just forced
The UI label is no longer "forced" indeed, but I didn't know how to call that.

**Comment by gracile-fr** [comment]
There's one annoying little thing in the UI: if I have an auto-export set, and create another auto-export, in the export list, they both appear. But if I click Refresh, the auto-export which I just created appears twice in the list…
Generally speaking, the Refresh button had a strange behaviour before this change.

**Comment by retorquere** [comment]
Is that still the case after the release? The refresh threw errors before, I'm still trying to find out how to succesfully clean out the export list.

**Comment by gracile-fr** [comment]
Yes. SVFTMA9F (created another auto-export, went to BBT prefs, clicked Refresh twice).

**Comment by gracile-fr** [comment]
But if you can't reproduce that, it might be a sequel of yesterday's attempt (something stored in the prefs file…?)

**Comment by retorquere** [comment]
No errors in the log. What about http://tempsend.com/85FF7196DC ?

**Comment by gracile-fr** [comment]
Perfect!

**Comment by retorquere** [comment]
Alright, so nested trees act funny. Gone they are.

**Comment by retorquere** [comment]
I'll cut a new release when the tests go green.

**Comment by phretor** [comment]
@retorquere I'm still unable to see autoexport working. I've triggered the export in many ways (e.g., modifying an item in the collection) but I keep seeing it as "pending". Only when I click on "export" it actually does the export.

**Comment by retorquere** [comment]
No worries, glad it's working for you.
