### ISSUE TITLE
Feature Request: Option to set filename to citekey

### ISSUE THREAD

**Issue by llorracc-git** [ZotPlus/zotero-better-bibtex#332]
Non-uniqueness is a perennial problem for both citekeys and filenames for the pdfs of papers.  Why not solve both problems by adding an option always to rename the pdf to have a filename identical to its citekey?  

(I'm doing this manually now; Zotero's built-in auto-renaming facility allows formulaic renaming but does not permit inclusion of the citekey as one of the elements in the formula).  

Among the advantages of this is that, when a library is exported (per feature request #126), it will be easy to find the cited paper on the local computer (e.g., for offline use).

PS.  Maybe this needs to be delayed until the (eagerly awaited) moment when you will change the system from the hand-generated citekeys having to be created using the "Extra" field?

**Comment by retorquere** [comment]
This is already possible by installing Zotfile in addition to BBT; when both are installed, Zotfile has access to the cite key using the pattern "%b".

**Comment by retorquere** [comment]
This will work BTW regardless of whether you have set a manual cite key in "extra"; Zotfile will pick up the auto-generated key too.

I have no other option than to use the "extra" field (although you can have BBT do it for you by right-clicking on the reference and selecting "generate BibTeX key"). I have been told by the Zotero devs in no uncertain terms that I should not attempt to use any other field. If I want the manually set cite keys to sync (which I do), my hands are tied on this one. Syncable fields for extensions are supposed to get some love after Zotero 5.0 drops, but I don't know when that is, and BBT is going to require a massive rewrite (as will all Zotero extensions) to cope with the changes made to Zotero in 5.0.

**Comment by llorracc-git** [comment]
Thanks, I hadn't realized that.


ᐧ

On Mon, Aug 31, 2015 at 9:10 AM, retorquere <notifications@github.com>
wrote:

> This is already possible by installing Zotfile in addition to BBT; when
> both are installed, Zotfile has access to the cite key using the pattern
> "%b".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZotPlus/zotero-better-bibtex/issues/332#issuecomment-136366666>
> .
>



-- 
- Chris Carroll

**Comment by llorracc-git** [comment]
That's too bad; but I guess other developers are in the same position.
I've refrained from adding the "Zotero Scholar Citations" for fear that
when it puts the number of citations in the "Extras" field it might
interfere with your bibtex entry; but maybe it just adds on to the contents
of the extras field (say, with some delimiter to separate it from the
bibtex: entry), and no harm will be done?
ᐧ

On Mon, Aug 31, 2015 at 9:17 AM, retorquere <notifications@github.com>
wrote:

> This will work BTW regardless of whether you have set a manual cite key in
> "extra"; Zotfile will pick up the auto-generated key too.
>
> I have no other option than to use the "extra" field (although you can
> have BBT do it for you by right-clicking on the reference and selecting
> "generate BibTeX key"). I have been told by the Zotero devs in no uncertain
> terms that I should not attempt to use any other field. If I want the
> manually set cite keys to sync (which I do), my hands are tied on this one.
> Syncable fields for extensions are supposed to get some love after Zotero
> 5.0 drops, but I don't know when that is, and BBT is going to require a
> massive rewrite (as will all Zotero extensions) to cope with the changes
> made to Zotero in 5.0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZotPlus/zotero-better-bibtex/issues/332#issuecomment-136368455>
> .
>



-- 
- Chris Carroll

**Comment by retorquere** [comment]
Everyone is in the same position, multiple authors are waiting for syncable
fields.

I don't know how ZSA handles the extra field, but unless it actually picks
a random position in the middle (hardly plausible), it should be fine. BBT
does its own fencing.

**Comment by retorquere** [comment]
Is this issue handled to your satisfaction?

**Comment by retorquere** [comment]
(assumed handled)

**Comment by llorracc-git** [comment]
Yes, many thanks.
ᐧ

On Tue, Sep 1, 2015 at 8:38 AM, retorquere <notifications@github.com> wrote:

> Is this issue handled to your satisfaction?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZotPlus/zotero-better-bibtex/issues/332#issuecomment-136700822>
> .
>



-- 
- Chris Carroll

**Comment by llorracc-git** [comment]
Thanks -- I've posted one more comment, to the original (closed) thread
#126, as follows:

I've got all of this working (including the renaming of filenames to match
the citekey) so that the desired workflow at the top ALMOST works
perfectly.

If my export directory is ExpDir, my bibfile is Exp.bib, and the
citekey-and-pdf-name is myPaper, the entry for myPaper in Exp.bib is

File                     = {MyPaper.pdf:/MyPaper.pdf:application/pdf}

which JabRef interprets literally as saying that the file is in my root
directory /.

This can be fixed by hand by adding the comment

@comment{jabref-meta: fileDirectory:.;}

to the Exp.bib file.  But I can't figure out any way to automatically add
that comment to the file.  And, having to do it by hand every time I
(automatically) export, or every time I use the bib file, kind of defeats
the purpose (which is to have a fully automatic process).

I guess this seems like maybe a question for the ZotFile developer, but the
context comes from this thread so I'm posting here.

ᐧ

On Wed, Sep 2, 2015 at 3:27 AM, retorquere <notifications@github.com> wrote:

> (assumed handled)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZotPlus/zotero-better-bibtex/issues/332#issuecomment-136960942>
> .
>



-- 
- Chris Carroll

**Comment by retorquere** [comment]
That seems like a bug to an existing feature of BBT, could you please open a new issue?

**Comment by llorracc-git** [comment]
Would it make more sense to reopen the original issue #126, and have me add
it there (actually, I already did add it as a comment, but then thought to
send you the email because earlier in the thread you mentioned that you
rarely look at "closed" issues)?

The reason to reopen rather than create a new issue is that (if I
understand the thread correctly) the BBT feature in question is invoked
only in the very specific context described in detail in issue #126?  My
understanding is that you check to see whether a file with the given
citekey already exists in the target directory, and if so you emit the
relative rather than the absolute path.

PS.  It would be extremely useful if this feature could be tweaked so that
it was possible to look in a predefined subdirectory of the target
directory.  That way, using a symbolic link, it would be possible to have a
single master library of all one's PDFs in a predefined location, and for
each project one could have a project-specific bibfile.  Should I add that
as a request to the original "comment"?

ᐧ

On Wed, Sep 2, 2015 at 9:32 AM, retorquere <notifications@github.com> wrote:

> That seems like a bug to an existing feature of BBT, could you please open
> a new issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZotPlus/zotero-better-bibtex/issues/332#issuecomment-137080796>
> .
>



-- 
- Chris Carroll

**Comment by retorquere** [comment]
I prefer a new issue. The original issue was a feature request handled the the requestors satisfaction. It also screws up the change log to re-open issues.

The second thing you mention is a feature request, for which I'd strongly prefer again a separate issue. It just makes it easier for me to weigh my work.

**Comment by retorquere** [comment]
Re-opening old issues also means I have to scroll through the whole history every time I look it up, where the history of building the enhancement is not really relevant to fixing this bug.

**Comment by tjallemaal** [comment]
can anybody tell me if i can reanme pdf according to citekeys? 
i am using zotero 5 here. i've inserted {"b": "citekey"} in the config editor,
but its not working.
am i missing something??
would be pure butter in terms of workflow ...
greetz,

halem

**Comment by retorquere** [comment]
You'd have to ask the zotfile developer(s?).

**Comment by tjallemaal** [comment]
sorry, i had the right thread open >.< 
ive read someone say %b  seems to work? let's see
looking forward to having an ios app really

**Comment by retorquere** [comment]
BBT patched Zotfile in the past but at some point it got into a nasty loop that would crash Zotero, so I've taken that out. If Zotfile wants to read the BBT database this is safe and easy, and I'll show them (him? her? I don't know really) how to do it.
