### ISSUE TITLE
preserve BibTeX Variables does not check for null values while escaping

### ISSUE THREAD

**Issue by willuxwil** [ZotPlus/zotero-better-bibtex#337]
ID: NRZU9WJX

in the last few months, this plugin is working really nicely. And thanks a lot for providing this amazing plugin which save me a lot time and effort for writing with latex.

Currently I am running into trouble with the plugin as continues error shows up which might first caused by big file size? After I update my library with some big books and lots of items, I discovered that this plugin is crashing. 

error like this "[JavaScript Error: "value is undefined" {file: "F:\zotero\translators\Better BibTeX.js" line: 3872}]"

the line 3872 which is "Translator.preserveBibTeXVariables && value.match(/^[a-z][a-z0-9_]*$/i);"

does this is cause by the empty field or multiple files or other things? Do you have a clue?

Thank you again.

regards,

Wil

**Comment by retorquere** [comment]
1.3.1 is out.

**Comment by willuxwil** [comment]
thanks for the updates and it work right now. really appreciate it!

**Comment by retorquere** [comment]
Always a pleasure, and thank you for reporting the issue. I've added a test
to prevent regression.
