### ISSUE TITLE
Fields missing when exporting an entry

### ISSUE THREAD

**Issue by benblamey** [ZotPlus/zotero-better-bibtex#343]
Fields seem to be missing when exporting a collection in "Better BibLatex" Format.

The test collection contains 1 entry,
exporting as default biblatex produces expected output.
exporting as "better biblatex" produces an entry with all of the fields missing.

The gist contains:
(1) zotero RDF export of the collection
(2) better biblatex export showing bug.
(3) default biblatex export showing expected output.

https://gist.github.com/benblamey/765c9fb20f751990ae33

**Comment by retorquere** [comment]
When I export that entry using Better BibLaTeX, I get

```
@book{last2015,
  title = {test title},
  volume = {1},
  timestamp = {2015-09-11 22:24:54},
  series = {1},
  author = {last, first},
  date = {2015}
}
```

could you do the following for me:

* Enable "extended debugging" in the BBT preferences
* Select this entry in your library and export it using Better BibLaTeX
* Select this entry in your library, right-click, and select "send ZotPlus report"
* Post the resulting ID displayed when you click through here

**Comment by benblamey** [comment]
Report ID: 8RXZZZRU

**Comment by retorquere** [comment]
There's nothing in the error log. Sometimes other firefox extensions interfere with BBT (there are at least 3 I know of), but before we look at that, could you try going into BBT prefs first, go to the debug section, and click "reset cache"? I still don't know how these entries got into your cache (this is not a format BBT exports as far as I can tell), but we'll look at that later. The same goes for #344.

**Comment by retorquere** [comment]
I can tell your cache is off, that's in the debug info -- I'm just not sure about the way that bibtex got into your cache in the first place, so I don't know yet it will not simply regenerate and recache that broken bibtex.

**Comment by retorquere** [comment]
Please don't reset the cache yet! See #344 -- I want to know what's behind the cache not updating.

**Comment by benblamey** [comment]
FYI -- could this relate to running Zotero standalone at the same time as running it in the browser? Is this usage supposed to be supported? (I might have been doing this at the time of the original import)

**Comment by retorquere** [comment]
Yes, it could in principle relate to such; the behaviour of BBT under that scenario is non-deterministic; it's unpredictable at what exact point it will break. 

I do want to support it but it's not currently supported, so I don't have an unequivocal answer to your second question, sorry.

**Comment by retorquere** [comment]
Resetting the cache (while not in connector mode) should fix your issues.

**Comment by benblamey** [comment]
Resetting the cache, without running Zotero standalone in the background worked. Thank you.

**Comment by retorquere** [comment]
My pleasure as always.
