### ISSUE TITLE
Soft citation key value changes when author tab is switched from single to double field form

### ISSUE THREAD

**Issue by gtoubekis** [ZotPlus/zotero-better-bibtex#349]
Report ID CPGAFQVV
When changing the author tab fom single to double (and vice versa) the soft bibtex citation key value changes.
Citation Key format  is set to [auth][year][0]  resulting in keys like eg. Falkingham2014. 
When changing the author tab from [Falkingham][Peter L.] to [Peter L. Falkingham] the soft key changes as well and becomes - PeterL.Falkingham2014 although citation key format is not altered.
Has been tested with various Jabref Key patterns, all show same behaviour.
Pinning of citation key can be performed, leading to misconfigured Citation Keys. eg. N-authors can be mixed with combination of last name, given names according to author tab setting.

**Comment by retorquere** [comment]
I don't quite follow. The soft key is expected to change when you change the author. Can you give me an example of what you expect/want but don't get?

When you change from double to single, Zotero doesn't tell me what the last name is, it just gives me "name", so I couldn't even keep the citation key the same if I wanted to.

**Comment by gtoubekis** [comment]
ok, I understand now that the zotero author field does not distinguish first/last name - the GUI nicely makes a difference though.  I would have expected that the bibtex key [auth][year] would keep stable, (auth understood as LAST name of author).  Changing the zotero author tab from double/single results in the below variants, although no "change of authors" took place. 

@article{YuHunter2013,
    author = {Yu, Chih-Hao and Hunter, Jane},
@article{Chih-HaoYuHunter2013,
		author = {{Chih-Hao Yu} and Hunter, Jane},
	}

@article{YuJaneHunter2013,
   author = {Yu, Chih-Hao and {Jane Hunter}},
 }

@article{Chih-HaoYuJaneHunter2013,
    author = {{Chih-Hao Yu} and {Jane Hunter}},
  }

Knowing that, I will keep an eye on display order of author names. Thanks for the very prompt reply.

**Comment by retorquere** [comment]
Hmm, now that you mention it, Zotero does seem to switch between the two pretty reliably. Let me see if I can reach into that.

**Comment by gtoubekis** [comment]
thanks for prompt reply. great piece of work, in any case!!

**Comment by retorquere** [comment]
Ah, no it doesn't really. If you switch from single to double field, it simply take the last "word" as the last name. That's a little too unreliable, certainly if you have a company name like Glaxo Smith Kline -- you wouldn't want that to become just "Kline".

Alway a pleasure. I'm sorry I couldn't be of more help.
