### ISSUE TITLE
BibLaTeX; export CSL override 'issued' to date or year

### ISSUE THREAD

**Issue by nickbart1980** [ZotPlus/zotero-better-bibtex#351]
From Zotero’s “Extra” field: `{:issued:2014-12-31/2015-01-01}`

export to pandoc CSL contains: `"issued":"2014-12-31/2015-01-01"`, ignoring/overwriting the content of Zotero’s “Date” field (which is useful, please don’t change that!)

When exporting to Biblatex, however, `{:issued:2014-12-31/2015-01-01}` is ignored, irrespective of whether Zotero’s “Date” field is empty or not.

Expected Biblatex, in both cases: `date = {2014-12-31/2015-01-01},`

BBT 1.4.6

**Comment by retorquere** [comment]
The CSL field mappings are added one-by-one as I find out their meaning. Could you do me a favor, right-click on the reference that has this, and "report zotplus error"? That will give me a ready-to-use testcase to add to my test set (prevents regressions).

Travis is having some issues so I can't release new versions right now, but it will be out in the next version as soon as that clears (and tests pass, of course).

**Comment by nickbart1980** [comment]
Ok, Report ID: HEE4J82M

A much nicer solution would be:
- for biblatex: Test whether string in `{:issued: …}`, `{:accessed: …}` etc. matches a biblatex (=EDTF Level 0) date or date range. (Biblatex manual: “The date fields … require a date specification in yyyy-mm-dd format. Date ranges are given as yyyy-mm-dd/yyyy-mm-dd. Partial dates are valid provided that date components are omitted at the end only. You may specify an open ended date range by giving the range separator and omitting the end date (e. g., yyyy/).”) When matching, export to the biblatex `date` field; if not, export to the biblatex `year` field (which, unlike `date`, can be used for literal/free-form date strings).
- for “Pandoc JSON”: Same test. When matching, reformat date or date range according to CSL specs, e.g., `{ "issued": { "date-parts": [ [ 2014, 12, 31 ], [ 2015, 01, 01 ] ] } }`; if not, export to a “literal” element, e.g., `{ "issued": { "literal": "13th century" } }`. See [citeproc-js specs](http://gsl-nagoya-u.net/http/pub/citeproc-doc.html#dates).

**Comment by retorquere** [comment]
I've added the enhancement as #352
