### ISSUE TITLE
Parse key-value pairs into Pandoc-CSL fields if the key is a CSL value

### ISSUE THREAD

**Issue by retorquere** [ZotPlus/zotero-better-bibtex#354]

**Comment by retorquere** [comment]
All vars are parsed out now (https://github.com/ZotPlus/zotero-better-bibtex/blob/master/resource/translators/translator.coffee#L48), but not all are put back into the Bib(La)TeX output. Leaving this open for feedback.

**Comment by nickbart1980** [comment]
Great. When/how will this be rolled out? Regular release? Or is there a dev version?

A few, e.g. those that are available in all Zotero entry types would not be neccessary, e.g., title and title-short. Will have a look.

I’ll also have a look at the biblatex side later.

**Comment by retorquere** [comment]
As soon as it does something halfway useful, it goes out. I don't really do dev releases. Removing vars would be easy, just commenting them out of the cslvars list would do it.

**Comment by nickbart1980** [comment]
I’d be great if you added `volume-title` (not official CSL yet, but everyone’s in favour, and both citeproc-js and pandoc-citeproc have implemented it already).

**Comment by retorquere** [comment]
I'll just add new behaviour as we come across it (on a new issue, please)
