### ISSUE TITLE
How to auto adjust the order of multiple attachments in the field "file" when a paper is exported

### ISSUE THREAD

**Issue by guantau** [ZotPlus/zotero-better-bibtex#355]
A paper is attached with multiple files, i.e. a snapshot and a pdf file. When I export this paper to a bibtex file, I want the pdf file always to be the first one in the field "file". Because when I import the bibtex file into JabRef, I can't open the corresponding pdf file if it is not in the first place in the field "field". But BBT sorts the attachments in the alphabetic order. As the following picture shows

<img width="778" alt="2015-09-22 20 56 20" src="https://cloud.githubusercontent.com/assets/7569393/10018860/734cd790-616c-11e5-9d92-6820178bccee.png">

So I wonder how can I solve this problem. Thank you very much!

**Comment by retorquere** [comment]
Can you try whether http://tempsend.com/3E854136CC does what you want?

**Comment by guantau** [comment]
Hi, retorquere. It makes no difference.

**Comment by retorquere** [comment]
Can you right-click on that reference, select "send zotplus error", and post the debug ID here?

**Comment by guantau** [comment]
The report ID is 3NRT85U2.
