### ISSUE TITLE
Export single-field names as “literal”

### ISSUE THREAD

**Issue by nickbart1980** [ZotPlus/zotero-better-bibtex#357]
BBT “Pandoc JSON” exports single-field names as `family`:

`"author":[{"family":"United Nations","given":""}]`

It should export them like Zotero’s “CSL JSON” exports them, i.e. `literal`:

```json
		"author": [
			{
				"literal": "United Nations"
			}
		],
```

See also http://gsl-nagoya-u.net/http/pub/citeproc-doc.html#names.

**Comment by retorquere** [comment]
Do you have a testcase for this? I like to add a testcase per issue handled.

**Comment by retorquere** [comment]
Ah, hold on, this needs to be handled in the Zotero CSL converter. The conversion from Zotero reference to CSL item loses the author order when multiple author types are present, so I can't safely match creators between the two to fix this after Zotero has done its work. I'll see if I can generate a pull request for Zotero.

**Comment by nickbart1980** [comment]
> … testcase …

How do you want the Zotero side of things represented?

> … Zotero CSL converter …

I don’t quite understand: Zotero itself gets this right (according to the specs) when exporting to "CSL JSON".

**Comment by retorquere** [comment]
You're right. Strange. I'll look into it (I have a testcase, but the "BetterBibTeX JSON is the preferred testcase format).

**Comment by retorquere** [comment]
(strange because I use that CSL converter too)

**Comment by retorquere** [comment]
Got it. Damn, that's going to be tricky. The CSL-JSON converter exposed to the translators broke protocol, and I can't easily change that without disabling the cache for Pandoc JSON.

**Comment by retorquere** [comment]
Yeah, this is going to require a full overhaul of the caching system. Zotero changed their translator internals in 4.0.27 but left in place a legacy mode which I simply inherited (and consequently stored in the cache); but the internal item to CSL-JSON converter only works with non-legacy items, so I need to start caching non-legacy items, and since this is a shared cache, everything needs to be updated. Not impossible, but not a quicky.

**Comment by retorquere** [comment]
OK, I have this fixed (and the overhaul would have to be done at some point anyway), but one testcase is still failing which is related to #348.
