### ISSUE TITLE
Option to omit square brackets for Pandoc Citation

### ISSUE THREAD

**Issue by adunning** [ZotPlus/zotero-better-bibtex#358]
This is an extremely minor thing: I've been finding that, more often than not, the brackets are not desirable when copying a Pandoc Citation out of Zotero: they're not needed when doing a citation with the author's name in the text, adding something another citation to an existing group, or listing references for the `nocite` mechanism. It only takes one keystroke to add a set of brackets in an editor before pasting the keys, whereas removing them requires several.

I would thus suggest making the default to omit the brackets, assuming there isn't a way to make this an option. (But I would keep the semicolons between multiple citation keys in all cases.)

**Comment by adunning** [comment]
Many thanks!

**Comment by retorquere** [comment]
Always a pleasure.
