### ISSUE TITLE
Date export to “Pandoc JSON”

### ISSUE THREAD

**Issue by nickbart1980** [ZotPlus/zotero-better-bibtex#360]
Just downloaded 1.4.7. Great. But it seems two things I was expecting based on the discussions here are missing; both concerning “Pandoc JSON” export:

(1) Just looking at `original-date` (I did not check all other variables yet): It appears in the output only if, in Zotero’s “Extra” field, the `{:original-date: 1777-07-27/1888-08-28}` syntax is used, not if it’s the newline-separated `original-date: 1777-07-27/1888-08-28`. 

It also appears as `"original-date": "1777-07-27/1888-08-28",`, but since it’s an EDTF Level 0 string, it should be properly parsed:

```json
      "original-date": {
         "date-parts": [
            [
               "1777",
               07,
               27
            ],
            [
               "1888",
               08,
               28
            ]
         ]
      },
```

(2) With an EDTF Level 0 string, e.g., `1985-04-12/1986-06-25`, in Zotero’s “Date” field, it’s still only the start date that gets exported. Expected, of course:

```json
      "issued": {
         "date-parts": [
            [
               "1985",
               04,
               12
            ],
            [
               "1986",
               06,
               25
            ]
         ]
      },
```

**Comment by retorquere** [comment]
Can you get me a debug ID for a reference(s) (right-click reference(s), send zotplus error) that has the input for these? That will give me a testcase.

**Comment by retorquere** [comment]
Should years be strings BTW? Not numbers?

**Comment by nickbart1980** [comment]
> Should years be strings BTW? Not numbers?

I’m pretty sure numbers would work, too – I just copied the Zotero => CSL JSON output. If in doubt, ask @fbennett.

**Comment by retorquere** [comment]
I've found the problem (and thanks for the testcase, it has been added to the suite), but it unearthed another bug in the csl date parser. Not a hard bug, should be done soon.

**Comment by nickbart1980** [comment]
Nice. But we need

```json
"issued":{"date-parts":[[1999,9,23]]}
```
rather than

```json
"issued":{"date-parts":[1999,9,23]}
```

**Comment by nickbart1980** [comment]
Also, the date variables `container`, `event-date`, and `submitted` should be parsed, too.

**Comment by nickbart1980** [comment]
Open-ended ranges seem to work best with just the end *year* set to `0`:

```json
"issued":{"date-parts":[[1999,9,29],[0]]}
```

rather than

```json
"issued":{"date-parts":[[1999,9,29],[0,0]]}
```

**Comment by retorquere** [comment]
Do you have a testcase for those two?

**Comment by retorquere** [comment]
How do you distinguish between "/2000" and "0/2000" if I return only `[0]` ? I am trying to re-find the place where I saw the suggestion to return `[0,0]` -- I didn't think that up myself.

**Comment by retorquere** [comment]
Ah, here: http://gsl-nagoya-u.net/http/pub/citeproc-doc.html, see "To specify an open-ended range, pass nil values for the end elements:"

**Comment by retorquere** [comment]
That should have been "a testcase for those 3": single date, open-ended date range, and container, event-date, and submitted.

Thanks!

**Comment by nickbart1980** [comment]
It seems neither the [citeproc-js data input (aka CSL JSON) specs](http://gsl-nagoya-u.net/http/pub/citeproc-doc.html#data-input) nor the [biblatex manual](http://mirror.ctan.org/macros/latex/contrib/biblatex/doc/biblatex.pdf) define a representation of an open or unknown *start* date, so for the moment, we need not worry about that.

**Comment by retorquere** [comment]
Works best with what, in in what way better than `[0, 0]`? The citeproc docs say `nil` means `[0, 0]`. And the same goes, in principle, for `-200/` and `-200/0`. I'm not principally opposed to `[0]`, but if `[0, 0]` a) works, and b) is in line with the docs, then that has my preference, obviously.

**Comment by retorquere** [comment]
[citeproc-js data input (aka CSL JSON) specs](http://gsl-nagoya-u.net/http/pub/citeproc-doc.html#data-input) also states that "To specify an open-ended range, pass nil values for the end elements" (note the plural in elements).

**Comment by nickbart1980** [comment]
>  The citeproc docs say nil means [0, 0]. 

I am pretty sure the examples in the [citeproc-js data input (aka CSL JSON) specs](http://gsl-nagoya-u.net/http/pub/citeproc-doc.html#data-input) contain two `0`s just because the example’s start date happens to contain two elements, too. If in doubt, best ask @fbennett.

> Works best with what …?

`"issued":{"date-parts":[["2012","1",13],[0,0]]}` =>

> “Extended Date/Time Format (EDTF) 1.0 Submission.” 2012–. January 13–0.
http://www.loc.gov/standards/datetime/pre-submission.html.

`"issued":{"date-parts":[["2012","1",13],[0]]}` =>

> “Extended Date/Time Format (EDTF) 1.0 Submission.” 2012–. January 13–.
http://www.loc.gov/standards/datetime/pre-submission.html.

**Comment by retorquere** [comment]
I'll be curious to say what @fbennet thinks of it, but what would a two-value nil field look like? I can't make sense of that. It just says "nil" in the docs.

Which processor formats these samples? Citepoc-js or pandoc?

**Comment by retorquere** [comment]
What happens if you feed `"issued":{"date-parts":[["2012","1",13],null]}` or 
`"issued":{"date-parts":[["2012","1",13],[null]]}` to that processor?

**Comment by nickbart1980** [comment]
> Which processor formats these samples? 

pandoc. I never figured out how to run simple cli tests with citeproc-js.

> What happens if you feed `"issued":{"date-parts":[["2012","1",13],null]}` or
"issued":{"date-parts":[["2012","1",13],[null]]} to that processor?`

`pandoc-citeproc: Could not parse RefDate`

and 

`pandoc-citeproc: Could not read as string: Null`

**Comment by retorquere** [comment]
Bah. OK, if it's Pandoc, I'll grudgingly accept `[0]`. I still suspect it is a pandoc bug, but since currently the only target of the csl array format is pandoc, I have to take its quirks into account.

**Comment by nickbart1980** [comment]
3 testcases for single date, open-ended date range, and container, event-date, and submitted: 62PAKCDQ

**Comment by nickbart1980** [comment]
I’m not exactly happy about the choice of `0` for “nil” either, since some calendars, including ISO 8601 and EDTF, *do* have a year zero, but this is the format we have, for now …

**Comment by retorquere** [comment]
Can you check whether [source](https://github.com/ZotPlus/zotero-better-bibtex/blob/master/test/fixtures/export/Date%20export%20to%20Pandoc%20JSON%20%23360.json) and [result](https://github.com/ZotPlus/zotero-better-bibtex/blob/master/test/fixtures/export/Date%20export%20to%20Pandoc%20JSON%20%23360.csl.json) match your expectations?

**Comment by fbennett** [comment]
If I read correctly, does this issue start with a problem in the citeproc-js docs ("nil" values to specify an open-ended range)?

**Comment by retorquere** [comment]
@fbennet (thanks for dropping in -- you probably dread my name by now for the stress I've put on you of late), it starts and ends with this issue: how exactly an open date should be encoded. The docs suggest `[0, 0]`, pandoc wants `[0]`.

I (now) know JSON doesn't support `null`, but for any future updates, perhaps `''` or `0` would be better nullish values?

**Comment by retorquere** [comment]
@nickbart1980 what happens if you replace those earlier nulls with `''` or `0`?

**Comment by retorquere** [comment]
@nickbart1980 : can you alse get me a testcase for the `13th cent.` (and the expected result)?

**Comment by nickbart1980** [comment]
> what happens if you replace those earlier nulls with '' or 0?

`pandoc-citeproc: Could not parse RefDate`

Since EDTF *does* have a year zero, and Zotero is apparently toying with the idea of adopting the EDTF format, using a representation that distinguishes “zero” from “nil” would probably have advantages.

Maybe `{"date-parts":[[2012,1,13],["unknown"]]}` or `{"date-parts":[[2012,1,13],["open"]]}`?

Or is there anything else that would uniquely be understood as “nil” in JSON? pandoc-citeproc could certainly be patched …

**Comment by fbennett** [comment]
So I can get oriented, which docs are you referring to above (that suggest using `[0, 0]`). It's been a long long time since I looked at any other this, and I'm trying to get oriented.

Re other values for `null`, maybe `false`?

**Comment by nickbart1980** [comment]
> which docs are you referring to above (that suggest using [0, 0])

the [citeproc-js data input (aka CSL JSON) specs](http://gsl-nagoya-u.net/http/pub/citeproc-doc.html#data-input)

**Comment by fbennett** [comment]
Good, thanks, I have the picture now. I take it that Zotero itself is not producing these values from parsed input, since it doesn't support ranges yet. If so, they would be coming out of the date parser code from citeproc-js/Juris-M, which is only really used so far in one small project (mine). So the cost of changing that description will be very small. When I opened the doc to make the changes discussed yesterday, I realized that it could use quite a bit of revision (it was last properly updated in 2011); so a revision will be coming out, and changes to the date input specs for these unusual cases could be among them.

**Comment by nickbart1980** [comment]
Basically, @retorquere wanted to know whether it’s ok to use, for the time being:

```json
"issued":{"date-parts":[[1999,9,29],[0]]}
```

rather than

```json
"issued":{"date-parts":[[1999,9,29],[0,0]]}
```

**Comment by fbennett** [comment]
No objections here - but I don't have a very full understanding of the EDTF requirements; I'll follow your lead.

**Comment by nickbart1980** [comment]
> Can you check whether source and result match your expectations?

Looks good.

[EDTF](http://www.loc.gov/standards/datetime/pre-submission.html), however, would use `accessed: 2014-12-31~` rather than `accessed: ~2014-12-31`.

**Comment by retorquere** [comment]
@nickbart1980 You mean circa is a tilde at the end? I can do that.

@fbennet anything that is unambiguous is good. Aamof I like the format
returned by parsedatetoobject a lot better than the format returned by
parsedatetoarray. Internally, I add an "empty: true" or "empty_end: true"
for empty date range parts.

**Comment by retorquere** [comment]
Pandoc also consumes csl-json, so if the spec is going to change it'd be
good to involve them.

**Comment by fbennett** [comment]
It sounds like you've come across some discrepancies. When the dust settles, if you can give me a list of issues, I'll get in touch with them. For the time being, I'll leave the text as it is, to avoid additional confusion.

**Comment by retorquere** [comment]
I'll be happy to. I'm pretty happy with the current state of things, but I
do a little preprocessing and shortcuts for date ranges, edtf dates and
approximate dates (which suddenly became very easy to do), I'll be happy to
gift that back to juris-m if there's value in it for juris-m. I can't
exclude however that the assumptions in the preprocessor are biased towards
BBT's needs.

**Comment by retorquere** [comment]
@nickbart1980 I've added both '~' and '?' to the date handling, but only '~' is acted on right now.

**Comment by retorquere** [comment]
Tests are running (should pass, as the ypass locally, but still).

**Comment by retorquere** [comment]
Da

**Comment by retorquere** [comment]
Damn, I forgot about the "13th cent". What is the expected output of that?

**Comment by fbennett** [comment]
If it's the one from my examples list, it was put in there as something that will not parse, and returns its input on a "literal" segment (or was it "raw"? I forget). Bedtime here now, will pick up in the morning if you need more from me.

**Comment by retorquere** [comment]
It's literal, and it currently isn't returned as such by my code. Looking into it.

**Comment by nickbart1980** [comment]
@retorquere: Fantastic. This looks very good so far.

**Comment by retorquere** [comment]
I am to please (and I like puzzles)

**Comment by nickbart1980** [comment]
@fbennett:

I see only one genuine issue with the [citeproc-js data input (aka CSL JSON) specs] (http://gsl-nagoya-u.net/http/pub/citeproc-doc.html#data-input), and this is
years BC/BCE which – unfortunatly complicating things – are **not** identical to negative years.

The most widespread civil calendar and de facto international standard, the Gregorian calendar, neither has a year zero nor does it ever use negative years. Years before the “Common Era” are **always** designated by “BC” or “BCE”. The [Battle of Issus](https://en.wikipedia.org/wiki/Battle_of_Issus), e.g., occurred in November 333 BCE.

Negative years are used in [ISO 8601]([https://en.wikipedia.org/wiki/ISO_8601), [EDTF](http://www.loc.gov/standards/datetime/pre-submission.html), and [Astronomical year numbering](https://en.wikipedia.org/wiki/Astronomical_year_numbering), and all these calendars do have a year zero.

However, there is **no** commonly used calendar system without a year zero but with negative years – as currently used by CSL and citeproc-js.

I would recommend that citeproc-js should no longer use negative years to represent years BCE, but switch to unsigned year numbers in combination with a dedicated `BCE` flag, e.g., for “5 November 333 BCE”:

```json
{  "issued": {
      "date-parts": [
         [ "333", "11", "5", "BCE" ]
      ]
   }
}

```

or for 23 September 63 BCE – 19 August 14 CE:

```json
{  "issued": {
      "date-parts": [
         [ "63", "9", "23", "BCE" ]
         [ "14", "08", "19" ]
      ]
   }
}

```

This would be helpful to avoid confusion in general, and in particular when using the  citeproc-js data input (aka CSL JSON) format alongside EDTF, since calendars using BC/BCE (Gregorian) and those using negative years (EDTF) **differ by one year** for years BCE.

In ISO 8601, EDTF, and the astronomical calendar, the year 1 BC/BCE is numbered 0, the year 2 BC/BCE is numbered −1, and in general the year n BC/BCE is numbered –(n–1).

Hence in EDTF, the date and date range above are

```
-0332-11-05
```

```
-0062-09-23/0014-08-19
```

When converting back and forth between the citeproc-js data input (aka CSL JSON) format and EDTF of course we have to consider this one-year difference between the formats for years BCE.

(If you’d like to continue this discussion elsewhere, please let me know …)

**Comment by retorquere** [comment]
@nickbart1980 the negative years are just an internal format, it doesn't dictate how it should be represented to the user (but if we're going to change stuff, let's ditch the array format altogether in favour of the object format already used internally in the processor)

**Comment by fbennett** [comment]
Good point. Eventually, though (and soon, I-hope I-hope) there will be EDTF parsers for the languages in which citeproc engines are written, and the CSL JSON date format can sink from view.

@retorquere The 1000+ fixtures in the CiteProc test suite are written in the array format (which exists to save typing -- the fixtures were all written by hand). Projects that depend on them would be affected if they are changed to another (also non-standard) form. Wouldn't it be better to leave them as they are, warts and all, and convert them all to EDTF when the parsing of it is a reasonable burden to impose on developers?

**Comment by retorquere** [comment]
As a legacy format, sure, keep it, but 1000+ fixtures are easy to change to a new format with a fairly simple script; I wouldn't make that a breaking point.

**Comment by retorquere** [comment]
(and if we're going to save typing: I wouldn't miss "date-parts" going missing in lieu of something like "start"/"end")

**Comment by fbennett** [comment]
On Tue, Sep 29, 2015 at 5:50 PM, retorquere <notifications@github.com>
wrote:

> As a legacy format, sure, keep it, but 1000+ fixtures are easy to change
> to a new format with a fairly simple script; I wouldn't make that a
> breaking point.
>

Given that the work is already done, that cuts both ways, doesn't it?

**Comment by retorquere** [comment]
Absolutely. No complaints on keeping a legacy format, as long as it's not a
barrier to new developments :)

**Comment by nickbart1980** [comment]
I’m pretty happy about the way BBT handles of dates and ranges with AC/CE/positive years now.

However, **negative** EDTF dates are not parsed correctly yet.

I’d say we should go all the way here, and correctly map negative [EDTF](http://www.loc.gov/standards/datetime/pre-submission.html) years to [citeproc-js data input (aka CSL JSON)](http://gsl-nagoya-u.net/http/pub/citeproc-doc.html#data-input) (which uses BC/BCE conventions) years by adding `1` to the year’s absolute value.

Read the following as

```
String in Zotero’s “Date” field
actual “Pandoc JSON” export
expected “Pandoc JSON” export
```

---


```
-0333
"issued":{"date-parts":[[0],["333"]]}
"issued":{"date-parts":[[-334]]}
```

```
-0333/-0332
"issued":{"date-parts":[["333"],["332"]]}
"issued":{"date-parts":[[-334],[-333]]}
```

```
-0332-11-05
"issued":{"date-parts":[["332","11","5"],["332","11","5"]]}
"issued":{"date-parts":[["-333","11","5"]]}
```

```
-0062-09-23/0014-08-19
"issued":{"date-parts":[["62","9","23"],[14,8,19]]}
"issued":{"date-parts":[[-63,9,23],[14,8,19]]}
```

```
0000
"issued":{"literal":"0000"}
"issued":{"date-parts":[[-1]]}
```

```
-0001
"issued":{"date-parts":[[0],["1"]]}
"issued":{"date-parts":[[-2]]}
```

---

correct:

```
0001
"issued":{"date-parts":[["1"]]}
```

---

correct, or at least I can’t complain (because these are not EDTF dates):

```
-333
"issued":{"literal":"-333"}
```

```
-333/-332
"issued":{"literal":"-333/-332"}
```

```
-333/525
"issued":{"literal":"-333/525"}
```
