### ISSUE TITLE
Menu and title bar hidden after El Capitan update

### ISSUE THREAD

**Issue by mijalce** [ZotPlus/zotero-better-bibtex#363]
First, I am not sure that BiBtex add-on create this issue, but I can not disable it, thus I am posting this as question. 
I have this problem. I updated to El Capitan. After the update I lost the menu and title bar from Zotero Standalone. I also can not resize Zotero Standalone. I contacted Zotero support, but they informed me that everything is okay from their side and nobody else reported this issue (https://forums.zotero.org/discussion/52710/no-menu-bar-after-el-capitan-upgrade-zotero-standalone/#Item_5) 
I know that when the picker was developed, one of the things was to hide Zotero Standalone so the focus can be returned to Scrivener. To be honest I do not know did I had this issue before I used cmd+Y from Scrivener to invoke the Picker. Thus now I am just raising this as a question.
What I can do to help you to see is this issue related to the picker. 
Thanks!

**Comment by retorquere** [comment]
Can you get a debug log from the command line (see real-time section at
https://www.zotero.org/support/debug_output)?

**Comment by mijalce** [comment]
I follow the procedure, zotero started after the command, I added references through Chrome connector, called the picker from Scrivener, added citation, but no debug was generated. 
Here you can find the debug output (not real time)
https://www.dropbox.com/s/j6l9vgjytbixa4k/Debug%20output.txt?dl=0

**Comment by mijalce** [comment]
one more thing. On Zotero forums one more person reported this problem. From his print screen I can see that he is not using BetterBibTex, thus the problem probably is not BetterBibTex.

**Comment by retorquere** [comment]
I see no errors in the log, unfortunately. I've upgraded to EC myself, and ZS starts up without a hitch, BBT or not.

**Comment by retorquere** [comment]
I've joined the forum thread, I'll help where I can.
