### ISSUE TITLE
Possible change to default of Preserve Capitalization?

### ISSUE THREAD

**Issue by happydemic** [ZotPlus/zotero-better-bibtex#364]
Should the default of Preserve Capitalization be switched to 'All words with capitals'? (Currently it's 'inner capitals'.)

BibTeX's behaviour with capitals is quite a trap for newcomers arriving from Zotero, who may wonder why their usual sentence case .csl styles are suddenly producing all-lowercase item titles.

Would it be annoying for BibTeX veterans? I'm not aware of any .bib processors which preserve text in item titles 'as is', so would anyone be inconvenienced?

**Comment by retorquere** [comment]
I can't find this issue on GH anymore. Have you deleted it?

**Comment by retorquere** [comment]
Why does BibTeX do the downcasing anyway? I suppose there must be some reason for it; I'd love to know about that reason before I (further) interfere with it.

**Comment by happydemic** [comment]
To cause the maximum possible frustration to new users? :wink: 

Because it offers multilingual accuracy in title case. Titles are entered into your .bib with upper case for all words which should be capitalised in title case. Words which should be capitalised in sentence case go in braces. That way you are not reliant on the software to judge which words remain in lowercase in title case (e.g. 'of', 'the', etc.), as you are in the Zotero system.
