### ISSUE TITLE
“Pandoc JSON” should be "Better CSL-JSON"

### ISSUE THREAD

**Issue by nickbart1980** [ZotPlus/zotero-better-bibtex#369]
I’m not happy with the “Pandoc JSON” label, as it seems to suggest that this is a format for pandoc only while actually both Zotero and BBT export to the same “CSL JSON”  format (both following the [citeproc-js data input format specs] and the [CSL specs] on types and variables), the only difference being that BBT does a *much* better job here.

So I’d suggest using one of these:

- Better BibTeX CSL JSON
- CSL JSON (Better BibTeX)
- CSL JSON (BBT)

This would also mean changing the format string in the pull export url from `pandocjson` to `csljson` (since the pull export url contains `better-bibtex` anyway, the difference from Zotero’s CSL JSON seems clear enough).

I feel it would also be good to change the name of “BetterBibTeX JSON” to something that makes it clear that this a format different from CSL JSON, and possibly gives a bit of a clue what this format would typically be used for (I have to admit I’m not too sure myself).

[citeproc-js data input format specs]: http://gsl-nagoya-u.net/http/pub/citeproc-doc.html#data-input
[CSL specs]: http://docs.citationstyles.org/en/stable/specification.html

**Comment by retorquere** [comment]
Tests on the rename are running. "BetterBibTeX JSON" is an internal format I use for debugging, it's the format that is used if you submit a ZotPlus Error Report. It's just a dump of the Zotero reference as it is passed to the translators by Zotero plus the settings in use. I can't prevent it from appearing in the translators menu, but hardly anyone should want to use it directly. There's no relation to CSL-JSON, but JSON just means "JavaScript Object Notation", and it is in fact JSON-formatted data (just as CSL-JSON is), but JSON is like a broad qualifier like "text" or "xml".

**Comment by nickbart1980** [comment]
Great, seems to work as expected – though it took me a while to figure out that the format for pull export is now `BetterCSL-JSON`. 

`bettercsl-json`, the string the error message below seems to suggest, does not work, however. (Note the part `No translator bettercsljson` – is there a problem with the hyphen? The command used was `curl http://localhost:23119/better-bibtex/collection?/0/XXXXXXXX.bettercsl-json`.)

`Could not export bibliography '/0/XXXXXXXX.bettercsl-json': No translator bettercsljson; available: {"betterbibtex":"ca65189f-8815-4afe-8c8b-8c7c15f0edca","bibtex":"ca65189f-8815-4afe-8c8b-8c7c15f0edca","betterbiblatex":"f895aa0d-f28e-47fe-b247-2ea77c6ed583","biblatex":"f895aa0d-f28e-47fe-b247-2ea77c6ed583","latexcitation":"b4a5ab19-c3a2-42de-9961-07ae484b8cb0","pandoccitation":"4c52eb69-e778-4a78-8ca2-4edf024a5074","bettercsl-json":"f4b52ab0-f878-4556-85a0-c7aeedd09dfc","csl-json":"f4b52ab0-f878-4556-85a0-c7aeedd09dfc","betterbibtexjson":"36a3b0b5-bad0-4a04-b79b-441c7cef77db","bibtexjson":"36a3b0b5-bad0-4a04-b79b-441c7cef77db","bibtexaux scanner":"0af8f14d-9af7-43d9-a016-3c5df3426c98","collectednotes":"be78e3e1-c0b7-4bb6-affb-2d0bc1c19958"} from` […]

**Comment by retorquere** [comment]
Wait what? It should be just `csljson`.

**Comment by nickbart1980** [comment]
Ok, with 1.5.8, `csljson` seems to work. Thank you!
