### ISSUE TITLE
very slow export?

### ISSUE THREAD

**Issue by rdiaz02** [ZotPlus/zotero-better-bibtex#370]
Exporting my Zotero library (~ 3700 references, and several tens of collections) with BBT (using the Better BibTeX translator) takes about 7 to 11 minutes, during which Zotero is of course non responsive.  (I am exporting notes, but not files, and I am not using journal abbreviation; I am exporting collections recursively).

In contrast, using the bibtex exporter from Zotero gets the job finished in about 30 seconds. I guess this must be the export of the collections. Is this long delay unavoidable? Am I doing something wrong? (As it is now, I must disable automatic export, because both of "On change" and "When idle"  lead to unacceptable interruptions in workflow).

**Comment by retorquere** [comment]
Strange -- the export is heavily cached and should be at least on a par with the stock exporters. Can you select a few references (doesn't matter which), right-click, and select "send zotplus error"? That at least will show me whether the cache is filled for those.

**Comment by retorquere** [comment]
I've added a comparison which confirms what I had thought -- BBT is on a par (usually, but not structurally faster) with the stock translator. After the initial export at least (this is of 1241 items):

[Very slow at the start](https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/84961369#L551)

[But once the cache is filled, a little bit faster](https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/84961369#L555)

[than the stock exporter](https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/84961369#L559)

so there must be something that is either preventing your cache from filling, or which empties the cache. By specced behaviour, this should only happen if you regularly modify the majority of your references. That seems unlikely to me though -- I can't imagine you regularly changing 3.7k items)

**Comment by retorquere** [comment]
Could you do the following for me:

* install http://tempsend.com/5CE3147724
* Enable "extended debugging" in the BBT prefs
* perform two exports of ***the same part*** of your library using Better BibLaTeX. It doesn't matter what part, as long as it takes at least a minute or so to do, and the selection is not changed. A single collection should do the trick from what you tell me.
* right-click any one entry and select "Report ZotPlus Error"
* Click through that dialog and post the debug ID here

That will give me an idea of the cache activity on your installation

**Comment by rdiaz02** [comment]
This is the ID using BetterBibLaTeX:

WCX445BB

**Comment by retorquere** [comment]
Doesn't matter, I just needed something to exercise the cache, and both do. I don't know why yet, but you're not hitting the serialisation cache, and that will have an impact. Could you try http://tempsend.com/58B5CB80EF ? This one will almost guaranteed throw errors (they're non-damaging) on BibTeX export, but those errors will tell me interesting things. You only have to do the BibTeX export once this time before submitting a new error report.

**Comment by retorquere** [comment]
BTW after you  generated those errors and the debug report you can just download and install the latest release and you'll be back to your working-but-slow exports.

**Comment by rdiaz02** [comment]
Hummm.. I just tried it, and the second export was almost instantaneous. No errors. This is an ID, though:
49INM5MP

**Comment by retorquere** [comment]
That's because this time you consistently hit the export cache, but you still had 209 misses against 889 hits on the serialisation cache, which means things are still not as fast as they ought to be. You can see how your cache is doing in the BBT preferences; ideally, if you don't change anything, the cache misses should remain constant after the first export.

Still looking into possible causes. If you only export, and don't change anything, the cache misses on both caches shouldn't grow after the initial export, and then, even if you change references, the misses should only grow by the number of changes you made, and the clears should grow along.

**Comment by rdiaz02** [comment]
Ooops, when using this new version I did not enable extended debugg logging. Sorry!!! I'll enable it, and report (probably tomorrow, though).
I just checked the cache activity:
`{"input":{"clear":0,"hit":20968,"miss":4330},"output":{"hit":11673,"miss":0,"clear":0}}`

**Comment by rdiaz02** [comment]
On exporting the full library (about 40") after the enabled extended debugging this is one ID:
3FTGGFJB
with cache statistics as
`{"input":{"clear":0,"hit":8435,"miss":0},"output":{"hit":3891,"miss":0,"clear":0}} `

**Comment by retorquere** [comment]
Those stats are perfect. Super! I think I found the problem; attachments weren't being grabbed from the serialisation cache (the Zotero serialiser is incredibly slow). They are now, and look at 'em go! :)

[Tests are running](https://travis-ci.org/ZotPlus/zotero-better-bibtex/builds/85005103) -- when they go green, I'll cut a release.

Thanks for helping me debug!

**Comment by rdiaz02** [comment]
Thank you for the fixes! I just installed v. 1.5.8.

**Comment by retorquere** [comment]
Always a pleasure.

**Comment by Jmuccigr** [comment]
I am having this same problem. Just upgraded ZBB and now in the background Zotero is grinding away. Fans are going strong on my MBP running Mavericks. The 1.8MB export was far from instantaneous.

**Comment by retorquere** [comment]
Directly after an upgrade the cache is dropped. How is performance/cache stats after initial export?

**Comment by retorquere** [comment]
Also, after the initial export is done, do the cache misses (see debug pane of the prefs) flatline?

**Comment by Jmuccigr** [comment]
I'll make a change and see what happens. I have 2,750 items in my main library, with lots of attachments.

OK, here's the Cache activity after the first one:

{"serialized":{"clear":80,"hit":17,"miss":4848},"cache":{"hit":0,"miss":2750,"clear":100}}

The next one went quietly in the background. Here's the activity:

{"serialized":{"clear":107,"hit":4845,"miss":4859},"cache":{"hit":2749,"miss":2751,"clear":134}}

**Comment by retorquere** [comment]
That's more cache clears than I would have expected (I'll think about that one), but exactly the amount of cache misses I would have expected after a single reference change.

I'm sorry about dropping the cache after each (fairly frequent) update, but doing selective drops depending on the code changes got to be too difficult.

**Comment by Jmuccigr** [comment]
Ah, the stats are additive, so just one miss after I changed one entry and total-1 hits.

I don't mind the clearing after updates. I was getting massive cpu usage on every change before. I find Zotero slow enough on normal activity, so this was really bothering me.

Thanks!

**Comment by retorquere** [comment]
Yup. Still looking for a nice way to generate line graphs that show in better detail what's going on. As it is, it's just the status since start of Zotero (counts resets to 0 after you close).
