### ISSUE TITLE
this.stats is undefined

### ISSUE THREAD

**Issue by cazgp** [ZotPlus/zotero-better-bibtex#371]
When running an export on any collection (including a brand new one) I get a pop-up and "An error occurred while trying to export the selected file.". The browser log from running with autobibexport says `this.stats is undefined` cache.js:227:0.

Running latest Zotero (4.0.28.7) and 1.5.5. Exporting to Better-BibLaTeX. FF 38.3.0.

Have restarted FF, and also ensured that everything is up-to-date. I'm assuming this might be cache related? Is there a way to clear the cache?

**Comment by cazgp** [comment]
Found it and that fixed it. Maybe a more helpful error message? Try clearing the cache on error or something?

**Comment by retorquere** [comment]
There should be no need to clear the cache, the error simply shouldn't
occur. I'll look into it.

**Comment by retorquere** [comment]
Found it, release tests are running, 1.5.6 should be out soon.

**Comment by cazgp** [comment]
Legend! Thank you :D

**Comment by retorquere** [comment]
Thank you for reporting the error rather than giving up in frustration. Error reports are vital in keeping BBT healthy.
