### ISSUE TITLE
BBT CSL JSON: Do not use ‘shortTitle’ and ‘journalAbbreviation’

### ISSUE THREAD

**Issue by nickbart1980** [ZotPlus/zotero-better-bibtex#372]
BBT CSL JSON exports `shortTitle` and `journalAbbreviation` (just like Zotero CSL JSON does).

`shortTitle` and `journalAbbreviation` are not CSL variables. While citeproc-js understands them, pandoc does not.

`shortTitle` should be `title-short`; `journalAbbreviation` should be `container-title-short`.

See http://docs.citationstyles.org/en/stable/specification.html#appendix-iv-variables

**Comment by retorquere** [comment]
(you knew it was coming) can I bother you for a testcase?

**Comment by nickbart1980** [comment]
Sure :-) – 3FKQ56ND.
