### ISSUE TITLE
Podcast date

### ISSUE THREAD

**Issue by cazgp** [ZotPlus/zotero-better-bibtex#375]
This may be out the scope of the plugin, but Zotero still doesn't have a date field for podcast.
I've tried adding one by various combinations of `date` in the `extra` field, but it just shows up in `note`. 

Is there a way to do this?

Cheers!

**Comment by retorquere** [comment]
Several ways, in fact; see [Customized Exports](https://zotplus.github.io/better-bibtex/export.html). You can add literal Bib(La)TeX fields using the `bibtex[...]` or `bibtex{...}` formats, or you can add any of the date-ish [CSL variables](http://docs.citationstyles.org/en/stable/specification.html#appendix-iv-variables) in the format `{:varname: value}`.

**Comment by nickbart1980** [comment]
CSL variables: `varname: value` on a line of its own works, too.
