### ISSUE TITLE
not the same cite key with Zotero for titles with apostrophe

### ISSUE THREAD

**Issue by shahryareiv** [ZotPlus/zotero-better-bibtex#377]
From a title "Napoleon's retreat from Moscow", Zotero creates `northen_napoleons_1866` (note s after napoleon) but BBT , with `[auth:lower]_[veryshorttitle:lower]_[year]` creates `northen_napoleon_1866` (without s). I am not sure which is right solution ( 's can be part of a name in some situations?) but this inconstancy between Zotero and BBT creates problem if one wants to keep with both of them (specially if lots of cite keys have been used in works before)

**Comment by retorquere** [comment]
I will look into this particular case, but perfect synchronicity with
Zotero is not an explicit design goal, and concretely
undesirable/impossible in some circumstances. The main reason to set the
key pattern default this way is to ease transition into BBT.

**Comment by retorquere** [comment]
Oh BTW, can you right-click that reference and select "send zotplus
report"? That will give me a test case to work with.

**Comment by shahryareiv** [comment]
Thanks! Now I used your suggested pattern instead of my simple one:
```[auth:lower][Title:fold:nopunct:skipwords:select,1,1:lower:alphanum:prefix,_][year:prefix,_][0]```
and it does include the s in Nappleon's!
Anyway I sent the zotplus report. Thanks!

**Comment by retorquere** [comment]
I don't understand. You mean shorttitle does include the s where
veryshorttitle doesn't?

**Comment by retorquere** [comment]
Ah, wait, I think I might understand. I don't have access to my computer
right now, but it could be the case that veryshorttitle uses 1 word and
shorttitle uses 2, with the solitary s being treated as a single letter
word.

**Comment by shahryareiv** [comment]
Yes. I checked it again and the second pattern (yours recommended one) includes s but mine eliminates it.

**Comment by retorquere** [comment]
Super.
