### ISSUE TITLE
bibtex/biblatex capitalisation

### ISSUE THREAD

**Issue by nickbart1980** [ZotPlus/zotero-better-bibtex#379]
1. When exporting to bibtex and biblatex, words in Zotero title fields that contain capital letters are protected by enclosing them in braces (except the first word) – that’s fine.

2. Next, BBT should convert all titles to title-case if the ‘Language’ field is empty or starts with ‘en’, excluding, however, skip words, and strings enclosed in `<span class="nocase">…<span>`.
‘All titles’ means title, volume-title, container-title, collection-title, including their ‘short’ forms.
Titles in entries with a non-empty ‘Language’ field that does not start with ‘en’ should be left alone (see the notes on `\MakeSentenceCase`, biblatex manual 4.6.4, and compare the [man page](https://github.com/jgm/pandoc-citeproc/blob/master/man/pandoc-citeproc.1.md#titles-title-vs-sentence-case) of pandoc-citeproc, which has to do the inverse conversion when using a biblatex database – as would, BTW, any import of bib(la)tex into Zotero).
For bibtex, which does not have a langid field and thus cannot distinguish languages, I would guess that the complete title fields of non-English titles should be wrapped in braces to prevent bibtex from messing with capitalisation.

3. I don’t think a preference ‘Preserve capitalization’ is necessary at all (unless you are aware of users who say they never use biblatex styles that convert titles to sentence case [such as apa], and insist they do not want the extra braces).

4. Protecting two-field names, journal, magazine, and newspaper titles, location, publisher, institution, and organization fields etc., or parts of these is unnecessary on principle. (Only single-field names should be enclosed in one pair of braces, as currently [2.3.3], and in addition, literal ‘and’s in biblatex literal lists, i.e., institution, organization, publisher, location, origlocation, origpublisher, address and school should be wrapped in braces – or alternatively enclose the entire field in braces [2.3.4]).

**Comment by retorquere** [comment]
I have broken up your issue in 3 separate issues. If you need to enumerate concerns in a single issue, that's a strong indicator multiple separate issues are at play, and the discussion gets muddled really quickly this way.
