### ISSUE TITLE
CSL title, volume-title, container-title → BL title, booktitle, maintitle

### ISSUE THREAD

**Issue by nickbart1980** [ZotPlus/zotero-better-bibtex#381]
Books: If there’s a CSL volume-title, it should be mapped to BL title, and CSL title to BL maintitle.

Book chapters: If there’s a CSL volume-title, it should be mapped to BL booktitle, and CSL container-title to BL maintitle (CSL title continues to be mapped to BL title).

If you have pandoc installed, compare how pandoc-citeproc, inversely, maps these BL fields to CSL variables.

**Comment by retorquere** [comment]
Testcase?

**Comment by nickbart1980** [comment]
Testcase: NG929ANF

Expected:

```
@incollection{plato-republic-1902,
  location = {Oxford},
  title = {Republic},
  booktitle = {Clitophon, Republic, Timaeus, Critias},
  maintitle = {Opera},
  series = {Oxford classical texts},
  volume = {4},
  timestamp = {2015-10-17T11:40:45Z},
  publisher = {Clarendon Press},
  author = {Plato},
  editor = {Burnet, John},
  date = {1902},
  pages = {327--621},
  langid = {british}
}

@book{plato-opera-1902,
  location = {Oxford},
  title = {Clitophon, Republic, Timaeus, Critias},
  maintitle = {Opera},
  volume = {4},
  timestamp = {2015-10-17T16:58:22Z},
  series = {Oxford classical texts},
  publisher = {Clarendon Press},
  author = {Plato},
  editor = {Burnet, John},
  date = {1902},
  langid = {british}
}
```

**Comment by retorquere** [comment]
Looking at [this](https://github.com/ZotPlus/zotero-better-bibtex/blob/master/test/fixtures/export/BraceBalancer.bib), should that then be maintitle instead of booktitle? In addition to it?

**Comment by nickbart1980** [comment]
It all depends on whether there’s a `volume-title` on the Zotero/CSL side. If not, [this](https://github.com/ZotPlus/zotero-better-bibtex/blob/master/test/fixtures/export/BraceBalancer.bib) is ok as it is.

**Comment by retorquere** [comment]
I don't follow. Can you sketch what combinations of input would yield what combinations of output?

**Comment by nickbart1980** [comment]
- Books: 
    - If there is no CSL volume-title:  
     CSL title → BL title
    - If there is a CSL volume-title:  
     CSL title → BL maintitle  
     CSL volume-title → BL title

- Book sections: 
    - If there is no CSL volume-title:  
     CSL title → BL title  
     CSL container-title → BL booktitle
    - If there is a CSL volume-title:  
     CSL title → BL title  
     CSL volume-title → BL booktitle  
     CSL container-title → BL maintitle

**Comment by retorquere** [comment]
The Bib(La)TeX translators don't map CSL fields to BL fields, just Zotero fields to BL fields. Having BBT deal with CSL internally would require some major work (although I'd just wish Zotero would make the CSL format the internal format).

**Comment by nickbart1980** [comment]
Ok, then use the Zotero equivalents (Z booktitle = CSL container-title), but `volume-title` currently does not have a GUI field and can only appear embedded in the “Extra” field.

**Comment by retorquere** [comment]
I had to make a performance detour but will be picking up the capitalization again from now.
