### ISSUE TITLE
Capitalization: Don't caps-protect name fields

### ISSUE THREAD

**Issue by retorquere** [ZotPlus/zotero-better-bibtex#384]
@nickbart1980 says:

> Protecting two-field names is unnecessary on principle; only single-field names should be enclosed in one pair of braces, as currently [2.3.3].

**Comment by retorquere** [comment]
I already wrap `and` in braces (don't I?). So if I understand you correctly, names are treated differently from titles, in that they are not downcased by the bib processor then (otherwise caps protection would still be required to disclose user intent). But then why should one not just always do `{Lastname}, {Firstname}`? Seems much easier than the current caps preservation. In fact that then would maybe be the broader solution to `preserve caps = all`; just wrap the entire field in braces, no?

**Comment by retorquere** [comment]
And single-field names are also already enclosed in braces, right? So does this question then boil down to "don't caps-project name fields"?

**Comment by nickbart1980** [comment]
> But then why should one not just always do `{Lastname}, {Firstname}`?

To reduce clutter …

> I already wrap `and` in braces (don't I?).

Not in `publisher`, `location`, etc. But if that’s easier, just wrap the entire field in braces.

> So does this question then boil down to "don't caps-project name fields"?

It’s both about “don’t caps-protect anything except titles”, and “and-protect any literal ‘and’ biblatex might else parse as a literal-list separator”. Wrapping entire literal-list fields in braces would caps-protect them, too – which doesn’t hurt, but the aim is only to “and-protect” them.

**Comment by retorquere** [comment]
Ah, I indeed don't protect publisher, location, etc for `and`s. I didn't know they required that. But in any case, I'd only wrap the entire field if the user has selected the "all" version of preserve caps, not for inner.

Can you elaborate the `etc` when it comes to fields that require `and` protection?

WRT the preserveCaps, I currently have it on:

* place
* chapter
* edition
* title
* volume
* rights
* shortTitle
* conferenceName
* journaltitle
* book title
* journalsubtitle
* journal
* shortjournal
* booktitle
* titleaddon
* series
* institution
* publisher
* any kind of creator field

Which should go?

**Comment by nickbart1980** [comment]
> Can you elaborate the etc when it comes to fields that require and protection?

All biblatex literal list fields:  institution, organization, publisher, location, origlocation, origpublisher, address and school (see biblatex manual, “2.3.4 Literal Lists”).

**Comment by nickbart1980** [comment]
> WRT the preserveCaps, I currently have it on: … Which should go?

That list is a bit of a mix of CSL and biblatex?! – I’d *keep* only those fields whose name contains “title”, plus “series”.

**Comment by retorquere** [comment]
Sorry, I have Zotero-internal names in the list (place and conferenceName). I've updated the list.

**Comment by retorquere** [comment]
So journal(sub)title doesn't get protection?

**Comment by retorquere** [comment]
So to be clear, `author = {von Hicks, {III}, Michael},` should always be `author = {von Hicks, III, Michael},`?

**Comment by retorquere** [comment]
Instead of me just copy-pasting the lot here, could you look through https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/85899312 to see if these are indeed all desired consequences?

**Comment by retorquere** [comment]
https://travis-ci.org/ZotPlus/zotero-better-bibtex/builds/85905734 has only the diffs with caps protection removed. Could you go through that? It's a pretty big behaviour change.

**Comment by nickbart1980** [comment]
Sure, but I’m travelling, so it might take a while.

**Comment by nickbart1980** [comment]
https://travis-ci.org/ZotPlus/zotero-better-bibtex/builds/85905734: Most of this looks good.

- https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/85905735

    Actual:

    `+  institution = {Royal Veterinary and Agricultural University, Department of Animal Health and Animal Science, Division of Ethology and Health},`

    Expected:

    `+  institution = {Royal Veterinary {and} Agricultural University, Department of Animal Health {and} Animal Science, Division of Ethology {and} Health},`

- https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/85905736

    Actual:

    `title = {Problèmes d’organisation de l’{Administration} {[}1966-1967]},`

    Expected:

    `title = {Problèmes d’organisation de l’Administration {[}1966-1967]},`

    (non-English titles never need protection – I trust there’s some reason for using `{[}`?!)

- https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/85905737

    ok

- https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/85905738

    Actual:

    `+  publisher = {MIT Press ZKM/Center for Art and Media in Karlsruhe},`

    Expected:

    `+  publisher = {MIT Press ZKM/Center for Art {and} Media in Karlsruhe},`

**Comment by retorquere** [comment]
So I'm getting back to this now that #385 is done. Looking over all these changes, if `{X and Y}, {Firstname}` is effectivley the same as `X {and} Y, Firstname`, that format would make name formatting dramatically easier. Is it the same? Because if so, that would have my preference at this point.

**Comment by nickbart1980** [comment]
I’d say these two are equivalent – but note that `Firstname` never needs curly braces, it’s just literal `and`s in ‘name lists’ and ‘literal lists’ that need protection.

Corporate authors and editors – i.e., Zotero’s single-field names – on the other hand must always be wrapped in an extra pair of curly braces to prevent data parsing from treating them as personal names which are to be dissected into their components.

**Comment by retorquere** [comment]
But is it safe to wrap firstnames in braces? Looking to simplify the output algorithm, and bracing it would automatically handle edge cases.

**Comment by nickbart1980** [comment]
Actually, the two forms are **not** equivalent if two or more first names are wrapped in curly braces: 
in styles that abbreviate first names, `author = {Doe, John Paul}` is rendered as “Doe, J. P.” whereas  `author = {Doe, {John Paul}}` is rendered (incorrectly!) as “Doe, J.”.

So first names must not be wrapped in curly braces.

What are the edge cases you are worried about?

**Comment by retorquere** [comment]
I'm trying to find out whether it is always safe to use `author = {{Lastname}, Firstname, suffix and {Other}, Firstname}`. I don't know of any sensible samples, but if suffixes or firstnames can plausibly include `and` or `,` this wouldn't work.

Still, this algorithm might work:
1. Split name into Firstname, Lastname, and suffix (optional)
2. Convert each to LaTeX
3. Lastname = {Lastname}
4. Firstname = Firstname.replace(/\band\b/, '{and}').replace(',', '{,}')
5. suffix = suffix.replace(/\band\b/, '{and}').replace(',', '{,}')
6. output `{Lastname, Firstname, suffix}`

Does that sound reasonable?

**Comment by retorquere** [comment]
I'm looking at [your comment](https://github.com/ZotPlus/zotero-better-bibtex/issues/384#issuecomment-149200946) again; if I understand correctly, `institution` and `publisher` are name-ish fields, and the comment about `title` is really for #383.

**Comment by retorquere** [comment]
Would it be possible for you to assemble new test cases specifically for this issue? It would be cleaner than discussing the impact on existing cases. I'll deal with the existing cases when the cases specifically for this issue (and thus only relating to name-ish fields) pass.

**Comment by nickbart1980** [comment]
> “… name-ish …” 

Sort of: From the biblatex manual: “The Biblatex package implements three distinct data types to handle bibliographic data: name lists, literal lists, and fields.” – `institution`, `organization`, `publisher`, `location`, `origlocation`, `origpublisher`, `address` and `school` are literal lists, so literal “and”s must be protected as `{and}`, but biblatex is not trying to parse literal list elements into first, last, etc.

> “Would it be possible for you to assemble new test cases specifically for this issue?”

Yes, but I won’t be able to do much before the weekend.

> Still, this algorithm might work:

My comments below refer to Zotero two-part name fields; single-part name fields should just be wrapped in extra curly braces, no other parsing required.

> 1\. Split name into Firstname, Lastname, and suffix (optional)

1\. Split name into non-dropping particle, lastname, firstname, dropping particle, and suffix.

For biblatex: If any of the primary creators’ firstname fields in Zotero contains `!,`, add `juniorcomma=true` to the biblatex entry’s `options` field.

> 2\. Convert each to LaTeX

ok

> 3\. Lastname = {Lastname}

Why not like 4. firstname and 5. suffix?

\+ 3a. Only if in Zotero the lastname is wrapped in double quotes, wrap bib(la)tex lastname in curly braces.

> 4\. Firstname = Firstname.replace(/\band\b/, '{and}').replace(',', '{,}')
> 5\. suffix = suffix.replace(/\band\b/, '{and}').replace(',', '{,}')

ok, but do the same for non-dropping particle and dropping particle

> 6\. output {Lastname, Firstname, suffix}

output `{dropping-particle non-dropping-particle Lastname, suffix, Firstname}`

For biblatex: If any of the primary creators’ non-dropping particles is non-empty, add `useprefix=true` to the biblatex entry’s `options` field.

For bibtex it might make sense to output `{dropping-particle {non-dropping-particle Lastname}, suffix, Firstname}`.

**Comment by retorquere** [comment]
If treating firstname like 4/5, that's perfectly fine by me.

So the algorithm for two-part names then becomes:
1. Split name into non-dropping particle, lastname, firstname, dropping particle, and suffix.
2. Convert each to LaTeX
3. on all of those, brace `and` and `,`
4. Do not do any caps protection (OK so that's not a step, but let's just be clear on it not being a step)
5. output `{dropping-particle non-dropping-particle Lastname, suffix, Firstname}`
6. Profit

That is doable. I'll get to work on that.

For institutions etc, I'd prefer to have a separate issue and separate test cases.

**Comment by retorquere** [comment]
What should the algorithm do if the firstname is quoted? `["retorquere + nickbart1980"] [first, von]` converts into 
```
family: "retorquere + nickbart1980"
given: first
particle: von
```

Where those quotes are to be interpreted as "use literally"

 `["retorquere + nickbart1980"] [first, von]` should output `{von {retorquere + nickbart1980,  first}`, correct?

**Comment by retorquere** [comment]
Which would make the updated algorithm:

So the algorithm for two-part names then becomes:
1. Split name into non-dropping particle, lastname, firstname, dropping particle, and suffix.
2. Convert each to LaTeX
3. If it was quoted, surround with braces, if not brace `and` and `,`
4. Do not do any caps protection (OK so that's not a step, but let's just be clear on it not being a step)
5. output `{dropping-particle non-dropping-particle Lastname, suffix, Firstname}`
6. Profit

**Comment by nickbart1980** [comment]
> Which would make the updated algorithm: …
1. Split name into non-dropping particle, lastname, firstname, dropping particle, and suffix.
2. Convert each to LaTeX
3. If it was quoted, surround with braces, if not brace `and` and `,`
4. Do not do any caps protection (OK so that's not a step, but let's just be clear on it not being a step)
5. output `{dropping-particle non-dropping-particle Lastname, suffix, Firstname}`
6. Profit

Looks good. We’ll still need a few minor tweaks, e.g., when a particle ends with `’` or `-`, we should probably add a `\relax`, as in `author = {d’\relax Ormesson, Jean}` (see Tame the BeaST, 13.4, “How to remove space between von and Last?”); and for bibtex only, we might want to protect lowercase elements inside last names (see TTB, 13.3, “How to get lowercase letters in the Last?”; not needed for biblatex, see [here](https://github.com/plk/biblatex/issues/236) and [here](https://github.com/jgm/pandoc-citeproc/issues/50)).

**Comment by retorquere** [comment]
OK, so:

1. Split name into non-dropping particle, lastname, firstname, dropping particle, and suffix.
2. Convert each to LaTeX
3. Protect lowercase inside lastname if we're in BibTeX
3. If it was quoted, surround with braces, if not brace and and ,
4. Do not do any caps protection (OK so that's not a step, but let's just be clear on it not being a step)
5. If non-dropping-particle ends in a space, don't change it; if it ends in a punctuation char, add `\relax` and a space, otherwise, add a space
5. output {dropping-particle non-dropping-particleLastname, suffix, Firstname}
6. Profit

**Comment by retorquere** [comment]
Before I forget, can you open a new issue for publisher, location etc?

**Comment by retorquere** [comment]
OK, tests are running on the above algorithm.

**Comment by nickbart1980** [comment]
> 6. If non-dropping-particle ends in a space, don't change it; if it ends in a punctuation char, add \relax and a space, otherwise, add a space

dropping-particle, too!

**Comment by retorquere** [comment]
Already included.

**Comment by retorquere** [comment]
What would be the right course of action for a two-part name where only the last name is supplied?

**Comment by retorquere** [comment]
(I'm going to assume you'd rather see `{Lastname}` than `{Lastname,}`)

**Comment by nickbart1980** [comment]
That’s right. (A single word will always be parsed as Last, so no comma is needed.)

**Comment by retorquere** [comment]
Cool, easy to change. In the interim, [this](https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/88002084) has a few `\relax` insertions of which I'd be interested whether they're OK this way.

**Comment by nickbart1980** [comment]
No, I’ve been testing this, and the comma does *not* keep bibtex or biblatex from parsing `{Foo Bar,}` as Foo=First and Bar=Last. So it seems *multipart* last names need to be wrapped in braces, just like corporate names.

**Comment by retorquere** [comment]
What is a "multipart name"? Anything with whitespace? Anything with non-alphabetic characters? and this affects both last and firstnames? Do the particles always go outside the braces?

**Comment by nickbart1980** [comment]
Anything with whitespace. This affects only lastnames. Particles should always go outside the braces, but OTOH, if there are particles, the braces aren’t even needed.

**Comment by nickbart1980** [comment]
[This](https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/88002084) looks good – but only for bibtex. Unfortunately, the `\relax` trick does not seem to work for biblatex. I’ll have a closer look …

**Comment by retorquere** [comment]
OK, then:

1. Split name into non-dropping particle, lastname, firstname, dropping particle, and suffix.
1. Convert each to LaTeX:
 1. If quoted, brace entire part
 1. If not, and it's a last or first name, and it contains a space, brace entire part
 1. If not, brace `and` and `,`
   1. If in BibTeX, brace `<space><lowercase letter><word boundary>`
1. Postfix the particles:
  1. If it ends in a space, leave it
  1. If it ends in a punctuation character
    1. add `\relax<space>` if we're in BibTeX
    1. add a space otherwise (this still under investigation)
  1. Otherwise, add a space 
1. Output `{<dropping-particle><non-dropping-particle><Lastname>, <suffix>, <Firstname>}`
1. Profit

**Comment by retorquere** [comment]
tests are running on https://github.com/ZotPlus/zotero-better-bibtex/issues/384#issuecomment-152109856

**Comment by retorquere** [comment]
Changed to:

1. Split name into non-dropping particle, lastname, firstname, dropping particle, and suffix.
1. Convert each to LaTeX:
 1. If quoted, brace entire part
 1. If not, and it's a last or first name, and it contains a space, brace entire part
 1. If not, brace `and` and `,`
   1. If in BibTeX, brace `<space><lowercase letter><word boundary>`
1. Postfix the particles:
  1. If it ends in a space, leave it
  1. If it ends in a punctuation character
    1. add `\relax<space>` if we're in BibTeX
    1. add `<space>` if the punctuation character is a period
    1. add nothing otherwise.
  1. Otherwise, add a space 
1. Output `{<dropping-particle><non-dropping-particle><Lastname>, <suffix>, <Firstname>}`
1. Profit

**Comment by retorquere** [comment]
https://github.com/ZotPlus/zotero-better-bibtex/issues/384#issuecomment-152125210 passes all current tests, which means it has the same behavior as 1.6.2, except that empty last names don't generate a trailing comma. This probably means we don't have sufficient coverage; it would be a little surprising that the behavior was essentially OK as-is.

**Comment by nickbart1980** [comment]
> 2\. ii. If not, and it's a last or first name, and it contains a space, brace entire part

Do not brace entire first names, or else abbreviation to initials won’t be correct.

**Comment by retorquere** [comment]
1. Split name into non-dropping particle, lastname, firstname, dropping particle, and suffix.
1. Convert each to LaTeX:
 1. If quoted, brace entire part
 1. If not, and it's a last name, and it contains a space, brace entire part
 1. If not, brace `and` and `,`
   1. If in BibTeX, brace `<space><lowercase letter><word boundary>`
1. Postfix the particles:
  1. If it ends in a space, leave it
  1. If it ends in a punctuation character
    1. add `\relax<space>` if we're in BibTeX
    1. add `<space>` if the punctuation character is a period
    1. add nothing otherwise.
  1. Otherwise, add a space 
1. Output `{<dropping-particle><non-dropping-particle><Lastname>, <suffix>, <Firstname>}`
1. Profit

tests are running

**Comment by retorquere** [comment]
Tests have passed without changes to the test cases.

**Comment by retorquere** [comment]
Are you satisfied with the current implementation?

**Comment by nickbart1980** [comment]
I haven’t lost sight of this, but am much too busy with other stuff. I’ll try to upload test cases as soon as I can. Anyway, with 1.6.3, I still get:

```
@book{vangogh,
  author = {van {Gogh}, {Vincent}},
  options = {useprefix}
}

@book{humboldt,
  author = {von {Humboldt}, {Alexander}}
}

@book{beauvoir,
  author = {de {Beauvoir}, {Simone}}
}

@book{degaulle,
  author = {{de Gaulle}, {Charles}}
}

@book{king,
  author = {King, {Jr}., {Martin} {Luther}}
}
```

I’d say none of the braces around any of the elements are necessary, except those around `{de Gaulle}` when Zotero’s lastname is protected by quotes: `"de Gaulle"`.

**Comment by retorquere** [comment]
1.6.3 doesn't have these changes yet. All these changes are on a separate branch which I mean to merge as soon as I have decent confidence that it works as intended -- no rush, but I'm going to hold off until I have the test cases.

**Comment by nickbart1980** [comment]
A few test cases: 8ZTVU26A

Expected biblatex output:

```
@book{vangogh,
  author = {van Gogh, Vincent},
  options = {useprefix=true}
}
@book{humboldt,
  author = {von Humboldt, Alexander}
}
@book{beauvoir,
  author = {de Beauvoir, Simone}
}
@book{degaulle,
  author = {{de Gaulle}, Charles}
}
@book{king,
  author = {King, Jr., Martin Luther}
}
@book{stevenson,
  author = {Stevenson, III, Adlai E.},
  options = {juniorcomma=true}
}
@book{nationalaeronauticsandspaceadministration,
  author = {{National Aeronautics and Space Administration}}
}
@book{bovendeert,
  author = {boven d' Eert, Christianus},
  options = {useprefix=true}
}
@book{s-gravesande,
  author = {'s- Gravesande, Goverdus},
  options = {useprefix=true}
}
@book{dequincey,
  author = {De Quincey, Thomas}
}
@book{ortegaygasset,
  author = {Ortega y Gasset, José}
}
@book{damato,
  author = {D’Amato, Alfonse}
}
@book{sadat,
  author = {el- Sadat, Anwar}
}
@book{lafollette,
  author = {La Follette, Sr., Robert M.}
}
@book{delamare,
  author = {de la Mare, Walter},
  options = {useprefix=true}
}
@book{degette,
  author = {DeGette, Diana}
}
@book{saunders,
  author = {Saunders, John Bertrand de Cusance Morant}
}
@book{marcusaurelius,
  author = {{Marcus Aurelius},}
}
@book{dumas,
  author = {Dumas, père, Alexandre}
}
@book{vanrensselaer,
  author = {Van Rensselaer, Stephen}
}
@book{lenfant,
  author = {L’Enfant, Pierre-Charles}
}
@book{vangulik,
  author = {{van Gulik}, Robert}
}
@book{sackville-west,
  author = {Sackville-West, Victoria}
}
@book{vaughanwilliams,
  author = {Vaughan Williams, Ralph}
}
@book{miesvanderrohe,
  author = {Mies van der Rohe, Ludwig}
}
@book{dalembert,
  author = {d’ Alembert, Jean le Rond},
  options = {useprefix=true}
}
@book{tocqueville,
  author = {de Tocqueville, Alexis}
}
@book{lafontaine,
  author = {de La Fontaine, Jean}
}
@book{lasalle,
  author = {de La Salle, René-Robert Cavelier}
}
@book{dupuydeclinchamps,
  author = {du Puy de Clinchamps, Philippe},
  options = {useprefix=true}
}
@book{stein,
  author = {vom und zum Stein, Heinrich Friedrich Karl}
}
@book{silva,
  author = {da Silva, Agostinho}
}
@book{dagama,
  author = {da Gama, Vasco},
  options = {useprefix=true}
}
@book{dannunzio,
  author = {D’Annunzio, Gabriele}
}
@book{daponte,
  author = {Da Ponte, Lorenzo}
}
@book{dellarobbia,
  author = {Della Robbia, Luca}
}
@book{este,
  author = {Este, Beatrice d’}
}
@book{medici,
  author = {Medici, Lorenzo de’}
}
@book{al-hakim,
  author = {al- Hakim, Tawfiq},
  options = {useprefix=true}
}
@book{levayer,
  author = {Le Vayer, François de La Mothe}
}
```

Expected bibtex output:

```
@book{vangogh,
  author = {{van Gogh}, Vincent},
}
@book{humboldt,
  author = {von Humboldt, Alexander}
}
@book{beauvoir,
  author = {de Beauvoir, Simone}
}
@book{degaulle,
  author = {{de Gaulle}, Charles}
}
@book{king,
  author = {King, Jr., Martin Luther}
}
@book{stevenson,
  author = {Stevenson, III, Adlai E.},
}
@book{nationalaeronauticsandspaceadministration,
  author = {{National Aeronautics and Space Administration}}
}
@book{bovendeert,
  author = {{boven d'Eert}, Christianus},
}
@book{s-gravesande,
  author = {'s-Gravesande, Goverdus},
}
@book{dequincey,
  author = {De Quincey, Thomas}
}
@book{ortegaygasset,
  author = {Ortega y Gasset, José}
}
@book{damato,
  author = {D'Amato, Alfonse}
}
@book{sadat,
  author = {el-Sadat, Anwar}
}
@book{lafollette,
  author = {La Follette, Sr., Robert M.}
}
@book{delamare,
  author = {{de la Mare}, Walter},
}
@book{degette,
  author = {DeGette, Diana}
}
@book{saunders,
  author = {Saunders, John Bertrand de Cusance Morant}
}
@book{marcusaurelius,
  author = {{Marcus Aurelius},}
}
@book{dumas,
  author = {Dumas, père, Alexandre}
}
@book{vanrensselaer,
  author = {Van Rensselaer, Stephen}
}
@book{lenfant,
  author = {L'Enfant, Pierre-Charles}
}
@book{vangulik,
  author = {{van Gulik}, Robert}
}
@book{sackville-west,
  author = {Sackville-West, Victoria}
}
@book{vaughanwilliams,
  author = {Vaughan Williams, Ralph}
}
@book{miesvanderrohe,
  author = {Mies van der Rohe, Ludwig}
}
@book{dalembert,
  author = {d'Alembert, Jean le Rond},
}
@book{tocqueville,
  author = {de Tocqueville, Alexis}
}
@book{lafontaine,
  author = {de La Fontaine, Jean}
}
@book{lasalle,
  author = {de La Salle, René-Robert Cavelier}
}
@book{dupuydeclinchamps,
  author = {{du Puy de Clinchamps}, Philippe},
}
@book{stein,
  author = {vom und zum Stein, Heinrich Friedrich Karl}
}
@book{silva,
  author = {da Silva, Agostinho}
}
@book{dagama,
  author = {{da Gama}, Vasco},
}
@book{dannunzio,
  author = {D'Annunzio, Gabriele}
}
@book{daponte,
  author = {Da Ponte, Lorenzo}
}
@book{dellarobbia,
  author = {Della Robbia, Luca}
}
@book{este,
  author = {Este, Beatrice d'}
}
@book{medici,
  author = {Medici, Lorenzo de'}
}
@book{al-hakim,
  author = {al-Hakim, Tawfiq},
}
@book{levayer,
  author = {Le Vayer, François de La Mothe}
}
```

(I’ve used dumb apostrophes for biblatex; not sure whether you also want to asciify Unicode chars such as `é` and `ç`.)

**Comment by retorquere** [comment]
Super. Most things pass, but [some do not](https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/88910827):

* I can't figure out why line 599/612 should be braced; "van"/"boven" is a particle, so the lastname doesn't have a space
* 619/689/761: the particle parser deems `'s-`/`d'`/`al-` to be a particle, so that triggers useprefix. I assume that's OK.
* 625/631/641/666/677/683/700/706/712/737/743/767 has a space in the last name, so I've braced it.
* 647/722: the particle parser deems "de la"/"da" a particle, so the lastname doesn't have a space, so no brace
* 657: I thought you preferred to drop the trailing comma in this case?
* 749: I thought you wanted non dropping particles in front?

**Comment by retorquere** [comment]
There is something called a "zero width space" after the apostrophe that currently causes [this](https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/88910827#L756); what does a ZWS mean there? Should I just ignore it?

**Comment by nickbart1980** [comment]
> I can't figure out why line 599/612 should be braced; "van"/"boven" is a particle, so the lastname doesn't have a space

That’s for bibtex (not biblatex): always “van Gogh”/“van Gogh, Vincent” etc. seems much better than “Gogh”/“Gogh, Vincent van”.

> 619/689/761: the particle parser deems 's-/d'/al- to be a particle, so that triggers useprefix. I assume that's OK.

Not for bibtex; bibtex doesn’t have `options`.

> 625/631/641/666/677/683/700/706/712/737/743/767 has a space in the last name, so I've braced it.

That’s not needed when Last does not begin with a word starting with a lowercase letter, *and* there is a First after the comma. (In other words, brace a Last that starts with uppercase *only* if there is no First.)

> 647/722: the particle parser deems "de la"/"da" a particle, so the lastname doesn't have a space, so no brace

Sorry, this should be ["de la Mare"][Walter] ["da Gama"][Vasco]` on the Zotero side (both from the Chicago Manual).

> 657: I thought you preferred to drop the trailing comma in this case?

I guess this shows I’m undecided here. Keeping it would flag the fact that it came from a two-field name, but I’m not sure whether that’s ever useful. Do you see any arguments for or against?

> 749: I thought you wanted non dropping particles in front?
> "zero width space" after the apostrophe

Sorry, these slipped through. For bibtex, use `{d’\relax Este, Beatrice}` and `{de' Medici, Lorenzo}`. For biblatex, please use `{d’ Este, Beatrice}` and `{de’ Medici, Lorenzo}`.

Note that “Lorenzo de’ Medici” is the only name I’ve encountered so far that needs a space after a particle ending with punctuation, so for biblatex (not bibtex) the space would have to be protected somehow (or rather, the punctuation masked). `{de’\mbox{} Medici, Lorenzo}` seems to work for biblatex.

That’s also why I have been experimenting with "zero width space" (and inadvertently left it in). Please either remove the ZWS, or, if you feel that’s not too hackish, you could leave it in, and map it to `\mbox{}`.

**Comment by retorquere** [comment]
>> I can't figure out why line 599/612 should be braced; "van"/"boven" is a particle, so the lastname doesn't have a
>> space
>
>That’s for bibtex (not biblatex): always “van Gogh”/“van Gogh, Vincent” etc. seems much better than “Gogh”/“Gogh,
>Vincent van”.
>
>> 619/689/761: the particle parser deems 's-/d'/al- to be a particle, so that triggers useprefix. I assume that's OK.
>
>Not for bibtex; bibtex doesn’t have `options`.

I've split the test cases into BibTeX and BibLaTeX export; tests results for BibLaTeX are [here](https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/88972569#L1009) ; feel free to edit the [expected output](https://github.com/ZotPlus/zotero-better-bibtex/blob/384/test/fixtures/export/Do%20not%20caps-protect%20name%20fields%20%23384.biblatex) where you think mismatches are not actually errors. There are BibTeX tests in place, but they won't run until the BibLaTeX ones pass first.

>> 625/631/641/666/677/683/700/706/712/737/743/767 has a space in the last name, so I've braced it.
>
>That’s not needed when Last does not begin with a word starting with a lowercase letter, *and* there is a First after
>the comma. (In other words, brace a Last that starts with uppercase *only* if there is no First.)

But last names will never start with a word with a lowercase letter, since that word will be deemed a particle.

>> 647/722: the particle parser deems "de la"/"da" a particle, so the lastname doesn't have a space, so no brace
>
>Sorry, this should be ["de la Mare"][Walter] ["da Gama"][Vasco]` on the Zotero side (both from the Chicago Manual).

OK, I've adjusted those.

>> 657: I thought you preferred to drop the trailing comma in this case?
>
>I guess this shows I’m undecided here. Keeping it would flag the fact that it came from a two-field name, but I’m not
>sure whether that’s ever useful. Do you see any arguments for or against?

I personally like the flagging function if it doesn't do harm otherwise

>> 749: I thought you wanted non dropping particles in front?
>> "zero width space" after the apostrophe
>
>Sorry, these slipped through. For bibtex, use `{d’\relax Este, Beatrice}` and `{de' Medici, Lorenzo}`. For biblatex,
>please use `{d’ Este, Beatrice}` and `{de’ Medici, Lorenzo}`.
>
>Note that “Lorenzo de’ Medici” is the only name I’ve encountered so far that needs a space after a particle ending with
>punctuation, so for biblatex (not bibtex) the space would have to be protected somehow (or rather, the punctuation
>masked). `{de’\mbox{} Medici, Lorenzo}` seems to work for biblatex.

But how should I decide which way to go, algorithmically? It seems a little weird to hard-code a rule specifically for `de' Medici'.

>That’s also why I have been experimenting with "zero width space" (and inadvertently left it in). Please either remove
>the ZWS, or, if you feel that’s not too hackish, you could leave it in, and map it to `\mbox{}`.

I'll see whether I can get it to work, but I wouldn't want to consider it a blocking problem for #384. I've seen other places recommend `\hspace{0pt}` BTW.

**Comment by nickbart1980** [comment]
> But last names will never start with a word with a lowercase letter, since that word will be deemed a particle.

Last names sometimes do: `{{de la Mare}, Walter}`, `{{van Gulik}, Robert}`, `{{da Gama}, Vasco}` etc. are cases where strings that might appear to be particles are not, but should be parsed as fixed parts of the last name, that’s why they are braced.

I’ve edited the [expected biblatex output](https://github.com/ZotPlus/zotero-better-bibtex/blob/384/test/fixtures/export/Do%20not%20caps-protect%20name%20fields%20%23384.biblatex).

>  I wouldn't want to consider it a blocking problem for #384.

Fine with me. –  `\hspace{0pt}` BTW does not seem to protect/mask the apostrophe; biblatex’s `\addspace` OTOH works.

**Comment by retorquere** [comment]
But those names are already handled correctly. It's names like `[De Quincey] [Thomas]` that offered the mismatches. According to the rule we discussed at https://github.com/ZotPlus/zotero-better-bibtex/issues/384#issuecomment-152155662, that requires bracing, but `[de Quincey] [Thomas]` would not be a lastname with a space in it, but a last name `Quincy` (no spaces in that), with a non-dropping particle `de` -- so no bracing.

Just put the `\addspace` where you'd like it to be, I'll see if I can get it to show up, but it seems a little counter intuitive to replace a ZWS (which doesn't add spacing) with `\addspace` (which does).

**Comment by retorquere** [comment]
Is there a specific reason to favor `options = {useprefix=true}` over `options = {useprefix}`?

**Comment by nickbart1980** [comment]
> https://github.com/ZotPlus/zotero-better-bibtex/issues/384#issuecomment-152155662: “2\. ii. If not, and it's a last name, and it contains a space, brace entire part”

Sorry about that; it would seem this should be: 
“2\. ii. If not, and it's a last name, and it begins with a lowercase letter, brace entire part”
(Spaces are irrelevant, and braces aren’t needed if the last name starts with an uppercase letter, but all last names that start with lowercase need to be braced, even if they do not contain spaces; just tested this for `author = {{cummins}, e. e.}`.)

**Comment by nickbart1980** [comment]
> Is there a specific reason to favor options = {useprefix=true} over options = {useprefix}?

Yes: I found this much easier to parse in `\DeclareSourcemap` if needed (see, e.g., https://github.com/ZotPlus/zotero-better-bibtex/issues/353#issuecomment-143433819).

**Comment by nickbart1980** [comment]
> Just put the `\addspace` where you'd like it to be, I'll see if I can get it to show up, but it seems a little counter intuitive to replace a ZWS (which doesn't add spacing) with `\addspace` (which does).

So would mapping ZWS to `\mbox{}` be ok for you?

**Comment by retorquere** [comment]
Tests are running again.

**Comment by retorquere** [comment]
(I've added the mapping to mbox, and the useprefix, and the lowercase-starting names)

**Comment by retorquere** [comment]
So technically, the ZWS is valid where it is; unless ASCII-coding is set for BibLaTeX, it won't be translated into `\mbox{}`, and ASCII-coding is off by default for BibLaTeX. You want me to force translation of ZWS into `\mbox{}` even if it is off?

**Comment by nickbart1980** [comment]
Just tested this, and a ZWS seems to protect/mask the apostrophe in biblatex, too. So if you’d just let any ZWSs through as is when ASCII-coding is off, that should work nicely for the time being.

**Comment by retorquere** [comment]
Can you add in the ZWS into the biblatex file? I don't know how to.

**Comment by nickbart1980** [comment]
Done.

**Comment by retorquere** [comment]
Aww yeah, BibLaTeX [passes](https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/88993825), on to BibTeX. It's a simple copy of the BibLaTeX file, so there will be loads of misses.

**Comment by retorquere** [comment]
BibTeX also shouldn't have caps preservation, right? Let me turn that off first.

**Comment by retorquere** [comment]
Tests are running at https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/88994655

**Comment by retorquere** [comment]
I know there are quite a few boneheaded errors in there -- don't worry about them, just make the BibTeX file look good, and I'll get to work on making the output match.

**Comment by nickbart1980** [comment]
I’ve been testing a few things by processing the output with bibtex, and I have to say: what a mess. bibtex seems to ignore hyphens after prefixes, and sometimes complete multi-part prefixes. Also, I haven’t found a single bst style that demotes prefixes (have you?), so I’m not sure why we should bother parsing out prefixes more or less cleanly in the first place. I can have a further look, but it’ll probably take a while.

**Comment by retorquere** [comment]
I don't use BibTeX myself, only BibLaTeX, so I have very little experience here. It would be trivial to just do `{{<dropping-particle> <non-dropping-particle> <family>}, <suffix>, <given>}` for BibTeX, or even just `{{Zotero Lastname}, {Zotero Firstname}`, if that by and large does the right thing. The 2nd form is pretty much what BBT did before I started parsing particles.

**Comment by nickbart1980** [comment]
`{{<dropping-particle> <non-dropping-particle> <family>}, <suffix>, <given>}` sounds ok to me.

**Comment by retorquere** [comment]
Tests are running on that [here](https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/89095909), you know the drill

**Comment by retorquere** [comment]
Make that [here](https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/89097028), the previous version didn't handle quoted names properly.

**Comment by retorquere** [comment]
All tests pass.
