### ISSUE TITLE
Extra \url in url field with biblatex

### ISSUE THREAD

**Issue by danielrschmidt** [ZotPlus/zotero-better-bibtex#386]
This is more of a feature request: Whenever I auto-export an item with better bibtex, it ends up having the url field enclosed in \url{...}. Now, I'm using biblatex and biblatex automatically adds \url{...} to the url field, so now all my bib items have \url{\url{...}} ;) Any way to prevent better bibtex from adding \url{...}?

Thanks!

**Comment by retorquere** [comment]
Disable "fancy urls" in the settings.

**Comment by danielrschmidt** [comment]
Great, that worked perfectly -- thank you!
