### ISSUE TITLE
Quick format citation dialog: Insert entire BibTeX record?

### ISSUE THREAD

**Issue by orschiro** [ZotPlus/zotero-better-bibtex#387]
Dear all, 

Thanks for your fantastic work! I'm using the following command with a custom keyboard shortcut to call the quick format citation dialog:
```
elinks "http://localhost:23119/better-bibtex/cayw?format=BibLaTeX&clipboard=yes"
```

I'm looking for the right `format=` to paste the entire BibTeX record of a reference. 

Any ideas which format is the right one?

Thankfully,

Robert

**Comment by retorquere** [comment]
Wow. That is currently not possible, but I'll have a look at it.

**Comment by orschiro** [comment]
Dear @retorquere,

That would be great, thank you!

This would ease the workflow with Zotero and Authorea.

**Comment by retorquere** [comment]
Cool. I'm currently doing performance work on #385 that I want to finish before anything else, after that I'm diving back into features.

There may be another way to get what you want: you could set up [git access](https://www.authorea.com/users/3/articles/17235/_show_article) to your article, set up auto-export in BBT, and then use auto-commit to push it to Authorea. I have not tested this **(!!)** but in theory that should get you near-realtime updated bib files on Authorea. For autocommit you could use something like [SparkleShare](http://sparkleshare.org/) or a [shell script](https://github.com/nevik/gitwatch); there are without a doubt others.

**Comment by orschiro** [comment]
@retorquere 

Thanks for your alternative suggestion! I think I would try it out if my initial request is technically not feasible. 

I still think it offers many benefits that go beyond the concrete use of Authorea. :)

~ Robert

**Comment by retorquere** [comment]
1.6.1 will be out in a bit, documentation has been updated

**Comment by orschiro** [comment]
Great, thank you! 

I had a look at the documentation and figured must be the following command which, however, only pastes the `cite` element:

    elinks "http://localhost:23119/better-bibtex/cayw?format=translate&translator=csljson&clipboard=yes"

**Comment by retorquere** [comment]
That URL is correct, and for me it does indeed put the Better CSL JSON reference on the clipboard. Can you submit an [error report](https://zotplus.github.io/support.html)?

**Comment by orschiro** [comment]
@retorquere,

Apologies. I forgot to update to v1.6.2....

It is working now! :)

~ Robert

**Comment by retorquere** [comment]
Cool, thanks for the confirmation.
