### ISSUE TITLE
Oriental dates trip up date parser

### ISSUE THREAD

**Issue by zhuzhongshu** [ZotPlus/zotero-better-bibtex#389]
Hello, I find I can't  export my library to Better BibTeX  format. The error message is "An error occurred while trying to export the selected file". I have tried to reinstall Zotero and  Better Bib(La)TeX but it didn't work. My OS is Ubuntu 14.04. The softwares I use are  Zotero 4.0.28 & Better Bib(La)TeX 1.5.11.

**Comment by retorquere** [comment]
Please upgrade to the latest version, and if the error persists, submit an [error report](https://zotplus.github.io/support.html#better-bibtex) with extended debugging enabled.

**Comment by retorquere** [comment]
Can you check,whether #390 applies to your case?

**Comment by zhuzhongshu** [comment]
i have update the better-bibtex to 1.6.2 but the error still exits. The error report ID is VKJ8ZGNK.

>Can you check,whether #390 applies to your case? 

Sorry I am not sure... Could you please tell me what should I do to check it?

**Comment by retorquere** [comment]
If you go to the Firefox Add-ons manager, has better bibtex been disabled?

In any case, could you first upgrade to 1.6.2?

**Comment by zhuzhongshu** [comment]
i have upgraded better bibtex to 1.6.2 both in Firefox and Zotero. But it doesn't work. 
The  better bibtex is enabled in Firefox.

**Comment by retorquere** [comment]
Wait, do you have both running? That doesn't work.

**Comment by zhuzhongshu** [comment]
Yes, Both firefox and Zotero standalon are running. 

I just tried to close firefox but this error still exits.

**Comment by retorquere** [comment]
OK, can you do the following:

1. Close Zotero Standalone
2. In Zotero Firefox, go into Preferences/Better BibTeX/debug, and enable extended debugging
3. Close Firefox
4. Start Firefox
5. Perform an export (which will fail)
6. From the Zotero gear menu, choose "Report ZotPlus error"
7. Post the resulting debug ID here

**Comment by retorquere** [comment]
Does this problem still occur? If so, I'd like to fix it, if not, I'd like to close the issue.

**Comment by zhuzhongshu** [comment]
Sorry for my late reply, the problem still occur and the debug ID is BN75W6NR.
Many thanks for your  help!!

**Comment by retorquere** [comment]
Interesting -- the dateparser trips on what it thinks is a Japanese date. From what I can tell, it's the 3rd item in the set you're trying to export that triggers the error; could you try to find one entry that triggers the error, right-click it, and then select "report ZotPlus error" (or it could be "report BetterBibTeX error" now; they're the same), and paste the ID here. That will give me the problematic reference so I can reproduce, but I have some idea of the problem that underlies it (the library I use to parse dates didn't expect something that's in your reference)

**Comment by zhuzhongshu** [comment]
Hello, the third item do cause this error and the debug ID is X5AGNUZ2. I tried some other items randomly and they can be export successfuly.

**Comment by retorquere** [comment]
1.6.5 contains a fix, you should now again be able to export.

**Comment by zhuzhongshu** [comment]
Yes, I can export my library now. Many thanks for your help!
