### ISSUE TITLE
Do not caps-protect literal lists

### ISSUE THREAD

**Issue by retorquere** [ZotPlus/zotero-better-bibtex#391]
@nickbart1980 says:

> Protecting journal, magazine, and newspaper titles, location, publisher, institution, and organization fields etc., or parts of these is unnecessary on principle; literal ‘and’s in biblatex literal lists, i.e., institution, organization, publisher, location, origlocation, origpublisher, address and school should be wrapped in braces – or alternatively enclose the entire field in braces [2.3.4]).

**Comment by nickbart1980** [comment]
I guess the easiest approach is to brace the whole fields, regardless of whether they contain a literal “and” or not. I’m not sure whether BBT ever uses `organization`, if so, brace this, too. `address` and `school` are aliases for backwards compatibility, and AFAICS not used by BBT at all.

Test cases: SZ2WJFAS

Expected output, bibtex and biblatex:

```
@book{-publisher,
  location = {{Trinidad and Tobago}},
  title = {Publisher},
  publisher = {{Miller, Smith and Jones}},
  origlocation = {{Saint Kitts and Nevis}},
  origpublisher = {{Doe and Company}}
}

@report{-institution,
  title = {Institution},
  institution = {{Office of Information Management and Communications}}
}

@thesis{-university,
  title = {University},
  institution = {{University of Saint Kitts and Nevis}}
}
```

**Comment by retorquere** [comment]
Cool, thanks. Could you upgrade BBT to 1.3.5 BTW? There was an error in the translator that generates test cases.

**Comment by retorquere** [comment]
Almost done, but a few tests fail right now. Tomorrow it should be done.
