### ISSUE TITLE
Auto-export doesn't work.

### ISSUE THREAD

**Issue by sdaza** [ZotPlus/zotero-better-bibtex#392]
Zotero Better BibLatex 1.6.2
Desktop Zotero 4.0.28.8
Mac The Capitan

**Comment by retorquere** [comment]
Where do you get this message? I'm not seeing it. Could you upgrade to 4.0.28.8 and see if it still happens?

**Comment by sdaza** [comment]
I am using the last zotero version. 
[Here a screenshot](https://dl.dropboxusercontent.com/u/18116710/Screenshots/Screenshot_2015-10-30_12.24.26.png)

**Comment by retorquere** [comment]
I thought your message said 4.0.28.0 before. But is there any problem beyond that message being present in the addons pane?

**Comment by sdaza** [comment]
My library is not automatically exported.

**Comment by retorquere** [comment]
There are a couple of situations where BBT could be expected to auto-export:

1. When manually kicked off from the preferences
2. When auto-export is set to idle, and you've not touched the computer for about 20 seconds
3. When auto-export is set to "on change", and you've changed an item in a collection that is set up for auto-export

Which of these is failing?

**Comment by sdaza** [comment]
When it is set to idle or on change.

**Comment by retorquere** [comment]
Can you try this version: http://tempsend.com/15CC8978C7

**Comment by sdaza** [comment]
It doesn't  work.

**Comment by retorquere** [comment]
And this one: http://tempsend.com/B71473EC94

**Comment by sdaza** [comment]
Now it is working :+1: 
Thanks!

**Comment by retorquere** [comment]
Super, thanks for reporting it and helping me test. Release tests are running, when they go green I'll release 1.6.3.

**Comment by retorquere** [comment]
Please force-upgrade to 1.6.3; an updated library just managed to slip in during that last debug build, 1.6.3 contains a fix for an api change in it.

**Comment by phretor** [comment]
@retorquere I'm still getting this problem. I'm on El Capitan, latest version of Zotero, BBL 1.6.16. Let me know if you need me to provide some debug traces.

**Comment by retorquere** [comment]
I didn't know you were experiencing problems. A debug trace will be most
helpful.

**Comment by retorquere** [comment]
BTW @phretor could you please open a new issue for the problem you are experiencing? It is hard to track progress on closed issues, I am bound to forget action is still desired. I've just tried on my on Mac (also on ElCap), and I'm not experiencing problems with auto-export.

**Comment by retorquere** [comment]
A new release is out that may incidentally fix your problem as it may be related; if not, please do open a new issue.

**Comment by phretor** [comment]
@retorquere the new release seems to have fixed the problem. Thanks!

**Comment by hetsch** [comment]
@retorquere I'm currently (since ca. 1 month) experiencing  the same problem's with autoexporting a bibliography "on change". I don't know exactly how to provide you debugging information but if you tell me what you need I will be more than happy to provide you all the logfiles etc.

OS: 10.9.5
Zotero: 4.8.28
Zotero Better BibLatex: 1.6.22

**Comment by retorquere** [comment]
Let's find out whether the log has enough detail:

* Go into BBT prefs, "debug" tab, enable extended logging
* Trigger a change that should cause an auto-export
* From the zotero gear menu, select "send BBT error"
* Paste the resulting ID here.

**Comment by hetsch** [comment]
@retorquere Thank you for your help. The id is JKTNV6IX.

**Comment by retorquere** [comment]
Super, that had the info I needed. It looks to be a shamefully stupid mistake on my part for which I honestly don't know how the current test that's supposed to cover it runs green :worried:. Looking into that separately.

I think I have it fixed though; could you give http://tempsend.com/C8DCFEB249a try?

**Comment by hetsch** [comment]
@retorquere Great that you have found the bug! Nothing to shame, I wouldn't even know where to start bughunting! Anyway, this is a good one :) I couldn't give it a try because the temporary url throws a 404. Do you mind reuploading it?

**Comment by retorquere** [comment]
Oops, that closure was accidental. I'll get you a new version when I'm home, about 15 minutes

**Comment by retorquere** [comment]
http://tempsend.com/7CF025465E

**Comment by hetsch** [comment]
@retorquere Thx for the quick response. I'm sorry to say that it does not solve my problem. I have sent you another report XHI6EPAW.
It might be interesting that in the "better bibtex preferences pane" under "automatic export" the status says "done (undefined)". If I remember correctly, there was always a timestamp/date instead of undefined.

**Comment by retorquere** [comment]
Could it be this is a new auto-exported collection? There was indeed a bug where newly added exports did not get a timestamp.

The new log doesn't show any auto export activity, but it also doesn't show any item change activity. If it is true there was no item change, there won't have been a trigger to kick off an auto-export. Could you make a trivial change to a reference (adding a character to a field and then removing it would do it) to kick it off?

**Comment by hetsch** [comment]
Here is the new debug id WIPP6BTD. The auto-export collection has persisted a long time (think half a year) before it stoped working. Since then I've added it various time but had no luck. I've now added a book to the collection and changed some characters, no automatic export ...

**Comment by retorquere** [comment]
I see the activity in the log; it's even scheduling an export, but not performing it. Can you get me a log from http://tempsend.com/E24DC6F202 ?

**Comment by hetsch** [comment]
@retorquere the log id is SNG6KCW2. What I've done was importing a book into the collection and no autoexport happend and status was still undefined. Then I triggered a manual export sucessfully wit status showing a new timestamp.

**Comment by retorquere** [comment]
This is so weird. I don't see any activity indicating a reference import in that log. Not from BBT, but also not from Zotero itself.

Can you try the following:

* Install http://tempsend.com/5FB06AAEC9
* Go into preferences, BBT, debug, and enable extended debugging if you haven't already
* Still in preferences, BBT, debug, check "show reference ID"
* In the reference list, at the far right of the column headers, you'll see a blocky icon with a down arrow. 
Under "More columns", make sure "call number" is checked.
* Go into preferences, advanced, clear the log
* Import a new reference
* Post the debug ID, the title of the reference you just imported, and the reference ID which is now in the call number column.

**Comment by hetsch** [comment]
@retorquere I hope that I did not mess up anything if this behaviour is so strange. I did all what said, the id is CGE3D44H, the title of the book was "Ecotourism: Principles and Practices", the reference id is 188. I hope this take helps you to find the problem. Thank you so much for spending your time on that issue. Highly appreciated!

**Comment by retorquere** [comment]
Is this item 188 a new or an existing item? Zotero should have fired an itemChanged event (doesn't matter if it's a new item or a change). That event is simply not present in the log. I do see activity around 188, but that's addition to a collection, but that's an addition of an existing item to a collection 56, where you only have collection 39 set up for auto-export.

**Comment by hetsch** [comment]
This is totally crazy. Item 188 is an existing item. My collection structure looks like:

- **col1** (this is the autoexport collection)
  - col1.1
     - item 188 (this is the added item)
     - item 2
     - item 3
  - col1.2
     - item 4
     - item 5
- col2

I have setup an autoexport for col1, as said half a year ago and it was working. If I add an item to col1.1 the autoexport was triggered and the whole col1 was exported to the specified bibfile. Since short, same procedure nothing happens. Then I tried to create an autoexport for col1.1, add an item directly to this collection and the autoexport is triggered and executed. Has something changed in the latest releases in a matter that changes in a subcollection does not trigger a autoexport event in the parent collection?

**Comment by retorquere** [comment]
Do you have recursive display on or off?

**Comment by hetsch** [comment]
Hell, this was the problem! Setting extensions.zotero.recursiveCollection to true did the trick! I, really, can't remember that I have changed this option (btw, I have never heard about it) ... Anyway, it is good to know that this affects the export. I'm very sorry for all the time you have spend for solving my problem. Autoexport is one of my favourite features! Thanky, you, REALLY!

**Comment by retorquere** [comment]
No worries. In the BBT preferences, "export collections recursively" in fact toggles this setting. BBT always tries to export what the collection actually shows. I'm actually a little ambivalent about the current implementation, I do sometimes want to export recursively but not display recursively, but this was conceptually most clear I thought.

Does this account for all your problems with auto-export?

**Comment by retorquere** [comment]
(don't forget to undo the debugging settings)

**Comment by hetsch** [comment]
It seems that all my problems are gone! Good hint with debugging, was on :-). Please close the ticket and have a nice weekend!

**Comment by retorquere** [comment]
Don't forget the call number thingie.

My pleasure. I've cleaned up some things as I was going through this, so it's never a loss.
