### ISSUE TITLE
Citation keys not recognized when compile

### ISSUE THREAD

**Issue by mijalce** [ZotPlus/zotero-better-bibtex#393]
I am not sure is it related to BBT (but it is the only updated add-on today so I am raising it here)
I am using the picker to insert citations in Scrivener. When I compile from Scrivener (or in Marked2) it gives me an error that it does not recognize the BBT citation keys. I use zotxt to access Zotero libraries (zotxt add-on was last updated 5 October). 
Yesterday and the days before that everything was functioning well.

**Comment by retorquere** [comment]
Do the keys in your scrivener document match the keys displayed in Zotero? If not, that is certainly a BBT error; if not, it is (without meaning to deflect) an issue in ZoTXT; there have been substantial changes in the internals of BBT of which I failed to appraise @egh; it is not at all unlikely that the updates to BBT have broken the access ZoTXT uses to tap into the BBT keys.

@egh: all data access has moved into chrome/content/zotero-better-bibtex/db.coffee; where ZoTXT previously picked keys from Zotero.BetterBibTeX.keymanager.keys, it needs to pick them from Zotero.BetterBibTeX.DB.keys now. It could well be that this is all that is needed; I haven't changed the layout of that DB.

**Comment by mijalce** [comment]
I just checked and all the keys in the scrivener document match the BBT keys in Zotero. So probably the issue is the broken access ZoTXT uses. 
Should I raise this issue at zotxt?
Thanks!

**Comment by retorquere** [comment]
I'm afraid so, but I'll be around to help.

**Comment by mijalce** [comment]
ok, I will do so. 
Keep the good work.

**Comment by egh** [comment]
Thanks for the info @retorquere . This should be fixed in the latest version of zotxt.
