### ISSUE TITLE
Error when exporting library to Better BibTex and BibLaTex

### ISSUE THREAD

**Issue by legendaryApps** [ZotPlus/zotero-better-bibtex#394]
When I try to export a collection or a single item to Better Bibtex/BibLaTex, the error message is "An error occurred while trying to export the selected file" and the resulting file is empty. When I enable debugging and press "Report Better BibTex Errors", nothing happens.

Thanks in advance

**Comment by retorquere** [comment]
Is there anything salient in the debug log when you go to Advanced/View Output in the prefs?

**Comment by retorquere** [comment]
Does this problem still occur? If so, I'd like to fix it, if not, I'd like to close the issue.

**Comment by retorquere** [comment]
Hello?

**Comment by retorquere** [comment]
Closed for lack of feedback.

**Comment by legendaryApps** [comment]
Sorry for the delay. I got:

[JavaScript Error: "NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]" {file: "chrome://zotero-better-bibtex/content/zotero-better-bibtex.js" line: 11}]

[JavaScript Error: "NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]" {file: "chrome://zotero-better-bibtex/content/zoteroPane.js" line: 2}]

[JavaScript Error: "bad script XDR magic number"]

[JavaScript Error: "NS_ERROR_FILE_NOT_FOUND: Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIXPCComponents_Utils.import]" {file: "chrome://zotero-better-bibtex/content/zotero-better-bibtex.js" line: 11}]

**Comment by retorquere** [comment]
On what version of Zotero are you?

**Comment by legendaryApps** [comment]
I just updated to the newest version. Works like a charm. Thx for the support!
