### ISSUE TITLE
Some minor issues when exporting in biblatex

### ISSUE THREAD

**Issue by samspo** [ZotPlus/zotero-better-bibtex#399]
- When there is a word between square brakets (for example: [1973]) in my annotations or abstract, it is exported with the following form:
{[}1973]

- When I have a # (for example: #tag) in my annotations, it is exported with the following form:
\#tag

- The related items in zotero are note exported in biblatex (maybe not possible but just to have your confirmation - https://forums.zotero.org/discussion/50839/collection-with-related-items-export-and-then-import/)

Thank you

**Comment by retorquere** [comment]
Hi, 

1. I do this because I may output a closing brace just before it, and it might be interpreted as an argument to a function by LaTeX rather than a literal bracket. 
2. What would you like to see instead? Isn't the hash a valid character? 
3. I don't know of a Bib(La)TeX construct that is equivalent to Zotero's relations. I tried xref, but xref is unidirectional, where Zotero's relationship are bidirectional. There's no way to tell which way the relationship goes in Zotero.

**Comment by retorquere** [comment]
Or do you mean with 3. that you'd want the related items to be included in the export, regardless of whether they were included in your export selection? That would require a change in Zotero, the translators get a ready-made list to export, you can't expand the set of items inside the translator.

**Comment by samspo** [comment]
Thank you for you very quick answer
For 2, sorry, something was missing. I see:  \#tag
For 3, I'd like to see the relationships (not include the related items in the export)

**Comment by samspo** [comment]
The Backslash is sticked to the # but can't write that here else we don't see the \  (don't know why)

**Comment by retorquere** [comment]
Ah, I see. I thought `#` needed to be escaped in BibTeX? If not, easy to change.

In what way would you want to see related items? xref doesn't do it correctly, and the translator may not be handed the reference in the first place (when it does not happen to be in the set you selected for export).

**Comment by samspo** [comment]
xref would be nice. But I don't know the implications of that (I wouldn't use it to generate bibliography but just to have the information in my database when I look for the relevant papers while I writer a paper)

**Comment by retorquere** [comment]
That's the thing, xref has different semantics from Zotero relations, and Zotero would have to make a change to hand the referenced items to the translator. So I don't have them, and if I would have them, I don't know where to put them. xref is semantically wrong, and I don't know any other field that would qualify.

**Comment by samspo** [comment]
Okay. I understand. Thank you really much for your answer.

**Comment by retorquere** [comment]
Sorry I couldn't be of more help. If you do think of a way it could be represented validly, don't hesitate to reopen the issue.
