### ISSUE TITLE
Add Bibtex field 'lastchecked' for websites.

### ISSUE THREAD

**Issue by toni1991** [ZotPlus/zotero-better-bibtex#401]
Thank you very much for your great work! I really like your plugin!

As a enhancement it would be very nice, if the plugin would create the 'lastchecked' field from the urldate as it exports websites as 'misc' for Bibtex. So it would be much simpler to make the lastchecked-date visible.

**Comment by retorquere** [comment]
Do you mean for BibTeX or for BibLaTeX?

**Comment by toni1991** [comment]
My particular need is BibTeX but why don't implemenet it for both?

**Comment by nickbart1980** [comment]
For biblatex: it has `urldate`, and `lastchecked` is not a valid field; so: no.

**Comment by retorquere** [comment]
The biblatex exporter already outputs `urldate`.

Your JS looks OK. If it doesn't output anything that means there's an error somewhere -- if you enable extended debugging and try another export, you will find lines with `postscript error:` in your debug log.

But if lastchecked is valid for BibTeX I have mo problem just adding it to the exporter.

**Comment by retorquere** [comment]
Ah, `ref` needs to be `this`; you may also want to check for `Translator.BetterBibTeX` -- it will only be true if you're in the Better BibTeX exporter, not the Better BibLaTeX.

**Comment by retorquere** [comment]
So more something akin to:

```
this.add({
  name: 'lastchecked',
  value: Translator.BibTeX && this.item.accessDate && this.item.accessDate.replace(/\s*T?\d+:\d+:\d+.*/, '')
});
```

**Comment by toni1991** [comment]
I'm currently not even sure if im editing the right file...I have to possibilities in my profile folder.
	zotero/better-bibtex/
	└── translators
	    └── Better\ BibTeX.js
	zotero/translators/
	└── Better\ BibTeX.js

By the way, the code:
```javascript
ref.add({
      name: 'urldate',
      value: item.accessDate && item.accessDate.replace(/\s*T?\d+:\d+:\d+.*/, '')
    });
``` 
is part of your plugin.

**Comment by retorquere** [comment]
Edits to the files get overwritten at every start of Zotero, so they get overwritten before your changes are loaded; that explains why you see no output.

You can add your own scriptlets using [this](https://zotplus.github.io/better-bibtex/export.html#you-wanted-customized) and they will persist. If you want to edit the translator files themselves you will have to open up the xpi. I don't recommend that though, as it's hard to debug problems for me; I can't support locally modified versions.

BTW the accessdate is already exported as 'urldate' in the BibTeX exporter, is that the wrong field?

**Comment by toni1991** [comment]
Thanks, will give it a try. 

Yes, at least for me, bibtex uses the 'lastchecked' field for the date a url was called the last time.

**Comment by retorquere** [comment]
I'm probably going to make this the default behavior as part of fixing #402

**Comment by retorquere** [comment]
It looks like BibTeX doesn't support lastchecked across the board ([1](http://tex.stackexchange.com/questions/48983/urldate-in-bibtex-gets-ignored), [2](http://tex.stackexchange.com/questions/89058/which-bibliographystyle-for-lastchecked-and-url-attribute)) and the behavior is style-dependant. I'd rather not bake in behavior which requires a specific style. Is the postscript as shown in the [examples](https://github.com/ZotPlus/zotero-better-bibtex/wiki/Scripting-examples) sufficient?

**Comment by retorquere** [comment]
closed for lack of feedback.
