### ISSUE TITLE
cache not changed after renaming attachments

### ISSUE THREAD

**Issue by rdiaz02** [ZotPlus/zotero-better-bibtex#403]
I think the cache should be updated/cleared for those references that have attachments renamed (e.g., using ZotFile) so that the exported BibTeX has the correct new file name. Currently it does not happen, and the filename is not changed. (I can get it fixed if I reset the cache but then the export takes very long, so ideally, only the renamed entries would need to have to be changed, not the whole cache cleared).

Example: I had a database with an entry that had, in the file field

`file = {Snapshot:/home/ramon/Zotero-data/storage/JKFK3GJH/1494.html:;Lightowlers et al_2015_Mutations causing.pdf:/home/ramon/Zotero-data/storage/KC4NIRXF/Lightowlers et al_2015_Mutations causing.pdf:application/pdf}`

Now, I rename the attachment, using ZotFile. The new attachment is now called `Lightowlers_et_al_2015_Mutations_causing_349_1494-1499.pdf`. But exporting keeps the old name. If I reset the cache, I see the correct

`
file = {Snapshot:/home/ramon/Zotero-data/storage/JKFK3GJH/1494.html:;Lightowlers_et_al_2015_Mutations_causing_349_1494-1499.pdf:/home/ramon/Zotero-data/storage/KC4NIRXF/Lightowlers_et_al_2015_Mutations_causing_349_1494-1499.pdf:application/pdf},`

**Comment by retorquere** [comment]
tests are running.

**Comment by retorquere** [comment]
Could you try http://tempsend.com/669E7B0B2D ?

**Comment by rdiaz02** [comment]
I just tried: not working. I installed, cleaned the cache, exported, renamed, exported again, and file names did not get updated.

**Comment by retorquere** [comment]
Wow, that was a nasty one. See if this one works: http://tempsend.com/EB9E88B01C

**Comment by rdiaz02** [comment]
Yes, it seems to work in a test where I renamed three files. And it did without having to clear the cache before the first run.  I then tested with another changed, and everything worked again.

Thanks!

**Comment by retorquere** [comment]
Super. Tests are running, when they go green I'll cut a new release.
