### ISSUE TITLE
Colon in bibtex key

### ISSUE THREAD

**Issue by melsophos** [ZotPlus/zotero-better-bibtex#405]
I suspect that there is a bug in the escaping of colon in citation key. Indeed using the following format

    [auth:alphanum][year:prefix,\:][Title:nopunct:skipwords:capitalize:select,1,3:alphanum:prefix,\:][0]

provides a key where the first colon is missing (on some example)

    Blumenhagen2014:CourseNoncommutativeGeometry

On the other hand if I replace the first "\:" by something else (such as a an underscore "_"), then it works well

    Blumenhagen_2014:CourseNoncommutativeGeometry

The same appears using "postfix" except if it is in the end of the "Title" field.

By the way the documentation does not mention that one can use backslash to protect colon.

**Comment by retorquere** [comment]
Can you right-click on a reference where you experience this, select "Send Better BibTeX error", and put the resulting debug ID here?

**Comment by retorquere** [comment]
Ah, I think I know why this happens. Hmm.

**Comment by retorquere** [comment]
tests are running.

**Comment by melsophos** [comment]
Sorry for the late answer, I did not have internet up to now.
This works perfectly fine now, thank you!

**Comment by retorquere** [comment]
No worries, my pleasure.
