### ISSUE TITLE
dot-separated date not parsed

### ISSUE THREAD

**Issue by surmann** [ZotPlus/zotero-better-bibtex#406]
After my question on [tex.stackexchange](http://tex.stackexchange.com/questions/281366/presentation-of-year-and-isbn-of-betterbiblatex-from-zotero-in-latex) I think my problem is an issue of BetterBibLaTeX.
The export of the year and date filed are mixed and in the wrong format.

Here is my MWE:
BetterBibLaTeX 1.6.6 within Zotero Standalone 4.0 gives me an export of a book like this:

    @book{west_introduction_2000,
      edition = {2},
      title = {Introduction to Graph Theory},
      isbn = {978-0-13-014400-3},
      pagetotal = {470},
      timestamp = {2015-11-23T15:45:12Z},
      publisher = {{Prentice Hall}},
      author = {West, Douglas Brent},
      year = {22.08.2000}
    }

With the MWE LaTeX document

    \documentclass{scrartcl}
    
    \usepackage[style = authoryear, url = false]{biblatex}
    \addbibresource{book.bib} 
    
    \begin{document}
    \textcite{west_introduction_2000}
    \printbibliography
    \end{document}

I get the following result:
![screenshot](https://cloud.githubusercontent.com/assets/4048472/11596494/a371ce12-9ab5-11e5-9c6d-3015b170c6f5.png)
As you can see, the complete content of the year is shown and not parsed by biber because it is in the year field and in the wrong fromat. It should be 22-08-2000.

Do I have a problem with my fresh installation or is this an issue?

**Comment by retorquere** [comment]
Can you right-click that reference, select "send better bibtex error", and
post the resulting id here?

**Comment by surmann** [comment]
Sure: GJ2CFX6D

**Comment by surmann** [comment]
The book I posted above gives the correct result with version 1.6.13. Unfortunately, I have problems with some other references. Here are the corresponding ids:
ET2ZEDWU
ZGVAZRXX
WSCB9ITF

**Comment by retorquere** [comment]
What kind of problems do you experience for these references? 

No need to resubmit, but if you need to submit future error reports, you can select more than one reference and it will submit all of them at once.

**Comment by surmann** [comment]
Exactly the same as mentioned in the initial post. Is this information enough to identify the problem?
Ok, I will take this into account.

**Comment by retorquere** [comment]
I see. This wasn't the case before? That would be surprising. Or did you
just now notice it?

**Comment by surmann** [comment]
This was the case before. It was a general issue on nearly all references in my .bib file. However, I showed the problem on one example.

**Comment by retorquere** [comment]
Ah cool, that makes sense. I know what I have to do but I'm not near a pc
until later tonight.

**Comment by retorquere** [comment]
Release is out

**Comment by surmann** [comment]
Thanks for the release. Unfortunately, I cannot observe a change in the .bib file. I used version 1.6.14 and still observe this issue. The year still contains a complete date with dots. Here are two lines from a `git diff` between the last working version and the current one:
```
-  date = {2012-06-08}
+  year = {2012.06.08}
```

**Comment by retorquere** [comment]
For me locally and in the automated tests `2012.06.08` translates to `date = {2012-06-08}`. Could you try the following:

* Get the XPI from http://tempsend.com/100CD9E1CB and install it
* Turn on extended debugging in the BBT prefs
* Export the reference that has the `2012.06.08` date
* Submit an error report

I've added more debug loggin to the XPI at tempsend, hopefully it will tell me more.

**Comment by retorquere** [comment]
Can you submit that new report by right-click on this last reference? Then
I'll also have that to test with. Do the earlier 3 you submitted now export
correctly btw? They do for me.

**Comment by surmann** [comment]
I don´t know why, but now it works and I cannot reproduce the issue. Thanks for your fast support!

**Comment by retorquere** [comment]
Perhaps you didn't force the upgrade? By default, Firefox only checks for updates once every 24 hours.

**Comment by surmann** [comment]
I think I did and checked the version before my post. Never mind, no it works.
