### ISSUE TITLE
Breve accent for export

### ISSUE THREAD

**Issue by sterrier** [ZotPlus/zotero-better-bibtex#407]
When exporting my library as Better BibTeX, I've seen that the accents are automatically exported as a latex code (ö to {\"o} for example). However, I have an author with a "ğ" (g with breve accent, {\u g}) that doesn't and creates an error in latex. It there a way to add this during export so I don't have to correct it every time I export?

**Comment by retorquere** [comment]
I'd consider this a bug. Can you right-click that reference and submit a
bibtex error report? If you paste the debug id here I can investigate.

**Comment by sterrier** [comment]
8GTUKXQT

**Comment by retorquere** [comment]
If I import that reference, I get `{K{\"o}kpinar, Mehmet Ali and G{\"o}{\u g}{\"u}{\c s}, Mustafa}` for the authors on export. Which translator are you using, BibTeX or BibLaTeX? Your settings indicate that you have set BibTeX to export ASCII (which changes accents to LaTeX commands) and BibLaTeX to keep unicode characters, but that doesn't explain why some characters like ö are translated but ğ not.

**Comment by sterrier** [comment]
Now it exports as {\u g}. I don't understand... I replaced it with a normal "g" for a while to avoid the problem, and put the "ğ" back when you asked for the report. Maybe the original "ğ" character wasn't exactly "ğ" but something very close? Anyway this is solved for me. Thanks for looking!

**Comment by retorquere** [comment]
No problem. If it happens again, just submit a sample in the same way and
I'll have a look.
