### ISSUE TITLE
CSL variables only recognized when in lowercase, DOI not read from extra

### ISSUE THREAD

**Issue by stevious** [ZotPlus/zotero-better-bibtex#408]
I had the following error pop up using Zotero Standalone (v4.0.28.7, Better Bibtex 1.6.14) while trying to export my library to Better BibLaTeX:

An error occurred while trying to export the selected file.

I've submitted an error report - report ID is V8NUZWRC

I get the same error trying to export to Better BibTeX too. The normal BibTeX and BibLaTeX exporters from within Zotero seem to work fine though (although... the citation keys... *shakes fist* ).

Strangely enough, everything seemed to be working just fine until I rebooted my machine a little while ago, now I can no longer export my library :(

Cheers!

Edit: I've tried reverting back through previous versions of Better Bibtex - I've found that version 1.6.6 exports fine.

**Comment by retorquere** [comment]
From what I can tell, it's the 12th item in your export. Could you try to export only that item to verify that that is the culprit, and then right-click it and select "send BBT error"? That will give me the reference so I can try to reproduce.

**Comment by stevious** [comment]
Thanks for the very prompt reply! I'm not sure if this is the 12th item in my export, as some items do write out before the error and the order of items doesn't seem to match any order I can deduce! But I did find a few individual entries having the export issue - I have submitted one as report ID EK7XUBGA.

Many thanks!

**Comment by retorquere** [comment]
Tests are running.

**Comment by retorquere** [comment]
Your comments did help, BTW. Book section is peculiar in that Zotero doesn't allow one to specify a DOI for it; I'd venture to guess the failing entries all had a DOI or another field in the 'extra' field.

**Comment by retorquere** [comment]
New release is out. Firefox will update automatically somewhere within the next 24 hours, but you can manually upgrade in the FF addons pane.
