### ISSUE TITLE
Book sections have book title for journal in citekey

### ISSUE THREAD

**Issue by Jmuccigr** [ZotPlus/zotero-better-bibtex#409]
My cite key includes "journal:nopunct", and book sections are getting what are sometimes very long book titles added included. I was surprised by this, since I deliberately don't include book titles and they don't show up for books. It looks like this happens because item.publicationTitle gets set to the value of the book title for book sections.

Any way around this, either by not making this equivalence (if I have understood it correctly), or by there being some other way to include titles of journals, but not books?

**Comment by retorquere** [comment]
Can you submit a sample reference by right-clicking it and selecting "submit BBT error"?

**Comment by retorquere** [comment]
@nickbart1980 do you know which reference types are supposed to get journal abbreviations?

**Comment by retorquere** [comment]
never mind @nickbart1980, I found it. @Jmuccigr, I'd still dearly love to get a sample, I like to have a testcase for each change to prevent future regressions.

**Comment by retorquere** [comment]
I have a change lined up that most likely fixes the problem, but a testcase to make sure would help. Hint hint, nudge nudge and all.

**Comment by Jmuccigr** [comment]
Error report BP5EPZSC.

**Comment by retorquere** [comment]
Thank you -- tests are running.

**Comment by Jmuccigr** [comment]
Based on the behavior of the latest version, should I assume that this is "behavior as expected; do not fix"?

**Comment by retorquere** [comment]
No, I fixed the problem and cut a new release. I don't ever close an issue
as wontfix without explanation; that would be highly disrespectful of the
effort you took to submit the issue. Close without comment always means
"implemented, release scheduled". You should be able to upgrade right now.
You will need to right click and clear the BibTeX key; I don't dare just
regenerate all keys since it might lead to breakage in existing articles.

**Comment by Jmuccigr** [comment]
Thanks. Got the new version and it works.

Honestly I'm tempted to just use author-year-number on everything to avoid worrying about journal abbreviations at all.

**Comment by retorquere** [comment]
Ah right, I'd forgotten that: if you change the pattern it will regenerate all keys you haven't pinned, so just adding a character, closing prefs (or just unfocussing the pattern field really) and removing it will change all keys that are dynamic.
