### ISSUE TITLE
Sorting and optional particle handling

### ISSUE THREAD

**Issue by danilomm** [ZotPlus/zotero-better-bibtex#411]
Prepositions between family names are wrongly migrating [at least in portuguese] to the beginning of the entry. I don't know if there is a way to make an option on exportation, but for example:

    Oliveira, Maria Manuel Lobo Pinto de
    and
    Macedo, Agostinho José da Costa de

Are being converted as:

    author = {{de Oliveira}, Maria Manuel Lobo Pinto}
    author = {{de Macedo}, Agostinho Jos{\'e} da Costa},

And therefore are all grouped in bibliography in the “d”, and not in the corresponding “O” and “M” letters.

**Comment by retorquere** [comment]
@nickbart1980, this is your area of expertise, ideas?

@danilomm, how would you want to see them represented in Bib(La)TeX?

**Comment by danilomm** [comment]
Thank you for your prompt response. I'd like to see them like this:

    author = {{Oliveira}, Maria Manuel Lobo Pinto de}
    author = {{Macedo}, Agostinho Jos{\'e} da Costa de}

I guess that in Spanish that would be the same…

**Comment by retorquere** [comment]
@danilomm kan you right-click that reference and select "report BBT error"? It will give you an ID, if you post that here I will have that reference as a sample.

With the above BibTeX, the author will not only be sorted under O/M, but they will also be listed as "Oliveira" rather than "de Oliveira". Isn't the "de" really part of their last name? Is this perhaps only a sorting issue, in which case it would be related to #353?

**Comment by retorquere** [comment]
Could you try [this suggestion](https://github.com/ZotPlus/zotero-better-bibtex/issues/353#issuecomment-143433819) to see if that gets you the desired results? Alternately, http://tempsend.com/2FB535C954 has a version with a hidden preference `extensions.zotero.translators.better-bibtex.parseParticles`, which, if set to false, might do what you want, so if you could test that that would also be interesting to know.

**Comment by danilomm** [comment]
I've reported:
id: QAPD2R5R

As for your question, I guess that Portuguese is different than other languages in this issue:  "La Place", "La Grange", or "La Caille" (in French) are usually used as family names (and sorted alphabetically as "L"), the same happens in italian (De Angelis) and something different as reported in #353 in Dutch and German, where the particle goes in front but the name is not sorted as such ("van Gogh, Vincent" is sorted as "G").

However, in Portuguese it is simpler: the preposition is not a part of the last name. It just should stay where I put it in my Zotero record. I guess that it would be simpler than having its place changed by BBT, and then patching its sorting name with LaTeX, would't it? Then, those who want the particle to move over to the beginning simply would fill it in Zotero as "De Angelis, Andrea", for instance, or "van Gogh, Vincent", export it like that with BBT and then patch the sort order in LaTeX…

Thank you for sending a new xpi, and forgive me for my ignorance, but how do I set the ``extensions.zotero.translators.better-bibtex.parseParticles`` to false as a preference?

**Comment by retorquere** [comment]
You can set it by typing "about:config" in your browser location.

The "La Place" entries would be handled correctly as the Zotero name parser doesn't deem words starting with uppercase a particle. It's just lowercase stuff that gets shuffled around. I don't honestly know the finer points of name-handling in BibTeX, my goto guy for this is @nickbart1980, and we had a long discussion on this point in #383. But if the simpler rule fits your use-case, I don't mind adding this preference and exposing it in the prefs UI.

**Comment by danilomm** [comment]
Dear @retorquere , thank you very much for your fast answers and solutions.
I'm working now with that variable turned off.

As for putting it as an option in future standard updates, I think that the Portuguese and Spanish-speaker community would be thankful.

BTW, congratulations for the excellent work with this plugin. It has enormously improved my experience with Zotero and Pandoc (for I'm originally a markdown user, and I deal with LaTeX only for additional formatting and bibliographical issues). Thank you.

**Comment by retorquere** [comment]
It is my pleasure. So the setting does yields the desired effect? If so, I can add the preference to the UI.

**Comment by danilomm** [comment]
Yes.
Please, do so.

All the best,
Danilo

**Comment by retorquere** [comment]
Is [this](https://github.com/ZotPlus/zotero-better-bibtex/blob/411/test/fixtures/export/Sorting%20and%20optional%20particle%20handling%20%23411.off.bib) to your satisfaction?

**Comment by retorquere** [comment]
Fixed & will be released somewhere tonight.
