### ISSUE TITLE
URL missing in bibtex for Book Section

### ISSUE THREAD

**Issue by datascibox** [ZotPlus/zotero-better-bibtex#412]
Hello,

I have posted an error report ID "3UFN6DAK", for which I realized that the "url" field in the resulted .bib file is missing, even though it is available in the Zotero entry. This *only* happens with Book Section entries in Zotero, which are converted to @incollection or @inproceedings entries in BibTeX.

Thanks for considering this.
Cheers
Tod

**Comment by retorquere** [comment]
Is this specific for BibTeX? As far as I can tell, the BibLaTeX exporter does export the URL, and BibTeX (by default) doesn't support the URL field. There's a (currently) hidden preference `extensions.zotero.translators.better-bibtex.bibtexURLs` that puts URLs in a note field if set to `true`.

**Comment by retorquere** [comment]
Are you sure it does export URLs for other reference types under BibTeX? That would be really surprising. For BibLaTeX, the reference behind 3UFN6DAK (thanks BTW) does export the URL.

**Comment by datascibox** [comment]
Thanks for the prompt response.
I only use BibTeX and not BibLaTeX. For reference types other than Book Section, like Conference Paper or Journal Article, everything works perfectly.

Nowadays, we have lots of full-length conference papers published in a book, e.g. in a volume of a Springer book series, whether each individual paper has its own URL and DOI. Unfortunately the DOI is not captured by Zotero for this type of references (e.g. http://link.springer.com/chapter/10.1007/978-3-540-31880-4_22), while the URL is however captured appropriately. But then the Better BibTeX utility does not export the URL field. (I notice that the original BibTeX exporter of Zotero *does* export the URL for the reference type Book Section.)

Would it be possible that you enable the export of URL for the Book Section reference type, just like what we currently have with Conference Paper and Journal Article. Of course I am talking about Better BibTeX, not Better BibLaTeX.

Thanks for your work and support.
Tod

**Comment by retorquere** [comment]
Do you have an example reference for a Conference Paper that does export the URL for you? I have no issue making the change but I currently can't explain why you do get an URL for Conference Paper. Unless you have bibtexURL set to true, but then I can't explain why you don't get the url in the export, and in your earlier reference (which contains a copy of your settings) I don't see bibtexURL set.

**Comment by datascibox** [comment]
Ah sorry, it was my mistake. For the Conference Paper type, Zotero captures the DOI and also displays the URL field. Then Better BibTeX exports the DOI (and not URL as you've just pointed out), and I can live very well with DOI only. However, for the Book Section type, Zotero does not display the DOI field; it only captures and displays the URL field. URL now is my unique choice, but then Better BibTeX does not export this URL (while the Zotero BibTeX exporter does) :-(.

**Comment by retorquere** [comment]
Two options here: you could try [this version](http://tempsend.com/AB3B8A4540) to see if it does what you want, and if so, I'll probably release that as-is, but the other option you have is to add `DOI: whatever` to your reference and that will be exported as the `doi` field.

**Comment by datascibox** [comment]
Thanks for the file. I've just tried removing the recently updated Zotero Better Bib(La)TeX version on my Zotero Standalone and install the version you sent. But it still works like previously, i.e. for the Book Section type, I have URL field but it is not exported via the Better BibTeX exporter.

For the second option, honestly I don't know how to add DOI for a Book Section entry where Zotero does not display that field on the right panel.

**Comment by retorquere** [comment]
Did you change the preference?

**Comment by datascibox** [comment]
Sorry, I did not notice that there is an option to set. Now I set the option "Add URLs to BibTeX export..." to "in an url field" and it works!

However I see that the resulting .bib file has the url field like: url = {\url{http://...}}, and I wonder whether we need to wrap the URL within \url{}. Personally I don't think we need \url{} -- the BibTeX style file and/or the LaTeX template will have to handle an URL properly itself.

**Comment by retorquere** [comment]
Try http://tempsend.com/4BE408076A. It does assume your style understands these URLs will be in verbatim mode.

**Comment by retorquere** [comment]
I have added test cases, it would be great if you could review them, for the setting:

[off](https://github.com/ZotPlus/zotero-better-bibtex/blob/412/test/fixtures/export/BibTeX%3B%20URL%20missing%20in%20bibtex%20for%20Book%20Section%20%23412.off.bib)

[note](https://github.com/ZotPlus/zotero-better-bibtex/blob/412/test/fixtures/export/BibTeX%3B%20URL%20missing%20in%20bibtex%20for%20Book%20Section%20%23412.note.bib)

[url](https://github.com/ZotPlus/zotero-better-bibtex/blob/412/test/fixtures/export/BibTeX%3B%20URL%20missing%20in%20bibtex%20for%20Book%20Section%20%23412.url.bib)

**Comment by retorquere** [comment]
Oh BTW you can just literally type `DOI: something` on a line of its own in the "extra" field and it will be exported as a separate BibTeX fields. It's a workaround for Zotero missing fields for certain reference types.

**Comment by datascibox** [comment]
Many thanks! Everything is now perfectly.
Now I also know a workaround for adding Zotero missing fields. Thanks!

**Comment by retorquere** [comment]
It's not universal, but it works for a lot of fields, the bbt site has more
info.

**Comment by datascibox** [comment]
BTW, I don't think the recent removal of the option for capitalizing *only* iNNer words of the title field is delicate. That option removal results in all title being capitalized, and BibTeX styles (at least those I used) cannot render the title in a consistent format. Anyway, this is not a serious problem for me.

**Comment by retorquere** [comment]
Yeah, that was a bit of a thing. Zotero recommends however to store titles
and such in proper case rather than title case, in which case the new BBT
will do the right thing. There's no automated way to change titles to
proper case however.
