### ISSUE TITLE
Upgrade forgets to ask whether cache should be retained

### ISSUE THREAD

**Issue by lizzydoodle** [ZotPlus/zotero-better-bibtex#413]
When I am trying to export my Zotero library, the spinning beach ball keeps running forever - basically the entire MacBook Pro is coming to a crawl (switching apps takes a long time etc.) and there's no other solution than to Force Quit Firefox. Error ID J2S7FT84.

**Comment by retorquere** [comment]
You're on a beta version of Zotero? Could you try using the release version to see whether it still happens? There's not really much in the logs -- some errors from other extensions, but not really any significant BBT activity.

Could you also try disabling all other extension (except Zotero, obviously) to see if it's an interaction with another plugin?

**Comment by retorquere** [comment]
ExecuteJS and zotero quick look would be my first candidates.

**Comment by retorquere** [comment]
How many references does your library have btw, and is this the first time you export it?

**Comment by retorquere** [comment]
I can't reproduce the problem, so I really need your input.

**Comment by lizzydoodle** [comment]
Thanks for your support. I have been now able to export. It took a very long time. This has happened before, I have been running into this sort of issue repeatedly with new versions. In the past, it used to be some issue with special characters in my data. The Zotero database is relatively large (6403 items). While this is certainly not my first export, it has been the first export with the latest version. I should probably simply stop autoupdating when it works again (as it has done prior to the latest update). The database exported actually pretty fast. I have been disabling ExecuteJS, with no difference.

**Comment by retorquere** [comment]
* An update will generally drop the cache, which means first export after update will be slower
* However, when you have 3k items or more, the upgrade process ought to have asked you whether you want to drop the cache or not.
* It is of course your prerogative to not upgrade, but I'd rather not stimulate that, and I can't accept debug reports on any versions but the last version, so please do keep that in mind.

So it doesn't look like you're experiencing a crash. The slowness is unfortunate, and I'm always trying to make improvements there, but that's of no immediate help to you. You should have been offered an opportunity to retain your cache however, so I am going to look into that.

**Comment by retorquere** [comment]
The upgrade process now asks whether you want to keep the cache if you have over 1000 references in it. If you say "no" here, there should be no slowdown.

**Comment by retorquere** [comment]
.20 is out. I urge you to please not stop upgrading. You have full control now over whether or not your cache is retained.

**Comment by retorquere** [comment]
(the 1000 is settable in the preferences BTW, but with 6k you ought to get the conformation step in any case)

**Comment by lizzydoodle** [comment]
THANK YOU for the immediate support and the update (which I will keep installing of course now). The cache message worked just fine and did the trick. Again, thanks so much for solving this issue!

**Comment by retorquere** [comment]
No problem. This feature ought to have worked all along, so I'm pretty happy you reported this. I know BBT is substantially slower than the standard BibTeX exporter, so I know how necessary the cache is; I had not sufficiently tested this feature.
