### ISSUE TITLE
Duplicate citekeys generated in chronological order w.r.t. Date Added

### ISSUE THREAD

**Issue by datascibox** [ZotPlus/zotero-better-bibtex#415]
Hello,

We have a few thousands of references with citation keys generated with the convention [authorsAlpha:lower][year]. Please take a look at the report ID "A2SKB47D". Here duplicate citekeys are added a letter as suffix. The only problem I faced is that *older* references (in terms of their Date Added) have their citekeys considered as a *duplication* of the citekey of the most recently added, and thus added a letter as suffix. I think that this should be in reverse order in order to avoid possible key changing when new references are added and the whole library is undergone "Generate BibTeX key" at some point later.

For example, in the report ID "A2SKB47D", the reference with citekey "kn2008" was recently added, while the reference with citekey "kn2008a" had been added quite a long time ago. What one would normally expect is the key "kn2008a" assigned to newly added reference and the key "kn2008" still reserved to the previously added reference, right?

Many thanks for your great work!
Tod

**Comment by retorquere** [comment]
http://tempsend.com/A796C487F1 should do the job, could you verify?

**Comment by datascibox** [comment]
Verified. Works perfectly now.
Thanks for the swift action!
- Tod

**Comment by retorquere** [comment]
Super. I don't expect there to be any side effects, but I'm running the test suite anyway; when it passes, I'll release. Thanks for reporting this.

**Comment by datascibox** [comment]
Great! Looking forward to seeing the new release.

**Comment by retorquere** [comment]
.19 is out

**Comment by datascibox** [comment]
Updated and tested. Thanks!
