### ISSUE TITLE
Missing URL from @misc type

### ISSUE THREAD

**Issue by pmgurman** [ZotPlus/zotero-better-bibtex#416]
I am having some difficulties with the better bibtex output type. It currently does not output the URL for a zotero "Web page" item type. As an example, this is the output produced by the better biblatex translator:

    @online{EcoSure_2008,
    title = {{{EcoSure}} 2007 {{Cold Temperature Database}} - {{FoodRisk}}.org},
      url = {http://foodrisk.org/exclusives/EcoSure/},
    timestamp = {2013-08-13T03:58:33Z},
    author = {{EcoSure}},
    urldate = {2013-05-09},
    date = {2008-10-15},
    file = {EcoSure - - 2008.pdf:\\storage\\F7EJC7IR\\EcoSure - - 2008.pdf:application/pdf;EcoSure 2007 Cold Temperature Database - FoodRisk.org:\\storage\\WNP5N8TP\\EcoSure.html:}
    }

This is the equivalent result using the better bibtex translator:

    @misc{EcoSure_2008,
    title = {{{EcoSure}} 2007 {{Cold Temperature Database}} - {{FoodRisk}}.org},
    timestamp = {2013-08-13T03:58:33Z},
    urldate = {2013-05-09},
    author = {{EcoSure}},
    month = oct,
    year = {2008},
    file = {EcoSure - - 2008.pdf:\\storage\\F7EJC7IR\\EcoSure - - 2008.pdf:application/pdf;EcoSure 2007 Cold Temperature Database - FoodRisk.org:\\storage\\WNP5N8TP\\EcoSure.html:}    
    }

Any ides? Is this something i am doing wrong or something going on inside the translator?

Other than this niggle, this is a great addon to zotero, that has solved me a lot of time and effort.

**Comment by pmgurman** [comment]
As soon as i posted this, i found the button on the citation tab to add URL's to bibtex. My apologies for adding this issue.

**Comment by retorquere** [comment]
No need to apologize. I'd rather have one report too many over one to few. 

The reason why this is not on bbt default is that bibtex by default does not support urls, and apparently sometimes trips over it.

**Comment by pmgurman** [comment]
Fair call. It looks like I will be forced down the biblatex path anyway as I cannot get any form of accessed date working. Oh well.

**Comment by retorquere** [comment]
From the top of my head (not near a pc) the "note" setting does something
to that effect, otherwise look at the docs on the website for "customized
exports"
