### ISSUE TITLE
No urls in BBT

### ISSUE THREAD

**Issue by barklem** [ZotPlus/zotero-better-bibtex#418]
I can't seem to get any urls to export using Better Bibtex.  It seems to work for Biblatex.
I think I have checked all required preferences.

This used to work for me, but this problem seems to have appeared recently.

Thanks, Paul

**Comment by retorquere** [comment]
What do you have set for the "Add URLs to BibTeX export" preference?

**Comment by barklem** [comment]
I have “in an url field” at present, but have tried the note option.

**Comment by retorquere** [comment]
Odd. Could you do these things for me:

1. Export that reference, then right-click it and select "send BBT error". It will give you a debug ID, if you post that here, I'll have that reference and any errors it may have generated during exporting.
2. If you don't have too big a library, could you go into the BBT prefs, debug pane, and click "Reset cache", and see if you now do get the URL.

Please do 1. before 2. as 2. will skew the test.

One possible reason for the url not showing up could be that you have a fairly big library and you were offered a chance to not drop the cache when upgrading. It's a fairly obnoxious popup, you would remember seeing it. The downside of keeping the cache during upgrade is that newly implemented behavior won't be reflected in the export until the cache for the corresponding entry is dropped; one way is to drop all entries at every upgrade (and that used to be the way things went), the other is to wait for a change to occur on a reference (which still works).

**Comment by barklem** [comment]
> On 15 Dec 2015, at 10:53, retorquere <notifications@github.com> wrote:
> 
> Odd. Could you do these things for me:
> 
> 	• Export that reference, then right-click it and select "send BBT error". It will give you a debug ID, if you post that here, I'll have that reference and any errors it may have generated during exporting.

2GAZVM56

> 	• If you don't have too big a library, could you go into the BBT prefs, debug pane, and click "Reset cache", and see if you now do get the URL.
> Please do 1. before 2. as 2. will skew the test.

Yes, now it works!

> One possible reason for the url not showing up could be that you have a fairly big library and you were offered a chance to not drop the cache when upgrading. It's a fairly obnoxious popup, you would remember seeing it. The downside of keeping the cache during upgrade is that newly implemented behavior won't be reflected in the export until the cache for the corresponding entry is dropped; one way is to drop all entries at every upgrade (and that used to be the way things went), the other is to wait for a change to occur on a reference (which still works).

Yes, I remember seeing it, so this was certainly the reason.

Many thanks for your amazing quick help, and this great addon to zotero!

Cheers, Paul

**Comment by retorquere** [comment]
I am reading through the text in the popup now, and I see that the effect you experience hasn't really been laid out clearly. Is there a way I could have worded this that would have explained this better? I'm trying to avoid having a big wall of text (no one reads those) or some obnoxious confirmation method (like 'type "yes" here to...'), but preferably I would be able to disclose what's happening in a way that you as a user would be aware of the effects of the choice.

**Comment by barklem** [comment]
If you send me the text of the popup I’d be happy to comment - I don’t have it.

If I remember correctly, it seemed to me like the default option would be to not reset the cache.

**Comment by retorquere** [comment]
The popup reads:

> You have upgraded BetterBibTeX. This usually means output generation for Bib(La)TeX has changed.
> If you want this change to be applied immediately, you can clear the BibTeX cache. If you have a large library, first (auto)export will be slower than usual
> If you are in principle satisfied with the output you had, you can just have Better BibTeX replenish the cache as items are changed or added
> 
> Do you want to reset the BibTeX cache now?

The default ought to be "Yes" which would mean the cache would be cleared at that moment.

**Comment by barklem** [comment]
I guess the issue was that I was “in principle satisfied with the output [I] had”.  Then the problem was the output was not what I had before.  I think it would be good to make it clearer that the default position would be to clear the cache.

How about something like:

You have upgraded BetterBibTeX. This usually means output generation for Bib(La)TeX has changed, and it is recommended to clear the cache in order for these changes to take effect.  

If you have a large library, this may lead to a slow first (auto)export, and you may consider skipping this step. 

Do you want to reset the BibTeX cache now?

**Comment by retorquere** [comment]
OK, I've changed it to:

> You have upgraded BetterBibTeX. This usually means output generation for Bib(La)TeX has changed, and it is recommended to clear the cache in order for these changes to take effect.
>         
> Since you have a large library, with `<N>` entries cached, this may lead to a slow first (auto)export as the cache is refilled.
>
> If you don't care about the changes introduced in `<release>`, and you want to keep your old cache, you may consider skipping this step.
>
> If you opt NOT to clear the cache, and you experience unexpected output at some point in the future, please first clear the cache from the preferences before reporting an issue
>
> Do you want to reset the BibTeX cache now (recommended)?

**Comment by barklem** [comment]
Ok, that seems very clear now.

Thanks again.

Cheers, Paul

**Comment by retorquere** [comment]
Thanks again for your report and the feedback.
