### ISSUE TITLE
Better Bibtex exports File and Note even when these options are unchecked

### ISSUE THREAD

**Issue by IdoBar** [ZotPlus/zotero-better-bibtex#419]
__Report ID__: 6BEX6DCH

__Description__: When exporting bibliographic entries, the tool exports the "File" and "Note" fields even when these are not checked in the "Translator Options".
The Note field when existing is being printed in most bibliography styles and causes undesired output (such as abstracts being printed with the bibliography entry)
The File field is usually only relevant for the local repository and is not relevant for citation.

Thank you very much.

[Exported Items.txt](https://github.com/ZotPlus/zotero-better-bibtex/files/66574/Exported.Items.txt)

**Comment by retorquere** [comment]
The meaning Zotero has traditionally given to these checkboxes is subtly different; usually these are interpreted as:

* File: should I export the file attachments along with the bib file, or just paths to them
* Notes: should I export any attached notes

interpreted this way, the BBT exporter kind of does what it's supposed to do: it's not exporting files, and the "note" field that shows up has the content of the extra field (guessing here, I don't know for sure).

There is a workaround to achieve what you want: in the preferences, enter `note, file` in the field where it says "Fields to omit from export".

**Comment by IdoBar** [comment]
Thank you very much,
I've tried your workaround and it world perfect for me.
Apologies for the false bug ticket.

**Comment by retorquere** [comment]
It's not a false bug ticket, you had a genuine question. I always prefer
people ask when in doubt; better one too many than one too few. Glad I
could be of help.

**Comment by IdoBar** [comment]
Thanks!
