### ISSUE TITLE
File field format customization

### ISSUE THREAD

**Issue by Dabsen** [ZotPlus/zotero-better-bibtex#423]
This zotero forum discussion seems to suggest that there is an option in better bibtex to alter the file field format to make it compatible with ebib : 
https://forums.zotero.org/discussion/38209/problem-with-export-to-bibtex/
which would be convenient for me (althouth I realize this is not a priority and is more of an ebib bug).

I cannot find this option. Has it been deleted in a later version ? if not, where can I find it ?

**Comment by retorquere** [comment]
It's in the "Import/export" pane, a checkbox with the text "Export attachments without metadata"

**Comment by Dabsen** [comment]
Excellent, thank you ! It works.

**Comment by retorquere** [comment]
It wasn't too clear. I've added an explanation of the preferences at https://zotplus.github.io/better-bibtex/configuration.html
