### ISSUE TITLE
BBT doesn't work with zotero 4.0.22, notification of this is blank. 

### ISSUE THREAD

**Issue by mullenkamp** [ZotPlus/zotero-better-bibtex#425]
Hi,

Sorry for the vagueness, but I thought I had one problem and it seems as though it's a bigger problem.

I'm running version 1.6.24 on Debian with Zotero standalone. 
When I installed the add-on, I tried to export a file/collection, but it failed similarly to https://github.com/ZotPlus/zotero-better-bibtex/issues/421

Then I tried to make a proper error report from the preferences menu. I activated it, restarted zotero (a couple times), but I got no option to provide an error report as you mention in https://zotplus.github.io/support.html

I don't know if this has any significance, but in the preferences menu for better-bibtex there is a tab named "Better BibTeX has been disabled". There's nothing in it though...

I sense that the whole add-on is simply not working.

Thanks for your help.

**Comment by retorquere** [comment]
Can you call up the debug log from the zotero advanced preferences and
attach it? Which zotero version do you run, and what other plugins are
installed?

**Comment by mullenkamp** [comment]
Here's the log file. The interesting stuff seems to be at the top and the bottom.
The Zotero version is 4.0.22-1 and I am also using the Zotfile add-on. I'm also using xulrunner-24.0 if that has any meaning to you.
[debug-BBT.txt](https://github.com/ZotPlus/zotero-better-bibtex/files/74837/debug-BBT.txt)

Thanks again!

**Comment by retorquere** [comment]
I'd have to investigate why the message in de disabled window isn't shown,
but the problem is your zotero version. BBT requires at least 4.0.27 from a
technical point of view (the zotero internals changed incompatibly between
4.0.26 and 4.0.27), and only the latest is tested to work (currently
4.0.28). To use BBT, you will have to upgrade.

**Comment by retorquere** [comment]
I think I've found why the notification is blank thanks to the error report you attached.

**Comment by retorquere** [comment]
I realize Debian may not have packaged a newer Zotero (Debian is on the conservative side of things when it comes to upgrades). There is a PPA (https://forums.zotero.org/discussion/25317/install-zotero-standalone-from-ubuntu-linux-mint-ppa/) which appears to install the latest version. I have not tried this though, I've simply installed the standalone version from the zotero website.

**Comment by mullenkamp** [comment]
Thanks. I did manage to install the newest version of Zotero on Debian from a script in a Github repository: https://github.com/smathot/zotero_installer
Which is by the same guy who made the PPA for Ubuntu.

Using the new Zotero version, the BBT plugin seems to work fine (so far).

Thanks again!
