### ISSUE TITLE
Atom Zotero Scan

### ISSUE THREAD

**Issue by musebrarian** [ZotPlus/zotero-better-bibtex#429]
Error code: VH52AHRA

Not sure if this is a BBT problem or the Atom package.

Zotero Pick works fine, but when Zotero Scan is run,  Zotero locks up and crashes. 

OSX 10.9.5
Atom 1.3.2
Zotero (standalone) 4.0.28.2

**Comment by retorquere** [comment]
The problem is in BBT. I'm guessing you have a pretty large library, and the atom scanner demands that all references have a citation key set, so it generates one for every reference that doesn't have one before the scan starts. Firefox is single-threaded, so everything freezes while it does that; depending on how many you're missing, it can take a while.

I've added a change that will warn you about this happening and allow you to abort (you can try [this version](https://s3.eu-central-1.amazonaws.com/zotplus-builds/zotero-better-bibtex-1.6.25-travis-2340.xpi) to try it), but I'm open to better suggestions. In the interim, exporting your entire library to Better BibTeX once will prime the cache, and it should be fast after that. This priming export will take a long while depending on how many references you have.

**Comment by musebrarian** [comment]
Thanks for the quick reply.   Yes, I have a very large Zotero library. (2500 items, my .bib export ended up being 1.8 Mb.  Boy that's embarrassing - I need to do some cleanup. :) ) 

"exporting your entire library to Better BibTeX once will prime the cache"

It took me a while to figure out that this wasn't in the BBT preferences window and that it means I need to go back to my main Zotero and manually do an export. (and still not sure that was the right thing to do).  Maybe this could be clearer in the documentation for others who follow. 

Zotero  Standalone gear menu -> Export Library
Select "Better BibTex"
Check "Keep Updated"

I hadn't done that before, so that may could  be the source of the original error.  

After exporting my library and being a little more patient when Atom couldn't get the bibliography right away (it churned away for a good 3-4 minutes), Zotero scan successfully added a bibliography to my markdown. 

Thanks!

**Comment by retorquere** [comment]
> Thanks for the quick reply.   Yes, I have a very large Zotero library. (2500 items, my .bib export ended up being 1.8 Mb.  Boy that's embarrassing - I need to do some cleanup. :) ) 

I have a little under 2900, I know how it is. I know BBT users who have 30k references.

> "exporting your entire library to Better BibTeX once will prime the cache"
>
> It took me a while to figure out that this wasn't in the BBT preferences window and that it means I need to go back to my main Zotero and manually do an export. (and still not sure that was the right thing to do).  Maybe this could be clearer in the documentation for others who follow. 

That was indeed what I meant. Perhaps I should add a feature to just generate all citation keys; the export just does it as a side effect.

> Zotero  Standalone gear menu -> Export Library
> Select "Better BibTex"
> Check "Keep Updated"

You don't need to tick "Keep updated"; ticking this means it will export every change. You can remove this full-library auto-export in the BBT settings. Just exporting once will "touch" every reference and give it a citekey. After that, new references will either immediately get a citekey, or a scan will generate the few missing ones but they will be so few you won't notice.

> I hadn't done that before, so that may could  be the source of the original error. 

It is very likely the reason Firefox froze. If you hard-aborted Firefox (which I would have done), not all keys it generated will have been saved, so you'd see it again next time.

> After exporting my library and being a little more patient when Atom couldn't get the bibliography right away (it churned away for a good 3-4 minutes), Zotero scan successfully added a bibliography to my markdown. 

And after this, it should be near instantaneous. BBT does a whole lot of processing, so having the cache filled makes a [huge difference](https://zotplus.github.io/better-bibtex/cache.html).

**Comment by retorquere** [comment]
I've added some text to explain the problem (and the workaround) to the [bbt docs](https://zotplus.github.io/better-bibtex/performance.html)
