### ISSUE TITLE
Cache no preserved

### ISSUE THREAD

**Issue by lizzydoodle** [ZotPlus/zotero-better-bibtex#431]
I really liked the new feature that asked me, whether I wanted to preserve my cache - I have a rather extensive library and so exports tend to take a veeeery long time to export if the cache is not retained. With the last update I did not see the dialogue box anymore that asked me, whether I wanted to preserve my cache or proceed unchanged. Also, I am not able to locate the option for the threshold when the new cache is being offered? Thanks for your support! I am using v. 1.6.28

**Comment by retorquere** [comment]
The option is hidden (see [here](https://zotplus.github.io/better-bibtex/configuration.html#hidden)), but the prompt only appears if you have more than that many cached, not whether you have that many references. If you just changed a preference, which will [drop the cache](https://zotplus.github.io/better-bibtex/performance.html#cache-drop)?
