### ISSUE TITLE
yaml output for usage with pandoc-citeproc

### ISSUE THREAD

**Issue by danilomm** [ZotPlus/zotero-better-bibtex#432]
Hi,

As a markdown user, I came to appreciate plain-text formats in "cleaner" versions.
Today, I use pandoc as a file converter, and therefore pandoc-markdown syntax.

Pandoc-citeproc, which handles bibliographies, allows us to add bibliographical information as a yaml block directly into the text file. Thus, it is possible to have a standalone clean human-readable file, which can be safely stored without the risk of losing bibliographical information. It also makes easier cooperation. 
I guess the benefits would be the same as with adding bibliographical information in LaTeX files -- to which you may be used to.

Pandoc already provides a conversion tool bib2yaml. However, exporting directly into yaml from Zotero would spare us this step.

Therefore, since you already have an export tool for json, maybe it is possible to provide an yaml output as well. It would be great for markdown users!

More information on:

pandoc:
http://www.pandoc.org/README.html#citations

pandoc-citeproc [and csl standard]
https://github.com/jgm/pandoc-citeproc/blob/master/README.md

All the best,

Danilo

**Comment by retorquere** [comment]
*Technically*, the Better CSL JSON exporter [already does this](http://yaml.org/spec/1.2/spec.html#id2759572).

**Comment by danilomm** [comment]
Yes, as I said:

>  since you already have an export tool for json, maybe it is possible to provide an yaml output as well;

:)

yaml is a superset of json, but it is not json -- and therefore cannot be included as a yaml block in a text.
Therefore, for pandoc-citeproc users willing to have a “standalone human-readable document” with all its bibliography embedded, it still requires conversion.

Since better-BibTeX is “half-the-way” towards a yaml format with json, can/will it be done?

**Comment by retorquere** [comment]
I'm looking into it, but I need to figure out how to cache partials, or performance will be abysmal.

But as a technical point, since yaml is a superset of json by specification, every valid json document is also a valid yaml document. If Pandoc doesn't allow json where it says it will accept yaml, it's not following the spec.

That said, I'm going to give it a shot.

**Comment by danilomm** [comment]
Thank you!

BTW:
pandoc accepts json. 
A json file, as much as a bib file [and many others](https://github.com/jgm/pandoc-citeproc/blob/master/man/pandoc-citeproc.1.md), can be used as an external bibiographical resource for a md file. 

The point is that only with yaml (for its human-readability) a bibliography can be embedded into the original md text file.
In [pandoc-markdown syntax](http://pandoc.org/README.html#citations), it works like including the bibliographical bib entries into a tex file -- making it a "standalone" enduring document.

**Comment by retorquere** [comment]
I understand that pandoc *also* accepts external CSL-JSON as bib resource, but according to the JSON spec, if pandoc accepts inline yaml, it must ipso facto also accept JSON in the same place (since JSON is apparently a strict subset of YAML). If it does not (and that wouldn't be weird, as no one I know knows that this relation exists), it is out of spec; it says it accepts YAML, JSON is YAML, it must accept JSON *everywhere* it accepts YAML.

**Comment by retorquere** [comment]
And it does, in fact: if you pass [this](https://gist.githubusercontent.com/retorquere/157c8304f02f77a7886c/raw/4f6fcde4ffd0531532061379c227829ab9bff0e9/json.md) through `pandoc json.md --filter pandoc-citeproc -o json.html`, you get a bibliography.

**Comment by danilomm** [comment]
Yes, technically speaking, of course you have a point. It *can* be done with other formats.

One point I'm trying to stretch here is the one of human readability.
As much as markdown is more human-readable than LaTeX,
citation-yaml is more human-readable than Bibtex. 
citation-json stands halfway, because it still has the brackets and lots of indentation.

Therefore, yaml is the format chosen as “conceptually” compatible with markdown syntax.

Perhaps [this article](http://blog.martinfenner.org/2013/07/30/citeproc-yaml-for-bibliographies/) makes the point better than I do.

One of the things that attracted me to markdown syntax was its human readability in plain-text format.
It is a long-standing text document that can be fully read by anyone in a long-term. Imagine someone wandering through thirty-year-old files in the future. Markdown files with a yaml bibliography will still be readable to anyone who deals with the file as a document. 

All the best,
Danilo

----

p.s. Just as a matter of curiosity: which bibliography parsers process json bibliography? I never managed to find it out.

**Comment by retorquere** [comment]
I might have something, but the mozilla signing server which they love so dearly is, as usual, offline, so I can't do anything.

re: p.s.: citeproc-js and its derivatives (of which pandoc is one as far as I know).

**Comment by retorquere** [comment]
Could you see if https://s3.eu-central-1.amazonaws.com/zotplus-builds/zotero-better-bibtex-1.6.28-travis-2370.xpi does what you want?

**Comment by danilomm** [comment]
Thank you very much for your fast and good work.

I've performed some tests with some sample references, with the following results:

`````

------------------------------------------------------------------------------
file                    generation process              results with pandoc
----------------------  ------------------------------- ----------------------
sample-bbt-bibtex.json  BetterBibTex "BibTex JSON"      couldn't parse 

sample-bbt-csl.json     BetterBibTex "CSL JSON"         parsed but couldn't 
                                                        find the references.

sample.yaml             BetterBibTex "YAML"             couldn't parse

sample.bib              BetterBibTex "BibLaTeX"         parsed fine
sample-bbt.yaml         bib2yaml pandoc-citeproc tool   parsed fine
------------------------------------------------------------------------------

`````

To the file `sample.yaml` I have then added:

1. Blank lines before every entry;
2. A header and footer:

~~~~

---
references:
[entries]
...

~~~~
And then it has been parsed without problem. :)

Then I've exported my full collection as `yaml`, and I noticed that the notes and files are being exported together, which brings us to a possible need of the same options as we have to export it as `BibLaTeX`…

I'm sending the files [here](https://dl.dropboxusercontent.com/u/6602984/sample-yaml-test.zip).

Still, I'm having trouble with title capitalization. I've set the language to `-V lang=pt` on export incantation, but it still comes out capitalizing every single word (english standard).

I'll try to bring Mr. MacFarlane into this conversation too.

All the best,

Danilo

**Comment by retorquere** [comment]
"BetterBibTex JSON" is the export format used for sending debug logs. I can't remove it from the export list, but it's not meant to be used for anything but debugging. It makes sense it wouldn't parse to a bibliography.

There's a new build [here](https://s3.eu-central-1.amazonaws.com/zotplus-builds/zotero-better-bibtex-1.6.28-travis-2371.xpi) which adds the leading dashes, the trailing dots, and newlines between the references. But I thought you'd want to have the YAML inline? 'm not sure whether the dots and dashes are part of the YAML (it parses fine without it in python and ruby either way) or whether they are fences around the YAML. The requirement for empty lines between references certainly is not according to spec, but it's also not against the spec, so it's easy to add.

When you say

> I noticed that the notes and files are being exported together,

I don't understand. When I export to CSL YAML, notes and attachments are not exported at all, which is what I'd expect.

When you say that you set `-V lang=pt`, where do you set that? Is that a Zotero flag?

**Comment by retorquere** [comment]
(in any case, capitalisation is a different problem, so please file a new issue for that separately)

**Comment by danilomm** [comment]
It occurs now a *Javasrcipt error* with all the formats.

> capitalisation is a different problem,

ok.

**Comment by retorquere** [comment]
Can you send an error log for that export error? The version behind that link has passed all the tests in the suite on my end.

**Comment by danilomm** [comment]
I've restarted zotero twice, tested Java version and it worked. Who knows? :)

As for the format:

- It still lacks the header `references:` on top, bellow the lines. But with that it's working fine!
- The three dashes and three points are [yaml standard](http://www.yaml.org/spec/1.2/spec.html#id2760395). In markdown, as you realized, it serves to aisle a yaml block from text.
- I'm not 100% sure about the lack of quotes in text fields (provided that pandoc's examples don't have them either). How does it behave in json -- bringing it to your field -- when there is quoted multiline text into the field contents?

**Comment by retorquere** [comment]
Ah. So it's not really a reference block, it's just a block of metadata, of which one key can be references. Which makes generating the fences a little tricky; it assumes you want no other metadata. Anyhow, a new version can be found [here](https://s3.eu-central-1.amazonaws.com/zotplus-builds/zotero-better-bibtex-1.6.28-travis-2373.xpi).

JSON is very rigid when it comes to newlines; you can enter them as `\n` in a string, but you can't actually break lines within JSON. YAML is much more flexible that way. I honestly don't exactly know what the rules are regarding when you must use quotes. I just use js-yaml to generate YAML, pumping in the same CSL objects that the Better CSL JSON exporter generates.

**Comment by danilomm** [comment]
Thank you.
It is working right out of the box now!

The only remark is that standard pandoc extension is `yaml`, and not `yml` (it simply doesn't accept this last one).

On the notes issue, I guess I had an extensive unnoticed abstract in some record, that seemed to be a note.
I tried with specific files and there is no note in the final yaml.

As for the quotes' standards, let's hope for the best. Truth is I haven't found documentation on the “BibYAML” syntax other than in pandoc's examples.

So, will it be implemented in standard BetterBibTeX? :)

**Comment by retorquere** [comment]
yup. I'm starting a release build now.

**Comment by danilomm** [comment]
Thank you very much once again.
This tool will be very useful for me -- and I guess that for many other users too.

All the best,
Danilo

**Comment by danilomm** [comment]
(I think that the link to "latest version" on README is broken)

**Comment by retorquere** [comment]
On what page is this?

**Comment by danilomm** [comment]
https://github.com/ZotPlus/zotero-better-bibtex/blob/master/README.md
