### ISSUE TITLE
Suggestion: Rephrase configuration options and/or add link to the docs

### ISSUE THREAD

**Issue by openmedi** [ZotPlus/zotero-better-bibtex#433]
Even as a user who uses Better BibTeX now quite regularely I find myself getting confused by or being unsure of the meaning of certain options on the config pages of Better BibTeX. Most recent case in point:

```
Auto-pin citation keys (requires sync to be off or auto)…[options]
```

What sync is meant here? The webdav/zotero-sync itself? The auto-export which can be understood as a sync in itself? There is a lot of ambiguity here that seems to me doesn't have to be there. Of course, the best would be to reformulate the preferences of Better BibTeX to be less ambigious, but one first step that would improve the usability greatly would be a link/questionmark-button like this one on the config pages of the extension that links to the most times [very helpful documentation](https://zotplus.github.io/better-bibtex/index.html).

<img width="35" alt="screen shot 2016-01-13 at 17 30 50" src="https://cloud.githubusercontent.com/assets/423471/12300372/7162e214-ba1b-11e5-95ee-ba159ee4459e.png">

**Comment by retorquere** [comment]
Those are all valid comments; I can't get to it immediately as I am a little busy right now.

**Comment by retorquere** [comment]
It is indeed webdav/zotero sync itself. I'm looking into adding those question-mark thingies. In the mean time, if you have a better phrasing in mind, I'm very much open to changing that text. I couldn't think of anything better.

**Comment by retorquere** [comment]
Links to documentation have been added.
