### ISSUE TITLE
Dead link in README.md

### ISSUE THREAD

**Issue by kingjr** [ZotPlus/zotero-better-bibtex#436]
The link indicated in the `Configuration` section of `README.md` seems dead, even if copied and pasted:

https://zotplus.github.io/better-bibtex/chrome://zotero/content/preferences/preferences.xul#better-bibtex

**Comment by kingjr** [comment]
![screenshot from 2016-01-19 15 45 46](https://cloud.githubusercontent.com/assets/4881164/12431501/bd9d8038-bec3-11e5-8a9a-ece0ee9752f5.png)

**Comment by retorquere** [comment]
OK, the double header is gone, but from what link did you get there?

**Comment by kingjr** [comment]
The link I get is '
http://zotplus.github.io/zotero-better-bibtex/chrome://zotero/content/preferences/preferences.xul#better-bibtex
'

I'm using firefox 42.0 for Ubuntu canonical, with 14.04.

**Comment by retorquere** [comment]
But where is this link?

**Comment by retorquere** [comment]
You mean the link under the "configuration" header in the README? That link is not clickable.

> You can get also there by pasting this link in Firefox. Clicking the link won't work, sorry.

**Comment by kingjr** [comment]
Yes, I'm copying this link with a right click (copy link location)) and
pasting it. Should the user do something else?

**Comment by retorquere** [comment]
Ah, I see the problem now! Hmm, Jekyll doesn't seem to want to render these links anymore. I've replaced that description.

**Comment by kingjr** [comment]
Ok, thanks @retorquere for the quick response.
