### ISSUE TITLE
Fatal error when checking for cache preserval

### ISSUE THREAD

**Issue by Cutuchiqueno** [ZotPlus/zotero-better-bibtex#437]
See Issue Report: DHKXGZZV

One day Better Bibtext just stoped working. No keys are shown anymore in the special key field, no keys are generated anymore.

The reason is an automatic update of Better Bibtex from the 15.01.2016

**Comment by retorquere** [comment]
This is on standalone?

**Comment by retorquere** [comment]
Could you give https://s3.eu-central-1.amazonaws.com/zotplus-builds/zotero-better-bibtex-1.6.31-travis-2385.xpi a try?

**Comment by Cutuchiqueno** [comment]
works like a charme again. Thank you very much for the quick respons and fixing!
