### ISSUE TITLE
BibTeX name escaping has a million inconsistencies

### ISSUE THREAD

**Issue by noehmeier** [ZotPlus/zotero-better-bibtex#438]
I used before for export the "BibTeX" format, where i can change the encoding from utf8 to western. There everything works fine. I think i might need this for German umlauts (äöü) in the names, but im not sure. But otherwise i get a LaTeX error. When i change at the export to "Better BibTeX" for automatic export (keep file updated), the dropdown for the encoding is not shown. In the settings i see, that it uses utf8 by default. I can't change the encoding in the settings table, too.

Did i something wrong or can you add the encoding dropdown menu or an other option that i can change the encoding for automatic exports?

**Comment by retorquere** [comment]
Absolutely; you can toggle this behaviour [in the preferences](http://zotplus.github.io/zotero-better-bibtex/configuration.html#export-biblatex-as-ascii). The "export charset" in the standard Bib(La)TeX translators do something similar, but they don't actually export to the selected charset; it's just that if you select anything but UTF-8, you get the behaviour that BBT calls "export as ASCII".

**Comment by retorquere** [comment]
But rather, you want [this](http://zotplus.github.io/zotero-better-bibtex/configuration.html#export-bibtex-as-ascii) preference, sorry.

**Comment by noehmeier** [comment]
Hi retorquere, thank you for your fast response. When i check the box "Export BibTeX as ASCII" i don't get a encoding error anymore, thanks a lot :-) 

But i get a "! File ended while scanning use of \thebibliography." error. I tried to understand the problem step by step, so i removed all sources in the .bib file and added them one by one. So i found out, that there is a problem with the brackets.

"Better BibTeX" format (works not):
author = {**{**N{\"o}me**}**, Name},

"BibTeX" format (works):
author = {N{\"o}me, Name},

Is it possible to change this format?

**Comment by retorquere** [comment]
Do you have a minimal example that fails? Because [this example](https://www.sharelatex.com/project/54feca38f58d781e0c982eeb) compiles. Feel free to edit that sample, BTW.

I don't know exactly what damage would result from not protecting the given name, so I'd love to know what the resident BibTeX experts have to say on the matter -- @gracile-fr, @nickbart1980, how say you?

**Comment by retorquere** [comment]
Wasn't "Export BibTeX as ASCII" already enabled BTW? It's the default.

**Comment by noehmeier** [comment]
Well, i used your example and i get the same error in my environment. In your web-example it works. If i use the follwing, it works for me:

@article{a,
  author = {N{\"o}me, Name},
  year         = {2015},
  title        = "Why Is Apple Launching a New Version of the {{iPod}}?"
}

I'm using an extended latex template and I am not the latex professional to find the dependencies to reproduce the problem based on your example. If you have an idea of the direction in which the error could be, you are welcome and maybe i could locate it. Otherwise, you are friendly guys (thank you for your fast responses) and if it is a problem on my side, i don't want to take your time. Maybe its better i use the default Zotero, where it works for me, i just wanted to safe time with skipping the export process each time ;-)

Yes, it was set by default. I played with the parameters, because of the errors.

**Comment by retorquere** [comment]
There's no guys, just me :) 

* To verify: the MWE from sharelatex does not compile in your environment? If so, this is not a matter of packages, since it's not loading any.
* Which LaTeX processor do you use? 
* What bibliography processor do you use?
* What happens if you use `author = {{{N{\"o}me}}, Name}`?

**Comment by noehmeier** [comment]
Sorry, i ment you :)
I didn't try your example in my environment. I copied the article to my environment and it failed, that was that what i ment. I mean with my environment my latex project.

I am on a Mac and i use MacTeX (/Library/TeX/latex") with BibTeX (/Library/TeX/texbin/bibtex) and texmaker as IDE. The bibliographystyle is "alphadin".

I use also the follwing (maybe relevant?) packages:
\usepackage{ngerman} 
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}

author = {{{N{\"o}me}}, Name} doesn't work also.

If you look into MWE, i get the error "argument of \T1\" has an extra }." like on mine environment, but it compiles anyway there.

**Comment by retorquere** [comment]
I've found some sources that do indicate these errors happen, and they have something to do with "fragile commands" (but I have no idea what that means). The easiest way to work around that problem is to brace individual letters instead of whole words, but that runs into [this](http://tex.stackexchange.com/questions/10772/bibtex-loses-capitals-when-creating-bbl-file/140071#140071) problem. Still trying to figure out a way that works everywhere.

**Comment by retorquere** [comment]
It's not just braces -- `author = {nN\"ome, Name},` also yields an error (non-fatal on sharelatex). In the MWE on sharelatex, I don't get the `File ended while scanning use of \thebibliography.` error though. Locally on my mac, compilation stops at `Argument of \OT1\" has an extra }`.

I've submitted the problem to [stack exchange](http://tex.stackexchange.com/questions/288765/argument-of-ot1-has-an-extra-when-i-have-an-umlaut-in-the-name) -- to be continued.

**Comment by retorquere** [comment]
Could you give this a try:

* Download and install http://tempsend.com/34FED09515
* Go into `about:config`, find `relaxAuthors` and set it to true
* Export and compile

**Comment by retorquere** [comment]
Hold on, that won't do anything. Tests are running on feedback I got from stack exchange, I'll have a new XPI for you in just a bit.

**Comment by noehmeier** [comment]
Thanks for your effort :+1: Is there a working version? :)

**Comment by retorquere** [comment]
Not yet. BibTeX has a gazillion edge cases, and my experiments haven't turned up an algorithm yet that covers even all those that I happen to know about. I did manage to reproduce the compile failure, and I'm working to add the LaTeX compiles to my test set, but finding that algorithm might take me a few days.

**Comment by retorquere** [comment]
If you're under time pressure, I *think* adding `<pre>\\relax </pre>` in front of the last name will help for the time being, but I wouldn't advocate that as a permanent solution.

**Comment by retorquere** [comment]
That would be `<pre>\relax </pre>`, sorry.

**Comment by retorquere** [comment]
OK one thing I've already learned from stack exchange about the alpha style is, and I quote

> My advice is never using the alpha style; it's a relic of the past, when numbering citations was very difficult because one didn't know the full citation list when writing a paper. In order to have the bibliography in alphabetical order, such tricks were devised.

I have a change under test which I will get into the next release, whose outputs compiles with `alpha`, but the discussion on SE indicates alpha is likely to have edge cases always. Are you bound to alpha?

**Comment by retorquere** [comment]
You could give [this](https://s3.eu-central-1.amazonaws.com/zotplus-builds/zotero-better-bibtex-1.6.33-travis-2412.xpi) a go. No hidden config; this currently passes all my tests.

**Comment by noehmeier** [comment]
To alpha: it have not to be "alpha", it have to be a style where the author(s) and the year of publishing have to in the citation. Like [Sch15] for Schneider, 2015. The bibliography list have to be in native language, in this case German (like preconfigured words for conjunctions etc). So "alphadin" complies both. If there is something better, it would be nice ;-)

Your new add-on version solves the problem, thanks a lot! It compiles without an error. Now i see, that the Citation Key is not the same like the BibTeX export. 

BibTeXs citation key has spaces in the authors name:
authorpart1_authorpart2_title_2016

Better BibTeXs citation key removes the spaces:
authorpart1authorpart2_title_2016

You write (https://zotplus.github.io/zotero-better-bibtex/citation-keys.html#configurable-citekey-generator), that [auth:lower] is for the authors names without spaces. Later (https://zotplus.github.io/zotero-better-bibtex/citation-keys.html#advanced-usage), at auth i read, that there is a version, where the spaces are used, but it will not lower the name and don't remove other unwanted stuff.

So i see no option, to get the "default" Zotero BibTeX citation keys. And i don't want to change all the setted citation keys to switch them in the format :/

**Comment by noehmeier** [comment]
Yes, i didn't change the citation key and i want the default of Zotero. So i have the same:
[auth:lower][Title:fold:nopunct:skipwords:select,1,1:lower:alphanum:prefix,_][year:prefix,_][0]

Excuse, I have expressed myself quite incomprehensibly. The problem are not the lowercases, everything is in lowercases and fine. The problem are the missing **_** and **-** between the authors first and last name or between the last name of two authors  (like the examples in the last post). And in your options in don't see parameters, which would fix that. So the goal should be, that the citation key of Zotero BetterBibTeX would be the same as the citation key of Zotero BibTeX.

Thanks for the tipp with apa, apalike, or author-year. I will try them :)

**Comment by retorquere** [comment]
Wait what hold, zotero adds underscores between authors? Hmm. Let me have a look at that later this evening.

**Comment by retorquere** [comment]
Could you open a new issue for the cite key please, and include a sample reference by right-clicking one in Zotero and selecting "send bbt error"?

**Comment by retorquere** [comment]
I've opened #439 for the key, but I can't replicate the key; I'd appreciate it if you could join me on #439 to see what's desired.
