### ISSUE TITLE
Auto export is not working

### ISSUE THREAD

**Issue by madhusudansingh** [ZotPlus/zotero-better-bibtex#440]
I am using the latest Zotero version with the latest version of better biblatex. When I export "My Library" (this used to work last week before a bunch of updates), with the Keep updated checked, the exported file does not appear in the list of auto exports.

Can you please help me debug this?

**Comment by madhusudansingh** [comment]
This is erratic. I just tried again (no change). It worked. Then I tested it again (deleted the auto export, created another), and it didn't. I don't think I can reproduce it, so I am closing it.

**Comment by retorquere** [comment]
I don't like erratic. If it happens again, can you send me a debug log via
"send better bibtex error" from the gear menu?

**Comment by madhusudansingh** [comment]
I will!
