### ISSUE TITLE
Support to accented characters

### ISSUE THREAD

**Issue by alinecrsouza** [ZotPlus/zotero-better-bibtex#442]
Hello, I am a new user of Zotero Better Bibtex. I've installed it hoping to solve a problem with accented characters on the exported .bib file, but appears that Better Bibtex doesn't offer support to this issue. 

So, my suggestion is that Zotero Better Bibtex while generates the .bib file automatically replace the special characters like accents or umlauts using the special bibtex notation found in http://www.bibtex.org/SpecialSymbols/.

This would be awesome.

**Comment by retorquere** [comment]
BBT [already does](https://zotplus.github.io/zotero-better-bibtex/configuration.html#export-bibtex-as-ascii), and it's the default for Better BibTeX. For [Better BibLaTeX](https://zotplus.github.io/zotero-better-bibtex/configuration.html#export-biblatex-as-ascii) the default is to leave accented chars as-is, but if you enable it, I think it will do what you want.

**Comment by alinecrsouza** [comment]
Yes, you are right. But for some reason the file .bbl generated by the latex does not update and keep the accented chars as-is. So, I am still having these errors. I am thinking on exclude this file and maybe latex will generate it again, but I am a little bit worried on doing this.

**Comment by retorquere** [comment]
I can't control how latex converts the bib file into bbl. I usually throw
away the bbl file myself.

**Comment by alinecrsouza** [comment]
Yes, I did this and worked fine. Thank you!
