### ISSUE TITLE
Unsupported key patterns break export

### ISSUE THREAD

**Issue by felixhaass** [ZotPlus/zotero-better-bibtex#446]
Hi @all , first off: thanks for such a great piece of software!

Now, I'm currently setting up a new work computer and ran into some issues with exporting my library through Better BibTex.

Here is the error report ID: ZTNCJX52

The problem is as follows: I'm simply trying to export the library through File -> Export Library -> Better BibTex. I usually use "keep updated" but the error remains whether the keep updated-box is checked or not. After clicking ok, Zotero throws me the error:

[Java Script Application] "Ein Fehler ist aufgetreten bei dem Versuch, die ausgewählte Datei zu exportieren."

It's German, and says that there was an error in exporting the chosen file. 

What I did already: full reboot of my machine, re-install the Better BibTex .xpi, reinstall Zotero Standalone.

I'm using Chrome as standard browser with the chrome plugin for Zotero.

**Comment by retorquere** [comment]
There's something in you key pattern that's not supported, but that shouldn't react by breaking export. If you could try https://s3.eu-central-1.amazonaws.com/zotplus-builds/zotero-better-bibtex-1.6.34-travis-2430.xpi with debug logging on? It won't throw an error, so exports will work, but it won't do what you expect as part of your pattern is unsupported; your debug log will say 'unsupported reduction' somewhere detailing the bit that isn't right. 

There's no @all BTW, just me.

**Comment by felixhaass** [comment]
Thanks, @retorquere for the quick reply.

I did as you suggest; associated error report is: 426XD3D5

**Comment by retorquere** [comment]
You have `[author]` in your pattern, which isn't supported. I'll admit this isn't well communicated.

**Comment by felixhaass** [comment]
Ok great. That fixed the issue. Thanks for the quick help!

**Comment by retorquere** [comment]
It's just a temporary fix. I have a fix lined up that will give feedback
while you're entering the pattern, and it will give a modest performance
benefit too. I will release it when I get home and will have had a chance
to test.

**Comment by retorquere** [comment]
The new release will color the pattern editor red if it sees an error.

**Comment by felixhaass** [comment]
Great, thanks!

On Mon, Feb 1, 2016 at 11:41 PM, retorquere <notifications@github.com>
wrote:

> The new release will color the pattern editor red if it sees an error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ZotPlus/zotero-better-bibtex/issues/446#issuecomment-178236127>
> .
>



-- 
Felix Haaß
Justus-Strandes Weg 4
22337 Hamburg | Germany

+49 177 5276292
