### ISSUE TITLE
Export formatting as Markdown in CSL YAML

### ISSUE THREAD

**Issue by adunning** [ZotPlus/zotero-better-bibtex#447]
Hate to say this, but apparently formatting for CSL YAML is meant to be done using Markdown rather than CSL's HTML-style tags (cf. <https://github.com/jgm/pandoc-citeproc/issues/212>):

- `<i>...</i>` = `*italics*`
- `<b>...</b>` = `**bold**`
- `<span style="font-variant:small-caps;">...</span>` or `<sc>...</sc>` = `<span style="font-variant:small-caps;">small capitals</span>`
- `<sub>...</sub>` = `~subscript~`
- `<sup>...</sup>` = `^superscript^`

**Comment by retorquere** [comment]
Huh. That's surprising, given that html is valid markdown. I'll see what I
can do. But could you also file an issue with the pandoc devs?

**Comment by retorquere** [comment]
Oh, sorry,you already did. I'll have a look-see.

**Comment by retorquere** [comment]
Can you submit a sample reference through the error report facility?

**Comment by retorquere** [comment]
And could you give https://s3.eu-central-1.amazonaws.com/zotplus-builds/zotero-better-bibtex-1.6.35-travis-2434.xpi a whirl?

**Comment by adunning** [comment]
Sample reference: 4FUUPGE2.

**Comment by adunning** [comment]
Thanks for taking care of that! Only problem I am seeing: it looks as if `<sup>` and `<sub>` are being closed with `**` rather than `</sup>` and `</sub>`. The problem is at <https://github.com/ZotPlus/zotero-better-bibtex/commit/dbfdfb7420782a4d1a5c41eafb7572e0cf7e4fe3#diff-a583cbafa3e71ad4e909e64aa4938e41R53>. (Example: report ID JBIF4BRG.)

**Comment by adunning** [comment]
(Which is to say, rather than `^` and `~` respectively.)

**Comment by adunning** [comment]
One more thing: `<span class="nocase">` is not being passed through. Report ID KJMIKBJP.

**Comment by retorquere** [comment]
That's why I love tests. All have been added, and are green locally. Travis tests are running; if you're curious you can grab a test build from the s3 url at the end of https://travis-ci.org/ZotPlus/zotero-better-bibtex/jobs/106619542 when it finishes, but if you think these tests cover your cases I'll just cut a release when it goes green.

Pandoc is pretty schizo when they don't support `<b>` but do support `<span class="nocase">` BTW.

**Comment by retorquere** [comment]
The travis build is up at https://s3.eu-central-1.amazonaws.com/zotplus-builds/zotero-better-bibtex-1.6.35-travis-2436.xpi, but if you're happy with the current tests I can just merge and release.

**Comment by adunning** [comment]
Seems to be working perfectly, as far as I can tell. Many thanks for this!
