### ISSUE TITLE
Exporting citation key to a CSV file

### ISSUE THREAD

**Issue by eds89** [ZotPlus/zotero-better-bibtex#448]
Hello,
Thanks for making BBT a great plugin, improving the productivity of millions of researchers every day!

So, I wanted to know if it'd be possible to export the citation key to a CSV file as a custom translator. I am aware of how Zotero's translator architecture works, however I am unable to access the citation key field since it is not an actual field of zotero, rather generated by bbt.

**Comment by retorquere** [comment]
I don't know about millions, but thanks :) It is possible as long as BBT is installed. You can grab the key by doing something like

```
var citekey = Zotero.BetterBibTeX.keymanager.get(item).citekey;
```

in your translator. This is an internal method of BBT, so I can't guarantee it's not ever going to change, but it hasn't changed in a long while. The keymanager will return an object with a few properties, but most are likely not interesting to you, except of course the `citekey` field.

There is one other aspect of calling the keymanager. I'm not sure you'd want to make use of it as it [has (intended) side effects](https://zotplus.github.io/zotero-better-bibtex/citation-keys#generation-of-stable-keys-and-syncing) you might not intend. You can call the keymanager with

```
var citekey = Zotero.BetterBibTeX.keymanager.get(item, 'on-export').citekey;
```
If called on a reference that doesn't have a pinned citekey, and the user has set auto-pinning to `on export` (see link above), calling the key manager with `'on-export'` will pin the key at that moment.
