### ISSUE TITLE
Crappy metadata breaks export

### ISSUE THREAD

**Issue by BonarBeavis** [ZotPlus/zotero-better-bibtex#449]
In the abstract of one of my items is a round bracket which is never closed. When exported it breaks the bib file.

**Comment by retorquere** [comment]
Can you right-click on the reference and select "report better bibtex error"? If you paste the resulting ID, I will have the reference to inspect.

**Comment by retorquere** [comment]
Really can't do anything without that sample.

**Comment by retorquere** [comment]
hello?

**Comment by BonarBeavis** [comment]
Sorry for the delay, the ID is 
36a3b0b5-bad0-4a04-b79b-441c7cef77db

This is the entry from the generated bib file:
```
@book{karmasin_gestaltung_2002,
  address = {Wien},
  edition = {3., vollst{\"a}ndig {\"u}berarb. Aufl},
  series = {Manual},
  title = {Die Gestaltung wissenschaftlicher Arbeiten: ein Leitfaden f{\"u}r Haus-, Seminar- und Diplomarbeiten sowie Dissertationen},
  isbn = {978-3-85114-698-1},
  shorttitle = {Die Gestaltung wissenschaftlicher Arbeiten},
  abstract = {Besprechung zur 2.Aufl. 1999)Kompakter, praxisorientierter und vor allem {\"u}bersichtlicher Leitfaden zur inhaltlichen und formalen Gestaltung wissenschaftlicher Arbeiten. In 4 Kapitel werden Planung und Konzeption, Form und Formatierung (unter Einsatz der Textverarbeitungssoftware Word), Literaturrecherche (inkl. Datenbanken auf CD-ROM, Internet und elektronischen Bibliothekskatalogen) sowie die Zitierregeln eingehend vorgestellt. Die zahlreichen Beispiele orientieren sich zwar an den {\"o}sterreichischen Gegebenheiten, was aber kaum zu Nutzungseinschr{\"a}nkungen f{\"u}r deutsche Studierende f{\"u}hren d{\"u}rfte. Zur Erg{\"a}nzung.(},
  language = {ger},
  timestamp = {2016-02-17T16:39:36Z},
  publisher = {{Facultas Verl}},
  author = {{Karmasin}, Matthias and {Ribing}, Rainer},
  year = {2002},
  keywords = {6.5,Ratgeber,Wissenschaftliches Manuskript},
  file = {/home/beavis/.zotero/zotero/lr3ez4k9.default/zotero/storage/NDF26T53/Karmasin_Ribing_2002_Die Gestaltung wissenschaftlicher Arbeiten.pdf}
}
```
In the abstract the last character the "(" was not escaped

**Comment by retorquere** [comment]
That's not the debug ID, that's the identifier of the translator. The debug ID is displayed in red after the report is submitted, it's a 8-character alphanumeric sequence. Could you try again, and click "next" until you see a red ID.

The bibtex you posted [compiles cleanly](https://www.sharelatex.com/project/54feca38f58d781e0c982eeb) for me though.

**Comment by retorquere** [comment]
What Zotero version are you on BTW? I see an error submission from today that lists "4.0.999.SOURCE.f9178a4" as a version. I can't tell whether that was your submission (doesn't look like it, because the associated reference doesn't list anything resembling the BibTeX you posted above), but if it is it looks like it might be a debug build of Zotero.

**Comment by retorquere** [comment]
Really can't do anything without that sample, as I don't know in what way "export breaks".

**Comment by BonarBeavis** [comment]
ID: HCSZWVVR

I thought "(" is a reserved character in a tex file. Because the posted bibtex only compiled when I removed the bracket. So the issue must be somewhere in my tex distribution.

Thanks for your time.

**Comment by retorquere** [comment]
The "(" is not a reserved character, no. If you can reproduce the problem with a minimal example (you can use the LaTeX I linked to if you want, it includes the reference) using your installation, tex.stackexchange.com is usually incredibly fast in figuring out what's wrong.

Something *is* going wrong during our export export though; in your logfile, I see

```
[JavaScript Error: "[Exception... "Component returned failure code: 0x80520012 (NS_ERROR_FILE_NOT_FOUND) [nsIFileOutputStream.init]"  nsresult: "0x80520012 (NS_ERROR_FILE_NOT_FOUND)"  location: "JS frame :: chrome://zotero/content/xpcom/translation/translate_firefox.js :: Zotero.Translate.IO.Write :: line 962"  data: no]" {file: "chrome://zotero/content/xpcom/notifier.js" line: 165}]
```

I can't reproduce that here however. My first guess would be you're trying to export to a directory that no longer exists, but that should be a very rare occurrence.
