### ISSUE TITLE
uninstall?

### ISSUE THREAD

**Issue by kjg04** [ZotPlus/zotero-better-bibtex#451]
Hey, sorry for the dumb question, but I really can't figure out how to remove the better bibtex plugin now that I've installed it. I haven't found any information here, on the Zotero forums, or anywhere else I've looked. What's the best way to uninstall better bibtex?

Thanks and sorry!

**Comment by retorquere** [comment]
No apologies necessary. You can uninstall BBT [just as you would any Firefox plugin](https://support.mozilla.org/en-US/kb/disable-or-remove-add-ons). Sorry to see you go -- is there any particular issue I should be looking into?

**Comment by kjg04** [comment]
oh (*´ω｀*) thank you! i was just testing out different ways of exporting zotero information and haven't actually used bibtex before, so it ended up being more work to try to figure that out than some other methods. thanks again!

**Comment by retorquere** [comment]
No worries. Yeah, if you don't need bibtex there's little additional value
to BBT.
