### ISSUE TITLE
BBT does not correctly exports arXiv citations with opening bracket [

### ISSUE THREAD

**Issue by anuragm** [ZotPlus/zotero-better-bibtex#452]
When exporting Zotero entry where the journal field is given by

```
 arXiv:1401.7087 [quant-ph]
```

BBT exports BibTeX file with entry,

``` 
journal = {ArXiv14017087 Quant-Ph},
```

This leads to wrong formatting in LaTeX file compiled with BibTeX. 

Steps to reproduce the problem

1. Install a fresh copy of latest Firefox, Zotero 4.0.28.10 and BBT 1.6.36.

2. Import this ArXiv entry using Zotero. http://arxiv.org/abs/1401.7087

3. Export using Better BibTeX.

**Comment by anuragm** [comment]
I have generated a report with ID --  ``W4ES3RHQ`` . This report was generated with my normal installation, so I had also reproduced the error with fresh installation. 

As a sidenote, Support Request guideline URL in Readme.md 404's . https://zotplus.github.io/zotero-better-bibtex/support.html

**Comment by retorquere** [comment]
I think you have "use journal abbreviation" on. When that is ticked, BBT just uses whatever Zotero thinks is the right abbreviation; Zotero abbreviates "arXiv:1401.7087 [quant-ph]" into "ArXiv14017087 Quant-Ph".

**Comment by anuragm** [comment]
Indeed, that seems to be the case. Well, that is a weird way to abbreviate arXiv. Turning off journal abbreviation indeed fixes the problem. It is turned on by default, and Zotero's own exporter is usually good about it. 

In any case, this is not a bug.

**Comment by retorquere** [comment]
It actually sort of was; the Zotero BibTeX exporter uses the journal abbrev you set specifically, and nothing if you set no abbreviation; BBT can also do that, but *by default* it uses the Zotero abbreviator if you did not manually set an abbreviation. That is not a good default in retrospect. You can achieve the same output by keeping on "use journal abbreviation" but going into BBT prefs and unticking "Journal Abbreviations -> Automatically abbreviate". I've changed the default to off, which I'll publish in the next release, probably somewhere tonight (I'm on a *really* lousy connection right now).

**Comment by anuragm** [comment]
Thanks! I like better defaults.
