### ISSUE TITLE
Cite keys not generated on import?

### ISSUE THREAD

**Issue by jarmitage** [ZotPlus/zotero-better-bibtex#453]
Hi, not sure if this is actually a bug, whether this feature exists, or whether I have not set up the plugin correctly, but currently cite keys are not being created for me when I import a paper into Zotero.

I almost exclusively use the Zotero Connector Chrome plugin to import.

Report ID: 8RPC9IBB

Thank you for the great plugin!

**Comment by retorquere** [comment]
I don't fully understand. In what way are they not being created? What is
not happening what you expected to happen?

**Comment by jarmitage** [comment]
I _thought_ they were not being generated when I import an article, but they actually are and I was looking in the wrong place. I'll close this.
