### ISSUE TITLE
Ignoring upper cases in German titles

### ISSUE THREAD

**Issue by uweobelix** [ZotPlus/zotero-better-bibtex#456]
Hi,
I encountered the following problem, when exporting my zotero library to bibtex using bbt.
Titles containing words in upper case are not exported as upper cases when language is set to non-English. When English or no language was specified, everything worked fine, i.e. the title's upper cases were maintained. When the language was specified to German, upper cases were ignored and the output resulted in lower cases only.
The debug id is: 3MEXISKC

The following examples might tell you what happened.
a) language field left empty (upper cases kept):

@article{Berger2004,
  title = {"{{{\"U}ber}} den {{Ursprung}} der {{Ungleichheit}} unter den {{Menschen}}". {{Zur Vergangenheit}} und {{Gegenwart}} einer soziologischen {{Schl{\"u}sselfrage}}},
  volume = {33},
  number = {5},
  journal = {Zeitschrift f{\"u}r Soziologie},
  author = {Berger, Johannes},
  month = jan,
  year = {2004},
  pages = {354--374}
}

b) language set to "de" (upper cases ignored):

@article{Berger2004,
  title = {"{\"U}ber den Ursprung der Ungleichheit unter den Menschen". Zur Vergangenheit und Gegenwart einer soziologischen Schl{\"u}sselfrage},
  volume = {33},
  number = {5},
  journal = {Zeitschrift f{\"u}r Soziologie},
  author = {Berger, Johannes},
  month = oct,
  year = {2004},
  pages = {354--374}
}

Kind regards,
uweobelix

**Comment by retorquere** [comment]
This is to BibTeX, not BibLaTeX, correct? For BibLaTeX, this is, I believe, the [correct behavior](https://github.com/ZotPlus/zotero-better-bibtex/issues/383).

**Comment by retorquere** [comment]
Eh, hold on, I think I didn't read your comment right. You're talking about caps protection, not autocapitalization.
