### ISSUE TITLE
BBT cache corrupted

### ISSUE THREAD

**Issue by kgemici** [ZotPlus/zotero-better-bibtex#461]
**Report IDs: BRBNKENC, EWKAGE7W, E2JN2VG9**

Generate citekey function and export functions do not work. Citation keys are blank. The following is representative of the errors I'm getting:

> [JavaScript Error: "SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data" {file: "chrome://zotero-better-bibtex/content/lokijs.js" line: 1}]
[JavaScript Error: "TypeError: Zotero.BetterBibTeX.keymanager is undefined" {file: "chrome://zotero-better-bibtex/content/itemPane.js" line: 51}]
[JavaScript Error: "1458305546325	Toolkit.Telemetry	ERROR	TelemetryStorage::loadAbortedSessionPing - error removing ping: PingReadError JS Stack trace: PingReadError@TelemetryStorage.jsm:80:15 < TelemetryStorageImpl.loadPingFile<@TelemetryStorage.jsm:1440:13" {file: "resource://gre/modules/Log.jsm" line: 749}]
[JavaScript Error: "no element found" {file: "https://zotplus-964ec2b7-379e-49a4-9c8a-edcb20db343f.s3.eu-central-1.amazonaws.com/" line: 1}]

Also, when I try to export an item, I get the following error:

>JS Stack trace: PingReadError@TelemetryStorage.jsm:80:15 < TelemetryStorageImpl.loadPingFile<@TelemetryStorage.jsm:1440:13" {file: "resource://gre/modules/Log.jsm" line: 749}]
[JavaScript Error: "no element found" {file: "https://zotplus-964ec2b7-379e-49a4-9c8a-edcb20db343f.s3.eu-central-1.amazonaws.com/" line: 1}]
[JavaScript Error: "no element found" {file: "https://zotplus-964ec2b7-379e-49a4-9c8a-edcb20db343f.s3.eu-central-1.amazonaws.com/" line: 1}]
[JavaScript Error: "no element found" {file: "https://zotplus-964ec2b7-379e-49a4-9c8a-edcb20db343f.s3.eu-central-1.amazonaws.com/" line: 1}]
[JavaScript Error: "no element found" {file: "https://zotplus-964ec2b7-379e-49a4-9c8a-edcb20db343f.s3.eu-central-1.amazonaws.com/" line: 1}]

Best,
Kurt

**Comment by retorquere** [comment]
Upgrade from what version?

It looks like the JSON files that BBT uses to store its data got corrupted somehow. Would you be OK with sharing the data with me so I can inspect them?

**Comment by kgemici** [comment]
Upgrade from 4.0.29.2. 

Shouldn't be a problem. Please let me know why you need. 

I tried to go back to 4.0.29.2 and I also reinstalled bbt. Did not make a difference.

**Comment by retorquere** [comment]
In your profile directory, under zotero/better-bibtex, there will be two files called db.json and serialized.json, I'd need those. You can drop them here https://dbinbox.com/retorquere and then let me know when you've done that.

**Comment by retorquere** [comment]
Downgrade (or upgrade -- 4.0.29.6 is the latest Zotero version) won't help. If I can look at the JSON files I might be able to correct the problem. If you want to get back to work right now you can move those two files to a different directory, and BBT will recreate them. In the meantime I've checked in a change that should prevent this happening, but I would really like to see what went wrong.

**Comment by kgemici** [comment]
Thanks. I moved the files to another folder and things seem to be working fine now. I send the corrupted db.json and cache.json files. No serialized.json under my profile though.

**Comment by retorquere** [comment]
Can you send me the fresh db.json (or db.json.bak if that's all there is)? Please make sure Firefox is closed before you copy the file.

**Comment by kgemici** [comment]
Just sent it.

**Comment by retorquere** [comment]
Super, I've compared them and the cache regenerated cleanly. With 1.6.38, this should not happen again.

Bit of a hoarder, aren't you? :smile: 6k+ references.

**Comment by kgemici** [comment]
Thanks for solving the issue. I guess you could say that I'm a hoarder :). 16 years of academic life. And citations that survived good (procite, zotero) & bad software (endnote, mendeley)...
