### ISSUE TITLE
Endpoint schomd.bibtex does not work

### ISSUE THREAD

**Issue by berndjr** [ZotPlus/zotero-better-bibtex#462]
There seems to be a bug in the code of the schemed.bibtex endpoint. It should be itemIDs instead if items in the following lines:

if (items.length === 0) {
  return '';
}
items = Zotero.Items.get(items);

I think this is the correct code:

if (itemIDs.length === 0) {
  return '';
}
items = Zotero.Items.get(itemIDs);

**Comment by retorquere** [comment]
Indeed it should, thanks for reporting it.
