### ISSUE TITLE
Hyphens inconsistently included in citation key

### ISSUE THREAD

**Issue by CarbonFixer** [ZotPlus/zotero-better-bibtex#465]
This is probably just a mis-configurarion but still here's the report ID: IDX499JE

I have two synced computes, one of them includes hyphens in the citation key and one of them doesn't. This causes my tex file to break when switching between them. This applied to when the reference title starts with a hyphened combo.
Example URL:
http://www.sciencedirect.com/science/article/pii/S1352231013004597
One system produces "yuval_datadriven_2013" as the key and the other "yuval_data-driven_2013". This happens with all titles that have a hyphen in their first phrase.
What could be the cause of this? On both systems the citation key format specified is [zotero].

I'm currently on the system that produces the hyphens and will be back on the system that does not produce hyphens on Sunday.

**Comment by CarbonFixer** [comment]
Worked around the issue by moving over ssh the entire zotero directory in the Firefox profile from one system to the other.

**Comment by retorquere** [comment]
I'm not sure why they'd generate different keys, but for stable sync of citation keys you will want to pin them. Duplicate key disambiguation is not stable if you don't, for example. For those cases you mght want to auto-pin either on change or on export.
