### ISSUE TITLE
Feature Request: Push Export

### ISSUE THREAD

**Issue by alexsb** [ZotPlus/zotero-better-bibtex#70]
Some use cases would be easier to address using a push export than a pull export. I could imagine such a functionality this way:

 * For every subcollection a user can define a path to which to export the bibtex.
 * Every time the subcollection is changed the bibtex file is replaced. 

This would work well with workflows where no local compile is executed (e.g., when using tools like ShareLaTeX) and would also be a lower technical hurdle compared to pulls.

**Comment by lucisandor** [comment]
Seconding the above: ZBA is not working properly with subcolections, and hasn't been updated in a while. My other bug report to ZBA is not faring very well either, so I am short on hopes on that side.

**Comment by AllThatIsTheCase** [comment]
The implementation on autoexport is feature complete, but I am still ironing out some bugs. Can't be too long off. The current release actually has most of the autoexport code for other purposes, the UI is simply switched off until I get it to work in a stable fashion.

**Comment by retorquere** [comment]
Done and done!
